### ISSUE TITLE
Clearing Bug: image shifts to bottom

### ISSUE THREAD

**Issue by tikot** [zurb/foundation#3410]
Sometimes this happens. I have looked into this to find what is the cause, but no luck yet. Maybe someone has an idea.

![clearing-bug](https://f.cloud.github.com/assets/2917117/1324039/a50a1870-34a4-11e3-8424-76905e120c86.jpg)

**Comment by Baedda** [comment]
@rafibomb will there be a push to bower-foundation so we can have a benefit from tikots fix, too?

**Comment by versedi** [comment]
+1

**Comment by versedi** [comment]
I've tried to make same changes to files but then Chrome got the same bug - just the image went to opposite corner.

**Comment by tikot** [comment]
@versedi just include this [commit](https://github.com/zurb/foundation/commit/e7a38167e4848b95e5520ea06e3bd5d37770234a)
