### ISSUE TITLE
request: make it simple to position .toggle-topbar and .menu-icon on the left

### ISSUE THREAD

**Issue by ryandeussing** [zurb/foundation#4102]
I was unable to write overriding classes that worked, and had to do ugly things in `components/_top-bar.scss`, where I shouldn't be messing in the first place.

![google chrome](https://f.cloud.github.com/assets/216835/1873025/cb2c7348-78b2-11e3-81eb-cc223763be82.png)

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
