### ISSUE TITLE
Tabs are not initialized when contained in an AJAX-Reveal

### ISSUE THREAD

**Issue by afoeder** [zurb/foundation#4543]
When fetching a reveal-model content via Ajax which has Tabs on it, these don't work because they are not properly initialized (concretely, the `settings` in this line aren't set because there's no `'tab-init'` data:

```
settings = tab.closest('[data-tab]').data('tab-init');
```
(`foundation.tab.js`)

When, on spec, re-calling `$(document).foundation()` after an ajax modal has been fetched, it works.

Tabs are likely not the only problem in this case.

**Comment by rafibomb** [comment]
We're working on the next version with JS updates and will keep this use case in mind.
