### ISSUE TITLE
Dropdowns (top position on mobile)

### ISSUE THREAD

**Issue by zslabs** [zurb/foundation#4606]
On the [demo page](http://foundation.zurb.com/docs/components/dropdown.html) for dropdowns the `top` position should remain at the top on mobile -- currently it breaks down below). I can understand for both left and right to go to the bottom, but top should remain as configured.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
