### ISSUE TITLE
Dropdown positioning not working within overflow: scroll div

### ISSUE THREAD

**Issue by Matt888** [zurb/foundation#4639]
I have a main content div that is using overflow: scroll, and it seems that when I scroll this div the dropdown menus within it are being positioned relative to the document (which is not scrolling), not the div's scroll.  It ends up looking like this:

![screen shot 2014-03-10 at 8 31 54 pm](https://f.cloud.github.com/assets/1594285/2380893/b3558b24-a8b4-11e3-9adf-22c45b85ce6a.png)

Using foundation-rails gem version 5.2.0.0

```
html, body, .off-canvas-wrap, .inner-wrap, #container, #content {
  height: 100%;
}

#content {
  overflow: auto;
}

<div class="off-canvas-wrap">
    <div class="inner-wrap">
      <div class="row" id="container">
        <section class="small-12 medium-9 large-10 columns" id="content">
          (Dropdown Code)
        </section>
      </div>
    </div>
  </div>
</div>
```

**Comment by rafibomb** [comment]
Example: http://codepen.io/rafibomb/pen/hApKk

**Comment by rafibomb** [comment]
Also, this is a very tricky problem to solve - 
See 
- https://github.com/angular-ui/ui-select/issues/308

I think for now, the initial position should be corrected, and if it detects scroll to close (temp solution). Thoughts?

**Comment by rafibomb** [comment]
Awesome! @jeaniec just committed a fix that works great in testing! It's on the master branch so if you guys could test it a bit more that would be great.
