### ISSUE TITLE
data-equalto throws mismatch when id="password"

### ISSUE THREAD

**Issue by jphase** [zurb/foundation#4730]
Just noticed an odd occurrence where I had two inputs (password and confirm password) throw a mismatch when I used id="password" on the first element and data-equalto="password" on the second confirm element. Chrome seems to work when I do this but Firefox and Safari threw a mismatch.

I changed the first input's id to id="thepassword" and the second input's attribute to data-equalto="thepassword" and it worked just fine. The odd part is that the Foundation 5 docs on abide use id="password" and things work just fine for me. I got rid of all of my custom regex patterns and changed my foundation call back to $(document).foundation(); to confirm that none of my customizations were causing the problem but was still unable to fix this in Firefox and Safari.

Perhaps this is user-error but I'd like to figure out what specifically might cause it. I'm happy to provide code samples if needed.

**Comment by rafibomb** [comment]
It's working on the docs...

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
