### ISSUE TITLE
Reveal doesn't respect open/closed callbacks passed as options 

### ISSUE THREAD

**Issue by jeremybrownau** [zurb/foundation#4746]
Hi,
If we create a reveal modal with option closed
```js
var foundationModal = $("#foundationModal");
var options = {
  closed: function() { alert("this doesn't work"); }
}
foundationContainer.html("<iframe id='foundation-modal' src=\"somepage.htm\" frameborder=\"0\" allowfullscreen></iframe>");
foundationModal.foundation("reveal", "open", options);
```

For the purpose of the exercise we changed the Foundation.libs.reveal.settings.closed to : 
```js
function(){
 alert("This is the default closed")
}
```
In the reveal.init we put breakpoints and can see the closed option extend works and its stored

If we put a breakpoint inside reveal.hide we can see this.settings.closed has passed correctly. Though it always fires the default message and not the options.closed?

We have had to work around it with this
```js
foundationModal.foundation("reveal", "open");
foundationModal.on('closed', function(){
                alert("this works"); 
}
```

**Comment by jeaniec** [comment]
I'm finding that this is now working as expected. When you pass a function in as a callback through the foundation options, it gets called correctly.
