### ISSUE TITLE
Tabs deep linking + no scroll not working (5.2.1)

### ISSUE THREAD

**Issue by fuzendesign** [zurb/foundation#4791]
The docs state the following options for tabs:
data-options="deep_linking:true"
data-options="scroll_to_content: false"

But there doesn't seem to be a way to have deep linking and yet NOT scroll the page. I've tried the following with and without a semicolon on the end:

data-options="deep_linking:true;scroll_to_content:false;"

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by UngererFabien** [comment]
If you can get the event on click of your href="tabId" inside your list tab-title, then e.preventDefault() and the browser will not scroll. But then the url dont change to toto.com/#tabId.

You can also just 'return false' in the click handler, but it will prevent event propagation.

See https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

**Comment by tarpanpatel** [comment]
Any news since then? This problem still goes on. I have 5.5.3
`TypeError: g.default_tab_hashes[0] is undefined`

**Comment by andrebautista** [comment]
No sorry, Ive just been resorting to bootstrap for all my styling now :p
