### ISSUE TITLE
Abide fires valid/invalid events for some single inputs, not only for the whole form

### ISSUE THREAD

**Issue by ruben-santacruz** [zurb/foundation#4802]
The [documentation](http://foundation.zurb.com/docs/components/abide.html#events) states that a **valid**/**invalid** event triggers for the whole form when it is valid or invalid.

But such events are also triggered for some single inputs within the form, as you can see here:
* [valid event](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L207) (file - 5.2.1 tag)
* [invalid event](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L214) (file - 5.2.1 tag)

I have tried to bind to those events in a simple example and they seem to work well:
```HTML
<input type="text" required pattern="[a-zA-Z ]+" id="name">
```
```JavaScript
$('#name')
   .on('invalid', function () {
         console.log("invalid field: " + this.id);
   })
   .on('valid', function () {
      console.log('valid!');
```

So, I suggest to document them as they can be useful. If for any reason they shouldn't be used publicly, I'll appreciate clarification.

Tested in Foundation 5.2.1

**Comment by rafibomb** [comment]
Also see https://github.com/zurb/foundation/issues/4805

**Comment by daffunn** [comment]
What about the "valid.fndtn.abide" and "invalid.fndtn.abide" events? I thought the simple "valid" and "invalid" events are becoming deprecated in future?
