### ISSUE TITLE
Abide single valid/invalid event for every input

### ISSUE THREAD

**Issue by ruben-santacruz** [zurb/foundation#4805]
Currently, there is a **valid**/**invalid** undocumented event triggered for **some** single inputs (not for the whole form - see issue #4802), **but not for all of them**.

Specifically, looking at [*check_validation_and_apply_styles()*](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L157-220) they are triggered only when:
* The input is NOT a radio button
* The input is NOT a checkbox
* There is NOT a custom validator associted to the input

When the three above conditions are satisfied, you can see that
```JavaScript
$(el).triggerHandler('valid');
``` 
or
```JavaScript
$(el).triggerHandler('invalid');
```
is called.

As I stated on issue #4802, I think that having these events available can be useful. Firing them for every input may be easy to implement as the *_el_* variable is always available:
* When it is a radio button they can be easily triggered calling 
```JavaScript
$(el).triggerHandler(...);
```
inside [valid_radio()](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L235-256)
* The same for checkboxes inside [valid_checkbox()](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L222-233)
* For custom validators, they can be triggered by the user within its own custom code, but adding them in [this if/else block](https://github.com/zurb/foundation/blob/v5.2.1/js/foundation/foundation.abide.js#L191-197) will make them always available.

Tested in Foundation 5.2.1

**Comment by rafibomb** [comment]
Duplicate, closing for https://github.com/zurb/foundation/issues/4802
