### ISSUE TITLE
Add Reveal (ajax) error callback

### ISSUE THREAD

**Issue by littleviking61** [zurb/foundation#4816]
Hi,
I experiment some issue. Reveal not appear to have some error callback extend for ajax. It can be interesting to add it. I just add this after success on line 182 and file foundation.reveal.js. This code is not the best but can we extend in another way ?

              
    $.extend(ajax_settings, {
      success: [...],
      error: function(data, textStatus, error) {
        modal.html('<h2>Error ' + data['status'] + '</h2><a class="close-reveal-modal">&#215;</a>'+ data['responseText']);

        self.S(modal).foundation('section', 'reflow');

        if (open_modal.length > 0) {
          self.hide(open_modal, settings.css.close);
        }
        self.show(modal, settings.css.open);
    }

**Comment by jeaniec** [comment]
Closed with https://github.com/zurb/foundation/commit/fcc5c55ca07e62ad8437d5d633c329112fe28ea8. I decided not to add a default error call in there, but you can specify a function on init, or when you're opening the modal, as before.

**Comment by potherca** [comment]
Nice!

**Comment by littleviking61** [comment]
Thanks!
