### ISSUE TITLE
Feature Request: Add ability to configure FastClick instantiation

### ISSUE THREAD

**Issue by bregenspan** [zurb/foundation#4860]
Currently FastClick is instantiated if it is found.  However, there are several reasons the user might want to instantiate FastClick separately:

1. To customize the parameters that FastClick is instantiate with
2. To save a reference to the FastClick instance (the project I am working on currently does this because we need the reference in order to destroy the instance when opening an editor that is incompatible with FastClick).

Adding a configuration option to disable FastClick would resolve the issue.

**Comment by rafibomb** [comment]
This will be something we'll do for the next version. Closing here as it is on our roadmap.
