### ISSUE TITLE
Feature Request: Add Ability to Quickly and Easily Center Nav Bar

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#4885]
Hello, 

I find myself needing to center the topbar on numerous sites. I know how to do this using CSS but it requires hacking away at the code. I would love to see the ability built in to quickly center the topbar menu items. 

For instance: 

This: 

    <section class="top-bar-section">
        <ul class="left">
            <li><a href="#">Home</a></li>
            
        </ul>
    </section>

Becomes this: 

    <section class="top-bar-section">
        <ul class="center">
            <li><a href="#">Home</a></li>
            
        </ul>
    </section>

Notice the class on the `ul` tag. 

Of course I realize it is not be that simple but I would love to see this as a feature in a future version of Foundation. 

Note: If I knew more about SCSS (and possibly JS?) I would submit a PR with this ability but unfortunately I do not. 

Thank You

**Comment by gakimball** [comment]
@Lynda333 Since you mentioned it in our Foundation 6 feedback thread, I'm going to close this. Top bar is getting an overhaul in the next version of the framework, and we can definitely keep this feature in mind.

**Comment by Lynda333** [comment]
@gakimball - That is fine. I cannot wait to see what you guys do with Foundation 6! Very excited. =>
