### ISSUE TITLE
Accordion multi_expand: Closing an open panel removes the 'active' class in all dd tags

### ISSUE THREAD

**Issue by cmoran** [zurb/foundation#4901]
If you have multiple panels open and close one of them the 'active' class is removed from all the dd tags, the panel stays open since it depends on the 'active' class inside the panel which is not removed.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
