### ISSUE TITLE
File to import not found or unreadable: foundation/_functions

### ISSUE THREAD

**Issue by ajzawawi** [zurb/foundation#4936]
First time using foundation, followed the instructions to install foundation with sass.

I keep getting the following error in app.css

Syntax error: File to import not found or unreadable: foundation/_functions.
              Load path: /Users/xxx/Desktop/sandbox/app
        on line 13 of scss/_settings.scss
        from line 1 of ./scss/app.scss

**Comment by rafibomb** [comment]
This has been resolved here: https://github.com/zurb/foundation/issues/6148#issuecomment-69477175
