### ISSUE TITLE
Off-canvas causes a link with data-method='delete' not to render a DELETE request properly on RoR 

### ISSUE THREAD

**Issue by prakashsejwani** [zurb/foundation#4939]
I have a link with data-method='delete' in the Off-canvas menu:
```ruby
<aside class="right-off-canvas-menu">
  <ul class="off-canvas-list">
        <li><a href="users/sign_out" data-method="delete" rel="nofollow">Logout</a></li>
    </ul>
</aside>
```
To send a DELETE request, I'm using jquery-ujs( on Ruby on Rails ). When clicked on the link from the offcanvas, a GET request is sent. On the other hand, when I move the <ul> outside the offcanvas or just remove the right-off-canvas-menu class from the div, everything works as expected - a DELETE request is sent.
Now, I'm not sure if this is because the way foundation renders offcanvas or because of jquery-ujs, but at this point I'm pretty sure it's a bug.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
