### ISSUE TITLE
topbar component with multilevel menu problem

### ISSUE THREAD

**Issue by caioh** [zurb/foundation#4958]
Greetings,
I am developing a webapp with a multilevel topbar menu like the one at this url: 
http://foundation.zurb.com/docs/components/topbar.html 
on the android (4.2, 4.3) default browser (not chrome) the menu breaks at the second level of depth showing no options.
I happens in my application and in your example page.

Thanks in advance for any help.

Best regards.

**Comment by jeaniec** [comment]
Added your fix @oller . Thanks!
