### ISSUE TITLE
Abide century limitation

### ISSUE THREAD

**Issue by darylprickett** [zurb/foundation#5036]
Code snippet from Abide:
```js
month_day_year : /^(0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])[- \/.](19|20)\d\d$/,
```

The month_day_year pattern limits year input to 1900, or 2000, instead of allowing any date range to be specified. This would prove to be an issue for systems designed to allow input of historical dates and may be confusing since the limitation is not mentioned in the documentation. Recommend updating the documentation or remove this arbitrary limit.

**Comment by gakimball** [comment]
Looks like this commit fixed the issue: cc2b71d4f56a522242745a5e07e9c3291a04106e
