### ISSUE TITLE
Tooltips slow down ajax apps with DOM removal

### ISSUE THREAD

**Issue by In4matik** [zurb/foundation#5069]
Hello,

I am building an ajax-based app, and use foundation tooltips.
I have an issue on firefox (not on chrome), that seems to be caused by Foundation Tooltips.

Firebug profiler shows that DOM modification / deletion detection slows down my whole script : https://github.com/zurb/foundation/blob/master/js/foundation/foundation.tooltip.js#L86

I remove and add ~300 `tr`s with 5 `td`s each at each ajax call, and commenting the line 86 fix the slowdown issue. There's 2 tooltips in every `tr`.

Any idea to fix this ?

Thanks by advance.

**Comment by gakimball** [comment]
Hey man, I know this is an older issue but I hope you were able to figure something out. Making 600 tooltips at once performant might be too much of an edge case for us to adequately handle it :) But if you ever run into any more troubles let us know!
