### ISSUE TITLE
Topbar hover dropdown IOS scrolling issue

### ISSUE THREAD

**Issue by unclediluvian** [zurb/foundation#5079]
On IOS 7.1.1 Safari on IPad, go to demo page...
http://foundation.zurb.com/docs/components/topbar.html
... scroll down a couple of inches then tap a couple of inches under the "Item 1" dropdown on the first bar - it should activate. However far you scroll down, it can be activated by clicking that distance below it. 

If you set is_hover to false, this fixes it, so a hack fix would be to write some javascript to check for touch and set the data_option accordingly.

This is surely something to do with the css :hover problems in ios. I only apply css :hover to descendants of the no-touch class. Perhaps this is all that's needed in the foundation css.

Please confirm on other IOS versions and other touch devices.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
