### ISSUE TITLE
Clearing - Add support to ignore hidden elements

### ISSUE THREAD

**Issue by laurent-le-graverend** [zurb/foundation#5097]
When using the great clearing tool with a set of images:

If I apply my own filter to show/hide images from the list.
Some `li` elements get the the attribute: `display: none`.

When I open the clearing carousel in full screen, it shows only the good images (I filtered) on the bottom navigation ==> OK good

But when navigating from one image to another one in the carousel, it shows all the pictures, including the `li` blocks that were in `display: none`.

Is it possible to improve this tool to also don't show the hidden elements in the full screen carousel?

**Comment by tdhartwick** [comment]
@laurent-le-graverend Thanks for pointing this out! This is a pretty specific use case, that will require some custom JavaScript. Currently, it looks like a visibility class is added, which overrides the `display:none;` property. We've added this feature to our [Trello Board] (https://trello.com/b/QBPKlQqf/foundation-sites). Feel free to vote this feature up.
Thanks!
