### ISSUE TITLE
Missing support for cancelling out of Reveal 'close' event

### ISSUE THREAD

**Issue by clone1985** [zurb/foundation#5114]
It would be very useful if it was possible to cancel out of the close event of the Reveal dialog, for example when a form has not been submitted.

Something like this:
```
('#my-modal').on('close', function( e ) {
    var ok = confirm( 'Are you sure you want to close this?' );
    if ( ! ok ) {
        e.preventDefault();
    }
}
```

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
