### ISSUE TITLE
[Interchange] Uncaught TypeError: Cannot read property 'trigger' of undefined 

### ISSUE THREAD

**Issue by niallobrien** [zurb/foundation#5121]
Hi all, I'm using html Interchange and as soon as I switch to the small view, I'm receiving the above error in the console.
It points to line 131 of foundation.interchange.js or line 2047 of foundation.js
```javascript
passed.el.trigger(passed.scenario[1], args);
```
Any suggestions as to what's causing this? Thanks.

**Comment by rafibomb** [comment]
There's been a lot of changes to Interchange since this issue was opened. We're not seeing any errors like this now on the docs or in projects. We'll close this here.
