### ISSUE TITLE
topbar menu-icon does not display on Android devices

### ISSUE THREAD

**Issue by sergeparis** [zurb/foundation#5134]
There is a bug on Android devices
box-shadow with no blur does not display
so instead of using the foundation box-shadow method to display the hamburger icon I just use the fa-bars icon from font awasome

hope it helps

regards
Serge

**Comment by rafibomb** [comment]
Adding the -webkit prefix doesn't solve it either. Looking into another suitable fallback.

**Comment by rafibomb** [comment]
MULTIPLE box shadows are not supported in 2.3

<img width="549" alt="screen shot 2015-10-09 at 11 43 29 am" src="https://cloud.githubusercontent.com/assets/5652085/10402644/787a6dce-6e7b-11e5-90fd-6e560df763ee.png">


It looks like addressing this would be a breaking change where the mixin and markup would need to be written. We did add the vendor pre-fix to for good measure e4403ce

In Foundation 6 we are addressing this to make sure Android 2.3+ displays the icon.
