### ISSUE TITLE
Abide: Manually Check if Form is Valid

### ISSUE THREAD

**Issue by rdetert** [zurb/foundation#5171]
I don't see a method to manually check if a form is valid. There is a trigger `.on('valid'` but I'm having issues with it. It seems to get called *after* the `.on('submit'` trigger no matter what I do.

**Comment by rdetert** [comment]
@imolorhe I've run into this issue again and calling directly like you've done works well for now. Looking forward to when the milestone is complete.

**Comment by imolorhe** [comment]
@rdetert :+1:

**Comment by jeaniec** [comment]
Hi all, I've made a commit where there's an option for different levels of control when it comes to validation. As this would be a breaking change (i.e. we're holding off until Foundation 6 to make this MAINSTREAM), I've still included the previous live_validate and validate_on_blur options.

You can, however, use this option when you initialize Foundation, like so:
```
$(document).foundation({
abide: {
validate_on: 'manual'
}
})
```
etc.

If you go with 'manual,' you can trigger your custom validations in this sort of manner:

```
$('#myInput').on('keydown', function() {
  $(this).trigger('validate.fndtn.abide');
});
```


Closing this issue for now with https://github.com/zurb/foundation/commit/3603d82e84cc43827b09d78bbf64c1da672155d5
