### ISSUE TITLE
5.2.2 version of Offcanvas looks very different between 'foundation' and 'foundation-rails'

### ISSUE THREAD

**Issue by alexagranov** [zurb/foundation#5183]
How are these supposed to be kept in sync?  They both claim to be version 5.2.2 of Offcanvas but are clearly not.

https://github.com/zurb/foundation/blob/master/js/foundation/foundation.offcanvas.js

https://github.com/zurb/foundation-rails/blob/master/vendor/assets/javascripts/foundation/foundation.offcanvas.js

**Comment by rafibomb** [comment]
Looks like this has been resolved, thanks!
