### ISSUE TITLE
Top bar Safari problem

### ISSUE THREAD

**Issue by krisztinatoth** [zurb/foundation#5222]
Expanded and collapsed Top Bar does not show the third level dropdown in Safari for Win and iOS. The third level navigation is not activated, or hidden by css.
Example here: http://tests.krisztinatoth.com/topbar/

Tested with a clean install of Foundation 5.2.2 and 5.2.1.

**Comment by jeaniec** [comment]
@gakimball is it okay to just place this in the topbar SCSS partial?

**Comment by gakimball** [comment]
The fix @ckaz suggested was implemented in this commit: 9b42da26e5e0af8a8774ce750245e925b8828337

And it was moved from the bottom of the file into the main Sass as part of this commit: 71d9af40a309e609b48ec0b8d2c9c4a16f00ddd6
