### ISSUE TITLE
Are "accordion groups" really a thing?

### ISSUE THREAD

**Issue by Vaguery** [zurb/foundation#5245]
I was pleased to find [the documentation for splitting and toggling multiple accordion groups across containers](http://foundation.zurb.com/docs/components/accordion.html), but can't seem to get it to work. To clarify, I had a peek at https://github.com/zurb/foundation/blob/master/js/foundation/foundation.accordion.js and looking at [how the options array is parsed in `foundation.js`](https://github.com/zurb/foundation/blob/master/js/foundation/foundation.js#L489), I'm wondering whether the example _could_ work.

That is, if the "accordion group" is just a string assigned to `data-accordion`, and that gets parsed as a list of key:value pairs, will this actually do anything at all?

If not, I'll be happy to try to fix it. I just need a bit of advice from somebody closer to the codebase about what happens when `data-accordion="foobar"` is parsed upon rendering.

**Comment by rafibomb** [comment]
Sorry this issue went stale. I don't see that option anymore on the docs. We'll see if this is feasible about it for the next version or we'd love to see a PR because it would be valuable to the community.
