### ISSUE TITLE
top-bar self toggle

### ISSUE THREAD

**Issue by 92arpitgoyal** [zurb/foundation#5269]
I made a one page website with two navigations one below another and on mobile version the above one collapses but not the second one
now the problem i faced is when i click on buttons from second nav, the first navigation toggles itself.
It is not supposed to happen, as websites with two navigations may have problems with it
maybe the toggle' code need a change?
for now I have applied preventDefault and stopPropagation to them(suggested by a friend)
link for it is cpll.co/photovisi

**Comment by rafibomb** [comment]
I'm pretty sure this is not an issue anymore in the latest version. I'll close it here. Thanks!
