### ISSUE TITLE
Tooltip positioning behavior problems

### ISSUE THREAD

**Issue by dizpers** [zurb/foundation#5272]
Hi everyone! I use tooltips in rich media webapp to describe some elements. Look at image below.
![screenshot from 2014-06-06 12 26 15](https://cloud.githubusercontent.com/assets/1190667/3196915/86875868-ed3b-11e3-811c-d52116b07a24.png)
As you can see - tooltip has a lot of space in left to be displayed, but it flows to right (relative to described element - "[4]").

Is this positioning behavior ok and if I want more "smar" positioning behavior - I must edit tooltip js code? And what about horizontal scrollbar appearing after tooltip appears?

PS I also tried make tooltip positoin left. But in this case tooltip position totally breaks. Look:
![screenshot from 2014-06-06 12 37 32](https://cloud.githubusercontent.com/assets/1190667/3196948/d7b52980-ed3c-11e3-9c8e-6182a3449801.png)

**Comment by rafibomb** [comment]
I'm not seeing this happen on the docs anymore. If you still have an issue, please reopen with example code. Thanks!
