### ISSUE TITLE
Reveal: Cannot read property 'bg_class' of undefined 

### ISSUE THREAD

**Issue by Koviko** [zurb/foundation#5281]
This is directly related to #3766.

When modals are generated after Foundation is initialized, it seems possible for them to not have `reveal-init` settings. I've run into this bug during a project where the modals are generated by an Angular directive. The bug occurs when you attempt to click the modal's `.close-reveal-modal` button.

I've been able to remedy this locally by defaulting `settings` to the default settings object in the `touchend.fndtn.reveal` and `click.fndtn.reveal` events handler.

I've submitted a pull request (#5282) that implements this change in **foundation.reveal.js**.

**Comment by jeaniec** [comment]
Look like this was closed with PR https://github.com/zurb/foundation/pull/5282
