### ISSUE TITLE
rtl topbar issue

### ISSUE THREAD

**Issue by dragondz** [zurb/foundation#5291]
Hi

Topbar rtl direction is not set on toggle-topbar menu-icon on small screen
And .top-bar-section ul li is not set to rtl also.

I had to correct that with this sass code:

```
.toggle-topbar.menu-icon
        {
            direction: rtl;
            padding-left: 40px;
            padding-right: 0;
            right: 15px;
            left: auto;
            
            a
            {
                text-indent: 0;
            }
        }
```

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
