### ISSUE TITLE
Using data-tab-content attribute instead of href on tabs does not work

### ISSUE THREAD

**Issue by tobiasf** [zurb/foundation#5310]
I tried using data-tab-content attribute instead of href, but there seems to be a bug in the code. I made a workaround with the following code in foundation.tab.js on line 105:
```
// allow usage of data-tab-content attribute instead of href
if (anchor.data('tab-content')) {
  target_hash = '#' + anchor.data('tab-content').split('#')[1];
  target = S(target_hash);
}
```
It works perfectly with this little fix

**Comment by jeaniec** [comment]
Committed. Thanks @tobiasf!
