### ISSUE TITLE
select with size attribute defined

### ISSUE THREAD

**Issue by istrasoft** [zurb/foundation#5326]
the _forms.scss forces a fixed height for select elements, even those with a size attribute set !

Please fix by including, for example :

    select[size] {
      height: auto;
    }

**Comment by zurbrandon** [comment]
I'll close this for now, I think that the height matching inputs seems more important and can easily be over ridden as personal preference.

**Comment by istrasoft** [comment]
So this means that with standard foundation there is NO way to have selects with height without override ? curious choice
