### ISSUE TITLE
Equalizer 5.2.3 broken and inconsistent

### ISSUE THREAD

**Issue by stephenvoisey** [zurb/foundation#5327]
Hey folks, is there a 5.3 version Equalizer JS floating around or is 5.2.3 the latest one?

If so, it is broken in Firefox and in Chrome even more issues seem to rear their ugly head. This issue has been previously reported on the forum thread months ago, but the issues remain.

First off: Check out this codepen:

http://codepen.io/internata/pen/ngGfD/

Using data equalizer how you'd expect, on a parent container, then watching on the child elements (columns), doesn't work at all.

If the data-equalizer-watch is applied to the panels, things improve - at least in the codepen. But this is how I see my code in final page in Firefox and Chrome

![broken equalizer](https://cloud.githubusercontent.com/assets/7124370/3297784/9f31e188-f5f8-11e3-9ad2-023f1724a30c.jpg)

Both have not rendered the containing element height correctly, making elements overlap the row below.

And here is the rub. If you resize the browser just a pixel - BOOM - it fixes it and renders properly in both browsers. I believe, reading through the thread this is a reflow issue that was supposedly fixed.

If I take the equalizer code from the docs - a very simple div setup - Firefox behaves, but Chrome does not.

I've looked at the older code and tried it on the site. This actually works better for me - the 5.1 equalizer has this:

<code>

      if (settings.use_tallest) {
        var max = Math.max.apply(null, heights);
        vals.height(max);
      } else {
        var min = Math.min.apply(null, heights);
        vals.height(min);
      }

</code>

Where as in 5.2.3 it is this:

<code>

      if (settings.use_tallest) {
        var max = Math.max.apply(null, heights);
        vals.css('height', max);
      } else {
        var min = Math.min.apply(null, heights);
        vals.css('height', min);
      }

</code>

For me, the old 5.1 code actually renders better - almost. It seems to give the containers twice the padding at bottom. But at least the containers don't overlap like shown above, and Chrome behaves.

At this point I'm looking at alternatives or using CSS display:table-cell etc.

**Comment by othermachines** [comment]
I am having the same problem as FernE97 - exactly as described - in **Chrome** (39.0) and **Opera** (26.0). In **IE 11** the rows don't overlap but are in fact too tall - until I resize the browser window at which time it adjusts to the correct height. 

**Firefox** (32.0.3) seems to be the only browser that resizes the columns correctly, on page load with no overlap.

Using Foundation 5.5.0.

**Comment by othermachines** [comment]
Following up on my last post... 

My problem seems to be at least partially related to an image being loaded with Interchange in the containers that are being resized. On page load it is calculating the height of the containers as being less than they actually are. Reinitializing (as below) doesn't seem to help. If I load the images the conventional way it works fine. Is there something I'm missing here?

This has no effect:
```javascript
$(document).foundation();
$(document).foundation('reflow');
```

I also tried targeting Equalizier specifically with

```javascript
$(document).foundation('equalizer', 'reflow');
```

My HTML:

    <div class="row" data-equalizer>
      <div class="small-12 large-8 columns" data-equalizer-watch>
        <img data-interchange="[images/slider-img01_16x9_large.jpg, (default)]" alt="" />
        
      </div>
      <div class="small-12 large-4 columns" data-equalizer-watch>
        <div class="panel">
          <h1>From the Principal</h1>
          <article>
            <figure>
              <img data-interchange="[images/img01_thumb.jpg, (default)], [images/img01_16x9.jpg, (large)]" alt="" />
              
            </figure>
            <header>
              <h1>Vestibulum augue nulla, consequat a accumsan dignissim</h1>
            </header>
            <p>Cras quis nulla semper, efficitur justo non, pulvinar nunc. Ut at nunc blandit, maximus tellus quis, viverra dui. </p>
            <footer>
              <small><a href="#">Read more</a></small>
            </footer>
          </article>
        </div>
      </div>
    </div>

Thanks!

**Comment by katrincwl** [comment]
you may try to use the Foundation debounce utility, 
e.g:
    $(window).on('resize', Foundation.utils.debounce(function(e){
        $(document).foundation('equalizer', 'reflow');
    }, 10));

The equalizer should then be able to recalculate the height correctly after the window resize

**Comment by jeaniec** [comment]
With a recent commit, you can manually group equalizer elements into groups by setting the data-equalizer and data-equalizer-watch attributes to the same group name. This might help alleviate problems we're having with this issue.
