### ISSUE TITLE
.button.post/prefix not rendered properly when using custom settings

### ISSUE THREAD

**Issue by jansson** [zurb/foundation#5329]
Line 209 in _forms.scss says the following:
    line-height: rem-calc(34);

Should this really be here at all? The prefix-postfix-base seems to take care of line-height properly, and then this hardcoded value overrides and breaks everything. Anyone with more insight into this may be able to tell what this is doing here, but removing this line seems to make the text properly positioned within the button.

**Comment by tdhartwick** [comment]
Looks like this issue has already been fixed with a similar solution to mpserellis' answer. Let us know if it's still an issue.

**Comment by MacWorks** [comment]
I'm still seeing this as an issue. I also had to divide by 2 to get it close to right ...

line-height: ($input-font-size + ($form-spacing * 1.5) - rem-calc(1)) / 2;
