### ISSUE TITLE
Deprecate Non-Namespaced JS Event Triggers in 5.4

### ISSUE THREAD

**Issue by thedeerchild** [zurb/foundation#5330]

**Comment by javiercejudo** [comment]
As of 5.4.7 this has not been deprecated (eg. https://github.com/zurb/foundation/blob/v5.4.7/js/foundation/foundation.offcanvas.js#L114).

I guess it should either be deprecated or the deprecation notices (eg. https://github.com/zurb/foundation/blob/v5.4.7/doc/pages/components/offcanvas.html#L346) updated. The current wording might make people think non-namespaced events have already been deprecated.

Happy to send a PR with either of those changes.

**Comment by rafibomb** [comment]
@javiercejudo A PR would be awesome!

**Comment by javiercejudo** [comment]
@rafibomb would you prefer a PR removing the non-namespaced events (the original issue) or updating the deprecation notices and leaving the events as is?
