### ISSUE TITLE
Tabs: Multiple events fired when deep_linking is enabled

### ISSUE THREAD

**Issue by dsignr** [zurb/foundation#5383]
When foundation's tab component is used normally, the callbacks, as [specified in the docs](http://foundation.zurb.com/docs/components/tabs.html#callbacks) fire only once. 

![screen shot 2014-06-26 at 10 48 52](https://cloud.githubusercontent.com/assets/5097028/3394946/7866d8ce-fcf1-11e3-81f4-77c8fcc100b0.png)

This is expected behaviour and it works fine. 

However, when you add the option:
```html
 data-options="deep_linking:true"
```
The events are fired multiple times, typically 4 or more times:

![screen shot 2014-06-26 at 10 49 08](https://cloud.githubusercontent.com/assets/5097028/3394950/84c1674c-fcf1-11e3-8fc5-2f761dee9dbb.png)

Is there a way to make them fire only once? Or am I just missing something?? Thought it could be a possible bug and hence the request.

Thanks!

**Comment by jeaniec** [comment]
Inadvertently fixed with https://github.com/zurb/foundation/commit/af0095559929a53da1ad89574bc5c3e888a7e8cf. Love when that happens.
