### ISSUE TITLE
Abide validation statuses triggered twice.

### ISSUE THREAD

**Issue by lgrandicelli** [zurb/foundation#5392]
Provided a simple form as the one from Foundation 5 Docs:

    <form data-abide="ajax" id="myform">
        <div class="name-field">
            <label>Your name <small>required</small>
                <input type="text" name="users_name" required pattern="[a-zA-Z]+">
            </label>
            <small class="error">Name is required and must be a string.</small>
        </div>
        <button type="submit">Submit</button>
    </form>

and a simple jQuery piece of code to handle abide validation

    $('#myform').on('valid.fndtn.abide', function(e) {

        // Handle the submission of the form
        console.log(e);
    });

THAT console.log is always fired twice!

Did any of you encountered the same issue? Any help please?
Thank You.

**Comment by pickledegg** [comment]
Same issue here. Changing to 'valid' did the trick. Second issue I've encountered with Abide so far, but good overall.

**Comment by maiolica** [comment]
+1

**Comment by hdra** [comment]
I believe this issue is cause because of the way [jQuery's event](http://api.jquery.com/on/#event-names) namespacing works. Basically, triggering a `valid` event will fire any listener listening to `valid.*` events.

Because Foundation is deprecating the `valid` event and moving to the `valid.fndtn.abide` event, the current version of the code triggers both during validation, but because of the way jQuery's event works, listener for `valid.fndtn.abide` will fire for both `valid` and `valid.fndtn.abide` event, and since both events fired, the listener ran twice, each for both event.

The obvious solution is to simply trigger the old events during validation, and I actually have prepared a PR with this fix, but I'm not sure what the developer's intentions are, since I noticed they are triggering both versions of the events in other places as well.

**Comment by patrickgalbraith** [comment]
Also having this issue. 

As mentioned earlier it is due to the way that jQuery event namespacing works. 
Simple fix is to check the event namespace. 

Like this:

    $('form').on('valid.fndtn.abide', function(e) {
        // Fix for valid event firing twice
        if(e.namespace != 'abide.fndtn') {
            return;
        }

        // Handle form...

**Comment by CrashIT14** [comment]
@patrickgalbraith +1 This solved it. Just remember to take 'e' as input in the function.

**Comment by pickledegg** [comment]
@patrickgalbraith cleanest solution I've seen yet, thanks.

**Comment by patrickgalbraith** [comment]
@hdra The fix is actually fairly simple instead of triggering the valid event like this:

    form.trigger('valid').trigger('valid.fndtn.abide');

Trigger it like this:

    form.trigger('valid.$').trigger('valid.fndtn.abide');

This will prevent both from triggering when listening to 'valid.fndtn.abide'.

See this fiddle for example http://jsfiddle.net/z0qfp6yh/

**Comment by DustinJSilk** [comment]
Using just "valid" did the trick. thanks

**Comment by mikejoyceio** [comment]
Using 'valid' worked for me too.

**Comment by TheHanna** [comment]
I'm having the same issue as @IshanUpmanyu. Is there a separate ticket for it somewhere? The solutions in this one did not resolve it. I still get multiple events triggering when I submit a form with `data-abide="ajax"`

I recreated the issue in Codepen: http://codepen.io/TheHanna/pen/XJyxXJ

Pop open the console and click submit on the form--you'll see the number of events logged increase by one each time you click.

**Comment by diegoviola1** [comment]
@TheHanna this is because you are binding the "fndt" event each time that you press the submit button. You don't need the onclick event, this work is made already by abide.

**Comment by TheHanna** [comment]
Thanks @diegoviola1, that was it.

**Comment by batfan** [comment]
@patrickgalbraith Thanks for that fix. Thought I was going nuts.

**Comment by redmoik** [comment]
I found a simpler solution that works even if you have a dynamic form. This is a combination of Foundation's JavaScript utilities.  

This will work as follows:
1. Validate the fields (assuming your fields has "required" tags and "error" classes)
2. If valid, prevent from submitting same content for 1000 milliseconds
3. (Optional) Clear the fields (add your function to clear all fields)
4. Re-validate

<pre>
$(document).on('valid.fndtn.abide','#myForm', Foundation.utils.debounce(function(e) {// Handles the Submission

    //ajax function here
      console.log('I am not fired twice');
    //clear all fields for re-validation after successful submission  


}, 1000, true));

</pre>

**Comment by bruteforcehub** [comment]
I did this and it fixed the issue:

 $(entry[0]).on("submit valid.fndtn.abide", function (event) {
                    // Handle the submission of the form
                   
                event.preventDefault();
            });

**Comment by mikejoyceio** [comment]
Using [jQuery's .one() method](http://api.jquery.com/one/) resolves this issue for me. 

```javascript
$('#form').one('valid.fndtn.abide', function() {

// Handle valid form...

});

```

The  .one() method is identical to  .on(), except that the handler is unbound after its first invocation.
