### ISSUE TITLE
mobile_show_parent_link doesn't exist?

### ISSUE THREAD

**Issue by wldcordeiro** [zurb/foundation#5415]
In the documentation for the topbar it mentions this option. But looking at the Javascript file for the topbar this doesn't seem to exist.

`foundation/js/foundation/foundation.topbar.js`

```js
// ...
    settings : {
      index : 0,
      sticky_class : 'sticky',
      custom_back_text: true,
      back_text: 'Back',
      is_hover: true,
      scrolltop : true, // jump to top when sticky nav menu toggle is clicked
      sticky_on : 'all'
    },
// ...
```

Is this on purpose? This seems like a really useful feature for when you have a mobile site.

**Comment by rafibomb** [comment]
Looks like that's been added in

{
  sticky_class : 'sticky',
  custom_back_text: true, // Set this to false and it will pull the top level link name as the back text
  back_text: 'Back', // Define what you want your custom back text to be if custom_back_text: true
  is_hover: true,
  mobile_show_parent_link: false, // will copy parent links into dropdowns for mobile navigation
  scrolltop : true // jump to top when sticky nav menu toggle is clicked
}
