### ISSUE TITLE
Sticky off-canvas

### ISSUE THREAD

**Issue by prembo** [zurb/foundation#5427]
A _sticky_ off-canvas would be most useful.  I note that there was another PR (#5135).  Is there any interest in adding this ability for the Offcanvas component?  

There have been [various workarounds](https://groups.google.com/forum/#!topic/foundation-framework-/du1SXOeI_Yo) posted on forums and also a couple of alternative off-canvas components e.g. [Off.Canvas](http://www.aidanzealley.com/offcanvas/).

Would love to stick with Foundation for Off-canvas though.

**Comment by rafibomb** [comment]
We added this to our "Suggested Features" section in our planning board for the next version. You can do this now with some CSS like so: http://codepen.io/rafibomb/pen/hApKk(NOTE: does not work with Joyride or Magellan). You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by iamjoshfrank** [comment]
@rafibomb - your Codepen link goes to a 404. Can you re-post it, or has this been addressed elsewhere?

**Comment by hyperfire4590** [comment]
I believe the Codepen link accidentally included additional text of "(NOTE."  If you remove that, the link works fine. Try this: http://codepen.io/rafibomb/pen/hApKk
