### ISSUE TITLE
In _dropdown.scss check if $f-dropdown-triangle-size is set to 0

### ISSUE THREAD

**Issue by istrasoft** [zurb/foundation#5450]
If the triangle is disabled by setting $f-dropdown-triangle-size to 0, none of the :after and :before triangle styles should be output in the CSS.

**Comment by tdhartwick** [comment]
@istrasoft Thanks! Just made the changes here https://github.com/zurb/foundation/commit/792b8c6acb2b65afaa06c1784ff9076a9c1866dd

I've also changed the default size back to the original 6px.
