### ISSUE TITLE
Button Hover and Border variables

### ISSUE THREAD

**Issue by rlafranchi** [zurb/foundation#5455]
I would like to add button and hover variables and have worked on the code below, but need someone to review and verify that it works properly.

https://github.com/rlafranchi/foundation/blob/c3f8d81e1812ed341b3b31fa93655f365a50c5b0/scss/foundation/components/_buttons.scss

**Comment by gakimball** [comment]
Those variables made it in with this commit: 652526a06343940f7bfe996ef66d3d507a3fa2e3
