### ISSUE TITLE
Topbar Dropdown is set to left: -999999px when toggle inside is clicked

### ISSUE THREAD

**Issue by Owlbertz** [zurb/foundation#5483]
I created a dropdown in my top-bar navigation. Inside this dropdown, there is an anchor that works like a toggle with AngularJS:
```
<a href ng-click="toggleTileEditing();">
                        Enable editing
</a>
```
While toggling between the two states works and the dropdown menu hides after clicking, the next time it is opened it has the wrong element.style:
![2014-07-22 09_58_14-my tiles](https://cloud.githubusercontent.com/assets/4280373/3655182/015fb054-1176-11e4-9a22-51c5e1c9487a.png)

Clicking the body of the page seems to reset this.

**Comment by rafibomb** [comment]
Not sure if this is happening to anyone using the standard jQuery version. We're not supporting an Angular version now. We'll close this here for now as we are working on the next version with lots of updates to top-bar.
