### ISSUE TITLE
[BUG] default global namespace value causes jquery error on init

### ISSUE THREAD

**Issue by limnick** [zurb/foundation#5486]
See http://sharktopus.com/foundationtest.html for an example

see set_namespace here:
https://github.com/zurb/foundation/blob/master/js/foundation/foundation.js#L380

if the font-family has ' in the name, i.e. 'Times New Roman' then jquery selectors will fail to compile and various functionality through foundation breaks. It should either be escaped like other uses of the font-family, or another way of setting the default namespace should be used. 

I'm not sure the rationale behind getting a global font-family as a unique identifier to begin with.

Let me know if there's anything else I can provide to help

**Comment by jeaniec** [comment]
@limnick, setting the font-family in the meta tag is a trick that we use to pass the media queries through to jQuery. If you don't have anything set already, the namespace should be an empty string by default, but you could also try manually setting it to an empty string by setting the property on the Foundation object

Foundation.global.namespace = '';

**Comment by limnick** [comment]
I understand how to fix this issue one-off, I just feel like the library should not completely shut down because of a single quote in the font-family. Perhaps just doing string replacement and removing the quotes prior to passing the namespace to jquery?

**Comment by jeaniec** [comment]
@limnick That would definitely work. We'll look into storing these string (with quotes) values via a different method with the next release. Maybe in an array or a JSON object or something.

**Comment by jeaniec** [comment]
@rafibomb let's add this to a 6.0 release as well.

**Comment by Elephant-Vessel** [comment]
Is this intended to have been fixed in version 5? Using 5.5.3 I still get this problem.

**Comment by DanielRuf** [comment]
> Is this intended to have been fixed in version 5? Using 5.5.3 I still get this problem.

Foundation Sites 5 is not supported anymore.
