### ISSUE TITLE
Support internal container for Ajax Reveal windows

### ISSUE THREAD

**Issue by davejlong** [zurb/foundation#5523]
When creating modal window's it would be helpful to be able to have a container within the modal div that the Ajax content is loaded into:

```html
<a href="/form.html" data-reveal-id="formModal" data-reveal-ajax="true">Open Form</a>

<div id="formModal" class="reveal-modal" data-reveal>
    <h2>New Something</h2>
    <div class="reveal-modal-content"></div>
    <a class="close-reveal-modal">&#215;</a>
</div>
```

In the example above the content would be loaded into `.reveal-modal-content` if available. If the element is not available, then the content would be loaded into `.reveal-modal` as it is currently.

**Comment by rafibomb** [comment]
There is a PR ^ in the queue for this. We'll close this in favor of it.
