### ISSUE TITLE
clicking inside/outside of .topbar does not close the menu (hover)

### ISSUE THREAD

**Issue by chrishough** [zurb/foundation#5551]
I have the following menu in slim:
```ruby
header[class="navigation-wrapper contain-to-grid fixed"]
  nav[class="top-bar" data-topbar data-options="scrolltop:false;is_hover:true;"]
    ul[class="title-area"]
      li[class="name"]
        = link_to AppConfig.product['name'], root_path
      li[class="toggle-topbar menu-icon"]
        a[href="#"]
          span
            |&nbsp;
    section[class="top-bar-section"]
      ul[class="nav-header right"]
        li
          a[href=""]
            |Sign In
        li
          a[href=""]
            |Register
        li
          = link_to "POV", AppConfig.product['social_blog'], target: "_blank"
```
and I have to use the following js to make the menu close when the page is clicked outside of the nav or hamburger icon:
```js
    $(document).mouseup(function (e){
      var container = $(".top-bar");
      if (!container.is(e.target) // if the target of the click isn't the container...
          && container.has(e.target).length === 0){ // ... nor a descendant of the container
          container.removeClass('expanded');
      }
    });
```
this does not seem right...

I am using https://github.com/zurb/foundation-rails for this project

**Comment by rafibomb** [comment]
We want the clickable top-bar to NOT close on click if it is a dropdown link to a submenu. 

Example: http://foundation.zurb.com/docs/components/topbar.html#clickable-top-bar
Click to open dropdown, then click Dropdown level 1a

It closes on click and should not, but should on any other link that does not have class `has-dropdown`

**Comment by alubbe** [comment]
Since #6127 was closed in favor of this, what is the status? Is this now part of the goals for 5.5.1?

**Comment by chrishough** [comment]
@rafibomb  I have been able to successfully test removing... 
```js
     $document.mouseup(function (e){
       var container = $('.top-bar');
       if (!container.is(e.target) && container.has(e.target).length === 0){
         container.removeClass('expanded');
       }
    });
```
but I am still running 5.5.0.  I would have assumed this was in the 5.5.1 release? am I mistaken?

Cheers.

**Comment by jeaniec** [comment]
@rafibomb we're declaring this as fixed, correct? So clickable non-hover drop bars now have dropdown links as NOT closing the menu and regular links CLOSING the menu.

**Comment by gramila** [comment]
@jamieshark I am having this issue with my top-bar dropdown. It is not closing when I click on regular links on the menu. I am using foundation 6.

**Comment by gccumber** [comment]
@jamieshark Same as @gramila - but to be more specific, on mobile. It doesn't seem reasonable to me that when users click on a regular <a> link, that menu should stay open. same as what @nkoren described on Oct. 20 (above).
