### ISSUE TITLE
right off canvas + visibilty class bug

### ISSUE THREAD

**Issue by elbarto132** [zurb/foundation#5561]
If you add a visibility class to the section tag of a right off canvas menu button the button bugs
Go to the "Tab Bar Section" -> "Right Section" example and add a visibilty class like "visible-for-small-up" to the right section to see it:
http://foundation.zurb.com/docs/components/offcanvas.html

**Comment by zurbrandon** [comment]
Hmm visible-for-small-up seems to be screwing that up, but also doesn;t exist as a class. Thats just showing it for every screen size. 

Using another seems to work.
