### ISSUE TITLE
exit-off-canvas is visually opinionated

### ISSUE THREAD

**Issue by shukriadams** [zurb/foundation#5568]
As per the latest documentation, .exit-off-canvas is supposed to be placed on an off-canvas menu item if we want clicking on that item to automatically close the menu. That would suggest the class is functional in nature, yet, it visually alters its elements too, in ways that seem unrelated to the function of menu closing.

- Position:absolute cases a column of menu items to now render heaped on top of each other. I'm currently overriding with position:relative to correct for this.
- background-color is forced to grey, so Foundation label colors no longer get applied to my off canvas menus items.

**Comment by rafibomb** [comment]
We hear you on this. We added this to our F-6 list. We are not going to be making this change for F-5 but will for F-6. Thanks!
