### ISSUE TITLE
-webkit-backface-visibility causes crash on iPad (Chrome & Safari)

### ISSUE THREAD

**Issue by skoften** [zurb/foundation#5603]
Tested on two iPads 2, one with iOS 6.1.3, another with 7.0.4.

Caused by : -webkit-backface-visibility: hidden;

After disabling all of these lines (required by off-canvas), pages scroll mooth again and don't crash the browser.

Tested in both Safai and Chrome.

**Comment by avr** [comment]
If possible, I'd love to see this sooner than later.  As a note, we've noticed this issue mostly on older hardware - iPhone 4, 4S.

My PR on #5205 makes this a setting - leaving the current behavior as default.

**Comment by rafibomb** [comment]
Closing in favor of https://github.com/zurb/foundation/issues/5205
