### ISSUE TITLE
Abide pattern name should be in a different attribute

### ISSUE THREAD

**Issue by imolorhe** [zurb/foundation#5607]
Currently, the way the Foundation abide validation system works, a custom pattern which is not a valid input type is specified in the javascript and the name of the pattern is used in the pattern attribute of the input element. e.g.

```html
  <input type="text" pattern="zimbabwe_tel" required>
```
This works fine as long as the pattern is specified in the script, and the abide validation script is included in the page. However, if the page loads without the abide validation script for any reason (like slow internet connection), the default browser validation kicks in and wouldn't allow the form to be submitted because the input value doesn't match the specified pattern. Below is a link to a JSBin showing the issue.

http://jsbin.com/qeditesunube/1/

I am not sure if this kind of issue can be prevented with the current setup, so I would suggest that named patterns should probably be in a different attribute, like a data- attribute.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
