### ISSUE TITLE
Foundation Resources

### ISSUE THREAD

**Issue by prestonmcp** [zurb/foundation#5609]
Hey community, If you any plugins, themes, tutorials or other great things you've made to help out Foundation, let us know!

Resources page: http://foundation.zurb.com/develop/resources.html

Give us a link with your name and we can check it out to see if it will go well on our Resources page.

Thanks!

**Comment by LebCit** [comment]
Hello,
I've just made a Cool WordPress Theme, aka "Nassim", using Foundation 5.5 and Underscores.
Demo : http://nassim.intowp.com/
Docs : http://nassim.intowp.com/docs/
Hope you'll like it !

**Comment by sloyer** [comment]
Hello Zurb!

I am saddened to announce I would like the removal of my Wordpress theme "WPBaseFoundation" theme. I have not touched the theme in quite awhile and would not like anyone to be upset by a theme that's become out dated and ruins the "Awesomeness" that is Foundation. 

I switched employers and during the transition the theme fell behind and many other great themes have came along! I am excited to say that I am creating another theme that will work as a boilerplate for a bare minimal theme utilizing not only Foundation but the Twig Templating Engine for Wordpress.

Thank you for allowing my theme to be shared and I can't wait to submit my next theme. Sometime in the next month =)

https://github.com/sloyer/WPBaseFoundation

**Comment by matjaztrontelj** [comment]
Pinegrow Web Editor - Visual site builder desktop app for Foundation

http://pinegrow.com

**Comment by lyphtec** [comment]
Express Foundation Template by lyphtec

Starter template for Express (Node / io.js) backend utilising jspm.io for browser package management (supports ES6!).

Repo: https://github.com/lyphtec/express-foundation-template
Live demo: http://express-foundation-template.azurewebsites.net/

**Comment by rafibomb** [comment]
https://github.com/marnen/foundation_form_builder via @marnen

**Comment by marnen** [comment]
@rafibomb Thanks! I should have posted here myself. :)

**Comment by rafibomb** [comment]
https://github.com/mgmartel/timber-foundation

**Comment by juliancwirko** [comment]
Free Ghost theme based on Foundation for sites with simple Grunt Scss workflow:
https://github.com/juliancwirko/abc

Meteor.js Foundation for sites package:
https://atmospherejs.com/juliancwirko/zf5

Blog post about Yeoman generator-zf5
http://julian.io/foundation-5-and-yeoman/

Blog post about Ghost theming with Foundation
http://julian.io/ghost-theming-with-zurb-foundation-and-scss/

**Comment by rafibomb** [comment]
Hey everyone - thanks for all you submissions! We just published all the tools, themes, and, integrations posted here. Let me know if anything is missing - Rafi at zurb . com   Thanks!

**Comment by dnomak** [comment]
flexible.gs is compatible with foundation : ) http://flexible.gs/support/

Flexible Grid System by Doğukan Güven Nomak

**Comment by SalahAdDin** [comment]
:+1: Very good thread :D
