### ISSUE TITLE
I found a problem

### ISSUE THREAD

**Issue by hiyali** [zurb/foundation#5616]
topbar - direction:rtl

error 
at: js/foundation/foundation.topbar.js    line : 221

This is my first time to response problem, so you know

- section.css({left: -(100 * topbar.data('index')) + '%'});
+ section.css({left: +(100 * topbar.data('index')) + '%'});

!!!: If you don't do this, dropdown can will be invisible

**Comment by jeaniec** [comment]
It looks like this is fixed by adding a "right" property on to the topbar.
