### ISSUE TITLE
Alert does not have an "open" event, or documentation is incorrect

### ISSUE THREAD

**Issue by grantnorwood** [zurb/foundation#5630]
While trying to use the Alert's open and close events, I've found the open event does not seem to exist as indicated in the [documentation](http://foundation.zurb.com/docs/components/alert_boxes.html).

In the docs at the link above, it states under the "Advanced" section:
```javascript
//We can respond to all the possible events.
$(document).on('open.fndtn.alert-box', function(event) {
  console.info('An alert box has been opened!');
});

$(document).on('close.fndtn.alert-box', function(event) {
  console.info('An alert box has been closed!');
});
```

However, 2 problems seem to exist here:

1. Searching for "close.fndtn.alert-box" returns zero results in the Foundation library - the event seems to be called "close.fndtn.alert".

1. Searching the Foundation library for "open.fndtn.alert" returns zero results - it does not seem to be an event at all.

Thank you for your attention on this, and please let me know if I can provide more info or otherwise be of assistance!

**Comment by gakimball** [comment]
You're right that `open` is not an event at all. (Which doesn't really make since anyway, because alert boxes aren't opened, just closed.) I corrected the documentation, which was referencing `close.fndtn.alert-box`, when the actual event is `close.fndtn.alert`.

**Comment by grantnorwood** [comment]
Thank you so much, Geoff!
