### ISSUE TITLE
Tabs scroll_to_content seems to ignore fixed Top Bar

### ISSUE THREAD

**Issue by ricardo-lewis** [zurb/foundation#5649]
Tabs scrolls the page right to the top of the window, ignoring the presence of a fixed Top Bar.

Tabs should instead scroll to right below the fixed Top Bar, which would be a Y coord of the exact height in pixels of the Top Bar.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
