### ISSUE TITLE
Specify multiple 'named' media query parameters for interchange?

### ISSUE THREAD

**Issue by oller** [zurb/foundation#5652]
A feature request I suppose, to make interchange more friendly / powerful.  A format to combine multiple 'named' media queries for interchange.  For example, say I want an interchange to fire only when both the named queries `large && retina` are met.

For example something like:
```
data-interchange="[image_path, (default)], [image_path, (large, retina)]"
- or -
data-interchange="[image_path, (default)], [image_path, (large and retina)]"
```

The docs explicitly states this is possible at https://github.com/zurb/foundation/blob/5eab832da39d677ec66bbded558916fcd070ac27/doc/pages/components/interchange.html#L78

"
You can easily include retina images by using a pixel-density media query for that image. **You can even combine multiple parameters in the media query if need be.** The retina media query would look something like this, but you can also use dpi or other pixel densities as well:
"

I can achieve this by injecting in the raw media query, but as soon as retina gets involved, that's 5 lines, each appended with an `and (min-width: Xpx)` to match the breakpoint I want to achieve.  Also, this current implementation is hardcoding breakpoints, so any change to these wouldn't be updated, whereas if this could be supported by the named queries, you'd still be in business.

Be interested to know your thoughts

Thanks!

**Comment by rafibomb** [comment]
We added this to our "components" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
