### ISSUE TITLE
Joyride is erroring out on templates

### ISSUE THREAD

**Issue by cereallarceny** [zurb/foundation#5689]
```
$(document).foundation({
    joyride: {
      scroll_speed: 500,
      template: {
        button: '<a href="#" class="small radius center-button button joyride-next-tip"></a>',
        prev_button: '<a href="#" class="small radius center-button button joyride-prev-tip"></a>'
      }
    }
  }).foundation('joyride', 'start');
```

Produces an error of:
`Uncaught TypeError: Cannot read property 'top' of undefined in foundation.joyride.js?body=1:775`

It appears as though the error is on this return statement:
```
return [
        el.offset().top < top,
        right < el.offset().left + el.outerWidth(),
        bottom < el.offset().top + el.outerHeight(),
        w.scrollLeft() > el.offset().left
      ];
```

So maybe `el` isn't defined?  I'm using Foundation 5.2.2 because I'm using the Rails gem.  Is this an issue that has been fixed since then?

**Comment by steoo** [comment]
It's still a bug, tried to work out with deep copy but not working yet.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
