### ISSUE TITLE
li.clearing-featured-img not responsive

### ISSUE THREAD

**Issue by giroin** [zurb/foundation#5719]
Using both clearing-thumbs & clearing-feature classes as per F5 docs example all elements keep their responsive width except for the li.clearing-featured-img. The result is not to have a responsive layout.

I tried to use small-block-grid-1 responsive is back but I miss clearing-featured-img effect.

Maybe the display:block rule (.clearing-feature li.clearing-featured-img - line 3135) is not the proper option.

Thx,
Giorgos

**Comment by rafibomb** [comment]
Ok, closing here. We're updating a lot of our JS for the next version so we'll keep this in mind. Thanks!
