### ISSUE TITLE
Gap between the top bar and the main image in Workspace Template

### ISSUE THREAD

**Issue by coala2000** [zurb/foundation#5744]
I have downloaded the complete copy of Foundation 5.4.0 and I copied in the Workspace template into the index.html file within the body tags. There is a gap between the top bar and the main image, there is also a black bar below the search box. I am using the Chrome 36.0.1985.143 and FireFox 32.0.

Thanks

**Comment by rafibomb** [comment]
Seems like, in testing this works fine now.
