### ISSUE TITLE
Inputs and textareas need better focus states

### ISSUE THREAD

**Issue by ghaida** [zurb/foundation#5745]
The gray glow doesn't look good, and one of the first things I'll do in a fresh project is disable that glow effect.
![screen shot 2014-09-05 at 10 31 02 am](https://cloud.githubusercontent.com/assets/342672/4168956/ae7a6854-3522-11e4-94dd-820d746d7a38.png)

**Comment by rafibomb** [comment]
We didn't add it if Foundation Apps so...

We set the default to $input-include-glowing-effect: false !default;

**Comment by arta** [comment]
Actually, I've been battling this issue for several hours now. Foundation's focus glow overrides browser's glow on text and textarea controls but not on select control. 1) How do we apply Foundation's glow on the select control? Or 2) How do we turn off Foundation's inconsistent glow override and restore browser's default glow over all controls (preferred!)? Thanks.
