### ISSUE TITLE
Magellan render artifact on Chrome

### ISSUE THREAD

**Issue by quinncomendant** [zurb/foundation#5749]
The example on the Magellan documentation page displays some part of a pink border when scrolling past a destination. This only occurs with a large screen size; resize the window to small and it displays correctly. It also doesn't occur in Safari. I'm using the docs in foundation revision 1a45d92be8af20bf6b3e8d28c12fdbc853205cce.

![screen shot](https://cloud.githubusercontent.com/assets/6884276/4175052/fd835c64-35bb-11e4-913c-9440fd26c60e.png)

**Comment by zurbrandon** [comment]
Doesn't look like this is anything specific to Foundation as it couldnt be duplicated on a few machines. Possibly due to how jquery handles scroll events on different machines. 

What type of machine are you working on? Is it constant across other ones for you?

**Comment by zurbrandon** [comment]
I'll close this for now but feel free to reopen.
