### ISSUE TITLE
input type="search" - the (x) button gets cut off in Safari

### ISSUE THREAD

**Issue by dgmstuart** [zurb/foundation#5755]
On an input with type `search` (e.g.The search box on the [Foundation docs page](http://foundation.zurb.com/docs/)) the padding on the search box partially obscures the (x) button which clears the content of the input (see screenshot)
![screen shot 2014-09-07 at 20 41 20](https://cloud.githubusercontent.com/assets/393167/4179460/52bd291a-36c7-11e4-8036-12a7c6675acc.png)

Also if you have e.g. `results=5` on the input element then a magnifying glass is rendered within the left side of the field - this is similarly obscured.

I guess Chrome implements these elements in a different way to Safari because they render fine in chrome.

Doesn't seem to be related to #5533

**Comment by zurbrandon** [comment]
Looks like it's a webkit issue and the only way to solve it would be to completely remove that padding. I'll close this since thats something we're not going to be able to do. Looked into this for a while and seems like a pretty common issue.

**Comment by dgmstuart** [comment]
OK thanks for looking :)

**Comment by dgmstuart** [comment]
There's a bug for this issue on the Webkit bug tracker: https://bugs.webkit.org/show_bug.cgi?id=111843
