### ISSUE TITLE
Nested modals doesn't work in Ajax

### ISSUE THREAD

**Issue by Schyzophrenic** [zurb/foundation#5791]
Using nested Modals works well, as described on the doc.
Nevertheless, it seems there is one major drawback in the way the reveal modals are implemented as it seems impossible to have nested ajax modals.

I use one div as a target, always the same, to load all my modals. They are all loaded in Ajax so it works fine accross the site. But things get messy when you try to load a modal within a modal as you define the same target ID. 

I have made a quick online demo to demonstrate the issue : http://schyzophrenic.free.fr/FoundationAjax/

Is there any other way than adding a div in the nested modal ? 

Thanks !

**Comment by jeaniec** [comment]
I recently tested this using the Mockjax library and the markup that you provided @Schyzophrenic. It seems this was fixed with a recent pull request https://github.com/zurb/foundation/commit/266423e7bfb21821ebf9af640064f2541f489307.
