### ISSUE TITLE
Reveal modal not in the page when set options animation: null

### ISSUE THREAD

**Issue by chuangbo** [zurb/foundation#5810]
If I set `data-options="animation:null"` to the modal div to disable the animation, the modal will not have a `top` in it. So that the modal might not be shown on the correct position.

Like this Pen http://codepen.io/anon/pen/holkL

```html
<a href="#" data-reveal-id="myModal">This modal not good</a>

<div id="myModal" class="reveal-modal" data-reveal data-options="animation:null">
    <h2>This modal not that good</h2>
    <p>The only different is this modal with options animation:null</p>
    <a class="close-reveal-modal">&#215;</a>
</div>
```

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by mitja-p** [comment]
I cannot vote on the issue on trello. But I would really like to have this bug fixed. It is really unexpected that animation works, but you turn off animation and it is broken.
