### ISSUE TITLE
Sass compile issue

### ISSUE THREAD

**Issue by paullaz** [zurb/foundation#5811]
This bit in _functions.scss fails in 5.4.4.0 on Rails

$modules: () !default;
@mixin exports($name) {
  @if(not index($modules, $name)) {
    $modules: append($modules, $name)} !global;
    @content;
  }
}

The "!global" is new from 5.4.3.1, removing it allows Rails to work.

**Comment by rafibomb** [comment]
This has been resolved here: https://github.com/zurb/foundation/issues/6148#issuecomment-69477175
