### ISSUE TITLE
Update box-sizing: border-box to new best practice

### ISSUE THREAD

**Issue by staaky** [zurb/foundation#5819]
See: 
- http://www.paulirish.com/2012/box-sizing-border-box-ftw/
- http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

box-sizing: border-box is currently implemented like this:
```
*,
*:before,
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box; }
```

Updating the implementation to the following will make it easier to reset box-sizing within components:
```
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
Components could simply reset on a parent element and have all their descendants inherit correct box-sizing, something that won't work with the current `* { box-sizing: border-box }` implementation:
```
.component {
  box-sizing: content-box;
}
```
Hopefully this can be implemented, would make things easier for third party components.

**Comment by tdhartwick** [comment]
@staaky Thanks! We just updated the codebase.
