### ISSUE TITLE
SideNav: Needs nesting padding option

### ISSUE THREAD

**Issue by doertedev** [zurb/foundation#5829]
*Story:*
As a frontend developer I expect my SideNav to support nesting. 

*Solution: 1*
A `_settings.scss` variable can be added to indent the nested Side-Navs. Adding a one liner is bullsh** here because only supporting one level of nesting would be just stupid. But, one could write a fancy scss function for nesting n-times adding the padding variable.

*Solution: 2*
Even more bullsh** to just do it via JS... But this is only bullsh** because there isn't a `foundation.sidenav.js` yet. And creating one just for the nesting would be just as stupid as only supporting one layer.

Let's be clever guys. Maybe in 2 or 3 days I can throw in a PR... if not someone would be neat enough to take over the lever :)

In deep love of this awesome project,
greetings from Germany.

**Comment by rafibomb** [comment]
We're actually going to do this for the next version as part of our menu-bar. A PR would be awesome here, or we'll figure it out then. Closing here as it's on our roadmap.
