### ISSUE TITLE
OffCanvas basically broken, or switches. You pick.

### ISSUE THREAD

**Issue by doertedev** [zurb/foundation#5850]
Well the discussion started here:
http://foundation.zurb.com/forum/posts/18632-offcanvas-and-duplicated-content

And I ended up with this:
http://pastie.org/9586894 (see {{ PROBLEM PART }} 1 + 2).

The duplicated content thing basically screws the reponsiveness over by causing 3-4 reflows. And if that is not the problem, IDs and headlines are. And basically every JS Module within your content:

In order to have a off canvas menu showing for medium-down but not large layouts, you'd have to insert your content twice. Once within the data-offcanvas container having a subcontainer called ```section.main-section``` and once beneath the whole offcanvas thing. 

So when I set my IDs correctly, I'd have to render my content somewhere COMPLETELY different, and then copy along... might look a little like this:

```js
(function(){

    $(document).ready(function(){

        var contentContainer     = $("#content-large")
            , offCanvasContainer = $("#content-small")
            ;

        contentContainer.children()
                        .clone()
                        .appendTo(offCanvasContainer);
    });
}());
```
Now after grudging a lot to even get the MADNESS of html div containers to properly layout with a 3-column-layout site which later is just a 1 layout site for medium-down, I realized a bug with switches, not in functionality but in optical switching: the offcanvas-contained- switches (all they do is limit the rows of a table underneath) within the offcanvas container flip correctly after clicking/tabbing+shift. The ones for the main container for large-up don't.

Now we can either a) consider this a bug or b) try to refactor the offcanvas thing. Because having a page layout person force an offcanvas navigation upon a 30" TV site visitor is just as weird as forcing a developer to render his page content twice or just as weird as forcing a developer to render his content and then copy it to another container. 

Sorry for the long read but I'm confused. And for the trolls: no I cant come up with a good solution for this right now. It's the HTML that causes my headache right now, so PLEASE if you have anything in mind that could tame this BEAST of div-forest: give me a hint. I need a beer and it's not even 10 in the morning... :-/

**Comment by tdhartwick** [comment]
@doertedev We're going to address this in Foundation 6. Thanks for bringing this to our attention. You can check out our roadmap here https://trello.com/b/QBPKlQqf/foundation-sites.
Cheers!
