### ISSUE TITLE
Dropdown javascript changes how page is rendered in version 5.4.4

### ISSUE THREAD

**Issue by liammcmurray** [zurb/foundation#5865]
We're in the process of upgrading from 5.0.2 to 5.4.4 and have noticed a different behaviour from using dropdown.

In 5.0.2, the default behaviour is to build the page, then expand it once the dropdown content is revealed.
(Example - the "research menu" content here: http://www.bath.ac.uk/research/videos/)
![screen shot 2014-09-26 at 14 30 46](https://cloud.githubusercontent.com/assets/3738895/4421190/698d3392-4581-11e4-8b1a-7a57abdbf5a8.png)

In 5.4.4, the default behaviour looks to be to consider the hidden dropdown content when rendering the page and accommodate by adding space when rendering.
(Example - as above: http://people.bath.ac.uk/lm317/research/videos/)
![screen shot 2014-09-26 at 14 30 57](https://cloud.githubusercontent.com/assets/3738895/4421194/6f9af490-4581-11e4-8154-a60f587ce2ed.png)

Anyone else noticing this, or - preferably - have a solution?

This issue is only noticeable on pages that have a length less than that of the exposed dropdown content, and only (for us) on a mobile device as that creates a long list of content in the dropdown.

**Comment by istrasoft** [comment]
Same problem, I was looking into upgrading, but this only appeared in last version after switching to a new JS for dropdown component handling proper positioning. I'm really sorry but this is in no way an acceptable behaviour, especially since it was behaving properly before. 

Please do adress this breaking change as soon as possible...

**Comment by gakimball** [comment]
A fix for this issue (#6242) should solve the same problem. By setting the dropdown to `display: none` while it's hidden, it won't overflow the page. ff12611acdc9e3272ad8fb14006a350f2d1936db
