### ISSUE TITLE
Tooltip tag uses the same ID as the target tag

### ISSUE THREAD

**Issue by waleedka** [zurb/foundation#5874]
This bug seems to have been introduced in this commit a809981877a96f38d431269c47a69891d329c86f. The tooltip template adds an ID attribute to the tip with the same value of the ID attribute of the target element. This causes more than one element in the document to have the same ID, which in turn causes random problems for anyone trying to find and manipulate the target element by it's ID.

**Comment by Lynesth** [comment]
Hey there.

You should change the label on this, it's related to tooltips not range-sliders.
I can confirm the bug described in this issue.

The fix would be easy on this though, just changing from line 144 of foundation.tooltip.js to this :
```javascript
selector : function ($target) {
      var dataSelector = $target.attr(this.attr_name()) || $target.attr('data-selector');

      if (typeof dataSelector != 'string') {
        dataSelector = this.random_str(6);
        $target
          .attr('data-selector', dataSelector)
          .attr('aria-describedby', dataSelector);
      }

      return dataSelector;
    }
```

I know all of this will be rewritten at some point but should easy fixes still be implemented ?

Regards,

Lyn.

**Comment by gakimball** [comment]
@Lynesth Thanks for the fix!
