### ISSUE TITLE
Why trigger resize event on window in foundation.topbar.js

### ISSUE THREAD

**Issue by yesmeck** [zurb/foundation#5892]
In https://github.com/zurb/foundation/blob/master/js%2Ffoundation%2Ffoundation.topbar.js#L234 the resize event is been triggered, this behavior leads to some codes depends on resize event mess.

**Comment by rafibomb** [comment]
Not sure if this is an issue specific to turbolinks or something else. Without more information, we'll close this here. Feel free to reopen with more information if it's still an issue.

**Comment by walter-schwarz** [comment]
I also have the same issue.
On line 240 of the the window resize event is called during the initialization of the top bar (see `.trigger('resize')`) .
```javascript
S(window).off('.topbar').on('resize.fndtn.topbar', self.throttle(function () {
  self.resize.call(self);
}, 50)).trigger('resize').trigger('resize.fndtn.topbar').load(function () {
  // Ensure that the offset is calculated after all of the pages resources have loaded
  S(this).trigger('resize.fndtn.topbar');
});
```
In my case the window resize event is used to redraw a number of graphs in a dashboard. These are first drawn after the data for them is loaded via AJAX. By firing the window resize event on load the graphs are drawn immediately with no data.
