### ISSUE TITLE
Apply fixed class when a page is refreshed, after scrolling past a sticky top bar

### ISSUE THREAD

**Issue by mintcanary** [zurb/foundation#5910]
I'm finding that if I refresh an already scrolled page (which then loads at its previous scroll position), the `fixed` and `f-topbar-fixed` classes are not (re)applied (so in my case, the page looks different/broken compared to when hitting it for the first time and then scrolling). Confusingly though, this is not the case in the Foundation [docs example](http://foundation.zurb.com/docs/components/topbar.html).

[Forum discussion](http://foundation.zurb.com/forum/posts/16152-sticky--already-scrolled-page)

**Comment by rafibomb** [comment]
Same thing? zurb/foundation: #5649

**Comment by Lynesth** [comment]
Hey there,

@rafibomb : Those are not he same issues.

@mintcanary : I don't seem to be able to reproduce the bug, do you have a link or something ? I know this is an old issue but who knows.

Regards,

Lyn.

**Comment by jeanieshark** [comment]
@mintcanary I'm also unable to reproduce this issue using the master branch, using the same code that you've used in the forums. Please let me know if this issue is still persisting for you.

**Comment by Lynesth** [comment]
Ok so....

I've been able to reproduce this while simply using a premade template from Zurb's (http://foundation.zurb.com/templates/workspace.html) and making the topbar sticky.

Here is the page : http://dev.tweefox.nc/demo.html

If you scroll down, the topbar follows. If you refresh, there's a high chance it won't be there anymore until you scroll a bit again.

(I simply downloaded the complete Foundation5 package from the website, and didn't add any css or javascript to it).

Regards,

Lyn.

**Comment by yakou32** [comment]
I have the exact same issue.
Did you find any solution?
If not, I would detect the page scroll coordinate on load to add the fixed class if required...

**Comment by philipp-cmd** [comment]
Why is this issue closed? I also stumbled upon this today - has anyone found a solution for this?

**Comment by mbellet** [comment]
I have the same issue in the same condition (Tested on Chrome and Opera) (But it doesn't happen each time that i refresh, sometimes work) are you planning to resolve this problem?
Version: Your V5 branch (Updated on 25/02/2016)
