### ISSUE TITLE
Clearing Lightbox bug

### ISSUE THREAD

**Issue by KatiaJones** [zurb/foundation#5940]
Clearing Lightbox bug/slow - Wrong image load order and unnecessary GET requests for images already downloaded

Consider this example (I used Firefox developer toolbar > Network Tab to check the GET requests for the first thumbnail click and the next button click):

http://computing-museum.com/

Problem 1 - When you click the first image - foundation loads the second image, then the first image, then displays the first image
>>This results in a long delay when using large images – it is not noticeable in the docs examples because the images are small
>>Foundation should load and display the first image then load the second image into cache so there is no delay for the user

Problem 2 - When you click the next button, foundation loads the current image again, then displays it again, then loads and displays the next image
>> This results in a flicker and another long delay
>> Foundation should not reload an image that has already been downloaded

**Comment by jeanieshark** [comment]
I'm seeing that the order of the images is fixed and that there are not longer unnecessary GET requests. This may be fixed as of the utility function 'image-loaded'. Please re-comment on this issue if the issue still persists for you.

**Comment by nopersonalive** [comment]
The exact description Katia Jones provided is still happening with Foundation 5.5.1: 

"Problem 2 - When you click the next button, foundation loads the current image again, then displays it again, then loads and displays the next image."
