### ISSUE TITLE
Inconsistent button padding in Chrome

### ISSUE THREAD

**Issue by bbcreatv** [zurb/foundation#5945]
For some strange reason Chrome calculates padding differently. Buttons in firefox are ok but chrome the padding is different: I've attached 2 screenshots. Any help would be apreciated thanks.

Firefox:
![screenshot-area-2014-10-17-103327](https://cloud.githubusercontent.com/assets/3500928/4676909/dcfcad20-55e0-11e4-9179-09a7233a2bf9.png)
Chrome:
![screenshot-area-2014-10-17-103355](https://cloud.githubusercontent.com/assets/3500928/4676912/e3cc840e-55e0-11e4-92b1-47f26b38ee30.png)

**Comment by rafibomb** [comment]
Chrome has a different way of rounding causing inconsistencies at different screen widths. Explained here: http://css-tricks.com/percentage-bugs-in-webkit/

There's unfortunately not mush we can do about it other some crazy hack.
