### ISSUE TITLE
top bar Menu broken on Chrome and Opera

### ISSUE THREAD

**Issue by karland** [zurb/foundation#5956]
If the viewport is small enough it displays the Menu-Icon instead of the top-bar entries. Clicking on the Menu-Icon works fine for Firefox, but seems to be broken for recent Chrome and Opera (on Windows). It folds out and folds in 1x allright, but the second time, it just does not fold in any longer. It works fine in Firefox.

**Comment by rafibomb** [comment]
Looks like it's not happening anymore. Let us know. Closing this issue.

Keep in mind, we'll be re-working the top-bar component for the next version.
https://trello.com/c/hep3MVZi

**Comment by karland** [comment]
Closing issue is fine with me. I have a working solution. Thanks and cheers.
