### ISSUE TITLE
Abide Live Validation

### ISSUE THREAD

**Issue by Ethanhackett** [zurb/foundation#5978]
I was working on modifying the live validation on a form to be less in your face the first time through the form. Although in some instances live validation can be handy it can be intimidating. We wanted our form to live validate errors only after the user submits the form. This way if they tab through the form before filling it out they aren't inundated with errors.

It might make sense to change live validation to 'always, after or never' instead of 'true, false' so that validation only occurs after the initial post to assist with he correction process not the initial filing.

Here's a thread on the forum http://foundation.zurb.com/forum/posts/1543-disable-abide-form-validation-on-blur-the-fields

**Comment by rafibomb** [comment]
We'll address the live-validation for this version. @Ethanhackett You're suggestion makes sense and we'll see if it's something we can implement as well. Either way....

We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites

**Comment by Ethanhackett** [comment]
Thanks @rafibomb

**Comment by jeaniec** [comment]
@Ethanhackett If I understand you correctly, you mean the following behaviors to correspond with the value of live validate as follows-

"always" : behavior as it stands now. Form will validate each section per changing fields.
"after" : after submission of the form
"never" : never validates the form

Is this correct?

**Comment by Ethanhackett** [comment]
Yes that's what I was thinking. And maybe a fourth which would be on command? But I guess that could be never or until command? 

Ethan Hackett

**Comment by jeaniec** [comment]
Maybe "never" could be renamed to "manual," which would basically mean that you can do some sort of selector event or 'on command' sort of thing. Essentially, it won't validate any element until otherwise triggered.

**Comment by Ethanhackett** [comment]
I think that's excellent that would allow for some very flexible validation procedures. I think manual is a great label. 

Ethan Hackett

**Comment by jeaniec** [comment]
Hi all, I've made a commit where there's an option for different levels of control when it comes to validation. As this would be a breaking change (i.e. we're holding off until Foundation 6 to make this MAINSTREAM), I've still included the previous live_validate and validate_on_blur options.

You can, however, use this option when you initialize Foundation, like so:
```
$(document).foundation({
abide: {
validate_on: 'manual'
}
})
```
etc.

If you go with 'manual,' you can trigger your custom validations in this sort of manner:

```
$('#myInput').on('keydown', function() {
  $(this).trigger('validate.fndtn.abide');
});
```
