### ISSUE TITLE
flex-video overflow:hidden causing bug in behaviour

### ISSUE THREAD

**Issue by lurnid** [zurb/foundation#6000]
I just noticed a bug in the behaviour of a flex-overflow div. This is the HTML that I'm using:

```
<div class="row">
    <div class="small-12 medium-10 large-9 small-centered columns">
        <div class="player-content flex-video">
            <video id="embed-video" class="video-js"></video>',
        </div>
    </div>
</div>
```

When it switches to the medium width, the bottom-padding ratio is applied to the right-padding of the element instead. That doesn't make sense. But that's what happens!
But if I override the `overflow: hidden` in the `.flex-video` attributes and make it `overflow-visible` the behaviour is as predicted in all widths.
Any idea why this behaviour is happening (I obsereved it on Chrome but haven't tested it in other browsers)? With a flex video container, there shouldn't be any overflow as long as the content is video at the aspect ratio in the mixin, so I'm guessing that as long as I stick to that then having overflow visible shouldn't give me any grief.

**Comment by zurbrandon** [comment]
The aspect ration trick is why the padding behaves that way. Flex-video works well for very specific video players as it needs to account for the aspect ration of that player. Things like youtube, vimeo and wistia are really well supported, while others may need some finagling. Not really a bug as a difficulty pinpointing the aspect ration of your video. Overflow visible would help, but also can create some odd backgrounds for other aspect ratios. 

If it works for you in this case i'd keep using it, but we wouldn't want to apply it overall. 

I'll close this for now, but feel free to reopen if you have additional information :)
