### ISSUE TITLE
ABIDE form error focus

### ISSUE THREAD

**Issue by illycz** [zurb/foundation#6002]
I found some closed issues, but when tested directly on the web pages foundation I found that the focus during the validation does not work properly. Can I do something in order to keep the focus on the first error item?

Thanks
![abide](https://cloud.githubusercontent.com/assets/2109984/4875084/4d1a99f2-6282-11e4-8476-2f579df2dcc4.jpg)

**Comment by pickledegg** [comment]
Will be happy to see this fixed too :)

**Comment by laantorchaweb** [comment]
It's fixed on my local but the changes will overwrite what was done by the commit that I referenced, the issue comes from the filter inside the validations array using the every method. I don't want to make the change before testing what that commit fixed...

**Comment by rafibomb** [comment]
Would love to see a PR for this @laantorchaweb because it would help many people.

**Comment by laantorchaweb** [comment]
I think that this is already solved by #6241 this line was removed and everything seems to be working fine.

**Comment by laantorchaweb** [comment]
I tested this on the master branch using the docs and is working as expected.

**Comment by rafibomb** [comment]
Sweet! Thanks @laantorchaweb

**Comment by proov** [comment]
Hello,
I have the same bug, Abide always focus the 1st required input even if it's not empty .. however validation works fine when all required fields are filled..

i Upgraded to the latest 5.5.1 :/

Thanks

**Comment by laantorchaweb** [comment]
The current version on the repository works fine, as well as the one that is being used on the docs:

[http://foundation.zurb.com/docs/components/abide.html](http://foundation.zurb.com/docs/components/abide.html)

But if you go to the [downloads page](http://foundation.zurb.com/develop/download.html) and download the .zip ("download everything") that version seems to be older and still has this bug on it.

**Comment by proov** [comment]
I updated via Bower. I'm going to try to download from the repo. Many tanks :)
