### ISSUE TITLE
AJAX-to-select with issue

### ISSUE THREAD

**Issue by maykelesser** [zurb/foundation#6007]
I have a simple form where, after an event "blur" in a text input, search some information via AJAX, and end up filling the form automatically. 

However, when I use with a select input, isn't' working. Doesn't fill the option with the attribute "selected"

I am using Foundation with Foundation Forms.

http://jsfiddle.net/Maykelesser/uyb7rn43/

**Comment by Lynesth** [comment]
Hello,

From what I understand, this is not a Foundation issue and should be closed.

@maykelesser : You can find some help here for what you want : http://stackoverflow.com/questions/13343566/set-select-option-selected-by-value

Regards,

Lyn.

**Comment by gakimball** [comment]
Yep, I found the same in my own testing, so I'm going to close this out. Thanks for the link, @Lynesth!
