### ISSUE TITLE
Add Accordion state variables

### ISSUE THREAD

**Issue by ldexterldesign** [zurb/foundation#6011]
Hey,

Would be useful to have the option to color the text in addition to the background-color:
```
// $accordion-navigation-bg-color: $silver  ;
// $accordion-navigation-hover-bg-color: scale-color($accordion-navigation-bg-color, $lightness: -5%);
// $accordion-navigation-active-bg-color: scale-color($accordion-navigation-bg-color, $lightness: -3%);
```

... becomes:
```
// $accordion-navigation-bg-color: $silver  ;
// $accordion-navigation-hover-bg-color: scale-color($accordion-navigation-bg-color, $lightness: -5%);
// $accordion-navigation-active-bg-color: scale-color($accordion-navigation-bg-color, $lightness: -3%);
// $accordion-navigation-color: TODO
// $accordion-navigation-hover-color: TODO
// $accordion-navigation-active-color: TODO
```
– https://github.com/zurb/foundation/blob/master/scss/foundation/_settings.scss#L322

Yours hopefully,

**Comment by rafibomb** [comment]
@ldexterldesign We're in general, not looking to add a bunch more variable if the styles are easy enough to override. We want to have settings form more complex stuff. For this version, we'll accept a PR on this. We are looking to update some of the Sass for this component in the next version. Closing here. Thanks!
