### ISSUE TITLE
Label text is selectable.

### ISSUE THREAD

**Issue by a-lucas** [zurb/foundation#6016]
For example, I have a checkbox inside a label : 

    <label>
      <checkbox name="checked" />
      Check Me
    </label>

when I click 3 times on it, the label get selected.

The normal behaviour should be that the check box is checked-unchecked-checked.

Many browsers consider that several consecutive clicks select the text under the cursor instead of sending click events to the DOM. 

I know this is minor, but why don't foundation make label text selection impossible with user-select: none by default ?

    .noselect {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
       user-select: none;
    }

I understand that there are many web designers that don't really care about optimal UE, and those will usually tell me something like : This is because you click too fast on the checkbox... 

I would answer them : I click fast maybe, but the result isn't the one expected.

**Comment by rafibomb** [comment]
@a-lucas If someone doesn't know what the label means they should be able to select it, copy, send it to someone or whatever. In terms of going one way or another, we'll keep it the way it is since it helps more than hurt.
