### ISSUE TITLE
Issues with data-interchange

### ISSUE THREAD

**Issue by thastark** [zurb/foundation#6027]
A couple issues with data-interchange 5.2.2:

1) interchange.settings.directives.replace ... line 47 needs to run null check on el and ensure el[0] exists before running the regex test:

fails when el is null or el[0] is null:
if (/IMG/.test(el[0].nodeName)) 

resolves the issue:
if(typeof(el) != "undefined" && el[0] && /IMG/.test(el[0].nodeName)) 

2) interchange.settings.directives.replace ... line 52 only sets the src property on the first image however there can be many.  

fails when el has more than one element:
el[0].src = path;

resolves the issue:
el.attr("src", path);

Cheers,

Matt

**Comment by jeaniec** [comment]
Closed with 0444e45
