### ISSUE TITLE
Abide does not focus on error iOS8.1

### ISSUE THREAD

**Issue by kestonh** [zurb/foundation#6037]
I'm seeing an issue where abide validation does not focus on the error field in iOS 8.1. The validation works properly in all desktop browsers, iOS7 devices & my Android device that I have tested.

When I click the submit button in iOS8, the screen scrolls up a few pixels, but it does not focus on the element where the error is. This issue has been replicated on device as well as in the iOS simulator. There are no console errors in the simulator to report.

**Comment by designerno1** [comment]
i think there is a problem with this fix and fixed top-bar
my topbar is fixed an i focus on a input element on my android phone the input gets covered by the topbar.
the scrollTop to the element.offset top position is the problem if i remove the scrollTop my android phone scrolls to to right position with the scrollTop the input gets covered

greet

**Comment by littleforest** [comment]
On mobile devices, this fix causes the input field to scroll to the top on focus, making the label move off the top of the screen.  Is it possible to have it scroll to the top -30 or -40 pixels instead?  It's frustrating not to be able to see the label for the input field you are filling out.  Or is there an easy way to override this?

**Comment by zdfs** [comment]
The jump that this fix created is rather annoying if we don't run into any of the use cases above. Focusing on a field in iOS makes the screen jump up and down every time. Any way it can be optional?

**Comment by justrhysism** [comment]
Yeah, the "fix" applied in 49b159689ffe56d6ea17b6f98e61cb6193b52f0c causes more problems than it solves.

**Comment by justrhysism** [comment]
I'll open a new issue if preferred?

**Comment by justrhysism** [comment]
I came across the iOS8 issue elsewhere - if triggering .focus() doesn't happen within a seemingly arbitrary amount of time (I think, it's probably something completely different) after a user interaction, the event is ignored.

In my case (not validation based) I was able to work around this by making my script run faster and fire the event earlier.
