### ISSUE TITLE
side-nav mixin should parameterize active colors

### ISSUE THREAD

**Issue by codemouse** [zurb/foundation#6046]
@mixin side-nav $side-nav-link-color-active should be specified as mixin parameter vs global scope of file. Should basically mimic behavior of $link-color-hover under @mixin side-nav.  Additionally, allow &:active designation for style override on a:not(.button).

**Comment by gakimball** [comment]
Hey @codemouse, sorry this issue has gotten a little stale, but would you be interested in writing a PR to implement the functionality the way you think it should be?

**Comment by tdhartwick** [comment]
@codemouse Thanks for pointing this out! Just pushed it to the repo.
