### ISSUE TITLE
Foundation topbar submenu parent with link double click on touch screen desktop

### ISSUE THREAD

**Issue by nghenglim** [zurb/foundation#6052]
seems is same issue as http://foundation.zurb.com/forum/posts/1679-top-bar-double-click-on-drop-down

My foundation.topbar.js has disappear and only left foundation.debug.js, I have fix it for my use case however not yet tested in other environment such as mobile, etc. Below is the script and should be a lot of improvement can be done to optimize it.

    events : function (bar) {
      var touching = 0,
          self = this,
          S = this.S;

      S(this.scope)
        .off('.topbar')
        .on('click.fndtn.topbar', '[' + this.attr_name() + '] .toggle-topbar', function (e) {
          e.preventDefault();
          self.toggle(this);
        })
        .on('click.fndtn.topbar','.top-bar .top-bar-section li a[href^="#"],[' + this.attr_name() + '] .top-bar-section li a[href^="#"]',function (e) {
            var li = $(this).closest('li');
            if(self.breakpoint() && !li.hasClass('back') && !li.hasClass('has-dropdown'))
            {
            self.toggle();
            }
        })
        // fix double click issue in touch + mouse device
        .on('touchstart.fndtn.topbar','.top-bar li a',function (e) {
            touching = 1;
        })
        .on('mouseover.fndtn.topbar','.top-bar li a',function (e) {
            if (touching === 1) {
                touching = 0;
            } else if (Modernizr.touch) {
                var li = S(this).parent();
                li.addClass('hover');   
            }
        })
        .on('mouseleave.fndtn.topbar','.top-bar li a',function (e) {
            if (Modernizr.touch) {
                var li = S(this).parent();
                li.removeClass('hover');
            }
        })
        .on('click.fndtn.topbar', '[' + this.attr_name() + '] li.has-dropdown', function (e) {

**Comment by rafibomb** [comment]
Looks like this isn't happening anymore. Tested on ipad ios 7 and 8 and iphone 6 ios 8.1. Let us know if you can still reproduce on version 5.1.1+
