### ISSUE TITLE
Tabs component: prevent both hash in URL and scroll to content

### ISSUE THREAD

**Issue by andresbc** [zurb/foundation#6058]
In the javascript for the tabs component there is this code which now adds a hash to the URL when deep linking is activated (line 79):

```
// prefix the hash to prevent anchor scrolling
hash = self.scope.location.hash.replace('fndtn-', '');
```

Our SEO people are asking us to configure the component to not add the hash. The problem is that by doing that we get the "scroll to content" behaviour which can be somewhat annoying.

Is there any other way to prevent both the hash and the scroll to content without hacking the Foundation code? If not, could you please find a way to provide this possibility? I get the feeling we're not the only ones who will post an issue about it.

**Comment by rafibomb** [comment]
Looks like there is an open one here https://github.com/zurb/foundation/issues/4791 We'll close this in favor of it.
