### ISSUE TITLE
off-canvas menu doesn't disappear when changing screen size (also on foundation-site!)

### ISSUE THREAD

**Issue by drm00** [zurb/foundation#6060]
Hi,

this issue can be seen on the main foundation page, so it should be easy reproducible.

When you have the foundation site open at a small screensize (so that the canvas-menu-"burger"-button is shown) and open the menu and then resize the site to the max, the off-canvas-menu stays open, but the "burger-menu-icon" disappears.

I would expect that the off-canvas-menu is closed on a resize to a visibility class other than small, and that the "normal-size" menu is shown in that case. The fact that this happens on the front page of this project lets me think that this is a general issue, but for the record, i have the same issue on my site as well.

Any hints?

Best,
drm00

EDIT: Just tried this on the bootstrap homepage, and this kind of bug does not happen there ;)

**Comment by rafibomb** [comment]
@drm00 What practical application would require the menu to close on a screen resize? Can you explain why this should be changed?

I can see the menu icon disappears when the screen is wider than the small breakpoint, but that can be easily changed and the menu can still be closed since the title acts as a button as well.

**Comment by brentdodell** [comment]
@rafibomb I assume this functionality has never been added?

My use-case would be that we need to move our top nav into a right off-canvas for small & medium breakpoints, but once the browser is resized to a large breakpoint, the off-canvas should be closed because the top nav links are shown.
