### ISSUE TITLE
Disable all :hover styles for mobile/touch with media queries

### ISSUE THREAD

**Issue by ArTiSTiX** [zurb/foundation#6061]
For most of links elements (button & a), Foundation defines a :hover effect...
But on touch devices, mouseovers make it look buggy...

For example, in offcanvas menus or icon bar, links are highlighted, sometimes for no reason.
(Using Safari & Chrome on iPhone 4 - iOS 7), because mobile web browsers emulates hover from previous touch events.

Would it be possible to wrap all :hover styles in a specific media query for only desktop platforms ? (in overrides variables, to choose when to disable it).

**Comment by rafibomb** [comment]
We're not going to be doing it for F-5 but we'll consider it for F-6. We're adding it to our maybe list. The concern is this is a preference and implementing it would be far reaching.

**Comment by davidgoli** [comment]
:+1: This is remedial touch interaction nowadays, guys.
