### ISSUE TITLE
Child element's margin pushing  centered column down

### ISSUE THREAD

**Issue by msadura** [zurb/foundation#6069]
Centered column has float:none, so if we put element with margin-top inside it, whole column moves down. This is normal behaviour of non-floated div but can be really annoying. Example:
![ss](https://cloud.githubusercontent.com/assets/5198394/5230488/3e54ec38-7727-11e4-9571-ae6fce2bcf28.jpg)
Below top menu you can see gray .row and centered column inside it. Element with margin makes a gap between column and top menu.
Problem can be solved by adding overflow:hidden to column, but it is not universal solution, because if for any reason there will be elements that will show partially outside column, they will be cropped.
Another solution is to add padding-top to column, but it is not good either, because noone would like to get padding out of nowhere.

I have found another solution, but this is kind of workaround so let me know how do youfeel about it:
Adding 1px invisible border top works excaclty as padding, so child's margin is added correctly and column won't be extended vertically because of box-sizing.

**Comment by brettdewoody** [comment]
While this is annoying it is accepted as 'normal' behavior among most browsers. A 'fix' would likely cause more issues. In your particular case I think you would want to use `padding-top` so the white box stays flush with the top but pushes the content down.

**Comment by gakimball** [comment]
It seems like since this is normal browser behavior, and the use case might be too hard for us to implement universally, I'll just close this.
