### ISSUE TITLE
foundation.min.js isn't Minified

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#6073]
I noticed today that if you download Foundation from the download page either downloading everything or using the custom download that the foundation.min.js file isn't minified. It contains all of the JS code but should be minified as well, correct?

I have minified it myself for my project but I assume this is a bug?

**Comment by Lynda333** [comment]
@rafibomb - It may be beneficial to throw a note on the custom downloader letting people know it isn't minified and they should minify it themselves. (Until this bug is fixed.) I am doing that and saving an average of 50% of the file size! In some cases this is 50 to 70kb! Huge savings.

**Comment by dud3** [comment]
@rafibomb Which uglifier are you using, I noticed this issue as well.

**Comment by chauncey-garrett** [comment]
It'd be good to sort this out. CDNs like jsdelivr source these releases for the minified versions.

**Comment by elliottb** [comment]
Upvote

**Comment by rafibomb** [comment]
This has been fixed! We had update a ton of dependancies and syntax.
