### ISSUE TITLE
Magellan resets when Reveal Modal opened

### ISSUE THREAD

**Issue by drouhard** [zurb/foundation#6100]
Issue: When you open a Reveal Modal, Magellan takes the current window position as the new offset for becoming sticky. If you close the modal and scroll up, Magellan pops back up to its non-fixed position, and only re-sticks when you pass the position where you opened the reveal modal.

Example: http://foundation.zurb.com/docs/components/kitchen_sink.html

Browsers: Chrome and Firefox (latest), and likely others

**Comment by bradfordbradford** [comment]
Also having this issue—and not just with magellan—actually had it first with Sticky Waypoints and Waypoints libraries. I've tried reflowing the dom elements after the reveal 'closed' event is fired, but it doesn't help.

**Comment by SamRyouji** [comment]
Same issue here and actually knew it when exploring the fusion possibility of the two.
It may take a while to sort this issue so I'm trying to fuse the reveal with other js navigation or vice versa for a quick relief. If I got one I'll update this comment.

**Comment by Kovas** [comment]
Same thing happens if page is loaded from the link, that leads to the anchor point.
Magellan will work for anchors below that point, but not for the ones above it.

Example: http://foundation.zurb.com/docs/components/kitchen_sink.html#top-bar

**Comment by aiphee** [comment]
Im still experiencing this issue as described here: 
http://foundation.zurb.com/forum/posts/23994-maggelan-error-after-ajax-modal-opened

**Comment by rafibomb** [comment]
The fix is in the master branch, we are tagging a new release this week so it will be out with that update.

**Comment by stirlingsohn** [comment]
@aiphee 
You need to re-initialize Magellan after loading AJAX content.
I was able to fix the Issue with the following Code:

// Re-Initialize Magellan after Modal is Closed
$(document).on('closed.fndtn.reveal', '[data-reveal]', function () {
  $(document).foundation('magellan-expedition', 'reflow');
});

References:
http://foundation.zurb.com/sites/docs/v/5.5.3/components/magellan.html#adding-new-content-after-page-load

http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html#event-bindings
