### ISSUE TITLE
Unable to pass extra data to event handler when closing Reveal modal

### ISSUE THREAD

**Issue by jbarker4682** [zurb/foundation#6111]
According to jQuery docs, we should be able to pass extra data parameters to an event handler when triggering the event manually via .trigger() method:

http://api.jquery.com/trigger/

However, when attempting to programmatically close the Reveal modal, the extra parameter is never passed through to the handler.  Stepping through the code, it appears this gets lost in the call to Foundation.libs.reveal.close.

I have tried all of the following, and all strip out the extra parameter:
```javascript

$(document).on('close.fndtn.reveal', '[data-reveal]', function (e, loginState)
{
    //form reset logic goes here...

    if (loginState.wasCanceled)
    {
        //tell app to cancel any pending actions that mayhave been queued awaiting a successful login
    }
});

this.CloseModal = function(wasCanceled)
{
    var _loginState = { wasCanceled: wasCanceled };
    $('#loginModal a.close-reveal-modal').trigger('click', _loginState);
    //$('#loginModal').foundation('reveal', 'close', _loginState);
    //$('#loginModal').trigger('close.fndtn.reveal', _loginState);
}
```

Is this something that can be fixed, or do I need to find another way.

**Comment by jeaniec** [comment]
You can use jQuery's API as follows in order to pass your data:

```
function loginHandler(e) {
  console.log(e.data);
}

var _loginState = { wasCanceled: wasCanceled };

$('a.close-reveal-modal').on('click', _loginState, loginHandler);
```

That should get your data through as long as you specify the handler function's name!

**Comment by jbarker4682** [comment]
Hi Jeaniec,

As I said, I **SHOULD** be able to do this, but I can't because the Zurb Foundation implementation for Reveal that wraps this behavior is not passing this extra data to the underlying jQuery call.

**Comment by jeaniec** [comment]
Hmmm. I just tested out that code snippet and it worked fine. :/ Let me see what I can whip up.

**Comment by jbarker4682** [comment]
@jeaniec The issue is not the jQuery click method, but the trigger. Additionally, we are listening to the *close.fndtn.reveal* event because the the pop-up can be closed multiple ways, and there is some additional clean-up that must occur if the login was cancelled. In my original example, even though I was passing loginState in my call to the trigger method, that value was never received in the "close.fndtn.reveal" handler.  When I stepped through the code, it looked like the jQuery trigger method was being wrapped / overridden by something in Zurb Foundation, and that somewhere in the hand-off where Zurb finally calls the original jQuery version, it never passes the extra data argument.

However, this was from several months ago. I think we worked around this by setting a flag in the closure and using that instead. But you may want to still look into this as a larger issue.

**Comment by hellojeanie** [comment]
@jbarker4682 Okay, am closing this issue for now, but for Foundation 6, we will definitely include more robust and scalable ways of passing through event handler data.
