### ISSUE TITLE
Dropdown position is off when using semantic grid markup

### ISSUE THREAD

**Issue by bwydev** [zurb/foundation#6119]
The new additions to dropdown in 5.5 are calculating the position of the dropdown incorrectly if you're not using row / column naming and are instead using semantic grid markup.

A dropdown which would correctly show with arrow on the left side of the anchor text and open to the right, now shows on the right side of the anchor text and opens to the left - as it would if it was pressed up against the right side browser window. 

5.5 on top, and 5.4 below:
![dropalign](https://cloud.githubusercontent.com/assets/7107235/5459897/fe23613e-8523-11e4-9693-565d6782f09f.jpg)

In testing, using default row and column classes works, but semantic row and column classes don't.

It could be the calculation for actualMarginWidth if their are no 'row' classnames found (foundation.dropdown.js around row 250).  This is part of the js additions to 5.5 for dropdown (see https://github.com/zurb/foundation/pull/5986/files ).

**Comment by bwydev** [comment]
Thanks for this, unfortunately pull request 6160 is being held up because of merge conflicts. Can't understand why this issue isn't more  of an issue, easy to see on the foundation docs site dropdown page.

**Comment by rafibomb** [comment]
Thanks! We'll close in favor of https://github.com/zurb/foundation/pull/6160. Sure the merge conflicts are no problem.
