### ISSUE TITLE
5.5 top bar: autoclose in link dropdowns

### ISSUE THREAD

**Issue by alubbe** [zurb/foundation#6127]
I am building a SPA and would like that the top bar dropdowns close after the user clicks on any of the available links instead of staying open and intruding on the new page layout. What I am looking for is essentially the autoclose feature that the normal dropdowns already have.

Is this possible today through a setting? If not, could it be done through a click event listener? I tried running ```Foundation.libs.topbar.toggle``` on the top bar, but to no avail. Any help would be greatly appreciated!

**Comment by jeaniec** [comment]
Hey @alubbe @bahart are you still experiencing this issue with the latest push? A change that I made to the non-hover top bar may have inadvertently fixed this.

**Comment by alubbe** [comment]
I'm still experiencing the same issue. However, my issue is with hover top-bars, I have not tested the non-hover ones.

What I am looking for is that hovering opens the next sub-nav hierarchy and that clicking closes all sub-navs & "loads" the new page (via JS, not full page reload). All of which works, except that the sub-navs stay open until the user moves his cursor away from the top-bar.

**Comment by rafibomb** [comment]
Closing in favor of https://github.com/zurb/foundation/issues/5551

**Comment by alubbe** [comment]
@rafibomb My issue is actually a different one from #5551 

Basically imagine that I run a SPA with the hover navigation. I hover over the navbar, a dropdown appears, I click on something on the dropdown and now I'd like it to be gone, just as it would be if a new URL had been accessed.

Instead it just stays open until I move my mouse away and blocks text/images on the new page.

**Comment by michaelBenin** [comment]
What is the current solution to this when working with Foundation with SPAs and not using angular? 

None of the solutions here work: 

http://stackoverflow.com/questions/18516696/how-can-i-close-the-foundation-topbar-menu-when-a-link-is-clicked

Also, I was really hoping this would work:

    Foundation.libs.topbar.toggle($('.top-bar'));

Unfortunately it doesn't. 

I've resorted to using this:

    $('.exit-off-canvas').trigger('click');

Can this issue be reopened?

**Comment by rafibomb** [comment]
Yes, @jeaniec Can we extend the fix you made to dropdows in top-bar with is_hover: true

**Comment by bahart** [comment]
jeaniec

I implemented the foundation.topbar.js as noted in  67b4477. My problem 
still exists.

In a hoverable top-bar
right-click and open a link in a new tab
the menu remains open (in the first browser window/not the new tab)
until you click anywhere else on the page.

Any thoughts? Can we reopen this issue?

Thanks
Barbara

**Comment by jeaniec** [comment]
@bahart I've added an event to detect that with https://github.com/zurb/foundation/commit/db2ba28b95eeac88700cd722116b73f2bec8f399 so let me know if that works for you!

**Comment by bahart** [comment]
jeaniec

Problem still exists.

In a hoverable top-bar
right-click and open a link in a new tab
the menu remains open (in the first browser window/not the new tab)
until you click anywhere else on the page.


Thanks
Barbara

**Comment by jeaniec** [comment]
@bahart Do you have a code snippet or a repo I can take a look at?

**Comment by bahart** [comment]
I am new to GitHub so no on the repo, I will put up a test page on our 
server (later tonight) so you can take a look. Any help you can provide 
would be very much appreciated. I'll email a link . Thanks

**Comment by Some1Else** [comment]
It is impossible to trigger a javascript event as a result of Right-click ->  Open Link In New Tab

**Comment by lkallday45** [comment]
This is still a problem. If a menu item is set to open in new page, the  menu stays open on the previous page until you click on an area of the page outside the menu.

www2.topekapublicschools.net

Schools->Elementary Schools->any school

If there is a fix for this, I would appreciate it.

Thanks,
Melvin
