### ISSUE TITLE
rails 4.2 Invalid CSS !global

### ISSUE THREAD

**Issue by chrishough** [zurb/foundation#6148]
It looks like the !global issue came back with the launch of rails 4.2 tonight.
```
Sass::SyntaxError at /join
Invalid CSS after "...ules: $modules ": expected "}", was "!global;"
```
Error Details:
```
// IMPORT ONCE
// We use this to prevent styles from being loaded multiple times for compenents that rely on other components.
$modules: () !default;
@mixin exports($name) {
  // Import from global scope
  $modules: $modules !global;
  // Check if a module is already on the list
  $module_index: index($modules, $name);
  @if (($module_index == null) or ($module_index == false)) {
    $modules: append($modules, $name) !global;
    @content;
```
The only thing I could do to get around this was to downgrade my gem to `gem 'foundation-rails', '5.4.5'` 

Can anyone point me in the right direction? Thanks and Merry XMAS.

**Comment by gakimball** [comment]
`sass-rails` version 5.0.0 is out now, which should make Rails compatible with Sass 3.4, and thus compatible with our codebase.

**Comment by Kriyo** [comment]
@jakzaizzat & @chrishough cheers for the fix (Y)

**Comment by rdetert** [comment]
Thanks @gakimball Adding gem 'sass-rails', '~> 5.0.0' works like a charm

**Comment by paulman93** [comment]
I have the gems *"sass-rails", "5.0.0"*  *"foundation-rails", "5.4.5"* and *"sass", "3.4.9"* and i still get the same error 
Sass::SyntaxError at /
Invalid CSS after "...ules: $modules ": expected "}", was "!global;"

I cant figure out where the problem is. Please help!

**Comment by gakimball** [comment]
Foundation 5.4.5 isn't compatible with the newest version of Sass, but 5.5 is.

**Comment by hayduke19us** [comment]
Rails 4.1.9
gem 'foundation-rails'
gem 'sass-rails', '~> 5.0.0'

Worked for me

**Comment by shaekuronen** [comment]
Rails 4.1.8
gem 'foundation-rails'
gem 'sass-rails', '~> 5.0.0'

Did not work for me

However

Rails 4.1.9
gem 'foundation-rails'
gem 'sass-rails', '~> 5.0.0'

Did

Thanks @hayduke19us !

**Comment by ssoulless** [comment]
Ok this worked for me

Rails 4.1.9
gem 'foundation-rails', '~> 5.5.0'
gem 'sass-rails', '~>5.0.0'

And do not forget to run 'bundle update' in order to update your sass version it has to be 3.3.x or higher in order to run foundation 5.x

**Comment by chrishough** [comment]
I can confirm that `gem 'sass-rails'` fixes this issue as it loads version `5.0.1`

**Comment by paulman93** [comment]
I have it working now with,

Rails 4.2.0
gem 'foundation-rails', '~> 5.5.0'
gem 'sass-rails', '~> 5.0.1'

**Comment by JonKernPA** [comment]
Hmmm, struggling with upgrading:

    Ruby 2.1.1

    rails (4.2.0)
    foundation-icons-sass-rails (3.0.0)
    foundation-rails (5.5.0.0)
    sass (3.4.10, 3.2.19)
    sass-rails (5.0.1)

**Comment by Mwathi** [comment]
ditto @jakzaizzat

**Comment by TaiwoAyanleye** [comment]
@JonKernPA 
gem 'rails', '4.1.6'
gem 'sass-rails', '>= 4.0.4'
gem 'foundation-rails', '5.4.5'

worked fine

**Comment by a17levine** [comment]
thanks everyone, downgrading foundation was key for me

**Comment by DaniG2k** [comment]
I'm getting this error as well. Is there any change it will be fixed soon without having to downgrade?

**Comment by gakimball** [comment]
@DaniG2k It has been fixed, you just need to use Sass 3.4+ in your asset pipeline. If you can't do that because other libraries require a lower version, use Foundation 5.4.7 instead. 5.5 is the point where we deprecated Sass 3.3 and lower.

**Comment by DaniG2k** [comment]
@gakimball Great! Thanks. Sorry I didn't catch that in the thread :confounded:

**Comment by introvert** [comment]
I'm unable to resolve this error with:

gem 'sass-rails', '~> 5.0.1'
gem 'foundation-rails', '~> 5.5.0'

What to do?

**Comment by soyarsauce** [comment]
Had the same issue but on rails 4.1.1, was using older version of sass-rails, below worked:

gem 'sass-rails', '~> 5.0.3'
gem 'foundation-rails', '~> 5.5.0.0'

@introvert check your sass version

**Comment by codesallday** [comment]
I ran into this with my Grunt workflow and `gem update sass` worked for me. Just thought I'd mention for the people using Foundation without Rails.

**Comment by rdamborsky** [comment]
Thanks guys, downgrading foundation-rails helped!

**Comment by takayuki905** [comment]
Same error, following.

**Comment by ronipl** [comment]
asdasd

**Comment by ronipl** [comment]
asdasdsd

**Comment by Bastes** [comment]
Same error, following.

**Comment by gakimball** [comment]
@takayuki905 @Bastes This issue has already been resolved, just make sure you're using the newest Sass compiler in your Rails project.

**Comment by Bastes** [comment]
@bakimball Ah, finally found what prevented my upgrade, now everything's fine and up to date. Thanks.

**Comment by danjames68** [comment]
Upgrading sass-rails to 5.0.1 worked for me.

**Comment by IlkhamGaysin** [comment]
```
gem "foundation-rails", "= 5.5.2.1"
gem "sass-rails", "= 5.0.3"
```
worked for me
