### ISSUE TITLE
Reveal Modal out of visible area on Firefox

### ISSUE THREAD

**Issue by AbuJunayd** [zurb/foundation#6154]
Hello,

I just wanted to report this bug about reveal modal.

While opening a modal from the documentation page on firefox: http://foundation.zurb.com/docs/components/reveal.html

I noticed that the modal was not opening on the visible portion of the page. Rather it's opening at the top, so we have to scroll up to the top of the page to see it.

I have only been able to test it on chrome 39.0.2171.95 (it is working on chrome) and on firefox 34.0 (not working)

**Comment by nickBumgarner** [comment]
What worked for me in the meantime is adding html { overflow:hidden;} . This fixed the issue in Firefox.

**Comment by redmoik** [comment]
@nickBumgarner , what class or ID specifically you added {Overflow:hidden} ? I can't find a fix for this problem.  

Is this because of the firefox update? I tried in the lower versions of FF and I found no problem.

**Comment by nickBumgarner** [comment]
When I did it, I set overflow:hidden; directly to the HTML element.

html {
overflow:hidden;
}

Try that and see? I found that information here http://foundation.zurb.com/forum/posts/783-zurb-reveal-doesnt-take-into-account-scrolling .

It's a little old but applied to my project.

**Comment by ummahusla** [comment]
Well, position:fixed worked for me.
