### ISSUE TITLE
Zurb dialog style is coliding with upcoming html5 <dialog>

### ISSUE THREAD

**Issue by phryniszak** [zurb/foundation#6157]
Hi everybody,
```<dialog>``` stays hidden. Of course I can manipulate css but I wonder is this planned effect/?
```
.reveal-modal, dialog {
  visibility: hidden;
  display: none;
```

**Comment by gakimball** [comment]
That's a holdover from us trying to use the `<dialog>` tag for Reveal, for accessibility purposes. But it has like, no browser support so we aren't doing that any time soon. So that bit of CSS should be removed.
