### ISSUE TITLE
Add value of $topbar-breakpoint to foundation.topbar.js at line 368

### ISSUE THREAD

**Issue by banacan** [zurb/foundation#6164]
Is there anyway to add the value of $topbar-breakpoint to foundation.topbar.js at line 368 so the li element with class="parent-link show-for-small" can be changed according to the variable value?  
I have:
$topbar-breakpoint: #{lower-bound($large-range)};
$topbar-media-query: $large-up; 
because I want my mobile nav to start below $large-up.  Unfortunately, show-for-small is hard-coded in the topbar.js not allowing it to respond to variable values in settings.scss.

Seem to be the same as:  Top bar parent links not visible on medium if the breakpoint is set to toggle on medium screens #5841

**Comment by rafibomb** [comment]
Yes, it is the same issue. We'll close this in favor of that. https://github.com/zurb/foundation/issues/5841 We'll address it there.
