### ISSUE TITLE
Topbar hover problem in Foundation 5.5

### ISSUE THREAD

**Issue by trailness** [zurb/foundation#6165]
I am trying to use click events instead of hover. In 4.3.2, you could accomplish this by adding `data-options="is_hover:false"` to the `nav` element. The example in the docs here works: http://foundation.zurb.com/docs/v/4.3.2/components/top-bar.html#clickable - You can click on the top-level to expand level 2, you can then click on level 2 to expand level 3.

But in 5.5, adding the same `data-options="is_hover:false"` to the `nav` element, you can click on the top-level to expand level 2, but then once you click on a level 2 item it navigates to that page rather than expanding level 3 of the menu. The example in the docs here is showing the same behavior I'm finding on my own site: http://foundation.zurb.com/docs/components/topbar.html#clickable

**Comment by jeaniec** [comment]
As a temporary solution, you can change the HTML mark up to prevent this behavior. If you have an item in your topbar menu that contains a dropdown list, just omit the "href" attribute from your <a> tags. 

I've updated the docs example to emulate this behavior until I can come up with a more stable JS solution.
