### ISSUE TITLE
Problem in Abide reset mehod?

### ISSUE THREAD

**Issue by pacoferre** [zurb/foundation#6171]
Hello!

Your reset method has two problems, I think :)

```javascript
reset : function (form) {
      form.removeAttr(this.invalid_attr);
      $(this.invalid_attr, form).removeAttr(this.invalid_attr);
      $('.' + this.settings.error_class, form).not('small').removeClass(this.settings.error_class);
    },
```

This:
```javascript
      $(this.invalid_attr, form).removeAttr(this.invalid_attr);
```
Must be this?
```javascript
      $('[' + this.invalid_attr + ']', form).removeAttr(this.invalid_attr);
```

And also, is there anything to do with aria-invalid attribute?
Perhaps:
```javascript
$('[aria-invalid]', form).setAttribute('aria-invalid', 'false');
```
Or:
```javascript
$('[aria-invalid]', form).removeAttr('aria-invalid');
```

Best regards, Foundation is very very good, thanks a lot for your job.

Sorry for my poor english :)

**Comment by jeaniec** [comment]
@pacoferre Hi! Thanks for catching that. I've made a recent commit that'll help with this issue. On your form, just include an element similar to:
```
        <button type="reset" class="medium button green">Reset</button>
```

And that should send the correct event to your form! Let me know.
