### ISSUE TITLE
Kitchen Sink Regression

### ISSUE THREAD

**Issue by ChrisLangsenkamp** [zurb/foundation#6172]
Please update and perhaps extend the Kitchen Sink to reflect changes and enhancements in version 5.5.  At the moment, Accordian is broken (needs to be changed to UL/ LI).

http://foundation.zurb.com/docs/components/kitchen_sink.html

Thanks!

**Comment by rafibomb** [comment]
done https://github.com/zurb/foundation/commit/2aaf70f0597eac545b07236f4c15f15ee66006bc
