### ISSUE TITLE
Bug in sass link to switch(es) scss

### ISSUE THREAD

**Issue by evertalbers** [zurb/foundation#6173]
In the sass version, the app.scss file links to 
```
_switch.scss
```
 This should be 
```
_switches.scss
```
I could not find it in the GitHub files, so I'm submitting it here.

**Comment by gakimball** [comment]
The typo was in the [libsass template](https://github.com/zurb/foundation-libsass-template/). Fixed it with [this commit](https://github.com/zurb/foundation-libsass-template/commit/139db9744533fbaf47422359b2987011a7461815).
