### ISSUE TITLE
Feature request: Datepicker and Timepicker

### ISSUE THREAD

**Issue by bastienJS** [zurb/foundation#6176]
I checked your http://foundation.zurb.com/apps/docs/#!/ but have not found any word about a datepicker or timepicker which I would need using your library.

I do not really like rely on multiple libraries to cover my control needs.

So please create the world`s best responsive datepicker/timepicker :-)

**Comment by gakimball** [comment]
It won't happen for Foundation 5, but it could happen for Foundation 6, which we're starting development on soon. I'll add it to the F6 wishlist here: #4710
