### ISSUE TITLE
BUG equalizer equalize_on_stack: true

### ISSUE THREAD

**Issue by octlabs** [zurb/foundation#6179]
Hi!
see stack example: http://codepen.io/anon/pen/QwdjqX

Fix:
first calculate inner elements to get exact height for outer (.info)

**Comment by rafibomb** [comment]
I'm not seeing the issue. Can you explain it better?

**Comment by octlabs** [comment]
Hi Rafi!
i update the example: http://codepen.io/anon/pen/QwdGyO

If you nest (or 'stack') equalizer elements into other, the outside equalizer elements should be height calulated after the inner inner elements are equalized.

Hope that's better for explanation.
Thanks 
- Stefan

p.s. It also  would be nice the have the option to equalize a list of paired elements like here in dl list. Currently i fixed it with only to elements in every dl equalized list.

**Comment by rafibomb** [comment]
Thanks for the detail. See it now. Equalizer was not built with the intent to next it. Probably delaying the outer equalizer call will solve this. In terms of adding this feature to Foundation, we'll accept a PR. If is not something on our roadmap to do since it is a specific use case. Thanks!
