### ISSUE TITLE
Latest version to NPM?

### ISSUE THREAD

**Issue by athanclark** [zurb/foundation#6180]
Hi everyone, could foundation's javascript be hosted on npm? I'm trying to use browserify with some of my code, and having it in npm in general might be a good practice. There are a few clones on npm now from independent and outdated forks, I'm sure some standard support would be nice :)

**Comment by jonathanmelville** [comment]
Browserify isn't meant to be a front end package manager, it allows you bring Node modules into the browser.

Bower is the better choice here.

**Comment by gakimball** [comment]
Yep, we can add the files to npm and maintain an official package (we started doing it on Foundation for Apps, so we should probably do it here as well), but they aren't packaged with any kind of AMD system, so they won't work with Browserify.

**Comment by athanclark** [comment]
@gakimball That's what I was afraid of. RequireJs has this one option for setting up a "shim", so augmenting `$` is done simply via the dependency load.

However! I think a viable solution, although pretty silly, could be something like this:

```javascript
// - Foundation Zurb's npm `index.js`
module.exports = function (jQuery) {
  // ... substitute `foundation.js`
  return $;
}
```

Then, when we use foundation in our dependency loader (browserify for instance concatenates all dependency into one file, RequireJs has both a runtime DOM-based `<script src=...>` appending mechanism and it's concatenator / compiler `r.js`), we just have to re-set `$`, like a `+=` would for Integers:

```javascript
// userFile.js
var jQuery = require('jquery');
      jQuery = require('foundation')(jQuery);

// ... proceed to use `jQuery`, and `jQuery.foundation`
```

 Including this feature would give Foundation a very flexible interface for your server-side deployment scheme.

I think this would be very cooperative with a lot of javascript frameworks in general, and could find benefit from it's design over the long run as well.

**Comment by rafibomb** [comment]
Glad you added a possible solution. We'll add to our list of considerations for F-6 and close this here.

**Comment by davidchase** [comment]
@athanclark Just a heads up it seems like they have a `package.json` right on this github repo so you could in your package.json do something like
```js
"zurb-foundation": "git://github.com/zurb/foundation"
```

this will pull from this repo more info [here](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

if you still you browserify you can check out [browserify-shim](https://github.com/thlorenz/browserify-shim) it makes non-CommonJS files work with browserify 

@jonathanmelville its unnecessary to install `bower` and maintain another package manifest when you can accomplish the same with npm. Bower is nice when you are not using node/npm environment

**Comment by gonsfx** [comment]
A pity this was closed. I'm working with AmpersandJS, managing all frontend dependencies using npm and browserify. Please rethink - additionally pushing stable versions of this to npm is not too hard! ;-)

**Comment by gakimball** [comment]
Hey guys, starting with v5.2.2 we're publishing Foundation with the package `foundation-sites`. As for module loader support, that's coming in version 6.
