### ISSUE TITLE
text-rendering: optimizeLegibility;Should Not Be Used?

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#6182]
I see in the Foundation CSS that the css `text-rendering: optimizeLegibility;` is used. I recently was reading about text rendering because of an issue I have (not Foundation related) and came across some information that said you should avoid using `text-rendering: optimizeLegibility;` because of Browser bugs but instead should `font-feature-settings` instead. 

Much of this is over my head but I thought I would post it for those smarter than myself to discuss it. => 

This [SO question and answer](http://stackoverflow.com/q/7968795/825757) explains it a bit more.

**Comment by rafibomb** [comment]
Interesting, although I can't remember any reports of issues with it. According to http://blog.typekit.com/2014/02/05/kerning-on-the-web/ there is limited browser suppoert for 'font-feature-settings'

**Comment by Lynda333** [comment]
Yeah, I am unsure if it is any real issue but it is something I have come across more than once. I [looked on Can I Use](http://caniuse.com/#search=font-feature-settings) and it would appear that it is supported in IE 10+, FF, Chrome. Safari and IE 9 and below are the biggest issues.

Again, this is just a thought I came across and wanted to share.

**Comment by rafibomb** [comment]
I'll add the suggestion to our version 6 of Sites planning and we'll review it with the team. Thanks!
