### ISSUE TITLE
Progressive render and responsive img

### ISSUE THREAD

**Issue by tifosiblack** [zurb/foundation#6183]
Hello guys,

I have an issue with rules added for fixing the issue https://github.com/zurb/foundation/issues/44.

The rule `img { max-width: 100%; height: auto; }` should not target img tag directly, but a class (like img-responsive in Bootstrap). The display before the image is loaded is broken, which leads to reflow and sometimes bug with third party libraries as filipegiusti pointed out.

This is a rule that I cannot override, because it prevails over width and height attribute on image.

I know it's a breaking change, but the initial solution would not have been accepted.

Regards

**Comment by tifosiblack** [comment]
For the moment, I can override $include-html-global-classes to false as a workaround.

**Comment by gakimball** [comment]
Like you said, since it's a breaking change that decision might need to wait until version 6 of the framework, which is in the early stages of planning right now.

> The display before the image is loaded is broken, which leads to reflow and sometimes bug with third party libraries as filipegiusti pointed out.

Where's this comment?
