### ISSUE TITLE
How to disabled dropdown hover in active accordion menu

### ISSUE THREAD

**Issue by darkcyber** [zurb/foundation#6186]
Hello, i plan to make accordion admin menu like wordpress have. so when i hover on active accordion menu it should disabled dropdown hover , else if i hover on not active accordion menu it should show dropdown hover.

as i do so far is create accordion menu then i put dropdown hover.

and it work like a charm , it will show hover if i hover on accordion menu. but i want only show hover on not active accordion menu just like wordpress admin menu.

how i can do that ?  

thanks in advance.

**Comment by darkcyber** [comment]
my javascript code so far

    $(".accordion-navigation").on('click', 'a', function(){

    // get data-dropdown value which contain disabled , e.g 'hover1 disabled', 'hover2 disabled', etc
    var dropdown = $("a[data-dropdown*='disabled']").attr('data-dropdown');
    // remove ' disabled' string and create new var , so result should be 'hover1', 'hover2', and etc.
    var dropdown_clean = dropdown.replace(' disabled','');
    // execute remove disabled from dropdown which contain disabled
    $("a[data-dropdown*='disabled']").attr('data-dropdown',dropdown_clean);
    
    // get data-dropdown target value which i click.
    var target = $(this).attr('data-dropdown');
    // execute add disabled on target
    $(this).attr('data-dropdown',target+' disabled');

    });

and not working.

**Comment by gakimball** [comment]
Could you post your HTML as well? That'd be super helpful.

**Comment by darkcyber** [comment]
Here is the HTML code , using laravel blade.
    
    <div id="main menu" class="medium-2 columns" style="padding-left:0px;padding-right:0px;">
         
        <dl class="accordion" data-accordion>
          <dd id="accordion-menu-1" class="accordion-navigation">
            <a href="#accordion-menu-1" id="accordion-menu-1" data-dropdown="hover1" data-options="align:right;is_hover:true;">Dashboard</a>
            <ul id="hover1" class="f-dropdown" data-dropdown-content>
              <li><a href="#1">hover1 This is a link</a></li>
              <li><a href="#2">hover1 This is another</a></li>
              <li><a href="#3">hover1 Yet another</a></li>
            </ul>
            <div id="accordion-menu-1" class="content active">
                <ul class="side-nav">
                    <li class="">{{ link_to('sempak/dashboard/home', 'Home') }}</li>
                    <li><a href="#l2">About</a></li>
                    <li><a href="#l3">Join</a></li>
                </ul>
            </div>
          </dd>
          <dd id="accordion-menu-2" class="accordion-navigation">
            <a href="#accordion-menu-2" id="accordion-menu-2" data-dropdown="hover2" data-options="align:right;is_hover:true;">Posts</a>
            <ul id="hover2" class="f-dropdown" data-dropdown-content>
              <li><a href="#21">hover2 This is a link</a></li>
              <li><a href="#22">hover2 This is another</a></li>
              <li><a href="#23">hover2 Yet another</a></li>
            </ul>
            <div id="accordion-menu-2" class="content">
              <ul class="side-nav">
                    <li class=""><a href="#l1">All Posts</a></li>
                    <li><a href="#l2">Add New</a></li>
                    <li><a href="#l3">Categories</a></li>
                </ul>
            </div>
          </dd>
          <dd id="accordion-menu-3" class="accordion-navigation">
            <a href="#accordion-menu-3" id="accordion-menu-3" data-dropdown="hover3" data-options="align:right;is_hover:true;">Accordion 3</a>
            <ul id="hover3" class="f-dropdown" data-dropdown-content>
              <li><a href="#31">hover3 This is a link</a></li>
              <li><a href="#32">hover3 This is another</a></li>
              <li><a href="#33">hover3 Yet another</a></li>
            </ul>
            <div id="accordion-menu-3" class="content">
              Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>
          </dd>
        </dl>
    </div>

Just plan to make admin menu like wordpress. thanks in advance.

**Comment by darkcyber** [comment]
my logic is ,
1. if ```<a href="...." >``` clicked
2. get the id of current ```<div id="..." class="content">``` or ```<dd id="..." class="accordion-navigation">``` which you clicked then save to var id; i use this to know which accordion menu is clicked.
3. go to target url (no ajax)
4. so all accordion is collapse by default.
5. then do  
```javascript
if($(".accordion-navigation").hasClass(".active") && $(".content").hasClass(".active")){
$(".accordion-navigation").removeClass(".active");
$(".content").removeClass(".active");
// add class
$("dd[id='+ id +']").addClass(".active");
$("div[id='+ id +']").addClass(".active");
}
```

so now accordion should expanded automatically deppends on what user click before.

how i can do this ? is foundation zurb dont have js library for add and remove class ?

**Comment by gakimball** [comment]
Sorry for the super late response, I'm taking a look at your issue today :)

**Comment by gakimball** [comment]
Alright, [here's a working example](http://codepen.io/anon/pen/NPvPJV?editors=101). This is the JavaScript:

```js
$('#dropdownAccordion').each(function() {
  var $accordion = $(this);
  var $accordionItems = $accordion.find('.accordion-navigation > a');

  // Store the IDs of each dropdown trigger in a separate attribute
  $accordionItems.each(function() {
    var dropdownID = $(this).attr('data-dropdown');
    $(this).attr('data-dropdown-id', dropdownID);
  })

  // Remove the dropdown from the first accordion link (assumed to be open by default)
  $accordionItems.eq(0).removeAttr('data-dropdown');

  // When an accordion item is clicked...
  $accordionItems.click(function() {
    // Re-add the dropdown attribute to all siblings
    $(this).parent().siblings().children().each(function() {
      var dropdownID = $(this).attr('data-dropdown-id');
      $(this).attr('data-dropdown', dropdownID);
    });
    // Remove the dropdown attribute from the clicked item
    $(this).removeAttr('data-dropdown');
  });
});
```

To disable the dropdown, I'm just removing the `data-dropdown` attribute from the active accordion item. But I store that value in a separate attribute called `data-dropdown-id` so I don't lose it. So when an accordion item needs to turn dropdowns back on, it copies the value from `data-dropdown-id` to `data-dropdown`.
