### ISSUE TITLE
Range Slider not working with Safari

### ISSUE THREAD

**Issue by Ltwrk** [zurb/foundation#6187]
It's my first project where I use the Foundation framework. It's very powerful, and does work great. But the Rangeslider doesn't work in Safari. It works fine in Chrome and all the others.

The url is: http://hilke-heizoel.de/bestellung/ You can find the range slider at: "2 Liefermenge:"

Does anybody has got a idea why it doesn't work in Safari ?

Cheers :)

**Comment by gakimball** [comment]
What version of Mac OS are you running? It seems to work with Safari 8, which comes with 10.10 Yosemite.

**Comment by Ltwrk** [comment]
I'm using Safari 8.0.2 with Yosemite 10.10.1

**Comment by gakimball** [comment]
Hm, I'm using the exact same version. I can drag the handle and the meter underneath will update. Are you getting any JavaScript errors in Safari's console?

**Comment by Ltwrk** [comment]
For me and another person who tried it it doesn't work.. http://www.vidup.de/v/IpoS8/

Yeah, i'm getting 2 errors: http://s22.postimg.org/ot9pnkx0h/Ohne_Titel.png

**Comment by gakimball** [comment]
In that video the slider works, so what part of it isn't working? Is the number in the box below supposed to change along with it?

**Comment by Ltwrk** [comment]
Oh, yeah I meant this.. sorry for my bad explanation. If you try the slider for example in chrome you see the number updating when you drag the slider

**Comment by gakimball** [comment]
Ahh, I see, no problem. Could you post a higher-resolution screenshot of the JS error you're getting? I can't read what's in that small thumbnail.

**Comment by Ltwrk** [comment]
[Error] Error: Error calling method on NPObject.
	(anonyme Funktion) (bestellung, line 1)
	symcBFPerformOnDOMChangedHandler (bestellung, line 1)
	dispatchEvent ([native code], line 0)
	respondToMessage (docstart.js, line 25)

[Error] TypeError: undefined is not an object (evaluating 'safari.application.addEventListener')
	global code (main.js, line 1)

Thank you for your help :)

**Comment by jeaniec** [comment]
@Ltwrk I was able to get this to work with a little code snippet. I put an ID on the range slider (but you can use any selector you wish) and specifically targeted the input to change its value attribute onchange.

```
$(document).foundation({
  slider: {
    on_change: function() {
      var val = $('#slider3').attr('data-slider');
      $('#sliderOutput3').attr('value', val);
    }
  }
})
```

That seemed to fix the Safari issue for me. Let me know.
