### ISSUE TITLE
No !important for visibility classes please.

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#6190]
Hello, 

I see this has been reference in #6024, #6050 and #6051 and I have to raise this issue again. 

@rafibomb You said, "Visibility classes need important because they are too easy to override."

I have *never* on my sites I have built with hiding content...that is until now. I was using `.hide` to hide content and then using javascript to reveal content when a person performed an action. I upgraded to a new version and all of the sudden all of my JS was broken. NOTHING was revealing. I now have to go through all of my sites when I upgrade them and remove `hide` and replace with `style:display:none;` so my javascript will function again. (I hope I have everything changed and don't get a call tomorrow from a client telling me something is broken because I missed it!)

I would really like to see this reverted back to it without a `!important` because this is causing way more problems than not having the `!important`. 

Also, if a person is having trouble with something not hiding (because of the lack of `!important`) it is very easy for them to override other styles to hide it. 

I believe @wolfgang-demeter had a pull request to revert this back. I must agree with @nblum "an important in a framework stylesheet is realy ugly... can't understand this"

Is there a specific use case for why this was done other than they are too easy to override?

**Comment by gakimball** [comment]
I can give you a basic example.

```scss
.button.expand {
  display: block; }

.hide {
  display: none; }
```

You could argue that this makes a good case against our style of writing CSS classes, but I don't know if that's likely to change, in this version of Foundation or the next. To be sure, the framework as it currently is has a little too much `!important` going on. Ideally the usage is *none*, except on these visibility classes. A well-written CSS component will avoid those specificity issues from the beginning and not resort to hacks.

The bigger issue is that we shouldn't have slipped an `!important` into an existing class that was widely used, when the framework is over a year old. What if we just revert that one change and keep the rest of the classes as they are? Changing any of the existing visibility classes to not use `!important` would be a breaking change in the same way changing `!hide` was.

**Comment by Lynda333** [comment]
Thank you for the example. I think you hit the target when you said: 

"The bigger issue is that we shouldn't have slipped an !important into an existing class that was widely used, when the framework is over a year old."

The `hide` class is the one I use the most frequently removing the `!important` would benefit me and even adding another class, such as `hide-important` or something of that nature for when we run into an issue with hiding an item. Of course there is probably a better way to phrase the class but that is the idea. 

Also, and I believe this is has been mentioned for F6, is less CSS Specificity would help this issue as well.

**Comment by gakimball** [comment]
Yep, we're looking at potentially using less tag selectors and more classes, which means less nesting and less specificity.

**Comment by Lynda333** [comment]
Thank You @gakimball!

**Comment by wolfgang-demeter** [comment]
Version 5.4.7 also introduced `visibility: hidden;`! To make `.hide` work again as expected - like in previous versions - this has to go to. I mentioned that in my - then declined - Pull Request (https://github.com/wolfgang-demeter/foundation/commit/dee0ca2463b7073284a55373eb646c4d8efcb9c4 and https://github.com/zurb/foundation/pull/6051).
But thankfully this abominiation has an end! ;)

**Comment by gakimball** [comment]
Done and done. 8bed21e7aa843b1e2be32f120d178c92892484f8
