### ISSUE TITLE
Opening two reveal modals in a row causes second one not being closed correctly 

### ISSUE THREAD

**Issue by Derrick666** [zurb/foundation#6192]
If you show a reveal modal, and then close it and show another at the same time you end up with the first one closing, removing the underlay and the second being shown with no underlay, and hence can't be closed.

Furthermore, when you close the second modal the underlay is displayed and is not removed on click.
The problem is reproduced [here](http://jsbin.com/wezequyapi/1/edit?js,output)

Interestingly, if you don't call .foundation('reveal', 'close') then it [works as expected](http://jsbin.com/zexiruhefo/1/edit?html,js,output).

**Comment by rafibomb** [comment]
Working here on the docs http://foundation.zurb.com/docs/components/reveal.html

**Comment by aexmachina** [comment]
The docs don't provide the same scenario as the JSBin example. The JSBin example clearly demonstrates the problem. Surely this isn't the desired behaviour?

**Comment by jeaniec** [comment]
In this case, the Foundation API is a bit misleading and not very clearly explained in the docs (I'll update accordingly), but to fix this problem, you actually do NOT call .foundation('reveal', 'close'). 

The 'open' method checks for whether or not other modals are currently open. If there are any others open, it'll automatically close them and open the next one in the "queue." This is similar to the example that @rafibomb showed in the docs, where there are "nested" subsequent modals.

**Comment by aexmachina** [comment]
Cool, I see. So @Derrick666 the solution is to not call close: http://jsbin.com/gevelu/1/edit?js,output
