### ISSUE TITLE
select[multiple]

### ISSUE THREAD

**Issue by hypeJunction** [zurb/foundation#6193]
Styling of multiple select is a bit off, background image should not appear, and the height should be set to something taller.

**Comment by rafibomb** [comment]
We don't have a multi-select component. Can you point us to what you're referring to?

**Comment by hypeJunction** [comment]
```<select multiple>``` is part of HTML 4.01 spec
http://www.w3schools.com/tags/att_select_multiple.asp

Foundation does not make an exception for multiple attribute and styles all
select elements in the same manner.

**Comment by tdhartwick** [comment]
We added basic height styling to select[multiple]
https://github.com/zurb/foundation/commit/13172287c83b4f0dcb9f1f8d4df94bc9cd2bdc0f

**Comment by hypeJunction** [comment]
I will double check but I think the background image might still be an
issue.
