### ISSUE TITLE
Foundation 6: grid feedback

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation#6195]
The grid is a signature component of the Foundation framework, and for version 6 we'd like to make it even better. In the past few years, lightweight, semantic grid frameworks with a ton of flexibility and customization have become popular. We'd like our grid to be able to compete with those frameworks, although we're still going to try and balance more features with more complexity. The aim wouldn't be to mimic every single feature that super advanced grid frameworks have.

The most common request we've gotten is for multiple grid definitions. The syntax would look something like this:

```scss
.custom-column {
  // 6/12 columns
  @include grid-column(6);

  // Now 6/8 instead
  @include grid-column(6 of 8);
}
```

As far as the actual structure of the grid, we like the padding approach for gutters we currently use because it makes framework code way easier to write and understand. The `margin-right` approach definitely has its benefits, like simpler nesting and potentially less HTML used, but the math is *crazy*, and nesting grids becomes more complex.

**What we'd like to hear is what features you're missing from the grid system.** If you have feedback on our other components, or how our HTML, Sass, and JavaScript are written, we have discussion threads for that as well.

**[View our other discussion topics for Foundation 6 here.](https://github.com/zurb/foundation/labels/Foundation%206)**

**Comment by datenimperator** [comment]
Please _do not_ change the way how the grid is used w/ respect to grid class names. It is a MPITA going through all views and replacing one system of class names with another. Didn't we go through this when Foundation went from 4->5? Or was it 3->4?

Foundation is the UI foundation for a number of customer projects that are maintained for quite a while. Updating them for new versions of ruby and rails and stuff isn't always fun already. Personally, I don't need even more hassle upgrading Foundation with every major release just because of a fancy new grid syntax.

**Comment by gakimball** [comment]
@datenimperator From 3 to 4 we changed the syntax (`one column` became `small-1 column`), but we don't plan on changing the grid syntax for version 6; we like how it is now. The structure of the grid mixins may change, however.

**Comment by datenimperator** [comment]
@gakimball \o/

**Comment by r3wt** [comment]
I agree with @datenimperator

**Comment by izakfilmalter** [comment]
Can we get a calc based grid that uses margin outside of the column instead of padding inside of it. Flex is the future and you have embraced it for Foundation for Apps. If the grid is set up this way we can use the column as the wrapper for a block instead of having them be independent and having more div soup.

Maybe a simplistic flex grid that is a bit of a beta release alongside the tradition float grid would help people see the power of flex.

**Comment by gakimball** [comment]
@izakfilmalter `calc()` is a possibility; I always forget it's supported in IE9. The `margin-right` grids that some frameworks use have this crazy math that seems like a lot of trouble to implement, but `calc()` would probably streamline a lot of that.

We also plan on bundling a flexbox grid along with the float grid. The two would probably use a very similar syntax, with added features for the flexbox grid (like auto-shrinking columns).

**Comment by izakfilmalter** [comment]
@gakimball AWESOME!!!!!!!! This would really bring a lot of modernness to foundations grid.

**Comment by joelkinzel** [comment]
I'm glad to see you're going to bring the flex grid to FFS (what acronym are we using?). Again, thinking forward, it is the future and you should be a step ahead of your competition. Personally if there is an option between the float and the flex, I'd go flex every time. No sense in using an inferior method.

**Comment by tsquez** [comment]
@joelkinzel I kind of like FFS - I can def see it on some swag!

**Comment by proimage** [comment]
Using flexbox for site column layout is madness. It's great for flexible components like nav bars and the like, but it's not geared towards proper layout from what I've seen.

I'd like to see native FFS support for a `tiny` grid size. I often find myself struggling with making the same grid work well for both 640px wide (`small`'s widest point) and 320px wide, which is the lower limit on screen width I typically build for.

Even better than that though would be support for Element Queries - even if only via a polyfill to begin with.

**Comment by rafibomb** [comment]
@joelkinzel @tsquez We're leaning to F4S, F4A, F4E, but open to suggestions on that ;)

**Comment by rafibomb** [comment]
@proimage Element queries are cool but outside polyfills there is no CSS support. It would be nice to get that control (such as min-width, max-width, min-height and max-height) and apply CSS.

**Comment by proimage** [comment]
@rafibomb Indeed. Why not have it be a component that requires JS, just like multiple other components?

**Comment by joelkinzel** [comment]
@rafibomb Yeah, I think FFS has some other meanings potentially associated with it ;-) F4A/S/E maybe the better option.
As far as the grid is concerned, I've never really had a problem, so perhaps just adding the flexbox grid is the ultimate solution here. I'm not sure there is any benefit to changing to the margin-right and calc (plus, performance wise, calc is pretty expensive still iirc). It avoids "div soup", but in all honesty, if you're building a complex site, chances are you will end up adding those extra divs for other reasons.

**Comment by gakimball** [comment]
@joelkinzel Yeah, when we think about if it's worth changing how the grid is structured, we need to consider *what problem we're solving when we add more complexity*. `calc()` and flexbox *do* make the grid structure more complex, even if they open up new opportunities.

We feel pretty good about how the grid works in Foundation 5, but a few of the key issues we've identified are:
- You can't directly style a column and make it look good
- You can't easily adjust the gutters on a row and still have everything line up (because there's padding on both sides of the column)
- You can't mix and match different grids

A `calc()` or margin-right grid solves some of these problems, but also opens up new ones. Our current approach works really well because understanding how it's built is easy (it's just percentages!), and the width of a column and its gutters can be set independent of each other.

**Comment by zakdances** [comment]
How about no grid? Or, more accurately, no grid abstractions and instead, direct flexbox manipulation?  The flexbox concept is simple enough and giving flex elements special semantic names like "grid-container" might be unnecessary. Everything is based on a modular scale, so boxes that serve as "rows" and "columns" don't need special treatment or distinction.

Instead, offer classes and mixins that refer **directly** to properties such as `display: flex`, `flex-grow: 1`, etc and make it easy to assign them padding, margins, and sizing from the modular scale.

Not only is this more "standards compliant", but it also increases flexibility, customization, and cuts down on nesting.

**Comment by erredeco** [comment]
I would like to see something similar to http://zengrids.com/... grid is an useful tool, but its drawback is that you eventually end up with a lot of classes you don't actually use ;)

**Comment by gakimball** [comment]
@erredeco We already have semantic mixins for the grid. Are there specific features of Zen Grids you think we should take a look at?

**Comment by erredeco** [comment]
@gakimball Ok, but...correct me if I am wrong, in F5 you must use _grid.scss which always adds the full grid for small, medium, large which means 12 classes .small-x, plus 12 classes .medium-x, plus 12 classes .large-x, not counting .small-push-x, .small-pull-x, .small-offset-x, .medium-pull-x, .medium-push-x, .medium-offset-x, .large-pull-x, .medium-push-x, .medium-offset-x. Total: 12x12 = 144 classes (!)

zen grid comes with multiple grid definition (you can decide how many subdivision you want for each grid); semantic grid (apply grid definitions only to the relevant elements you want), order of elements (see http://zengrids.com/help/#example-3) , different gutters (for each grid) and if you look for example at the example http://zengrids.com/help/#example-1 or http://zengrids.com/help/#example-4 you can achieve complex layouts with a very simple markup (even without nesting!)

**Comment by gakimball** [comment]
@erredeco Our grid includes classes and mixins, so you can use one or the other, or both. Each component has a variable that will disable its CSS output, while still allowing you to use the mixins. For the grid, that variable is `$include-html-grid-classes`. By setting it to `false`, you can turn off all of the pre-made CSS classes.

To be sure, we must not surface this information well enough, because plenty of folks assume there's no way to build semantic grids with Foundation, even though it's been there since version 3 ;)

We're going to streamline the process of managing imports in the next version of the framework. If you check out how we do it with [Foundation for Apps](https://github.com/zurb/foundation-apps-template/blob/408b2cad1bbb78ba19bac0085cb6d13b461ef5a0/client/assets/scss/_settings.scss#L39), you can get an idea of what's to come.

**Comment by erredeco** [comment]
@gakimball ok I got it you were right :) Maybe it's only a matter of documentation then, as in the doc page about the grid the $include-html-grid-classes is not even mentioned :)

I see that in the FFA a SCSS map is used :) It makes thing simplier, so kudos!

**Comment by kevbook** [comment]
Have you guys seen: https://github.com/corysimmons/lost

**Comment by GBratsos** [comment]
In Foundation 6 can we have more breakpoints like Bootstrap does ?

I think we need to control better the tablet version of site and the small screen.

Medium grid breakpoint is too big (1024px - 640px) to control and consider portrait and landscape devices.
Can we have somethig like (1024px - 800px) and (800px to 640px) native breakpoints to use? Also i think it would be usefull to have 1024px - 1300px breakpoint

**Comment by gakimball** [comment]
@GBratsos Manipulating breakpoints will be a lot easier in 6. Breakpoints are configured in a map, which makes it really easy to change both the values and the names of breakpoints, and even add new ones. Check out the implementation in [Foundation for Apps](https://github.com/zurb/foundation-apps/blob/master/scss/helpers/_breakpoints.scss) to get an idea of what it will look like.

We're also looking at lowering the current breakpoints by around 100px each, but we don't have exact values decided yet.

**Comment by proimage** [comment]
Ah, so technically, we could add a new `tiny` breakpoint like this, which would be available for the grid?
```
$breakpoints: (
  tiny: rem-calc(0),
  small: rem-calc(480),
  medium: rem-calc(640),
  large: rem-calc(1200),
  xlarge: rem-calc(1440),
  xxlarge: rem-calc(1920),
);

$breakpoint-classes: (tiny small medium large);
```

**Comment by gakimball** [comment]
@proimage Yes! Although one thing we didn't solve in Apps is what happens if you rename `small` and `medium`, because some of our components reference those breakpoint names.

Obviously for more complex components we typically let you change those breakpoints, like top bar. Most components only have two modes: a small-screen one and a large-screen one, and that shift typically happens on medium.

So maybe we can give users the option to define the global "stack point" (if we want to be reductionist about responsive design) of components?

**Comment by erredeco** [comment]
I would also like to add some inspirations/ideas:

1) placard input (bootstrap): http://getfuelux.com/javascript.html#placard
2) popout collapsible (materializecss) http://materializecss.com/collapsible.html
3) datepicker (materializecss) http://materializecss.com/forms.html (I like it)

**Comment by proimage** [comment]
@gakimball Ahh, cool. It seems to me that there's 3 aspects of Responsive Design that (ideally) should be taken into account:

- Screen size
- Interface method
- Bandwidth

The small/medium/large stuff deal with the screen size just fine. Unfortunately, screen size is also shoehorned into informing other decisions that (ideally) should be determined by the other two aspects. In other words, if it's a small screen, make interactible elements large enough for finger input (assuming that small screen = touchscreen).

Regarding Foundation, this affects mainly the top-bar breakpoint. The top-bar goes from from mouse-friendly to finger-friendly. Is there any way to make that breakpoint dependent on the interface method instead of the screen size?

 - Michael C.

**Comment by proimage** [comment]
@erredeco I like the placard, but that seems more suitable for a 1st-party add-on component to Foundation than something built in to the core.

The popout collapsible is already a thing in HTML5 (the `<summary>` and `<details>` elements), although [support isn't widespread yet](http://beta.caniuse.com/#feat=details). If Foundation were to do something like that, then IMO they should definitely base it off the existing elements, enhancing the styling and providing a polyfill for the browsers that don't support them natively.

I love the datepicker though. :)

**Comment by erredeco** [comment]
@proimage 
about the "breakpoind dependent on the interface method" AFAIK there are at least a couple of roads:

1) @media (pointer:coarse) but I don't remember how much it is supported
2) use modernizr.js detection of touch, but as far as I remember, it detects also windows 8

about your other observations ,
- placard >  I cannot but agree
- popout collapsible: I was referring on the popout animation of the accordion
- datepicker: yes, I like it too :) I also like full-screen modals
I've understood that the great "innovation" of Material Design is that the design "gains" the 3rd dimension (z-axis)... it could be very nice if FF could have its own implementation/styleguide that not mocks the Material's one.

**Comment by proimage** [comment]
Ahh, gotcha. I dunno about the popout animation - Zurb seem to tend towards no animations unless absolutely necessary (off-canvas, modals, etc). Not sure if an accordion would be considered necessary. God knows I've had to manually animate the old "tabcordion" plenty of times that I'd welcome native animation though. :)

**Comment by erredeco** [comment]
just as source of inspiration: http://www.smashingmagazine.com/2015/06/17/responsive-typography-with-sass-maps/

**Comment by zurbrandon** [comment]
Thanks for the feedback, all! We've looked it over and are really rocking away at getting Foundation 6 out very soon!
