### ISSUE TITLE
.dropdown toggle does not work properly

### ISSUE THREAD

**Issue by EnokViking** [zurb/foundation#6204]
```
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
```
this snippet from the docs disables the on-hover event and enables the click event, however, you cannot CLOSE the dropdown by clicking the ACTUAL DROPDOWN, you have to click OUTSIDE THE DROPDOWN to close it. This only affects:

```
 .dropdown
```

not

```
.f-dropdown
```

**Comment by gakimball** [comment]
By "actual dropdown" do you mean the parent link that opens the menu, or the menu items themselves?

The parent link should probably also be able to close the dropdown. But the menu items themselves don't necessarily need to, as it's assumed that your menu links are going to another page.

**Comment by rafibomb** [comment]
When clicking the dropdown links on a clickable dropdown, dropdown closes, unless it is the has-dropdown link that opens another level. Tested on docs v 5.5.1   Closing here, but if you still need help please post on the forum.
