### ISSUE TITLE
date validation in a form 

### ISSUE THREAD

**Issue by spagu** [zurb/foundation#6206]
It looks date validation does not work in Firefox 35 && IE11.
`<form data-abide>`
` <div class="row">`
`<div class="large-12 columns">`
` <label>Input Label</label>`
`<input type="date" placeholder="large-4.columns" required>`
`</div>`
`</div>`
`</form>`

this works with chrome only, other browsers won't pass and give a data format is not correct.

You can edit index.html that comes from zurb zip file with 
`type="date"` in any form section and test it with two browsers.

**Comment by gakimball** [comment]
Are you seeing this in our documentation or your own code? And what version of Firefox are you using?

**Comment by spagu** [comment]
I just checked problem occurs with IE 11 too. FF 35.0. Not sure about other versions. 

the problematic section is : 
<addr><input type="date" placeholder="anything" required > </addr>

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
