### ISSUE TITLE
There is no reflow method on abide.js

### ISSUE THREAD

**Issue by dmastylo** [zurb/foundation#6214]
There is no reflow defined here: https://github.com/zurb/foundation/blob/27b3fcf34050f6d341f2608149ddc58000686f7b/js/foundation/foundation.abide.js

This error occurs when trying to reflow abide using $(document).foundation('abide', 'reflow');

![image](https://cloud.githubusercontent.com/assets/2275125/5848677/cbffedb4-a1a0-11e4-90e4-bd07ce2522df.png)

I tried to monkeypatch Foundation.libs.abide

```javascript
Foundation.libs.abide.reflow = function() {
    this.bindings(null, null);
  };
```

This suppresses the error but doesn't work. Calling ```Foundation.libs.abide.reflow();``` directly doesn't work as well, obviously, because reflow is not defined.

**Comment by dmastylo** [comment]
I did a minor fix by adding an event handler on the input field when it's "blurred" (when a user moves focus to a different element)
```javascript
added_education.find('input').blur(function() {
  Foundation.libs.abide.parse_patterns($(this));
});
```

**Comment by rafibomb** [comment]
You're right! Can you submit a Pull Request?

**Comment by dmastylo** [comment]
I'm super well versed in how Foundation does reflowing and I just did a temporary fix instead of monkey-patching it. Are there any docs on reflowing or should I just follow the other libraries (accordion, orbit, etc)?

**Comment by jeaniec** [comment]
There aren't any docs on reflowing other than the basic "this is how you use 'reflow'" so if you just follow the general format of the other libraries, that should be good!

**Comment by dmastylo** [comment]
I'll see if I can cook something up.

**Comment by dmastylo** [comment]
Looks like a lot of the libraries just have an empty function on reflow? Is there something I'm missing?

**Comment by jeaniec** [comment]
I think that when the method was first implemented, it was very component-specific, so some of them didn't require having a reflow function if there wasn't a lot of dynamic animation/DOM manipulation going on.

**Comment by dmastylo** [comment]
Makes sense. How should I go about testing this? Is there a testing suite? Have never done automated testing on Javascript.

**Comment by dmastylo** [comment]
Nevermind I should read the documentation before asking a dumb question!

**Comment by jeaniec** [comment]
There's a spec file for abide.js that's written in jasmine. But if you submit a pull request with your changes, we'll take a look, test it, and merge it in if it passes! :)

Better coverage for testing is definitely on our roadmap!

**Comment by DecipherOne** [comment]
@dmastylo 's work around was the only way I was able to get this to work when dynamically adding fields. For anyone else out there looking for a solution, this is the one for now.

**Comment by jeaniec** [comment]
@dmastylo @DecipherOne Can you guys see if the recent reflow method I added works for your use cases? Thanks!

**Comment by dmastylo** [comment]
@jeaniec Sorry meant to do this myself but school started and has been pretty hectic last few weeks. I'll test it this weekend!

**Comment by DecipherOne** [comment]
@jeaniec , I'm out of the office for the weekend, but will give it a shot on Monday.

**Comment by DecipherOne** [comment]
This does not work for my use. This results in
uncaught type error : can not read property 'call' of undefined. and breaks on 

this line in foundation

 // # Patch to fix #5043 to move this *after* the if/else clause in order for Backbone and similar frameworks to have improved control over event binding and data-options updating.
    if (typeof method === 'string') {
      return this[method].call(this, options);
    }

**Comment by jeaniec** [comment]
@DecipherOne Do you have a code snippet that I can examine further? I can't seem to replicate this particular issue.

**Comment by jeaniec** [comment]
@DecipherOne Could you try the method again as of https://github.com/zurb/foundation/commit/fb92e427d2c1ad12e6b13013a8c3eede02a50fe1 ?

**Comment by TheHanna** [comment]
@jeanieshark I was experiencing a similar error to the one @DecipherOne was seeing. I can confirm that commit fb92e427d2c1ad12e6b13013a8c3eede02a50fe1 resolved the issue in my case.

**Comment by jkanie** [comment]
Hello! How would one do the equivalent of 
$(document).foundation('abide', 'reflow');
in Foundation 6?

**Comment by DanielRuf** [comment]
In Foundation 6 you have `Foundation.reInit()` and so on.

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/javascript.html

**Comment by DanielRuf** [comment]
`_reflow` is still available https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js

**Comment by jkanie** [comment]
@DanielRuf : Thank you! :)
