### ISSUE TITLE
Flex box & Masonry style gallery for F6

### ISSUE THREAD

**Issue by siddhion** [zurb/foundation#6216]
It would be great to have Flexbox as well as some type of Isotope or Masonry gallery component.

**Comment by siddhion** [comment]
It would be great to have Flexbox as well as some type of Isotope or Masonry gallery component.

**Comment by gakimball** [comment]
Masonry and Isotope do their job really well, so we aren't looking to implement anything that complex in the base framework. However, we will be including an experimental flexbox grid in Foundation 6.

If you have any specific feedback on features you'd like to see in the current float grid or a new grid, [let us know here.](https://github.com/zurb/foundation/issues/6195) :)
