### ISSUE TITLE
Rounded buttons? Wording issue.

### ISSUE THREAD

**Issue by doertedev** [zurb/foundation#6217]
OHAI.

https://fezvrasta.github.io/bootstrap-material-design/ Floating icon button (ToDo)
http://ui.lumapps.com/css/buttons (Exists)
Vanilla Foundation? (Missing)
Vanilla Bootstrap? (Missing)

I just whanted to create a round icon button but got hit by a wording issue, the name is taken by foundation. The CSS Class "round" creates round borders around a .button element. Can we either create round icon buttons or change the name in the next compatibility breaking version update? Like s/round/rounded/g ? What you guys think of that?

**Comment by gakimball** [comment]
We're actually considering deprecating the `radius` and `round` classes in Foundation 6, because we think their purpose is better served by Sass. That's still up in the air, though.

I'll add circular buttons to our Foundation 6 request list over this way: #4710
