### ISSUE TITLE
Interchange Header Image Not Working?

### ISSUE THREAD

**Issue by mAAdhaTTah** [zurb/foundation#6218]
The splash on my homepage: http://jamesdigioia.com/ doesn't swap out the small, medium and large images, despite being marked up for Interchange and background images:

```php
<header id="splash" data-stellar-background-ratio=".5" data-interchange="
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-large.jpg, (large-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-medium.jpg, (medium-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-small.jpg, (small-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header.jpg, (default)]
">
```

What am I doing wrong?

I'm on Foundation 5.3.3, admittedly. I had some issues upgrading which I haven't worked out yet, but if this is fixed in a later version, I'll upgrade and test again.

Thanks!

**Comment by gakimball** [comment]
You need to reverse the order of your media queries so they're mobile-first. Order them `default`, `small`, `medium`, and then `large`.

This is because Interchange goes with the *last matching rule* it can find. Since you have `default` last, `default` will always be the one it picks.

**Comment by rafibomb** [comment]
If you need more help, The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by mAAdhaTTah** [comment]
@rafibomb Actually, I think I may have found a bug. Take the code above and put default at the beginning:

```php
<header id="splash" data-stellar-background-ratio=".5" data-interchange="
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header.jpg, (default)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-small.jpg, (small-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-medium.jpg, (medium-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-large.jpg, (large-only)]
">
```

The last matching rule should be one of the `-only` queries, depending on the size of your window, but it's still matching default. You can see this here now: http://jamesdigioia.com/

I will note it works the way it's supposed to without the `-only` on all queries, and that's what I'm going to go with, but wondering if there's a bug when using those media queries with Interchange for background images.
