### ISSUE TITLE
hasOwnProperty instead of hasAttribute

### ISSUE THREAD

**Issue by Phr34ker** [zurb/foundation#6221]
I discovered a bug in the slider.
We had a slider, whose value should be transfered to a input:hidden.
In Firefox it refused to work. Instead of setting 

&lt;input ... value="8" /&gt; 

it set

&lt;input ... &gt;8&lt;/input&gt;

Turns out that when you ask Firefox if this.hasOwnProperty("value") (where this == the hidden input field), it says no. So it moves on to setting the innerText instead

          $(settings.display_selector).each(function(){
              if (this.hasOwnProperty('value')) {
                  $(this).val(value);
                  } else {
              $(this).text(value);
              }
          });

In Chrome it works, though.
So I had to change it to hasAttribute

          $(settings.display_selector).each(function(){
              if (this.hasAttribute('value')) {
                  $(this).val(value);
                  } else {
              $(this).text(value);
              }
          });

Then it worked like a charm in Firefox aswell

**Comment by gakimball** [comment]
Good catch, would you like to submit a pull request for the fix?
