### ISSUE TITLE
Top Bar: .f-topbar-fixed should be optional

### ISSUE THREAD

**Issue by pixelfreak** [zurb/foundation#6225]
There should be a way to specify whether the `f-topbar-fixed` class is injected to `body` or not. Or maybe the ability to specify which element to put the class in.

In my use case, there are designs that has elements behind a fixed translucent top bar and currently the only way to achieve this is to use negative positioning to compensate for the padding in the body.

**Comment by gakimball** [comment]
It's a single class selector, so you should be able to override it fairly easily:

```css
body.f-topbar-fixed {
  padding-top: 0;
}
```

**Comment by shadysamir** [comment]
But this creates undesirable effect when other scripts/logic wishes to add top padding to body. I'd rather be able to optionally turn off injection.

A sample case is using zurb foundation theme in Drupal and the toolbar adds body padding top depending on shortcuts bar status for logged in users.
