### ISSUE TITLE
How to set class active in accordion menu ?

### ISSUE THREAD

**Issue by darkcyber** [zurb/foundation#6226]
currently in my accordion content i have ```<a href="...." >``` , then every i click ```<a href="...." >``` it will open the target url (no ajax) and all accordion menu is collapse so user dont know where he now and if user want to click other link in the same accordion menu he must click accordion menu first to show accordion menu content , then click what he want.

now what i want is make accordion menu active after user click link in the accordion menu, so user know where he now and easy to navigate.

my html code laravel blade

    <div id="main menu" class="medium-2 columns" style="padding-left:0px;padding-right:0px;">
         
        <dl class="accordion" data-accordion>
          <dd id="accordion-menu-1" class="accordion-navigation">
            <a href="#accordion-menu-1" id="accordion-menu-1">Dashboard</a>
    
            <div id="accordion-menu-1" class="content">
                <ul class="side-nav">
                    <li class="">{{ link_to('sempak/dashboard/home', 'Home') }}</li>
                    <li><a href="#l2">About</a></li>
                    <li><a href="#l3">Join</a></li>
                </ul>
            </div>
          </dd>
          <dd id="accordion-menu-2" class="accordion-navigation">
            <a href="#accordion-menu-2" id="accordion-menu-2">Posts</a>
            <div id="accordion-menu-2" class="content">
              <ul class="side-nav">
                    <li class=""><a href="#l1">All Posts</a></li>
                    <li><a href="#l2">Add New</a></li>
                    <li><a href="#l3">Categories</a></li>
                </ul>
            </div>
          </dd>
          <dd id="accordion-menu-3" class="accordion-navigation">
            <a href="#accordion-menu-3" id="accordion-menu-3">Accordion 3</a>
            <div id="accordion-menu-3" class="content">
              Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>
          </dd>
        </dl>
    </div>

my logic is ,
1. if ```<a href="...." >``` clicked
2. get the id of current ```<div id="..." class="content">``` or ```<dd id="..." class="accordion-navigation">``` which you clicked then save to var id; i use this to know which accordion menu is clicked.
3. go to target url (no ajax)
4. so all accordion is collapse by default.
5. then do  
```javascript
if($(".accordion-navigation").hasClass(".active") && $(".content").hasClass(".active")){
$(".accordion-navigation").removeClass(".active");
$(".content").removeClass(".active");
// add class
$("dd[id='+ id +']").addClass(".active");
$("div[id='+ id +']").addClass(".active");
}
```

so now accordion should expanded automatically deppends on what user click before.

how i can do this ? is foundation zurb dont have js library for add and remove class ?

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
