### ISSUE TITLE
offcanvas menu delay on display

### ISSUE THREAD

**Issue by PsykoSoldi3r** [zurb/foundation#6227]
Off-Canvas

After opening the off-canvas menu by clicking on the menu button. De off-canvas will slided open and displayed the content. On Mozilla Firefox when you open the menu. After de menu is opened,  the content will displayed with a delay. It's also on the example page of Foundation.

http://foundation.zurb.com/docs/components/offcanvas.html

**Comment by jr-duboc** [comment]
I've tested this on Firefox 35.0.1, couldn't see the problem. What version of FF are you using?
Any problem with other browsers ?

**Comment by PsykoSoldi3r** [comment]
It looks like that's specific on Firefox 35.0 on Mac OS X. After upgrading to 35.0.1 it's working as normal.

Problems with:
* Firefox 35.0 ( Mac OS X Yosemite )
* Firefox 35.0 ( Mac OS X Mavericks, tested on BrowserStack )

No problems with:
* Firefox 34 - 30 ( Mac OS X Yosemite, tested on BrowserStack )
* Firefox 35 + 35.01 ( Windows 8 )
* Firefox 35 - 30 ( Windows 7 & 8, tested on BrowserStack )

**Comment by gakimball** [comment]
This might be related to [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1083079), which was indeed patched in version 35.0.1. If you scroll down and look at the attachments, there's a .mov file demonstrating the bug, and it's the same thing: when the animation finishes, the content briefly disappears and then snaps back into place.
