### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by Pat-Paran** [zurb/foundation#6228]
i extracted my repository on my public_html folder then when i git fetch on changes it says permission denied . when i tried another repositories its adding keys and will not give me error. i tried to register my ssh key to my github account they were paired but im having error whenever i use git on my server. please help thanks

**Comment by gakimball** [comment]
Can you elaborate on what you're trying to do? How are you installing and updating Foundation?

**Comment by Pat-Paran** [comment]
![screen shot 2015-01-28 at 2 00 38 pm](https://cloud.githubusercontent.com/assets/9376401/5940431/389fa4b8-a724-11e4-988d-77fbba34e255.png)

**Comment by gakimball** [comment]
Sorry, unless it's an issue with Foundation specifically, I don't think we can help you here. For SSH help I'd recommend one of the Stack Exchange sites, specifically [Super User](http://superuser.com/).
