### ISSUE TITLE
foundation.zurb.com or the foundation library causes complete freeze of Android w/ Chrome

### ISSUE THREAD

**Issue by lewisdiamond** [zurb/foundation#6234]
What happens: The website loads partially, then the entire system freezes and the battery must be removed from the device to recover. Also happens on the website I'm developing using Foundation.

Device: Samsung Galaxy S2
Cyanogenmod 11-20141115-SNAPSHOT-M12-i9100
Android 4.4.4
Kernel 3.0.64-CM-g4ca83ff

Chrome 40.0.2214.89 (stable & beta)

Does not happen on an android 4.4.2 tablet with 3.4.0 kernel.

**Comment by gakimball** [comment]
We test on Android 4.4 for every release. This specific bug would be *very* difficult for us to pin down. Does your phone crash when loading any other websites that use Foundation? Try loading any of our other properties, like [zurb.com](http://zurb.com/), our [blog](http://zurb.com/blog), or our [library](http://zurb.com/university/library). All of those sites are on Foundation.

**Comment by lewisdiamond** [comment]
Indeed it doesn't look like a simple bug to figure out. I haven't managed to find out exactly if the VM crashes or if it's the kernel. Is it a device specific bug with that specific kernel build from CM or does it have something to do with the android version + kernel version? I can't tell.

Yes, zurb.com, the blog and the library also cause the crash. Several other sites which don't use foundation work just fine.

It does not happen on the android browser (i.e. not chrome). It's a pretty obscure bug and I'm hoping you guys have more test hardware than I do.

**Comment by gakimball** [comment]
We don't have an S2 specifically, but we do test on 4.4, and older versions of Android as well. It's possible that your specific combination of hardware and firmware is causing the stars to align and make your phone crash. I can't think of anything about the framework that would cause a phone to hard lock.

Could you try loading a stock Foundation page with no JavaScript, just CSS?

**Comment by lewisdiamond** [comment]
That's actually how I found out foundation was causing the issue. I removed the CSS and the site started to work, I removed the JS and the site still didnt work.

As another test, I disabled Javascript on my browser and visited zurb.com and saw the exact same issue.

Note that I use foundation's css only, not the JS.

**Comment by ganiutomo** [comment]
Try removing the animation from css file.

**Comment by rafibomb** [comment]
This seems to be a more specific issue with the testing device. We'll close this here and keep it in mind as we build out the next version.

**Comment by lewisdiamond** [comment]
I managed to identify a subset of the library causing the issue.

If I only include the off-canvas part of the library, I still get the issue (and it doesn't happen if I only have forms for example). So the issue is inside this much smaller number of lines. I'll try to find out the exact cause another day.
