### ISSUE TITLE
Close reveal modal with button

### ISSUE THREAD

**Issue by darkcyber** [zurb/foundation#6235]
i have already try this
http://foundation.zurb.com/forum/posts/1542-how-can-i-close-a-reveal-modal-with-a-button

but the result is like [this picture](http://i.imgur.com/bHlBMvX.png) 

what i want is "X" still in the right top bar and i create new button which have function to close reveal modal.

thus cancel button class seems not working correctly but the function to close reveal modal is working, here is my cancel code, 

```
<input type="button" class="tiny button secondary close-reveal-modal" value="Cancel"></input>
```

and the second is ```data-modal-id``` and ```<div id=>``` for modal must contain "myModal" , without it reveal modal not working. because i use to loop reveal modal , like "myModal1" , "myModal2" and so on. dont know if this is reveal modal pattern or bugs. ?

**Comment by gakimball** [comment]
You could try adding your own event handler to the button. Add some unique class or attribute to the button that you can target with jQuery. In this example the class is `.close-button`.

```html
<input type="button" class="tiny button secondary close-button" value="Cancel">
```

And now in the JavaScript, trigger an `open` event on your modal when this close button is clicked.

```js
$('#modal .close-button').click(function() {
  $('#modal').foundation('reveal', 'close');
});

**Comment by gakimball** [comment]
The above solution has been tested and works, so I'm closing this. Let me know if you need any more help!

**Comment by jkyadav** [comment]
Hello @gakimball, I am also facing this problem, but in my case when clicking on cross button it just refreshes the page losses the page data.

Event same think happening with new button as he mention in the document. If am using normal and trying to call $('#myModel').foundation('reveal', 'close'); this code doesn't close modal.

Any help? Any idea?

**Comment by stefftabalong** [comment]
I just encountered this issue & was able to resolve this by just editing **foundation.css**

The class that trigger the link to close is 

   .close-reveal-modal

In foundation.css, look for the following class:

    .reveal-modal .close-reveal-modal {    
       //some css blocks
     }

now remove all of the css blocks inside and create another class, for example:

    .reveal-modal .close-x-btn{
       //paste the css blocks here from the .close-reveal-modal
     }

Overall your button should look like this

    <a class="button close-reveal-modal">Cancel</a>

As for the "x" at the top right corner of the modal

    <a class="close-reveal-modal close-x-btn" aria-label="Close">&times;</a>

So now, you can close a modal using a button and the "x" on the top right corner while still keeping the original style of the "x" link

**Comment by mota57** [comment]
this works for me to do in a more general way

```

 $('.btn-close-modal').on('click', function () {
            var div = $(this).closest('div.reveal-modal').first();
            $(div).foundation('reveal', 'close');
        })
```
