### ISSUE TITLE
Joyride post_ride_callback not working

### ISSUE THREAD

**Issue by steoo** [zurb/foundation#6238]
Settings like this

     $(document).foundation("joyride", "start", {
             "post_step_callback": function(){
                console.log("Fine step");
             }, 
             "pre_ride_callback": function(){
                console.log("Pre tour");
             },
             "post_ride_callback": function(){
                console.log("Fine tour");
             } 
         })
     }

It does not fire the `post_ride_callback` at all.

**Comment by steoo** [comment]
I debugged the `joyride.js` and noticed that, despite of what is written in the docs

> post_ride_callback     : function (){},    // A method to call once the tour closes (canceled or complete)

the `callback` is called **only** when the tour finishes and not when is canceled. 

The key of everything is the `abort` on line `898`. 

For what I got, the callback has to be called also when it is *aborted*, correct me if I am wrong.

**Comment by nic-potter** [comment]
have you tried setting the abort_on_close setting to false? looks like that should allow the callbacks to fire
```
abort_on_close           : true,      // When true, the close event will not fire any callback
```

**Comment by steoo** [comment]
I'll try but, anyway, this is confusing.
