### ISSUE TITLE
Clearing: Option to Use DataURI Instead of an HREF

### ISSUE THREAD

**Issue by rdetert** [zurb/foundation#6244]
When loading dynamic images, Clearing feels really slow since it has to download the images when using `<a href="path/to/image">`. It would be better if there was an option to use a DataURI instead.

HTML structure could look something like this, where `.full-size` takes precedence and the `href` param is fallback:

```
<li>
  <a href="path/to/your/img">
    <img src="data:image……" class="full-size hide">
    <img src="path/to/your/img-th" class="thumb">
  </a>
</li>
```

FancyBox has this capability:
http://stackoverflow.com/a/19070207/148390

**Comment by gakimball** [comment]
We'll look into it for Foundation 6. I'll add it to our [Foundation 6 wishlist](https://github.com/zurb/foundation/issues/4710) and the [Trello board](https://trello.com/b/QBPKlQqf/foundation-sites) we have for feature suggestions. :)
