### ISSUE TITLE
Problems with stacked button-group and dropdown content.

### ISSUE THREAD

**Issue by rhernandog** [zurb/foundation#6245]
Hi,

I'm experiencing some position issues with a very specific set up.

I have a button-group that stacks in small screens. One of the buttons has a dropdown list, which works fine for large-medium screens but there's an issue on small screens (anything over 320px width). On the first click/touch the element is out of position (it has a left position bigger than necessary) and on the second click/touch the left position is corrected.

I created a simple sample so you can see it:

http://codepen.io/rhernando/pen/e3a438d17172f9af19b6ff90d0489125

Here's the full screen link (here you can just resize and reload to test the issue)

http://codepen.io/rhernando/debug/e3a438d17172f9af19b6ff90d0489125

Thanks in advance,
Rodrigo.

**Comment by rafibomb** [comment]
Looks like in stacked and non-stacked examples the dropdowns are both left aligned. Where do you expect the stacked example to go?

**Comment by rhernandog** [comment]
Hi,

Thanks for the prompt answer.

As I mentioned in the first post, the issue happens on <strong>small screens</strong>, after the breakpoint that changes the width of the dropdown element and that stacks the button group. Please try the example in a screen size below the small breakpoint (under 640px).

I'm attaching a couple of images with the issue.

![foundation-issue---first-click-touch](https://cloud.githubusercontent.com/assets/4622323/6014239/28e7e41c-ab3f-11e4-82b7-21e5f1be2d34.png)

![foundation-issue---second-click-touch](https://cloud.githubusercontent.com/assets/4622323/6014238/28c70c2e-ab3f-11e4-9b3f-05d20d18ad82.png)

Finally is worth noticing that the bigger the screen size (obviusly before the breakpoint) the bigger the value in the left property. At 640px the left value after the first click is 161.5px. Please try this using the device mode in dev tools, for the full window sample to see it better.

Thanks again,
Rodrigo.

**Comment by tdhartwick** [comment]
Thanks, I see this now. 
@coreysyms Any ideas on this issue?

**Comment by coreysyms** [comment]
Might be at initialization or might be a "break point grey area" in the CSS. I noticed the full screen link working perfectly on my iPhone in portrait. But landscape showed the issue described. I can poke around and see what's going on.

**Comment by rafibomb** [comment]
Thanks for taking a look @coreysyms !

**Comment by coreysyms** [comment]
@rhernandog So the issue was the way things were being fired. The positioning was being set off a 200px width drop down box. Then CSS was being applied to make the drop down box 95% width. So on the first fire, the box is positioned based off initial CSS, then the correct CSS was applied making the box off to the right about 30px. The correct CSS is now inline on the drop down and the next fire of the event positions correctly which is why you see things fire in this order.

I changed this chunk of code in foundation.min.js

```
css : function (dropdown, target) {
			
			if (this.small()) {
				
                dropdown.attr('style', '').removeClass('drop-left drop-right drop-top').css({
                    position : 'absolute',
                    width: '95%',
                    'max-width': 'none'
                });
			}
			
			
            var left_offset = Math.max((target.width() - dropdown.width()) / 2, 8),
            settings = target.data(this.attr_name(true) + '-init') || this.settings;

            this.clear_idx();


            if (this.small()) {
               
				 var p = this.dirs.bottom.call(dropdown, target, settings);
				 
				 dropdown.css({
                    top: p.top
                });

                dropdown.css(Foundation.rtl ? 'right' : 'left', left_offset);
            } else {

                this.style(dropdown, target, settings);
            }
			
            return dropdown;
        },
```

As you can see this code now applies the correct CSS before the math is done so the first and subsequent clicks render the drop down in the correct place. THIS CODE IS FOR YOU ONLY as it needs to be tested more in other situations and I would advice the obvious of using at your own risk etc etc.

**Comment by rafibomb** [comment]
Sweet! Thanks @coreysyms for looking into it! I think this really help us formulate a better way to get this positioning down. You're awesome!

**Comment by jeaniec** [comment]
As this is kind of an edge case and a unique situation that has been resolved with some CSS offset, I'm going to close this in favor for a larger release where we'll tackle dropdowns and better positioning in general. Thanks so much for the contribution @coreysyms! It's definitely helpful to find all the different edge cases for using drop downs.
