### ISSUE TITLE
$input-error-message-bg-color cannot be 'none'

### ISSUE THREAD

**Issue by MichielDeMey** [zurb/foundation#6247]
It seems that I cannot disable the background color for the error message as the `lightness` function tell me that `none` as not a valid color.

**Comment by gakimball** [comment]
That's because `none` isn't a CSS color; the proper "null color" in CSS is `transparent`. However, the Sass color manipulation functions can't lighten or darken `transparent`, so you have to cheat by using a transparent RBGA value.

```scss
$input-error-message-bg-color: rgba(0,0,0,0);
```

That will prevent any color from appearing.
