### ISSUE TITLE
Top Bar mobile_show_parent_link only appears at Small breakpoint

### ISSUE THREAD

**Issue by ricardo-lewis** [zurb/foundation#6248]
The JS generated markup:
```
<li class="parent-link show-for-small-only">
<a class="parent-link js-generated" href="/products-services">Products &amp; Services</a>
</li>
```
It would be nice if the Parent Link would show at the ```$topbar-breakpoint``` instead of at Small only.

**Comment by rafibomb** [comment]
Can you submit a PR because this would help others?

**Comment by rafibomb** [comment]
The parent links visibility needs to match the top-bar breakpoint, not the grid breakpoint.

**Comment by jeaniec** [comment]
@gakimball Do we have a class that can signify a 'topbar breakpoint show/hide' behavior?

**Comment by ricardo-lewis** [comment]
@jeaniec that's a good idea – I can already think of places outside the Top Bar where I would use this. Quite a few elements change appearance at the TB breakpoint...

**Comment by vita10gy** [comment]
I've recently added this as a breakpoint, and came here to add this issue of the parent link as a request .

I'd be willing to make a pull request if those in the know think there's a good chance they'd accept it. 

What would be a good name for this breakpoint? Is there "official" foundation lingo for the full desktop menu vs the mobile menu?

**Comment by jeanieshark** [comment]
@vita10gy If you want to submit a pull request and all looks good, we'd be happy to pull it in. There's no official lingo, but exporting a class something along the lines of "hide-for-topbar-mobile" or "hide-for-topbar-desktop" should be fine. After you submit the pull request, the team will look over it and see if there are any changes that we might want to commit on our end as well.

**Comment by vita10gy** [comment]
I also added this breakpoint in to the grid so I could do something the equiv of topbar-desktop-5 That way I could make the header above the menu play ball with the menu breakpoint and visibility classes we're talking about. 

Would that interest people, or it that getting too specific? 

Also, one "catch" to this change we're discussing is that, as far as I can tell at least, though truth be told I didn't spend a ton of time on trying alternatives: the breakpoint needs to be defined with the others in _globals and not _topbar. 

Is that too "breaking" to justify for this?

**Comment by rafibomb** [comment]
Thanks for pointing this out. Ideally the visibility would match the top-bar breakpoints. We're not adding any features to Foundation 5 as we're concentrating on getting Foundation 6 out.
