### ISSUE TITLE
Tab deep linking error in go_to_hash method

### ISSUE THREAD

**Issue by akodde** [zurb/foundation#6250]
When I enable "deep_linking" and browse to a tab the hash changes. If I reload the page with F5, this error pops up:

Error: Uncaught TypeError: Cannot read property 'replace' of undefined in foundation.tab.js line 170:
```
default_hash = settings.scroll_to_content ? self.default_tab_hashes[0] : 'fndtn-' + self.default_tab_hashes[0].replace('#', '')
```

It happens because the handle_location_hash_change is is being called before the default_tab_hashes variable is 'filled'. (see init function, line 23-35).

I think we can easily fix this if we change the order:
```
init : function (scope, method, options) {
  var self = this,
      S = this.S;

  // Store the default active tabs which will be referenced when the
  // location hash is absent, as in the case of navigating the tabs and
  // returning to the first viewing via the browser Back button.
  S('[' + this.attr_name() + '] > .active > a', this.scope).each(function () {
    self.default_tab_hashes.push(this.hash);
  });

  // store the initial href, which is used to allow correct behaviour of the
  // browser back button when deep linking is turned on.
  self.entry_location = window.location.href;

  this.bindings(method, options);
  this.handle_location_hash_change();
},
```

Tested in 5.5.1 and it solved the error.

Any thoughts?

**Comment by gakimball** [comment]
Sounds good, would you like to open a pull request so you can take credit for the fix?

**Comment by rafibomb** [comment]
Hi @akodde Thanks for posting your solution here. Would be awesome to see a PR for this as it would help others. Thanks!

**Comment by rafibomb** [comment]
Closing in favor of PR
