### ISSUE TITLE
enhancement: separate out joyride into separate functionalities (popover + tour)

### ISSUE THREAD

**Issue by jasonday** [zurb/foundation#6251]
Enhancement idea:

Separate out functionality of joyride.

Have 'popover' - http://getbootstrap.com/javascript/#popovers
Fires on click, and includes close button.

Then have joyride provide the functionality of the tour.

**Comment by gakimball** [comment]
We're looking at something similar for Magellan—separating the sticky header/sidebar functionality from the "highlight the active section" functionality. We could take the same approach for Joyride as well. I'll add it to the Foundation 6 wishlist (#4710), and our [Trello board](https://trello.com/b/QBPKlQqf/foundation-for-sites), where we're collecting feature requests.

**Comment by jasonday** [comment]
thanks!
