### ISSUE TITLE
How do you increase the rang-slider max limit to say 50 0000

### ISSUE THREAD

**Issue by angelwizz** [zurb/foundation#6253]
I am using the range for a donation section and 100 bucks is a little low so i need to be able to increase it..

**Comment by angelwizz** [comment]
I tried this $('.range-slider').attr("data-options", "start: 1; end:50000;" ); but it doesn't work.. When they slide the max limit must be 50 000

**Comment by gakimball** [comment]
Try adding the `max` setting directly on the range slider, so that the option is there right when it's initialized. Those values are pulled once when the component is initialized and can't be changed after the fact.

```html
<div class="range-slider" data-slider data-options="start: 1; end: 50000;">
  <span class="range-slider-handle" role="slider" tabindex="0"></span>
  <span class="range-slider-active-segment"></span>
  <input type="hidden">
</div>
```
