### ISSUE TITLE
Reveal Modal Issue with multiple_opened

### ISSUE THREAD

**Issue by squalli2008** [zurb/foundation#6262]
Hi,

Looks like the following code was added in commit: 586fcb24779ac82bab22e178428b15b9b3dd256a

 if (open_modal.length > 0) {
                if (settings.multiple_opened) {
                  this.to_back(open_modal);
                } else {
                  this.hide(open_modal, settings.css.close);
                }
              }

I am now getting:

foundation.js:4575 Uncaught TypeError: undefined is not a function

Thanks

**Comment by ggn06awu** [comment]
+1
