### ISSUE TITLE
Problem with image url on Reveal Ajax

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation#6273]
Hi community,

Do you know if Foundation 5 can open image with Reveal Ajax ? In #myModal, i've "hieroglyph" when div is open. See my exemple :

    <a href="/path/to/image.jpg" data-reveal-id="myModal" data-reveal-ajax="true">
        Click Me For A Modal
    </a>

    <div id="myModal" class="reveal-modal" data-reveal></div>

Thank you !

**Comment by gakimball** [comment]
Reveal's AJAX mode assumes the URL you're pointing to is an HTML page, not an image. If you want to drop in an image, you can create an HTML file with an `<img>` element of the image you want to load.
