### ISSUE TITLE
Equalizer is broken when an image is returning a 404

### ISSUE THREAD

**Issue by boertel** [zurb/foundation#6276]
If one of the ```data-equalizer-watch``` container contains an image that's not found, equalizer isn't computing the correct height (or even doesn't set up the ```style="height: ??px"```)

Example: http://codepen.io/boertel/pen/NPwZNW (working only one page load, live editing the code seems to reflow correctly).

- first ```section``` is an example where it's working because all the images are returning 200.
- second ```section``` is not working because the last image is incorrect.

One workaround I found is to load a default image and play with the ```onerror``` event but it's bumpy because reflow seems to wait that the ```onerror``` is executed.

Is it possible that the issue comes from ```image_loaded``` function ? I don't see why it would affect the height, it should just ignore it.

**Comment by jeaniec** [comment]
@boertel Maybe I'm misunderstanding the usage here, but I'm showing that the current example is working correctly?

**Comment by boertel** [comment]
Here is how it looks on my browser (latest Chrome on Mac OS, and same with Firefox

![screen shot 2015-02-11 at 10 25 32 am](https://cloud.githubusercontent.com/assets/301183/6153295/89c4f5dc-b1d8-11e4-85d5-00bffbd71d20.png)
