### ISSUE TITLE
Reveal padding is multiplied by 1.5

### ISSUE THREAD

**Issue by danielsamuels** [zurb/foundation#6281]
Today I noticed that the `$reveal-modal-padding` variable gets multiplied by 1.5.  This doesn't seem to make a lot of sense and actually makes the variable misleading.  I followed the git history all the way back to [this commit](https://github.com/zurb/foundation/commit/6464da1106f3130a9d5383273700462ddf363c14), which was a minor refactor.  Changes to that file have persisted the behaviour ever since.  I think should be amended to use the base variable value as the padding amount.

**Comment by rafibomb** [comment]
Done: https://github.com/zurb/foundation/commit/f4a73be462a5d6a226f9563d71d1ad02dd59e590
