### ISSUE TITLE
A race condition exists in tooltip that can cause tooltips to stick open

### ISSUE THREAD

**Issue by jbafford** [zurb/foundation#6282]
Tooltip makes use of setTimeout() to trigger a delayed opening to the tooltip. However, due to a combination of poor management of the timer, and the possibility of multiple events being triggered on entry, a race condition exists such multiple timers can be started, and only one of them is cancelled, causing the tooltip to appear and stay visible, even though the mouse has left the triggering container.

**Comment by rafibomb** [comment]
Love the PR for the issue! Thanks!
