### ISSUE TITLE
hooking into foundation abide from multipurposuse form submission code.

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6284]
Quite some time ago, i got tired of writing an event handler for every form submission. So i decided to create a simple multipurpose solution. it uses the `action` attribute to submit the form to the endpoint,  and `data-callback` attribute to handle the callback for that particular form, passing the form and data response to the callback using the `window[fn].call(window, args)` method.

**the code:**

```js
$('form:not(.contains-file-input)').submit(function(e){
	e.preventDefault();
	var _this = $(this);
	$.post( _this.attr('action') , _this.serialize() ,function(data){
		data = JSON.parse(data);
		console.log(data);
		window[_this.attr('data-callback')].call(window,data,_this);//pass data and form to callback
	});
	return false;
});
```
What i would like to do is trigger data abide inside of this function. and capture the output of abide. if the form fails validation, i want to pass that data to the callback. else i want to continue submitting the form. is it possible? Where can i find more info about it?

**Comment by jeaniec** [comment]
As of the commit https://github.com/zurb/foundation/commit/adf3fbfd24b16512c1575f4e082246ba24f68946, each element has its own valid/invalid triggers (which you can listen for with something like` $(el).on('valid', function() {...})`). Theoretically, you can check if each of the validations pass, and if they do, then submit that data. Else, you can create an array or an object with the input that is invalid.
