### ISSUE TITLE
F5: Top bar; Left button overflow

### ISSUE THREAD

**Issue by steakknife** [zurb/foundation#6285]
The left button should either get folded into a drop-down or abbreviate with a text direction-appropriate ellipsis when it would overlap other elements.  Instead, it is appearing *below* the Top Bar area (see screen captures).

[html](https://gist.githubusercontent.com/steakknife/1bf2d8f83d6b04f4cd6b/raw/demo.html)

- Chrome 40.0.2214.111 (64-bit)
- MacBook Pro (13-inch, Mid 2012)
    - 13.3-inch (1280 x 800)
- OS X 10.10.2

Sans browser UI below.

## Zoom (Chrome): 150% 

![image](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/66129cd7-ab91-4638-8c4b-7f69da2eb30f/00000012.png)

## Zoom (Chrome): 175%

![image](https://cloud.githubusercontent.com/assets/224304/6147831/2ad12bae-b1b0-11e4-89aa-68bd8b5e82be.png)

**Comment by rafibomb** [comment]
Duplicate

**Comment by steakknife** [comment]
Not a duplicate, separate issues.

**Comment by steakknife** [comment]
@rafibomb Another [live example](https://codepen.io/steakknife/pen/gboKXv)

**Comment by steakknife** [comment]
Bump.

**Comment by rafibomb** [comment]
This is a really specific thing. When you zoom the browser down what really happens is top-bar collapses to mobile view. You could write CSS to make the text overflow and hide.

**Comment by steakknife** [comment]
The horse has already left the barn as we've already switched to bootstrap, which happens to have a larger community.

We might try foundation another time.

Thanks anyhow.
