### ISSUE TITLE
F5: Top bar; Left button disappears

### ISSUE THREAD

**Issue by steakknife** [zurb/foundation#6286]
In the **Build With HTML Classes** example, the left button disappears frequently, and it's not relocated to a drop-down, when there appears to be plenty of width remaining.

[html (Top Bar docs/demo)](http://foundation.zurb.com/docs/components/topbar.html)

- Chrome 40.0.2214.111 (64-bit)
- MacBook Pro (13-inch, Mid 2012)
    - 13.3-inch (1280 x 800)
- OS X 10.10.2

## Zoom (Chrome): 110%

![image](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/d2298b70-68f5-4e95-9714-ff89cf8a4b51/00000013.png)

## Zoom (Chrome): 125%

![image](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/7349e071-5707-4924-b3de-b446c7cd29f3/00000014.png)

**Comment by rafibomb** [comment]
This docs example has a visibility class on it because of the limited real estate. It does not happen on a project. See example http://codepen.io/rafibomb/pen/wBpXzj

**Comment by steakknife** [comment]
Ah, thanks.
