### ISSUE TITLE
Range Slider has unused options for border-radius / round

### ISSUE THREAD

**Issue by naeon** [zurb/foundation#6288]
The `settings.scss` as well as the `component/range-slider.scss` contain variables concerning the handle of the range slider, that can be set but are not implemented in the component itself.

The following variables are not used:
`$range-slider-handle-radius`
`$range-slider-handle-round`

The culprit seems to be line 169 in 
https://github.com/zurb/foundation/blob/73cedb9213018c548449440ac6b88b88675c0608/scss/foundation/components/_range-slider.scss#L169
`@include range-slider-handle-style($bg:true, $radius: false);`
where both variables should be used, but are not.

Hence, no border-radius or roundness can be achieved via settings.scss

**Comment by gakimball** [comment]
This is a weird quirk with how some of our component settings work—even if you change the `$range-slider-radius` and `$range-slider-round` variables, they don't take effect unless the slider mixin is called with the parameter `$radius: true` or `$radius: round`, *or* if you use the CSS classes `radius` or `round`. (You can see [here](https://github.com/zurb/foundation/blob/73cedb9213018c548449440ac6b88b88675c0608/scss/foundation/components/_range-slider.scss#L112) where it's applied.) Buttons work the same way.

It's pretty confusing and doesn't really make sense, as the border radius of a slider is a purely stylistic setting, and there should be just one variable that controls the radius of sliders. We made this change for Foundation for Apps, and we should do the same for version 6 of this framework.
