### ISSUE TITLE
Split Button in top bar

### ISSUE THREAD

**Issue by amichel86** [zurb/foundation#6289]
Hi, wonderful framework guys! Quick question, I would like to transform the magnifier button (top bar) into a split button to have more options available before submitting the form. When adding the code provided on your website (http://foundation.zurb.com/docs/components/split_buttons.html) it looks like it's breaking the bar and styles are not applied accordingly. Is it something that hasn't been thought of? If so I will develop it myself, but wanted to ask first. :)

![split](https://cloud.githubusercontent.com/assets/5871701/6174838/940ebd1a-b2bf-11e4-8c32-7dd2f25318f2.jpg)

**Comment by rafibomb** [comment]
Tob-bar support buttons but not split buttons. Here is an example: http://codepen.io/rafibomb/pen/yyvOYR
