### ISSUE TITLE
Topbar input and button slightly off

### ISSUE THREAD

**Issue by shadysamir** [zurb/foundation#6298]
Using 5.5.0 and looking at your demo at http://foundation.zurb.com/docs/components/topbar.html (possibly using 5.5.1)

![image](https://cloud.githubusercontent.com/assets/532005/6201297/46f53608-b4a9-11e4-8637-1854fe489a2f.png)

You can see how in your demo the button is one pixel lower than the input. Using both Chrome and FF. On my site the button is a lesser height than the input field. Causing a similar inconsistency. Input rendered height is 28px, the button is 27.1875px

![image](https://cloud.githubusercontent.com/assets/532005/6201303/d01b2488-b4a9-11e4-9f39-135731b6b096.png)

**Comment by gakimball** [comment]
This issue pops up every now and again, and the discrepancies come from the ways different browsers decide to round pixels. We'll take another look, though.

**Comment by rafibomb** [comment]
Can't consistently replicate this, though we know it crops up on occasion. No good solutions out there yet but we're looking at options as we build out the next version. Thanks!
