### ISSUE TITLE
Tooltip open link on small and medium

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation#6299]
Hi community,

I use tooltip module on my link, and if i "push" on smartphone or tablet, he's open the tooltip, but i would like open the link :(

I've see this on the doc :

    Tooltips applied to tags will automatically be disabled for touch events, so not to interfere with the link.

And my code :

     <a data-options="disable_for_touch:true" itemprop="sameAs" href="{{ site.github_url }}" target="_blank" class="has-tip tip-left icon-github" title="Github" data-tooltip aria-haspopup="true">Github</a>

Do you have any idea for resolve my problem ?

Thank you !

**Comment by LeG3nDz** [comment]
Any idea ?

**Comment by amecv** [comment]
What devices are you testing with? (If you could be as specific as posbible about Device, OS version & Browser that could help narrow it down)

**Comment by LeG3nDz** [comment]
Hi,

I've test on Windows Phone 8.1, IE browser.

**Comment by rafibomb** [comment]
Desired effect - disable_for_touch:true should "turn off" the tooltip and allow link to be clicked. Correct?

**Comment by LeG3nDz** [comment]
Hi @rafibomb 

Yep, I understand this. But it's open tooltip :(

**Comment by jeaniec** [comment]
@LeG3nDz  Try adding `data-options="disable_for_touch:true; show_on: large"` to override the behavior for it showing on mobile. Is that the solution you're looking for?

**Comment by LeG3nDz** [comment]
Hi,

Why closed this issue ? It's not fixed :( Your solution don't work

**Comment by yprez** [comment]
@rafibomb @attnjamie This still doesn't work for me (`data-options="disable_for_touch:true; show_on: large"` or combinations of them).

foundation 5.5.3 / tested on Chrome 51 on Android

@LeG3nDz did you manage to solve this eventually?

**Comment by yprez** [comment]
`show_on: large` by itself does work (hides the tooltip), but the button is still not clickable.

`disable_for_touch:true` seems to have no effect at all, by itself or combined with `show_on:large`...

**Comment by LeG3nDz** [comment]
Hi @yprez 

Since, i use tooltip full CSS (without module Foundation).

**Comment by yprez** [comment]
@andycochran @rafibomb @attnjamie any chance of reopening this ticket? (assuming the bug is real)
