### ISSUE TITLE
Prepopulated form item

### ISSUE THREAD

**Issue by b-d-b** [zurb/foundation#6300]
I am getting an error when I try to require a field to be filled that is automatically populated.  When I tab through my form, passing the pre-populated field, the error message shows up on the field.

I attempted to reflow the abide validation after I changed the form input but the problem persisted

**Comment by gakimball** [comment]
Could you post a code example so we can take a closer look?

**Comment by b-d-b** [comment]
I actually managed to fix this -- it was a dumb mistake on my end of things.  I'll close this.

Thanks for getting back to me! :)
