### ISSUE TITLE
Extra http requests from html interchange

### ISSUE THREAD

**Issue by BillBarron** [zurb/foundation#6301]
wrote a blog post and was asked to log it via twitter here at github, so I guess its an issue, here it is, my appologies if that isn't what you wanted.  Guess it would be nice if data-interchange handled this on its own with (default-small) by not loading the URL on initial load and just using the default in the div and only using the ajax request if the size has changed from the default and back again.

BLOG POST:
If you are using Foundation with Interchange you have seen extra requests that the client has to make to download the content. This is fine for images since that is a separate request anyway, but for HTML content I didn't want that extra request for mobile devices. 

My solution, so far, was to exclude my default template size, (small), from the data-interchange variable, and include that small template directly into the div as the default content. This works fine with loading on a small template since no other requests are done. But if the browser is resized to medium and back to small it would stay with the medium html loaded by interchange. 

To get around this I setup a new data attribute, and a little javascript. 

in the div where data-interchange exists, I added a data-interchangeonreplace attribute. 

Here is my example Div
<div id="testcontent" data-interchange="[medium.html, (medium)], [large.html, (large)]" data-interchangeonreplace="[small.html,(small)],[medium.html, (medium)], [large.html, (large)]">
  <div data-alert class="alert-box secondary radius">
    This is the default content.
    <a href="#" class="close">×
  </div>
</div>

Here is the javascript:

$(document).on('replace', 'div', function (e, new_path, original_path) {
	var divid = $('#' + e.currentTarget.id);
	if (divid.attr('data-interchangeonreplace')) {
		divid.attr('data-interchange',divid.attr('data-interchangeonreplace'));
		divid.removeAttr('data-interchangeonreplace');
  		divid.foundation('interchange', 'reflow');
	}
});

now when resizing past small it will add small.html back to the list so it if is then resized smaller it will display properly. 

The same can be done in reverse, use whatever methods to determine your default template to display and only include it back in if the size changes, eliminating an extra client HTTP request for each block of code you load dynamically on your page

**Comment by rafibomb** [comment]
Bill, thanks for the report - We're working on the next version now so it helps to know how we can improve the functionality. The next step is to see if this will be rolled into the current version or if the update requires more re-writing of the JS, it will be in the next.

**Comment by jeanieshark** [comment]
We'll be optimizing Interchange to handle these situations with Foundation 6. Because this particular use case seems fixed with this workaround, please continue to use @BillBarron's fix as a reference until the next version is released.
