### ISSUE TITLE
Accordion .title styling when active

### ISSUE THREAD

**Issue by cortopy** [zurb/foundation#6302]
At the moment it isn't possible to style active anchors within a Foundation accordion. This is because the `.active` class is toggled for parent `.accordion-navigation` and `div.active`

My problem was that I wanted to style `a.title` by adding different CSS depending on whether `a.title` was active or not. 

To solve this I've created a simple function:

```
$('.accordion-navigation > a.title').click(function() {
   $(this).toggleClass('title-active'); 
   $(this).siblings().removeClass('title-active');
});
```
This requires a new `.title-active' class. I haven't submitted this as a pull request because of the new class.However, I thought it was worth sharing in case someone needs to style the anchors of accordion based on whether content is active or not.

**Comment by rafibomb** [comment]
Hey @cortopy Thanks for sharing your solution. A PR would be accepted, otherwise it's good to have this reference for anyone doing the same.
