### ISSUE TITLE
Reflow preformance issues

### ISSUE THREAD

**Issue by alextyrey** [zurb/foundation#6306]
I'm having preformance issues with the following:
```
$(document).foundation('dropdown', 'reflow');
$(document).foundation('tooltip', 'reflow');
```
These are called in a callback when my infinitescroll script renders new content. On each page, 20 items are returned and each of those items have 1 dropdown and 1 tooltip.

When the infinitescroll script appends the new page, my browser freezes for ~2 seconds. It is very annoying. Doing something like `$('#stream').foundation('tooltip', 'reflow');` noticeably helps, but not passing the whole document results in "glitchy" behavior with the dropdowns and tooltips.

The tooltips seem to dis/appear at random and the dropdowns close even when hovering over them.

I debated whether or not I should post this because I can't offer a demo. And as dev, I definitely understand the frustration that comes after hearing that.

Any tips/suggestions are welcome.

**Comment by rafibomb** [comment]
Looking at the plugins, dropdown and tooltip don't have a reflow function built in. We'll be uniformly implementing it in the next version.

There is a JS utility for throttling available

// Throttled resize function
$(window).on('resize', Foundation.utils.throttle(function(e){
  // Do responsive stuff
}, 300));

We'll close this here, 
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here.
