### ISSUE TITLE
Deep linking w/o scroll to content breaks back button

### ISSUE THREAD

**Issue by eli-collins** [zurb/foundation#6310]
Under Foundation 5.5.1:

If the user follows a link with anchor `#foo`, and that points to a tab which has `deep_linking:true, scroll_to_content: false`, the browser gets redirected to `#fndtn-foo` (I think as part of rev 0e3b7a3244a46baffb75e9ac93eb26978c19911e's scroll_to_content fix).  

However, if the user tries to click the back button, they get sent to the `#foo` url, and are immediately redirected back to `#fndtn-foo`; rather than the previous page where the link was.  There's probably some way to fix this using `history.pushState`, but I'm not familiar enough with it or tabs.js to be sure how to accomplish it.

(This seems similar to issue #6118, but I don't think it's the same).

**Comment by rafibomb** [comment]
According to this issue and PR it should have been fixed: https://github.com/zurb/foundation/issues/6102

**Comment by jeaniec** [comment]
@eli-collins  Do you have the mark up for the tabs that you're using this for?

**Comment by eli-collins** [comment]
The following snippet recreates the issue.

Under Linux + Firefox 36, Chrome 40: following an anchorless link to a page containing this snippet works fine, *unless* you click on another tab (e.g. "Bar"), at which point you can't back up beyond the initial `#fndtn-foo` tab.

For Firefox only, following a link with an anchor (e.g. `tabs.html#foo`, `tabs.html#bar`) redirects to the `#fndtn-` equivalent, and I can't go backward.  After testing some more, I discovered Chrome seems to behave correctly in this second situation.

```html
<!DOCTYPE HTML>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/normalize.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/foundation.min.css" />
</head>

<body>

    <ul class="tabs" data-tab data-options='{"deep_linking":true, "scroll_to_content":false}'>
        <li class="tab-title active"><a href="#foo">Foo</a></li>
        <li class="tab-title "><a href="#bar">Bar</a></li>
        <li class="tab-title "><a href="#baz">Baz</a></li>
    </ul>

    <div class="tabs-content">
        <div class="content active" id="foo">foo content</div>
        <div class="content" id="bar">bar content</div>
        <div class="content" id="baz">baz content</div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/vendor/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/vendor/fastclick.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/vendor/jquery.cookie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/foundation.min.js"></script>
    <script type="text/javascript">
        $(document).foundation();
    </script>

</body>
</html>
```

**Comment by jeanieshark** [comment]
Ah, okay. Thanks, I see the issue you're talking about. I'll take a closer look at this.

**Comment by sammarks** [comment]
Updating to the latest version of Foundation (5.5.2) appears to have resolved the issue for me. I'm using tabs with deep linking turned on and scroll to content off.

**Comment by TW80000** [comment]
We are using 5.5.2 for our site and are experiencing the same issue when using Firefox. This is with deep linking on and scroll to content off. Using the back button works for us in Chrome and IE 11, but in Firefox we can't get back past the initial tab using the browser's back button.

**Comment by TW80000** [comment]
Building Foundation from source and using the new `foundation.min.js` file has resolved the problem for Chrome, Firefox, and Internet Explorer.

**Comment by sammarks** [comment]
@TW80000 - Perhaps that's because the PR I submitted (#6607) hasn't been rolled into a release yet? I guess we need to wait until the fix is released before closing this issue?

**Comment by TW80000** [comment]
@sammarks - Yeah, that must be it. We downloaded Foundation from the website in July, a month after your PR was merged. The release must not have been up to date with master, even though they're technically the same version. As far as I'm concerned, if the release is updated to match master, this issue can be closed. Thank you for the fix by the way!

**Comment by zurbrandon** [comment]
I'll close this since it looks like the problem has been fixed! If i'm mistaken, please reopen it or ping me. Thanks All!

**Comment by depiction** [comment]
I'm having the same problem and am using the latest version of Foundation (5.5.3).
