### ISSUE TITLE
Included Scripts Question

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation#6311]
Hey there Zurbians, I have a question I hope you can answer for me.

As some of you know I created a WordPress theme called WP-Forge which is built with Foundation. I submitted it to the WordPress theme review team over two months ago and it was just recently assigned a reviewer.

The reviewer asked me a question today and I could not find an answer. His question was 

> What do you need jquery.cookie.js for?

I basically just told him that it came bundled with Foundation. Now I am sure that all of the scripts that are included in Foundation are needed so I was wondering if you could tell me exactly what the scripts in the vendor folder are needed for, with the exception of jQuery of course.

I am sooooooooooooooooo close to getting my theme approved so keep anything and everything you can crossed (just don't give yourself a cramp)...lol :stuck_out_tongue_winking_eye:

**Comment by rafibomb** [comment]
It's used by joyride to remember if someone has seen the tour. For the next version we can use HTML5 local storage instead.

**Comment by tsquez** [comment]
Thank you sir it's greatly appreciated

via my phone
