### ISSUE TITLE
Foundation Top-bar with smooth scroll

### ISSUE THREAD

**Issue by joeylane1682** [zurb/foundation#6312]
This is my first post to github. Yay me. Anyway... I am having some real trouble finding a way to get F5's top-bar to play nicely with smooth scrolling and would be forever in debt to anyone that can help me see the light.  The top-bar nav is "fixed" and functions fine on desktop, but doesn't work properly on mobile.

On the index page (link below) I have a anchor link located mid way down the page for the work section. It is an empty div located just above the "Recent Projects" title. There are two links on the page pointing to the anchor. One is a main nav menu item and the other is the little cloud icon in the hero area. 

When you click the cloud "FIRST" you get the proper scrolling position, but when you access the anchor link from the nav menu, it does not scroll to the proper location. In addition, if you click on the fist work thumb "bean Creative", ( the only active page besides the index) and use the top bar to go back by clicking the "work" menu item it lands at yet another different position. I'm completely stumped. 

My guess is that this has something to do with 
1) the offset I have specified in the JS which is necessary for the page to not get sucked up below the "fixed" nav bar. 
2) the smooth scroll function or
3) the fact that the nav bar removes the fixed class once a nav item is clicked cause some kind of offset.

Below is a link to the page with the problem. Please let me know if you need me to post any further information. I have googled the hell out of this and haven't come up with anything. Any help would be greatly appreciated. Thanks!

http://jlaneportfolio.com/_dev/index.html

**Comment by joeylane1682** [comment]
I was actually able to resolve this issue on my own. Looks like the "Fixed" class is what was not playing nicely with the smooth scrolling, Once I removed that class and added the following CSS-Tricks smooth scroll script to my page it works great.

	jQuery(function() {
        jQuery('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                var target = jQuery(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                if (target.length) {
                    jQuery('html,body').animate({
                        scrollTop: target.offset ().top 
                    }, 1000);
                    return false;
                }
            }
        });
    });

**Comment by catchlightWeb** [comment]
Thanks so much for this!

**Comment by IamManchanda** [comment]
Dupe of #9587 
& Added in #9636 
Expected to be released around v6.4
