### ISSUE TITLE
Reverse animation order on Reveal close?

### ISSUE THREAD

**Issue by nitrammit** [zurb/foundation#6314]
A minor issue, but one that bugs me for some reason.

When you open a modal, it looks like the animations fire in the following order:

- Background (.reveal-modal-bg) fades in
- Modal box slides in from the top of the screen

This is perfect. No issues.

But, when you close a modal, the animations are in the same order. The background fades out and the modal slides up afterwards.

Is it possible to reverse the animation order on close so that the modal box slides up BEFORE the background fades out? I think it would make for a better experience.

It's the little things.

:)

**Comment by rafibomb** [comment]
Let's continue the conversation here: http://foundation.zurb.com/forum/posts/22971-reverse-animation-order-on-reveal-close

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by nitrammit** [comment]
@rafibomb Sounds good. And sorry, I'll keep that in mind for the future.
