### ISSUE TITLE
Off canvas' sub menus do not have 100% height.

### ISSUE THREAD

**Issue by F21** [zurb/foundation#6318]
To reproduce: http://jsfiddle.net/c2n46v9t/

1. Open the left off canvas menu. Notice there are many items, so there is a scroll bar.
2. Click the first menu item to open the sub menu.
3. Scroll the off canvas menu downwards and notice that the sub menu does not stretch to cover the parent menu.

**Comment by rafibomb** [comment]
We added this to our "known issues" section in our planning board for the next version. A PR would be valuable to the community, otherwise It will be addressed then. You can see and vote on the proposed updates here: https://trello.com/b/QBPKlQqf/foundation-sites
