### ISSUE TITLE
[BUG] Top-bar: Can't change breakpoint via sass

### ISSUE THREAD

**Issue by ste101** [zurb/foundation#6321]
I changed this in _settings.scss
```$topbar-breakpoint: 800px; // Change to 9999px for always mobile layout```
```$topbar-media-query: "only screen and (min-width: #{$topbar-breakpoint})" !default;```

But in frontend the mobile nav still disappears at medium breakpoint (641px)

**Comment by ste101** [comment]
Sorry my fault

**Comment by nffdiogosilva** [comment]
How did you solve this?
