### ISSUE TITLE
Bug in dropdown

### ISSUE THREAD

**Issue by mitja-p** [zurb/foundation#6323]
In foundation.dropdown.js there is a bug if you are using grid (class row) only inside tabs or the first row gets hidden generally. In case of tabs when first tab is hidden and with that document.getElementsByClassName('row')[0] is hidden dropdowns do not align properly anymore. I would suggest that if first row is invisible window.outerWidth would be used.

Current code:
        var actualBodyWidth;
        if (document.getElementsByClassName('row')[0]) { // Needs fix: should check if also visible or >0
          actualBodyWidth = document.getElementsByClassName('row')[0].clientWidth;
        } else {
          actualBodyWidth = window.outerWidth;
        }

**Comment by jeanieshark** [comment]
Hi @mitja-p -

I'm having trouble recreating your usecase. I've placed the dropdown in a row by themselves as well as in a tab that is not active by default but I'm showing the tabs are behaving as expected. Do you have a codepen or markup that duplicates this behavior?

**Comment by jeanieshark** [comment]
I see that with this markup: 
```
<ul class="tabs" data-tab>
  <li class="tab-title active"><a href="#panel1">Tab 1</a></li>
  <li class="tab-title"><a href="#panel2">Tab 2</a></li>
  <li class="tab-title"><a href="#panel3">Tab 3</a></li>
  <li class="tab-title"><a href="#panel4">Tab 4</a></li>
</ul>
<div class="tabs-content active">
  <div class="content" id="panel1">
    <p>This is the first panel of the basic tab example. You can place all sorts of content here including a grid.</p>
  </div>
  <div class="content" id="panel2">
    <div class="row">
      <div class="large-12 columns">
      <a data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">Has Dropdown</a>
      <ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
        <li><a href="#">This is a link</a></li>
        <li><a href="#">This is another</a></li>
        <li><a href="#">Yet another</a></li>
      </ul>
      <a data-dropdown="drop2" aria-controls="drop2" aria-expanded="false">Has Content Dropdown</a>
      <div id="drop2" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <p>Some text that people will think is awesome! Some text that people will think is awesome! Some text that people will think is awesome!</p>
      </div>
      </div>
    </div>
  </div>
  <div class="content" id="panel3">
    <p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel4">
    <p>This is the fourth panel of the basic tab example. This is the fourth panel of the basic tab example.</p>
  </div>
</div>
```
the drop downs are correctly aligned. So you can either place them in a large-12 columns div or just straight away in the tabs content div so that they are aligning correctly with the container.

**Comment by mitja-p** [comment]
The code below demonstrates the bug. The dropdown has to be on the right edge of the screen to see the clipping. When on the second tab, dropdown behaves differently than on the first page despite the same code. The problem is that the first element with row class get's hidden and calculation of body width fails.

Adding additional row element that encapsulates everything is a workaround as it is always visible and usually the full width of the page.

```html
<ul class="tabs" data-tab>
  <li class="tab-title active"><a href="#panel1">Tab 1</a></li>
  <li class="tab-title"><a href="#panel2">Tab 2</a></li>
</ul>
<div class="tabs-content active">
  <div class="content" id="panel1">
  <div class="row" style="max-width: 100%; width: 100%;">
    <div class="large-12 columns">
      <a data-dropdown="drop3" aria-controls="drop3" aria-expanded="false"  style="float:right;width:150px;">Has Content Dropdown 1</a>
      <div id="drop3" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <p>Some text that people will think is awesome! Some text that people will think is awesome! Some text that people will think is awesome!</p>
     </div>
    </div>
  </div>
</div>
<div class="content" id="panel2">
  <div class="row" style="max-width: 100%; width: 100%;">
    <div class="large-12 columns">
       <a data-dropdown="drop2" aria-controls="drop2"  style="float:right;width:150px;" aria-expanded="false">Has Content Dropdown 2</a>
        <div id="drop2" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
          <p>Some text that people will think is awesome! Some text that people will think is awesome! Some text that people will think is awesome!</p>
        </div>
      </div>
    </div>
  </div>
</div>

**Comment by grgcnnr** [comment]
Here's a slightly different use case that shows the same bug.

http://codepen.io/grgcnnr/pen/aONVrm

Basically when foundation checks for row width with `document.getElementsByClassName('row')[0]`

It assumes that the first row it finds is the effective width of the page.

If the first row on the page has a weird size (or is hidden for some reason) edge detection is all thrown out of whack.
