### ISSUE TITLE
Off-canvas toggle causes both sides of overlap off-canvas to open

### ISSUE THREAD

**Issue by benedictleejh** [zurb/foundation#6327]
When using the `overlap` move method for off-canvas, an off-canvas toggle would cause both left and right off-canvas to open, regardless of which it was supposed to open.

JSFiddle showing the bug: https://jsfiddle.net/uop2fum6/3/

I'm on Foundation 5.5.1, on Rails 4.2

**Comment by rafibomb** [comment]
You want to use 

```html
$(document).foundation({
  offcanvas : {
    // Sets method in which offcanvas opens.
    // [ move | overlap_single | overlap ]
    open_method: 'overlap_single', 
  }
});
```

http://codepen.io/rafibomb/pen/ogPYvE
