### ISSUE TITLE
Topbar 5.5.1 always sticky in iOS browser

### ISSUE THREAD

**Issue by dirksnat** [zurb/foundation#6329]
After updating to 5.5.1, the topbar is always sticky in both Safari & Chome in iOS, despite having set data-options="sticky_on: large".

Everything works as intended on a desktop browser with 5.5.1, sticky only on large.  But just not in iOS.

Going back to topbar 5.5 also fixes the issue.

Can anyone replicate?

**Comment by rafibomb** [comment]
Ya, replicated on the docs. On small screen sticky still applied.
