### ISSUE TITLE
The 'fonts' folder is not exist!

### ISSUE THREAD

**Issue by abdullahsalem** [zurb/foundation#6332]
Hi there,
I've just noticed that the <b>'fonts' folder is not exist</b> (/docs/assets/fonts/), and it's also not exist on the live version!

Thanks,

**Comment by tdhartwick** [comment]
@abdullahsalem Thanks for point this out. We purposely took it out since we are importing Helvetica. We leave it an option for the developer to create a "fonts" directory if he/she needs one.
