### ISSUE TITLE
Hard Coded single-transition in forms

### ISSUE THREAD

**Issue by khanh** [zurb/foundation#6352]
When $input-include-glowing-effect is false, we've got a hard-code single-transition. I know i could just override the class, butIt would be nice if we could get some variables to customize it in settings.

@include single-transition(all, 0.15s, linear);

I could probably submit a PR for it, if there is interest.

**Comment by rafibomb** [comment]
@khanh Yes, please on the PR ;)

**Comment by rafibomb** [comment]
Closing for PR, thanks!
