### ISSUE TITLE
variable for panel callout color

### ISSUE THREAD

**Issue by khanh** [zurb/foundation#6354]
Right now it's doing

@include panel(scale-color($primary-color, $lightness: 94%));

It'd be nice to have a variable for this too.

**Comment by rafibomb** [comment]
Maybe, although we don't want too many variables. We would rather have the color easily overwritten with a variable. A PR would really help. Thanks!

**Comment by khanh** [comment]
hey, looks like no PR is needed.  i must've been an a slightly dated label as #6231 took care of this weeks ago.
