### ISSUE TITLE
MapQuest API image tiles not showing

### ISSUE THREAD

**Issue by brettdewoody** [zurb/foundation#6355]
When using the MapQuest API to display maps in a Zurb Foundation website the images tiles are not displayed.

The solution is to remove the `max-width` from the tile images by targeting images within the map, something like:

    .mqa-display {
      max-width:none !important;
    }

There is already an exception for `#map-canvas` and `.map-canvas` in `_global.scss`.

I propose adding `mqa-display` to add support for MapQuest.

**Comment by rafibomb** [comment]
Hey Brett, sounds good! Can you submit a PR on this one? 
We're planning to a final release for Foundation 5 soon before we're too far into 6.

**Comment by brettdewoody** [comment]
[PR #6375](https://github.com/zurb/foundation/pull/6375) has the fix for MapQuest maps.

**Comment by gakimball** [comment]
#6375 was merged with this commit: 270ac408407ad8be2f856b546a974ac3d2728868
