### ISSUE TITLE
Abide form only within radio buttons

### ISSUE THREAD

**Issue by illycz** [zurb/foundation#6357]
I tried validating a form only with radio buttons. Validation added correctly buttons classes .error, but the form is sent.

**Comment by abdullahsalem** [comment]
Hi Patrik,
Could you please check out this <a href="http://codepen.io/abdullahsalem/pen/OPweqO" target="_blank">basic sample</a>. In that sample, you will notice that the form will not be sent until you choose one of the radio buttons.
However, I would appreciate it if you could share your exact code!
Thanks,

**Comment by illycz** [comment]
When I was tried your example there was only html5 validation: http://cl.ly/image/2K21471e1r0a
Anyway, I am I found out where the error was in my example :)

**Comment by abdullahsalem** [comment]
Good luck.
