### ISSUE TITLE
Icon Fonts

### ISSUE THREAD

**Issue by zitrusblau** [zurb/foundation#6361]
It would be great if you can update the social icons. There are icons of social communities which not longer exist e. g. 'orkut' and we're missing one important social community which have a local website in Germany, called 'Xing' -> https://www.xing.com/

**Comment by rafibomb** [comment]
While we're not actively updating the Icons, we can sometimes make edits. We made a recent push last week on the repo.  

If you put your recommendations in the repo we'll take a look as soon as we can https://github.com/zurb/foundation-icons
