### ISSUE TITLE
foundation.zurb.com website down?

### ISSUE THREAD

**Issue by themestechnology** [zurb/foundation#6363]
I am getting a cloudflair site down message

**Comment by abdullahsalem** [comment]
It seems up and running for me!

**Comment by themestechnology** [comment]
Yes backup now... odd

**Comment by themestechnology** [comment]
Ah I see its this path thats down http://foundation.zurb.com/forum/

**Comment by abdullahsalem** [comment]
You are right!

**Comment by gakimball** [comment]
A few of our properties (Notable and Verify as well) were down for a while, but they're all back up now.
