### ISSUE TITLE
panel-border-color is used nowhere?

### ISSUE THREAD

**Issue by AngeloG** [zurb/foundation#6364]
From my copy of the `bower-foundation` repository, the `$panel-border-color` variable is set, but used nowhere. It is also shown in the [example _settings.scss file](https://github.com/zurb/bower-foundation/blob/master/scss/foundation/_settings.scss#L978), but it turns out to nowhere be used, according to a quick search:

    ~/test/bower_components/foundation/scss/foundation/_settings.scss:
      975  // We use this % to control how much we darken things on hover
      976  // $panel-function-factor: -11%;
      977: // $panel-border-color: scale-color($panel-bg, $lightness: $panel-function-factor);
      978  
      979  // We use these to set default inner padding and bottom margin

    ~/test/bower_components/foundation/scss/foundation/components/_panels.scss:
       17  // We use this % to control how much we darken things on hover
       18  $panel-function-factor: -11% !default;
       19: $panel-border-color: scale-color($panel-bg, $lightness: $panel-function-factor) !default;
       20  
       21  // We use these to set default inner padding and bottom margin

Is this variable for use of files outside of the foundation base? If so, that should probably be clarified in the `_settings.scss`, no?

**Comment by abdullahsalem** [comment]
I agree with you, I've just checked the whole framework and found it not used anywhere!

**Comment by AngeloG** [comment]
So either the variable should be removed, or it should be used somewhere.

**Comment by rafibomb** [comment]
Probably should be added in. A PR would really help here, thanks!

**Comment by rafibomb** [comment]
Thanks for the PR - merged!

**Comment by abdullahsalem** [comment]
Thanks @AngeloG 
My pleasure @rafibomb
