### ISSUE TITLE
Custom queries not longer working for Interchange?

### ISSUE THREAD

**Issue by Tralapo** [zurb/foundation#6368]
I updated my Foundation copy to the latest version today and my Interchange (with .html parts) broke. It just showed the 'default' one and stopped showing the other ones.

I tried some things and now I found out custom queries don't work anymore? I had this, worked like a charm for a long time:

```html
<div data-interchange="[small.html, (default)], [medium.html, (only screen and (min-width: 1140px))], [large.html, (only screen and (min-width: 1320px))]"></div>
```

Now, above example doesn't work anymore. It will always show the one that states 'default'. If i change that one to an custom query too, nothing will show. It works again and as it's supposed to be, when I do this:

```html
<div data-interchange="[small.html, (default)], [medium.html, (medium)], [large.html, (large)]"></div>
```

In the [Docs](http://foundation.zurb.com/docs/components/interchange.html#custom-named-queries), I can see how you can register custom queries to give them a name, but I liked it the way I did. Is support for this just dropped and did I miss that, or is it indeed a bug?

Note: I downloaded a fresh copy of Foundation to check, same thing.

**Comment by rafibomb** [comment]
Can you try it this way and let us know?

```html
$(document).foundation('interchange', {   
  named_queries : {   
    my_custom_query : 'only screen and (max-width: 200px)'   
  } 
}); 
```

**Comment by Tralapo** [comment]
@rafibomb I'm sorry I didn't try that before starting an issue here. I can confirm that solution does work as expected. 

So it's just nog working when you add the query inside the interchange-div itself. Now it's up to you guys to call that a bug, or a no longer supported option ;)
