### ISSUE TITLE
Topbar variables documentation has git conflict tags

### ISSUE THREAD

**Issue by Akkifokkusu** [zurb/foundation#6369]
Looks like commit 9f7e322395cc750fec8e0c14d7a58c12815eb2dc added some git conflict tags to the documentation that's on the website.

**Comment by rafibomb** [comment]
Looks like it's been fixed. Thanks!

**Comment by Akkifokkusu** [comment]
Ah, I see. It just hasn't propagated to the docs on the site yet.
