### ISSUE TITLE
Accordion fails to expand when clicked when using the mixin

### ISSUE THREAD

**Issue by davegross** [zurb/foundation#6371]
This commit https://github.com/zurb/foundation/pull/5884 broke the accordion mixin because it hard codes the class `.accordion-navigation` into the click selector in the JS. 

If you follow the Foundation documentation for creating an accordion mixin by making your own class names, they fail to expand when clicked on.  
See http://foundation.zurb.com/docs/components/accordion.html#semantic-markup-with-sass-mixins

**Comment by rafibomb** [comment]
Thanks for the detail. We'll take a look. In the meantime, a PR would really help the community.

**Comment by davegross** [comment]
Sounds good. I will go ahead and fix and make a PR as soon as I'm done. Thanks!
