### ISSUE TITLE
Help with WordPress TinyMCE editor

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation#6380]
I know this is Foundation and has nothing to do with WordPress. However, I have developed a WordPress theme mixed with Foundation called WP-Forge https://github.com/tsquez/wp-forge and I am hoping that any Foundation users out there who use WP can help out.

I have gotten feedback many times about this issue. This user explained the issue very well in this issue: https://github.com/tsquez/wp-forge/issues/35

WordPress has a new feature or came out with a new feature called Distraction Free Writing https://en.support.wordpress.com/distraction-free-writing/

with this enabled the post editor jumps up and down. Now in WP-Forge's functions.php there is a line that looks like this:

```	/*
	 * This theme styles the visual editor to resemble the theme style
	 *
	 * @see http://codex.wordpress.org/Function_Reference/add_editor_style
	 */
	add_editor_style( array( 
		'style.css','css/foundation.css','fonts/wpforge-fonts.css' 
	));
```
Now basically what this does is add the foundation.css to the post/page editor so when the end user is creating a post/page they can see what it will look like without having to hit Preview.

Now what I did was remove the foundation.css from the editor and the jumping stopped. I added it back and the jumping came back. I have done this locally as well as remotely and its always the same.

If anyone uses WordPress as well as Foundation, could you take a look at WP-Forge and see what the issue is. I have been looking and can't seem to find whats causing it. Any help is greatly appreciated.

**Comment by Owlbertz** [comment]
Hi,
I'd take a look if you could give me the possibility to access the editor on any already existing site, since I'm currently not able to set up a WP with your theme at the moment.

**Comment by ross77** [comment]
I'm using WP-Forge and have noticed the editor expanding like mad when I'm creating/editing a post or page. I don't sadly have any insight as to what might be causing it. What I do know is it uses as small js file (wp-includes/js/tinymce/tinymce.min.js I think) so I'd have to guess there's some sort of conflict going on somewhere.

**Comment by jurajk** [comment]
Hey, i had the same problem:

```
body#tinymce {
  height: auto;
}
```

**Comment by Veraxus** [comment]
I've run into this problem in my own Foundation-based WordPress framework ( https://github.com/Veraxus/nouveau/ ). The problem is related to Foundation's html & body styles (in fact, there are numerous quirks when Foundation is dropped directly into TinyMCE).

To fix the wonky height issues, you have to override Foundation's generated CSS for html & body.

`html, body {
    height: 100%;
}`

If you are working with the sass version of Foundation, I fixed this by creating an editor.scss file, importing Foundation there, and then adding the override for height: auto. Mine editor.scss looks like this:

`@import "../../bower_components/foundation/scss/foundation";

#content_ifr {
    body, html {
        height: auto !important;
    }
}`

**Comment by tsquez** [comment]
Thanks @jurajk and @Veraxus - I took the TinyMCE styles out of style.css and moved them to editor.css. Then I added
```
body, html {
    height: auto !important;
}
```
and made sure that editor.css is loaded first. Works beautimous, thanks guys I really do appreciate it.

**Comment by ve3** [comment]
I have same problem. Thanks to @jurajk  that is working.
