### ISSUE TITLE
Nested data-equalizer discards parent instance of data-equalizer

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6384]

**Comment by rafibomb** [comment]
Sorry, can we get a bit more background on this issue? A markup example and steps to reproduce would really help out. Thanks!

BTW - Some changes have been added to master branch for equalizer. Maybe it's related? https://github.com/zurb/foundation/commit/5c537d14ea6c6e5918c9d7060cdf8c8d06ecf493

**Comment by r3wt** [comment]
@rafibomb how can i upgrade to get the latest version of equalizer? my css is too far gone to download a new package

**Comment by rafibomb** [comment]
If you're using the Sass version, you can run 'bower update' and the CLI will pull the latest. Please open a new issue with more details if you still see an issue. Thanks!
