### ISSUE TITLE
Tooltips are doubled up when doing reflow on $(document)

### ISSUE THREAD

**Issue by nesl247** [zurb/foundation#6386]
In order to fix my problems with Foundation's requirement to reflow every time an AJAX element is added, I added an event handler to DataTables to reflow Foundation using:

`$(document).foundation('reflow');`

When this is executed, tooltips double up as can be seen here.

![screenshot 2015-03-11 10 01 32](https://cloud.githubusercontent.com/assets/1037526/6597833/a81733e8-c7d5-11e4-93e3-3ec3f2bcbc4e.png)

**Comment by rafibomb** [comment]
Can you help us replicate this so we can see what's happening? This will help https://github.com/jakerella/jquery-mockjax

**Comment by kaptankorkut** [comment]
+1

**Comment by redmoik** [comment]
Can we see your code because it will depend on how you code the HTML of it. 
The reason is why it is doubling up is maybe you have a dynamic element that has a tooltip data attributes it in...

**Comment by nesl247** [comment]
I'm no longer working on the project where I experienced this, and don't have access to the code. I'll go ahead and close this.
