### ISSUE TITLE
Pattern for Foundation JavaScript library

### ISSUE THREAD

**Issue by Tasteful** [zurb/foundation#6388]
I have tried to find out what the pattern the Foundation JavaScript library is built around. Does it exists any place where I can find more information about that?

I saw the "Foundation 6" labeled issue about JavaScript framework but this is for current 5.x version.

**Comment by rafibomb** [comment]
Not sure I understand the question. The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
