### ISSUE TITLE
Animation is not working in foundation APP..............

### ISSUE THREAD

**Issue by dipongkor** [zurb/foundation#6391]
I wrote it like following

<div ng-class="['ui-animation']" ui-view></div>

And in template
name: myProfile.signal
url: /signal
controller : myProfileCtrl
animationIn: fadeIn
animationOut: fadeOut

NOT working...................

**Comment by Owlbertz** [comment]
I believe this should be posted in the [foundation-apps repo](https://github.com/zurb/foundation-apps)?

**Comment by gakimball** [comment]
Indeed, please re-open this issue on the [Foundation for Apps issue tracker](https://github.com/zurb/foundation-apps/issues).

However, I'll say that we have a lot of improvements to view animation coming in v1.1 of the framework, which we're trying to get out tomorrow. Stay tuned!
