### ISSUE TITLE
Merge markers in documentation

### ISSUE THREAD

**Issue by mininao** [zurb/foundation#6394]
Hey,
I've spotted a few merge markers in some documentation examples : 

* https://github.com/zurb/foundation/blob/master/doc/includes/dropdown_buttons/examples_dropdown_button_basic.html
* https://github.com/zurb/foundation/blob/master/doc/includes/dropdown_buttons/examples_dropdown_button_intro.html

I'm probably going to submit a PR soon

**Comment by rafibomb** [comment]
All good now, thanks!
