### ISSUE TITLE
Button groups broken on Chrome

### ISSUE THREAD

**Issue by p4sh4** [zurb/foundation#6397]
Foundation 5.5.1, Chrome 41.0.2272.89

This is how the kitchen sink looks at 100% zoom level:

![screen shot 2015-03-15 at 19 00 37](https://cloud.githubusercontent.com/assets/4428858/6655775/d028afb4-cb46-11e4-9e79-a32967f9968b.png)

Notice the different visible distance between grey Button 3 and Button 4, red and green Button 2 and Button 3. 

Changing zoom levels results in that gap appearing randomly between other buttons. 

In Firefox and Safari it looks good at any zoom level.

**Comment by tikot** [comment]
Actually I can replicate this in any browser, its something with the screen resolution (HiDPI). I have crazy big resolution. Technically the sites should be built without need to change the zoom level.

you can change to `-3px` this should help to account for the extra space
```css
.button-group > li {
     margin: 0 -3px;
}
```

**Comment by p4sh4** [comment]
Thanks for the tip! That solves the problem. 

I also originally thought it is a resolution issue, but so far have tried it on 2880 x 1800, 1366 x 768 and 1920 x 1080 with the same effect present. Now checking on the 1080p desktop I can also see it in all browsers. 2880 x 1800 had it only in Chrome. 

Do you think this is an issue worth fixing and setting the horizontal margin as `-3px` as default, as it affects all browsers and quite a few resolutions?

> Technically the sites should be built without need to change the zoom level.

Sure. It's just I noticed that the space appears at different places at various zoom levels. It's still present at the default zoom level.

**Comment by tikot** [comment]
Correct me if I'm wrong. I see this issue in High DPI screens. 1 pixel space sometime show up as 2 pixels.

**Comment by p4sh4** [comment]
You're absolutely correct. But I also see it in what I would consider lower DPI screens - such as the 11 inch Macbook Air with 135 DPI, and currently on a Dell 2414H with 93 DPI (for reference, the Retina iMac is 218 DPI).

**Comment by rafibomb** [comment]
This is an issue with how Chrome is rounding the widths inconsistently up or down. Not sure if there are good workarounds as of yet.

**Comment by p4sh4** [comment]
It's not just Chrome, I've also tested in Firefox and Safari and achieved the same effect, as did @tikot. 

It's the same on iOS Chrome. It pretty much renders the button group unusable out of the box without fixes.
