### ISSUE TITLE
grunt build does not minify the css

### ISSUE THREAD

**Issue by mef** [zurb/foundation#6401]
Hi,

I've installed foundation the following way:

1. clone the git repository, checkout v5.5.0 tag
2. `npm install`
3. `bundle install`

Then compiled it with `grunt build`

Result: the directory `dist/assets/css` does not contain a minified version of css. Gruntfile does not seem to contain any css minification task.

Is this normal? How are users supposed to get a minified version of the css when they want to customize foundation?

I couldn't find any installation instruction anywhere explaining how to build from the source code.

**Comment by rafibomb** [comment]
Looking at the Libsass template - the minification task is there. https://github.com/zurb/foundation-libsass-template/blob/master/Gruntfile.js
