### ISSUE TITLE
foundation 5, offcanvas menu. settings required to not print chevron styles.

### ISSUE THREAD

**Issue by airtonix** [zurb/foundation#6402]
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_offcanvas.scss#L337-L353

This section needs to be moved to a mixin and it needs to be wrapped in a feature flip settings variable.

It's preventing me from utilising the `:before` and `:after` of a submenu `<a>` for icons.

```html
...
	<li class="has-submenu open">
		<a href="/personal/"><i class="fi-torso"></i> Personal </a>
		<a data-toggle class="hide-for-large-up fi-arrow-down"></a>

		<ul class="submenu accordian-submenu second-level">
...
```
I can override it for the left menu, but then I also need to be able to do the same for the right... except that doing so wipes out any icon i put there.

**Comment by rafibomb** [comment]
It's not on our roadmap to make these changes on the multi level off-canvas right now. A PR would be valuable to the community on this.
