### ISSUE TITLE
Open dropdown programmatically

### ISSUE THREAD

**Issue by josh1324** [zurb/foundation#6405]
I'm building a shopping-cart with the foundation dropdown so i need a way to open the dropdown programmatically.
Is there any way? 

I tried this:
$(document).foundation('dropdown', 'open', ($('#top-bar-cart'), $('.top-bar-cart-link'));
And this:
Foundation.libs.dropdown.open($('#top-bar-cart'), $('.top-bar-cart-link'));

But i think the second parameter should be something else, 
Could someone help me?

Thanks!

**Comment by josh1324** [comment]
After some looking i found that my problem was somewhere else.
This works fine:
Foundation.libs.dropdown.open($('#top-bar-cart'), $('.top-bar-cart-link'));

check here for more info: https://stackoverflow.com/questions/29153050/open-foundation-zurb-dropdown-programmatically

**Comment by rdetert** [comment]
Strange that there isn't a better way.
