### ISSUE TITLE
Latest release CSS files are blank

### ISSUE THREAD

**Issue by laantorchaweb** [zurb/foundation#6408]
If you go to the readme of this repo an download the [latest release](http://foundation.zurb.com/cdn/releases/foundation-latest.zip) the css files, foundation.css and foundation.min.css are empty. If you download the .zip from the website the files are fine. Thanks!

**Comment by rafibomb** [comment]
We updated the readme link https://github.com/zurb/foundation/commit/453e120daa5f7a3da5961717283ee788a893d386
