### ISSUE TITLE
Joyride for other uses

### ISSUE THREAD

**Issue by davejlong** [zurb/foundation#6409]
I have an app that I'm working on that I'd like to use Joyride in, but it doesn't seem to support being used for anything besides a tour.

My client has requested a page where people will confirm information on a button click. I wanted to use Joyride to walk the user through the page and ask questions like "Does this information look okay?" throughout the elements that need to be confirmed, but Joyride doesn't seem very intuitive for this.

So my feature request is that Joyride supports confirmation style walk throughs as well as tours:

* Select the "previous" button on the first Joyride element
* Send the option chosen (previous or next) to `post_step_callback`
* Allow breaking out of Joyride at any time

Those are really the only items that would make Joyride usable in confirmation walkthrough use cases.

**Comment by davejlong** [comment]
btw I saw that there's some discussion about dropping Joyride from Foundation's core. I think that, if the above features were added, Joyride could be very usable when developing web applications.

**Comment by Lynda333** [comment]
+1. Interesting and I like it.

**Comment by rafibomb** [comment]
Hi Dave,
All that sounds great. We are not looking to stop supporting Joyride, but just make it an optional add on as people aren't using on most projects.

It is not on ur roadmap to change it further than bug fixes for now. As far as adding features, we're very open to pull requests for added functionality.
