### ISSUE TITLE
Unable to change alert border color in settings

### ISSUE THREAD

**Issue by cortopy** [zurb/foundation#6410]
I'm unable to change alert border colour directly on setting files. This is what I've done: 

```
// $alert-border-color: scale-color($primary-color, $lightness: $alert-function-factor);
```

to

```
$alert-border-color: #1e90ff;
```

I've overridden it in my own scss but I just think this is weird behaviour

**Comment by rafibomb** [comment]
This is something that can be done automatically in Sass. Adding this in would add a lot of code for something takes a little CSS. We'll add the function in for the next version, but for now the variable would need to manually changed based on the background you need.

`$alert-border-color: scale-color($primary-color, $lightness: $alert-function-factor);`

**Comment by MaxDBN** [comment]
same issue, it's just not working
tried change the variable manually
tried override in my own scss
