### ISSUE TITLE
Top bar content overflows and pushes buttons down if too big

### ISSUE THREAD

**Issue by estebanms** [zurb/foundation#6411]
I don't know if this is expected behavior or not, but to me content should be truncated if it's too big to fit the screen (just like it's being done in the "small" responsive version)

To reproduce this issue, simply go to the examples page (http://foundation.zurb.com/docs/components/topbar.html) and in the 2nd example change the title "My Site" for something large enough (I used the browser's dev tools to do that.) I was able to reproduce it for both medium and large screens.

I'm using Foundation 5 and I was able to reproduce it on Chrome and Firefox (I haven't tried other browsers)

**Comment by rafibomb** [comment]
This is more of a design decision. You can have fewer links, make them smaller, or make the top-bar breakpoint kick in sooner.

If you need help doing any of those, The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help.
