### ISSUE TITLE
How to make the height equal the width of a column?

### ISSUE THREAD

**Issue by JTallis** [zurb/foundation#6413]
I would like to know the best way to make the height of a column equalled to it's width.

It would be a good addition to Foundation to enable such things.
In my case, it would be nice to have a square column with a smaller column's height equalled to the square.

Something like this:

    <div class="row" data-equalizer>
        <div class="small-12 medium-8 columns" /*make height equal width*/ data-equalizer-watch>
        </div>
        <div class="small-12 medium-4 columns" data-equalizer-watch>
        </div>
    </div>

**Comment by rafibomb** [comment]
It would be interesting but doesn't really work well in a responsive environment. It's not something we'll be adding to Foundation. Thanks!
