### ISSUE TITLE
input HTML without type attribute does not get default foundation styles

### ISSUE THREAD

**Issue by jordan112** [zurb/foundation#6416]
In HTML,  

    <input/> defaults to <input type='text'/>

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-type

Some minifiers will strip out type='text' since it knows its default.   The Foundation css styling is specific to type='text', therefore just plain <input /> won't get the default foundation styling for an input text box.

I added an override temporarily to include this but it would be nice to have foundation default this.

````
input {
  -webkit-appearance: none;
  -webkit-border-radius: 0;
  background-color: #fff;
  font-family: inherit;
  border-style: solid;
  border-width: 1px;
  border-color: #ccc;
  box-shadow: inset 0 1px 2px rgba(0,0,0,.1);
  color: rgba(0,0,0,.75);
  display: block;
  font-size: .875rem;
  margin: 0 0 1rem;
  padding: .5rem;
  height: 2.3125rem;
  width: 100%;
  box-sizing: border-box;
  transition: box-shadow .45s,border-color .45s ease-in-out;
}
````

**Comment by rafibomb** [comment]
Makes sense. This is already in our early work for the next version. A PR would be helpful, otherwise it's addressed in F4S -6   Thanks!

**Comment by jordan112** [comment]
Thanks.  I was looking to submit a PR but couldn't quite tell with all the Sass where these get generated.   Here is what all the styles look like in css after they've been Sassed.

````
input[type="text"], input[type="password"], input[type="date"], input[type="datetime"], input[type="datetime-local"], input[type="month"], input[type="week"], input[type="email"], input[type="number"], input[type="search"], input[type="tel"], input[type="time"], input[type="url"], input[type="color"], textarea {
  -webkit-appearance: none;
  -webkit-border-radius: 0px;
  background-color: white;
  font-family: inherit;
  border-style: solid;
  border-width: 1px;
  border-color: #cccccc;
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
  color: rgba(0, 0, 0, 0.75);
  display: block;
  font-size: 0.875rem;
  margin: 0 0 1rem 0;
  padding: 0.5rem;
  height: 2.3125rem;
  width: 100%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  transition: box-shadow 0.45s, border-color 0.45s ease-in-out;
}
````

**Comment by jordan112** [comment]
ah, i see it in here. 

https://github.com/zurb/foundation/blob/a142083e6e7dad0282ebc8e132528ad54e1e0f2c/scss/foundation/_functions.scss

Maybe i could add a new type called default to 

     $all-text-input-types:

and then have the loop check for that.
