### ISSUE TITLE
Uncompiled Sass files unavailable for Foundation 3

### ISSUE THREAD

**Issue by greaveselliott** [zurb/foundation#6418]
Hi all,

I'm stuck with Foundation 3 as my client requires IE8 support. On the Foundation website I can't seem find the uncompiled .scss source for Foundation 3.

The compiled .css is the only download link I can find: http://foundation.zurb.com/develop/download-f3.html

Any help locating the source would be greatly appreciated!

Thanks,

- Elliott

**Comment by rafibomb** [comment]
I think this is what you're looking for - https://github.com/zurb/foundation/releases/tag/v3.2.5
