### ISSUE TITLE
Foundation-rails 5.5.1 Foundation is not defined

### ISSUE THREAD

**Issue by wldcordeiro** [zurb/foundation#6420]
I updated a project with bundle update to Foundation 5.51 and now I get 8 reference errors saying that Foundation is not defined.

**Comment by wldcordeiro** [comment]
Looks like this commit fixed it, 6ebd996d1965202bd85bb0aaff4449852f2bc2dd push a version 5.5.1.2 of the gem and all will be well.

**Comment by rafibomb** [comment]
Thanks Will! This will be rolled into our release next week of Foundation for Sites as a whole. Appreciate the note!

**Comment by alexpchin** [comment]
What is the solution?

**Comment by mikemerritt** [comment]
Any updates on this? foundation-rails is completely broken as it stands right now.

**Comment by alexpchin** [comment]
I got it to work yesterday. I had some trouble with the dropdowns and there are errors on the JS. What version of rails are you working with? Make sure you are using the latest gem.

**Comment by wldcordeiro** [comment]
5.5.1.1 is the broken build because `foundation.js` isn't loading before all the other plugins. If you get 5.5.1.2 it should be fixed now.

**Comment by frenkel** [comment]
When will 5.5.1.2 be released?

**Comment by wldcordeiro** [comment]
@frenkel It has been from the looks of it. https://github.com/zurb/foundation-rails/releases/tag/v5.5.1.2

**Comment by mikemerritt** [comment]
@wldcordeiro The latest on rubygems is still 5.5.1.1 https://rubygems.org/gems/foundation-rails/versions/5.5.1.1

**Comment by wldcordeiro** [comment]
@rafibomb @mikemerritt Can we get 5.5.1.2 pushed to Ruby Gems?

**Comment by alexpchin** [comment]
Yes please :)

**Comment by ivdma** [comment]
:+1: for pushing 5.5.1.2

**Comment by nicolasiensen** [comment]
+1 for pushing it

**Comment by a17levine** [comment]
I just got a ton of these errors on 5.5.2.0 and downgraded to 5.5.1.2 per this thread. It fixed them.

`gem 'foundation-rails', '~> 5.5.1.2'`
