### ISSUE TITLE
pagination-current-item Mixin // CSS inheritance

### ISSUE THREAD

**Issue by andi1984** [zurb/foundation#6422]
Currently the styling of current pagination's item is done directly on the leaf nodes (speaking with DOM structure in mind) of the item. Hence a flag ```$has-anchor``` needs to be set to true/false to style the correct element.

Wouldn't it be better to style the item itself (```$has-anchor: false``` mode) and inherit these properties to the eventually available anchor or button? I know, inheritance is not the same as it is done at the moment, but it would be really simpler to use the pagination without thinking about "Does the element has an anchor or not".

Just my two cents...

**Comment by zurbrandon** [comment]
Thanks Andi, We're reworking Pagination for Foundation 6 and took this into consideration. We're making it far less dependent on an a tag.
