### ISSUE TITLE
Foundation variable not found foundation-rails 

### ISSUE THREAD

**Issue by hayduke19us** [zurb/foundation#6427]
rails v 4.1.10
foundation-rails v 5.5.1.1
The Foundation class object is not found
Foundation.libs.abide 

I reverted to 5.5.1.0 and the error has gone away

**Comment by macowie** [comment]
+1 

Getting this with foundation-rails 5.5.1.1 and rails 4.2.1, but only in production

Reverting to 5.5.1.0 seems to have fixed it

**Comment by victorlamhk** [comment]
It's fixed in `foundation-rails` respository. Waiting for the Rubygem update. 

Meanwhile, use the following line in Gemfile.

`gem 'foundation-rails', git: "https://github.com/zurb/foundation-rails.git"`

**Comment by hayduke19us** [comment]
thanks victorlamhk!

**Comment by lugoff23** [comment]
Thanks a lot @victorlamhk

**Comment by mehlah** [comment]
The related issue for reference https://github.com/zurb/foundation-rails/pull/117

**Comment by gakimball** [comment]
This appears to have been fixed on their end.
