### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sticky_class' of undefined

### ISSUE THREAD

**Issue by jamescaruso** [zurb/foundation#6430]
I am using Foundation with RoR. foundation-rails-5.5.1

If I navigate to one of the links in the top bar and then back, I get the following error:
````
Uncaught TypeError: Cannot read property 'sticky_class' of undefined
foundation.topbar.js, line 64: var sticky = topbarContainer.hasClass(settings.sticky_class);

**Comment by Vibhuti** [comment]
+1, i am getting the same error:
Uncaught TypeError: Cannot read property 'sticky_class' of undefined

**Comment by rizidoro** [comment]
+1 I'm getting this error too

**Comment by casertap** [comment]
+1 same thing here
```
Uncaught TypeError: Cannot read property 'sticky_class' of undefined  --- foundation.js?body=1:5353 
Foundation.libs.topbar.is_sticky --- foundation.js?body=1:5602 
(anonymous function) 
jquery.min.js:4 x.extend.each
jquery.min.js:4 x.fn.x.each
foundation.js?body=1:5582 
Foundation.libs.topbar.resize  --- foundation.js?body=1:5522 
(anonymous function) --- foundation.js?body=1:439 
(anonymous function)
````

**Comment by baberthal** [comment]
+1

```
Uncaught TypeError: Cannot read property 'sticky_class' of undefinedFoundation.libs.topbar.is_sticky 
foundation.topbar.js 1:64(anonymous function) 
@ foundation.topbar.js 1:321 jQuery.extend.each 
@ jquery.js 1:385 --- jQuery.fn.jQuery.each 
@ jquery.js 1:137 --- Foundation.libs.topbar.resize 
@ foundation.topbar.js 1:301 --- (anonymous function) 
@ foundation.topbar.js 1:241 --- (anonymous function) 
@ foundation.js 1:447
```

**Comment by mido18** [comment]
getting this error also

**Comment by casertap** [comment]
I did not find any solution on this problem and it is getting more and more annoying.
I have white space at the to of my page and it seems that it comes because of this error.

**Comment by mido18** [comment]
@casertap    add your javascript in the head not in the body this fixed the issue for me
 = javascript_include_tag "application"

**Comment by sibinx7** [comment]
@mido18  added on the top but i still have same issues, accordion and some other items are not working, i need to reload pages again to work these items...

**Comment by kevinhq** [comment]
+1, getting exactly same error.. have no idea what's going on there. My js is on the body.

**Comment by fanfankormoran** [comment]
+1 same issue here, FF5 with RoR (foundation-rails) ... it prevents all javascript from working, you have to reload the page

**Comment by maxcal** [comment]
I can confirm that @fanfankormoran's solution of using the Turbolinks `ready page:load` event seems to solve this issue.

**Comment by endlos** [comment]
Thanks fanfankormoran

**Comment by tuchedsf** [comment]
Thanks @fanfankormoran! I solved my problem with your solution!

**Comment by casertap** [comment]
Thanks @fanfankormoran, it works.

**Comment by Janee** [comment]
Thanks @fanfankormoran ! Solve my problem with RoR 4.2 :+1:

**Comment by rafibomb** [comment]
Thanks for posting your solution @fanfankormoran ! We'll close this here. We're open to PR's and ideas on how to make Turbo Links and Foundation JS play nice together.

**Comment by prokizzle** [comment]
I was using chruby, and I had updated my system ruby to 2.1.5 using postmodern's ruby-install. The above solutions did not work, without a little finesse.

What finally worked for me (even after changing the user settings ruby path to `/Users/prokizzle/.rubies/ruby-2.1.5/bin/ruby` was running:

`/usr/bin/gem install htmlbeautifier`

Now everything is great.

**Comment by romeromfm** [comment]
Thanks @fanfankormoran ! The 'ready page:load' solution solved my problem perfectly!
