### ISSUE TITLE
Yahoo HREF Tel Issue

### ISSUE THREAD

**Issue by vinithktp** [zurb/foundation#6431]
Hi i am using Ink Framework for responsive email design, facing an issue with callable telephone number in Yahoo Mail Android devices

My Code: < a href="tel:1.888.222.3333" >

is not working on yahoo android devices. Working fine on Android Gmail, AOL, Outlook. Its rendering like in yahoo mail chrome debug mode. 

Out put from Yahoo Mail: < a rel="nofollow" >

Any one has any idea how to fix this issue

**Comment by vinithktp** [comment]
Hi,

Any updates

**Comment by rafibomb** [comment]
This is the Foundation for Sites repo. 

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here.

The Ink repo for reporting bugs or making fixes is here: https://github.com/zurb/ink
