### ISSUE TITLE
Top-Bar: padding-left broken on mobile-menu

### ISSUE THREAD

**Issue by DesignMitZweiS** [zurb/foundation#6433]
I've downloaded the bower-foundation version 5.5.1 and it seems there is an override happening in _top-bar.scss. (line 328)

padding-left: .9375rem gets an override from padding: 12px 0 which is really bad :-/

    .top-bar-section ul li>a {
      color: #5eabcc;
      display: block;
      font-family: Helvetica Neue,Helvetica,Roboto,Arial,sans-serif;
      font-size: .875rem;
      font-weight: 400;
      padding-left: .9375rem;
      padding: 12px 0;
      text-transform: uppercase;
      width: 100%
    }

**Comment by rafibomb** [comment]
Just downloaded a fresh copy of 5.5.1

I am not seeing this CSS output:
```
.top-bar-section ul li > a {
      display: block;
      width: 100%;
      color: #FFFFFF;
      padding: 12px 0 12px 0;
      padding-left: 0.9375rem;
      font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
      font-size: 0.8125rem;
      font-weight: normal;
      text-transform: none; }```

**Comment by DesignMitZweiS** [comment]
hmm, never mind. it must have been an local issue on my side.
