### ISSUE TITLE
Dropdown issues, when an anchor is used in the dropdown content

### ISSUE THREAD

**Issue by vdazrat** [zurb/foundation#6437]
If say I need to have a textbox and and a save button that appears when the dropdown button is clicked. When I click to enter text in the textbox, the drop down disappears.
This is seen even in the example in 
http://foundation.zurb.com/docs/components/dropdown.html
when clicked on anywhere besides the button, the dropdown closes

**Comment by caycek** [comment]
Hey... so this might help you find your answer. I didn't consider `textarea`, but would be similar... I think this weekend on some free time I'm going to look up a way in the documentation to make my own option set so I can keep all inputs, buttons and the such open. I think this could be very useful.

[Another type of issue like yours](https://github.com/zurb/foundation/issues/6441)

**Comment by rafibomb** [comment]
We have an option for this

```html
  <a class="button" data-dropdown="autoCloseExample" aria-controls="autoCloseExample" aria-expanded="false">Link Dropdown &raquo;</a>
  <ul id="autoCloseExample" class="f-dropdown" data-dropdown-content aria-hidden="true" aria-autoclose="false" tabindex="-1">
    <li><a href="#">This is a link</a></li>
    <li><a href="#">This is another</a></li>
    <li><a href="#">Yet another</a></li>
  </ul>
```

http://codepen.io/rafibomb/pen/bdNGyB
