### ISSUE TITLE
Focussing on input inside dropdown

### ISSUE THREAD

**Issue by 57u** [zurb/foundation#6441]
Seems to be a bug from a while ago, and still exists. i'm on the latest Foundation 5.5.1 and still when i focus on an input thats inside a dropdown it closes the dropdown...

This is the very simple code, using the raw Foundation lib, no fancy business. I have a click handler on the links within, just to show the #rejectQuoteOtherReasonWrap div that contains the input (well, textarea) - on focusing the textarea the dropdown will close...

```
<button data-dropdown="ddRejectQuote" aria-controls="ddRejectQuote" aria-expanded="false"
                class="button secondary dropdown pull-right" data-options="align:bottom">Reject Quote</button>
        <div id="ddRejectQuote" data-dropdown-content class="f-dropdown" aria-hidden="true">
            <ul class="side-nav">
                <li><a href="#" data-reason="Too Expensive">Too Expensive</a></li>
                <li><a href="#" data-reason="Delivery Too Expensive">Delivery Too Expensive</a></li>
                <li><a href="#" data-reason="Better Deal Elsewhere">Better Deal Elsewhere</a></li>
                <li><a href="#" data-reason="Deposit Too High">Deposit Too High</a></li>
                <li><a href="#" data-reason="No Longer Needed">No Longer Needed</a></li>
                <li><a href="#" data-reason="Other">Other</a></li>
            </ul>
            <div id="rejectQuoteOtherReasonWrap">
                <label>Enter Reason: </label>
                <textarea name="rejectQuoteOtherReason" id="rejectQuoteOtherReason" rows="2" placeholder="Enter reason here"></textarea>
                <button type="submit" class="button secondary small" value="acceptQuote">Reject</button>
            </div>
        </div>

```

**Comment by 57u** [comment]
Does anyone actively look at these issues...?

**Comment by 57u** [comment]
Ended up having to do:

```
 aria-autoclose="false"
```

On the dropdown container (#ddRejectQuote in my example code) - this keeps the dropdown open, and in my case it doesn't really matter because a click on a link, or pressing submit after entering text in the input, submits the form....

It's a shame issues like this exist in such an otherwise pretty powerful framework.

**Comment by caycek** [comment]
Hey so I did some digging for you on this. 

> # Autoclose
>There is an autoclose option that you can include in the mark up. This is an option that enables the dropdown to close automatically when a link is clicked within the dropdown.

>This option is enabled by default, but to disable (keep dropdowns persisting), set the attribute aria-autoclose to false.

I know you figured it out, but based on the new documentation for the dropdown plugin this is a desired effect. Luckily you were able to figure it out rather quickly, but I wanted to make sure this was mentioned. I'm not an expert, but I am trying to help out while learning as much as I can right now.

See [Foundation Dropdowns](http://foundation.zurb.com/docs/components/dropdown.html) for further information. (Also for fun there is this cool Pip Alignment thing that I noticed they have hidden in the comments for 5.5.2, you might be interested in reading it!)

**Comment by caycek** [comment]
So..... side note.... I determined just now for what I was working on that I want to be able to click links in the dropdown and have the list close, but when I click in the input I don't want the list to close...

On line 95 of `foundation.dropdown.js` I changed 

```javascript
if (links.length > 0 && parent.attr('aria-autoclose') !== 'false' ) {
```

to

```javascript
if (links.length > 0 && (parent.attr('aria-autoclose') !== 'false' && !S(e.target).is('input') )){
```
.

I think this should be an option or something that would be a good idea to fix. Something like an `aria-inputclick` and have it set to `true` as default. By having it set to `true` if an input is clicked on a dropdown it should persist. Otherwise it acts normal. This would most likely need to be added as a secondary if statement within the lines edited above, but I am keeping my edit on my site as it is the desired affect across the board for now.

This may not be ideal for all users, hence the option!

**Comment by rafibomb** [comment]
We have an option for this

```html
  <a class="button" data-dropdown="autoCloseExample" aria-controls="autoCloseExample" aria-expanded="false">Link Dropdown &raquo;</a>
  <ul id="autoCloseExample" class="f-dropdown" data-dropdown-content aria-hidden="true" aria-autoclose="false" tabindex="-1">
    <li><a href="#">This is a link</a></li>
    <li><a href="#">This is another</a></li>
    <li><a href="#">Yet another</a></li>
  </ul>
```

http://codepen.io/rafibomb/pen/bdNGyB

**Comment by caycek** [comment]
Hey Rafi, I know you closed this, but when you use an input like a text field inside the goal is to have it not close like you're example, but close on links like a normal drop down. At least that is how I understood it. In reality though, this is most likely a edge case scenario. I know I have a way to make what I want to happen in this scenario at the very least for text inputs, but I wanted to possibly create an option for selects, textareas and the like to work in this manner.

Hopefully that makes sense, but I wanted anyone who comes in the future to realize that the option you provided is correct, but doesn't do 100% exactly as desired.

**Comment by 57u** [comment]
As caycek has re-iterated - the actual issue is when we want a input/textarea inside of a dropdown-content - focussing on the input will close the dropdown (because the dropdown loses focus?)
