### ISSUE TITLE
Topbar Dropdown Bug on all IE

### ISSUE THREAD

**Issue by joshmedeski** [zurb/foundation#6443]
The dropdown triangle doesn't display properly on any version of IE for me [healthlabs.com](https://www.healthlabs.com)

![dashboard](https://cloud.githubusercontent.com/assets/2036594/7008446/4fdf79d2-dc58-11e4-89f5-566a598e3e38.jpg)

Please help, thanks :)

**Comment by tipsforthings** [comment]
Did you use rails for this? It seems the image/font src is incorrect.

**Comment by joshmedeski** [comment]
I'm using Craft, and I'm not able to replicate the incorrect image/font src :( 

Where would I find that reference?

**Comment by tipsforthings** [comment]
Can you elaborate a bit more on craft, I haven't had the fortune to come across this.

**Comment by joshmedeski** [comment]
[Craft](http://buildwithcraft.com/) uses the Twig templating language and all the front-end code was written by hand. 

There are no console errors or warnings telling me the image/font src is incorrect, but the following CSS doesn't work properly in all IE instances: 

```
border-color: rgba(255,255,255,.4)transparent transparent;
```

**Comment by tipsforthings** [comment]
it should be 0.4 instead of just .4

**Comment by joshmedeski** [comment]
Good call @tipsforthings! Now I get to figure out how to properly minify my CSS without removing the 0.

Thanks for helping :)
