### ISSUE TITLE
Replace [class*="column"] by [class^="column"] in grid construction

### ISSUE THREAD

**Issue by juanbrujo** [zurb/foundation#6448]
It's great how Foundation work with grid columns, but what if the CSS for this classname is not that restrictive?

In this line of the source: https://github.com/zurb/foundation/blob/master/scss/foundation/components/_grid.scss#L246

Using `[class*="column"]` matches every classname that includes **column**, even if it the selector has a `class="my-pretty-column-collapsed"`. But, better if the grid just detect the word **column** if it is starting the classname, so the word can still be used as a compound word: `[class^="column"]`. Even further, matching exactly the word column `[class="column"]`.

**Comment by jaimeguaman** [comment]
I had some ugly and difficult to debug problems for this selector in particular.
this is clearly an anti-pattern selector.

you are taking the word "column" and it can't be used anymore or will screw up third-party stylesheets

**Comment by juanbrujo** [comment]
Here`s a fiddle with pattern tests (the second word *columna* is *column* in spanish)

http://jsfiddle.net/7ru36hta/

**Comment by gakimball** [comment]
Fixed and replaced with normal classes.
