### ISSUE TITLE
Grid + Flexbox breaks Blink 

### ISSUE THREAD

**Issue by justrhysism** [zurb/foundation#6450]
I know this isn't actually a Foundation bug, per-se, but I didn't really know where to put it. I want to report an issue to Chrome, but could do with some help in better determining what the issue actually is. Here is a reproduction: http://codepen.io/justrhysism/pen/RNzPgX

**Comment by rafibomb** [comment]
Good to know. We actually have a built from scratch flexbox grid coming in the next version that is optional along with the float grid. I wouldn't imagine augmenting the float grid with flexbox would work as well. We'll need people to test the new grid out before we release it. If you're in, I'll put you on the list and let you know when it's ready for testing.
