### ISSUE TITLE
Side nav wrong spacing between items

### ISSUE THREAD

**Issue by collimarco** [zurb/foundation#6452]
As you can see there's extra spacing between red blocks (i.e. "edit" and "delete"):
![side-nav-bug](https://cloud.githubusercontent.com/assets/90962/7071222/402bd1e6-dee4-11e4-8f9c-357fa26cbfde.png)

Here's the simple haml code for the markup:

```
%body
  .row
    .column.medium-4
      %nav
        %ul.side-nav
          %li= link_to t('edit'), "#"
          %li= link_to t('delete'), "#"
    .column.medium-8
      ...

```

I've checked and there aren't any custom css that can be producing this behavior.

**Comment by collimarco** [comment]
The wrong behavior also persists ensuring that no white space is present between the elements.

**Comment by StoneCypher** [comment]
if you provide something like a fiddle then other people can help you

**Comment by collimarco** [comment]
Oops, it's simply `li` margin. So this is probably the expected behavior.

It seemed strange to me because **on http://foundation.zurb.com/docs/components/sidenav.html there aren't any margins** - and the side nav looks better! But this is because of another declaration in `docs.css`, which is part of the website, but not part of the framework.

Furthermore, being the links not adjacent, the "hover" effect is interrupted when the pointer is the space between `li`elements.
