### ISSUE TITLE
Validation on postfix fields (abide)

### ISSUE THREAD

**Issue by lucashpandolfo** [zurb/foundation#6453]
Example here: https://jsfiddle.net/emwxxtfo/

Whenever an error is found in a field, the label turns red and the optional error message is displayed.
![OK](http://i.imgur.com/GyU7gQZ.png)

When an error is found in a postfix field, the error message is displayed, but the label remains the same.
![NOT OK](http://i.imgur.com/B0hyepa.png)

BTW, I could not find a validation example using pre/post fix in the docs so my code may be wrong.

**Comment by Randore** [comment]
what's the point here, i don't understand what you mean post/prefixes.
You can write your own error messages for different form fields.

**Comment by lucashpandolfo** [comment]
Let me put it another way.

![:D](http://i.imgur.com/9CoEQaz.png)
![D:](http://i.imgur.com/P9eIaVt.png)

**Comment by Randore** [comment]
Okay I got it, it was my mistake that didn't checked latest foundation update - i just checked and noticed post and prefix classes.

Here is the solution for your problem.
https://jsfiddle.net/emwxxtfo/2/

**Comment by lucashpandolfo** [comment]
This solves the problem.
Thanks.

**Comment by zurbrandon** [comment]
Looks like this has been solved, based on the JSFiddle, so we'll close this. Let me know if I'm mistaken.
