### ISSUE TITLE
[bower] release don't match with the actual code on git repo

### ISSUE THREAD

**Issue by panurge-ws** [zurb/foundation#6456]
I found that with the release 5.5.1, something is missing.
Eg. _forms.scss line:329 -moz-appearance: none !important;
is missing when you try to update the bower component with:

$ bower update foundation 

I think it depends on the release number not changed (not resolved by bower): basically update can't download the actual code in the bower repo.

**Comment by gakimball** [comment]
`master` is our development branch, and the change you're referencing hasn't made it into a shipping release yet. It looks like it made it in about a week after 5.5.1 came out.
