### ISSUE TITLE
Turbolinks breaks Foundation tabs

### ISSUE THREAD

**Issue by valdis** [zurb/foundation#6461]
Scenario to repeat the problem
1) I load a page with foundation tabs 
2) call  $(document).foundation()
3) Using ajax i replace the existing tabs with a different set of tabs with different anchors
4) when i call $(document).foundation() i get an `Exception Uncaught TypeError: Cannot read property 'split' of undefined` for this line https://github.com/zurb/foundation/blob/master/js/foundation/foundation.tab.js#L131

If no tab with the memorized anchor is found, then it throws an error and other JS code after this line does not get executed.

My solution was to patch the `Foundation.libs.tab.reflow` function
```javascript
Foundation.libs.tab.reflow = function(){
  this.default_tab_hashes.length = 0
}
```
and call `$(document).foundation('tab', 'reflow')` 
before `$(document).foundation()`

**Comment by rafibomb** [comment]
Can you try initializing Foundation like this? It has helped with some issues
$(function(){ $(document).foundation(); });

**Comment by rafibomb** [comment]
We're looking for ways to avoid this for Foundation Sites 6. Until then, have any suggestions?

**Comment by rafibomb** [comment]
As we write JS for the next version, we'll keep turbo links compatibility in mind.

**Comment by dbjsy** [comment]
I know this is an old thread, however for anyone who got here through Google:

place foundation init function within turbolinks load event (new turbolinks):

`

document.addEventListener('turbolinks:load', function() {

    $(function(){ $(document).foundation(); });

});

`
