### ISSUE TITLE
Can't put typeahead above other grid-block

### ISSUE THREAD

**Issue by pidupuis** [zurb/foundation#6464]
See the following [plunker](http://plnkr.co/edit/PZRCmbyCxwMU9aAgtybX?p=preview) (better with smaller screen).

I'm using [foundation-apps](http://foundation.zurb.com/apps/docs/#!/grid) with grid-blocks generated by `ng-repeat`. The inputs are using [angular-foundation](http://pineconellc.github.io/angular-foundation/) typeahead. When you type an 'a' in one of the input, the dropdown will appear strictly within its grid-block. Consequently I obtain a scroll bar while I would like to see the dropdown above everything else...

A z-index does not seem to change anything.

**Comment by gakimball** [comment]
Grid elements are `overflow: auto` by default, so they can scroll when need be. Adding `overflow: visible` might fix your issue.

And for future reference, Foundation for Apps has its own issue tracker, which you can check out [over here](https://github.com/zurb/foundation-apps/issues).

**Comment by pidupuis** [comment]
Thanks, it works! :)

Sorry I have misplaced this issue. In my defence, the `foundation-apps` [support page](http://foundation.zurb.com/apps/support.html) redirects to `foundation` issue page (https://github.com/zurb/foundation/issues) instead of the one of `foundation-apps`. That's pretty confusing ^^'

**Comment by gakimball** [comment]
@pidupuis Ah yes, we fixed that recently, I'll make sure the fix was deployed to the live servers.
