### ISSUE TITLE
Make toggles respond to swipes on touch devices.

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation#6465]
I'd like to see the toggle controls respond to swipe gestures on touch devices. This would be similar behavior to default iOS controls as well as Google Material Design. In addition it would better match the affordance for a sliding toggle switch.

**Comment by rafibomb** [comment]
Sorry, what component does this relate to? Can you provide an example?

**Comment by christianmagill** [comment]
Sorry I meant the switch controls.

http://foundation.zurb.com/docs/components/switch.html

**Comment by zurbrandon** [comment]
This isn't something we'll be doing for default Foundation as we'd need to add another dependance to adequately account for the correct swipe. (most likely Hammer.js). 

Although If you have some experience with swipe so a PR would be welcome :)
