### ISSUE TITLE
JS Error: Ajax Reveal within an Ajax Reveal

### ISSUE THREAD

**Issue by jimkrill** [zurb/foundation#6466]
Was getting a JS error when trying to open a reveal within a reveal (both being ajax requests).

This was from version 5.5.1 - maybe there is already a fix.

Found the problem was in foundation.reveal.js on line 210 & 212:

```
if (open_modal.length > 0) {
                if (settings.multiple_opened) {
                  this.to_back(open_modal);
                } else {
                  this.hide(open_modal, settings.css.close);
                }
              }
```

the use of "this" in there should be "self" instead.

Should be this:
```
if (open_modal.length > 0) {
                if (settings.multiple_opened) {
                  self.to_back(open_modal);
                } else {
                  self.hide(open_modal, settings.css.close);
                }
              }
```

Since `this` is referring to the ajax event, not the reveal modal object.

Cheers.

**Comment by jimkrill** [comment]
Nevermind.

This was fixed here: https://github.com/zurb/foundation/commit/f379a79af0c61c2760846861713b58a726ca5fcf

But it's not updated in version 5.5.1. 

What is the release schedule like for Foundation?  How soon does this repo update the latest bower version - or is it one and the same? What am I missing?

**Comment by rafibomb** [comment]
Changes staged on the master branch are available to get by using bower to target update. 

In your bower.json file

{
  "name": "foundation-libsass-template",
  "dependencies": {
    "foundation": "master"
  }
}

The fully tested versions are the tagged releases. The milestone on 5.5.2 is scheduled to be pushed out on Tuesday the 28th.
