### ISSUE TITLE
Magellan offset problem

### ISSUE THREAD

**Issue by mgntrn** [zurb/foundation#6468]
Hi,

There's a strange problem with Magellan, in both Windows (Chrome and Firefox) and OS X (Firefox only). The issue exists on the demo page (http://foundation.zurb.com/docs/components/magellan.html), so I don't think it has anything to do with my implementation. The 'active' class isn't assigned to the menu item when clicked on it. I have to scroll a few pixels down to let the clicked item become active.

For example, on the demo page, when I click on 'Destination', the window scrolls down, to the Destination seciton. But the Arrival menu item stays active. When I click Destination again, the window scrolls a bit more down, but still the Arrival item stays active. When I scroll about 10 to 20 pixels down the Destinaiton item becomes active. Same goes for all other menu items. I think there's something wrong with the offset when clicked on an item. Chrome OS X works fine though.

mgntrn

**Comment by rafibomb** [comment]
Moving the `<a name>` inline or below the header works well across the browsers. We've updated the docs to reflect that.

```<h3 data-magellan-destination="arrival">Arrival</h3>
<a name="arrival"></a>```

**Comment by rafibomb** [comment]
https://github.com/zurb/foundation/commit/d29e5af7db676c277e1a891bb841d9274f3a6a5d
