### ISSUE TITLE
Rename progress to progress-bar

### ISSUE THREAD

**Issue by pedzed** [zurb/foundation#6470]
I find `progress-bar` (or `progressbar`) much more specific than `progress` and hope to see a change in Foundation 6.

```html
<div class="progress-bar">
    <div class="meter" style="width: 75%;"></div>
</div>
```

Now I have to name a class "progress-status" as a workaround (an element which is not a progress bar).

**Comment by rafibomb** [comment]
What if the progress is circular? Is it still a bar?

**Comment by rafibomb** [comment]
Just noticed our current SCSS file is named that way. We'll probably name it progress in version 6. Thanks!
