### ISSUE TITLE
Joyride bottom arrow is breaking

### ISSUE THREAD

**Issue by viniciusdacal** [zurb/foundation#6472]
![captura de tela 2015-04-15 as 08 40 39](https://cloud.githubusercontent.com/assets/2660570/7158016/aa3a10f0-e34b-11e4-9130-8dc08adb0255.png)
Chrome Version 41.0.2272.118 (64-bit) Mac OSX Yosemite.
This can easily be fixed just changing the order of border-color CSS rules.

**Comment by abdullahsalem** [comment]
Obrigado @viniciusdacal  :)

**Comment by rafibomb** [comment]
Thanks!

**Comment by abdullahsalem** [comment]
My pleasure!
