### ISSUE TITLE
opened.fndtn.reveal calllback invoked twice

### ISSUE THREAD

**Issue by ktei** [zurb/foundation#6482]
Dear Foundation Team:
I'm not sure this is expected or not, but after doing this:
```
$(document).on('opened.fndtn.reveal', '#' + this._id, this._onOpen)
```
where `this._id` points to a modal container, and `this._onOpen` is the callback function. However, I noticed that `this._onOpen` is invoked twice everytime the Modal is opened.

Also, if I change`el.trigger('opened').trigger('opened.fndtn.reveal')` to `el.trigger('opened.fndtn.reveal')` (in file `foundation.reveal.js`), this can resolve the issue but surely it's not the solution.

Can you give me any hints? Did I do something improper?

Cheers

**Comment by ktei** [comment]
By the way, I'm using 5.5.1

**Comment by rafibomb** [comment]
Looks like a similar one to this - https://github.com/zurb/foundation/issues/5482
Closing this in favor of that issue. 

Also we addressed this issue here:
- https://github.com/zurb/foundation/issues/6334

**Comment by ktei** [comment]
@rafibomb Thank you for your response. I also found another issue caused by this so I think it'd better to let your team know:

See `foundation.dropdown.js`, where you find `self.S(this).trigger('closed').trigger('closed.fndtn.dropdown', [dropdown]);`

This will trigger the `closed` event for sure however, it seems `closed` event will trigger a Reveal modal to be closed. Therefore, if you use dropdown button in a Reveal modal, whenever you close the collapse dropdown button, the Reveal modal gets closed too.
