### ISSUE TITLE
No markup on default attribute values

### ISSUE THREAD

**Issue by EtienneBruines** [zurb/foundation#6484]
I can either write:
```html
<input name="name">
```
or
```html
<input type="text" name="name">
```

Both are pretty much equivalent, except for Foundation: <b>only the latter gets the correct markup</b>.

This breaks compatibility with minified HTML-pages (using minifiers that remove attributes setting default values). 

I can assume the selector `input` does some things we don't want (?), but I guess the selector `input:not([type])` does what we want it to be. Not sure about cross-browser compatibility.

**Comment by gakimball** [comment]
`input:not([type])` would work pretty well. `text` is always the default value, and it works in IE9 just fine.

You can't style a plain `<input>` element because it could be a text input, or a checkbox, radio button, file upload, button, or a few other things.
