### ISSUE TITLE
Foundation 3 Top Bar Issue

### ISSUE THREAD

**Issue by Viriathus** [zurb/foundation#6486]

**Comment by r3wt** [comment]
Dude, We're on Foundation 5 now.

**Comment by Viriathus** [comment]
Lol I know and I even feel a little embarrassed asking that question. The thing is that I've done that template ages ago and a client detected that bug so I really should fix it.
Cheers!

**Comment by rafibomb** [comment]
We don't see a description but we're currently supporting 5 for bugs.

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here.
