### ISSUE TITLE
Foundation Apps (ng-click doesn't work inside tabs)

### ISSUE THREAD

**Issue by playnox** [zurb/foundation#6487]
<a ng-click="test()">test</a>

    
    <div zf-tabs="">
        <div zf-tab="" title="Tab1">
            <a ng-click="test()">test</a>
        </div>
        <div zf-tab="" title="Tab2">
            Tab content 1
        </div>
    </div>

    $scope.test = function() {
        console.log('test');
    }

**Comment by rafibomb** [comment]
Sorry for the confusion - the correct repo for Apps confirmed bugs is https://github.com/zurb/foundation-apps

**Comment by Silur** [comment]
any solution to this?
