### ISSUE TITLE
tooltip reflow is very slow in FF and IE

### ISSUE THREAD

**Issue by fayland** [zurb/foundation#6490]
it hangs actually.

it needs somehow 30+ seconds for a reflow.

I have attached one console.profile and sample a.html to test.

Thanks

[a.zip | uploaded via ZenHub](https://files.zenhub.io/55378cd1c5d756ee45134ebe)

![snip20150422_1](https://cloud.githubusercontent.com/assets/22424/7273837/0d3de22e-e92a-11e4-87dd-ec5e42e6571b.png)

**Comment by designerno1** [comment]
maybe same problem???
https://github.com/zurb/foundation/issues/6092

**Comment by rafibomb** [comment]
Seems related to this https://github.com/zurb/foundation/issues/6092

We'll be considering this for the next version.
