### ISSUE TITLE
aria-expanded tag of dropdown button not updating

### ISSUE THREAD

**Issue by ivankennethwang** [zurb/foundation#6491]
Problem: aria-expanded tag of dropdown button not updating

Steps:
1. Visit http://foundation.zurb.com/docs/components/dropdown_buttons.html
2. Look for the second "Dropdown Button" in gray
`<button data-dropdown="drop2" class="small secondary radius button dropdown" aria-expanded="false" aria-controls="drop2">Dropdown Button</button>`
3. Toggle the button, aria-expanded becomes true
`<button data-dropdown="drop2" class="small secondary radius button dropdown" aria-expanded="true" aria-controls="drop2">Dropdown Button</button>`
4. Click anywhere outside, dropdown closes
5. Button has aria-expanded still true
`<button data-dropdown="drop2" class="small secondary radius button dropdown" aria-expanded="true" aria-controls="drop2">Dropdown Button</button>`

Expected Result:
5. aria-expanded will be back to false

Actual Result:
5. aria-expanded is still set to true

Notes:
The first button of the page is updating properly. However the rest of the buttons are not updating anymore.

Occurrence Rate: Permanent

**Comment by abdullahsalem** [comment]
Hi @ivankennethwang ,
I had fixed that issue #6350 in this <a href="https://github.com/zurb/foundation/commit/4fe1071689175b5cb22a2faada18edf5db2f028e">commit</a>, but the code has been removed in this <a href="https://github.com/zurb/foundation/commit/55ff92ade2f14fdb77de9e54989d7d015ac53519#diff-1d14e68fa4bbca68bb9dc9aa7664fad4">commit</a> by @jeanieshark.

**Comment by rafibomb** [comment]
Ooops missed that one change - adding it back in for the next release. Thanks @abdullahsalem !
