### ISSUE TITLE
update matchMedia polyfill for better performance on legacy browsers

### ISSUE THREAD

**Issue by amclin** [zurb/foundation#6492]
The matchMedia polyfill was rewritten in Oct 2013 to solve some fairly substantial performance issues with IE9. Please update the version embedded within foundation.js to the latest (v0.2.0) to take advantage of these performance fixes.

https://github.com/paulirish/matchMedia.js/releases/tag/0.2.0

**Comment by rafibomb** [comment]
Thanks for the PR!
