### ISSUE TITLE
nav.top-bar.hide-for.. << causes the bar to be generally expanded 

### ISSUE THREAD

**Issue by doertedev** [zurb/foundation#6493]
OHAI.

I have a top bar. I want to display it only for certain sizes. When I give the nav bar a hide-for- statement as an additional classname, it is generally expanded, and the menu button is not functional.
Is this desired behaviour?

I mean sure,
```sass
.top-bar
  @extend .show-for-medium-down
```
this works but I haven't found the responsible code yet. H4lp?

**Comment by jherel** [comment]
if you want to display only certain heights, adds .show-for-medium-down in class.
Example:
<div class = "show-for-medium-down">
   <nav class = "top bar" topbar data-role = "navigation">
    ...
    ...
   </ nav>
</ div>

**Comment by doertedev** [comment]
Yes. Except when you want to omit the wrapper elements. Ofc this is debateable. But it is weird that this does not work out of the box.

**Comment by rafibomb** [comment]
I havn't been able to replicate it. Can you share your code? http://codepen.io/rafibomb/pen/WvbNao

**Comment by doertedev** [comment]
Closing this issue. 't was my bad. Had a version f***up on my client side, I somehow had the wrong interpreters in place. Maybe a gem cleanup between rbenv environment switches is a thing I should do more often.
Thanks for response though.
