### ISSUE TITLE
Proposal: responsive behavior for side nav

### ISSUE THREAD

**Issue by Musiksammler** [zurb/foundation#6494]
I came to the point where the side nav component on mobile devices doesn't fit very well. I had a list of items in a "small-12 large-10" grid container and the side nav in a "small-12 large-2" grid container. Everything fine on desktop browsers but on small mobile devices the side nav was sitting over the main content and due to the number of entries the main content wasn't visible when the whole side nav was in the view port.

So I searched for a better approach on mobile and came across this link: http://webdesignerwall.com/tutorials/css-responsive-navigation-menu

The idea: on small displays the whole list becomes a dropdown only with the help of css. This was exactly the thing I was searching for! So it would be nice if this approach can be integrated into foundation somehow. If anyone is interested I can post a working example with the side nav.

**Comment by rafibomb** [comment]
Depending on how you use the sidenav, you could just swap it for a mobile navigation on small like an off-canvas. I think the sidenav was meant to be a purely vertical nav and maybe not for main navigation. 

In the next version, we are making a menu bar that will have responsive modifiers that would replace the existing side-nav.
