### ISSUE TITLE
Triggered Modals (reveals) on Mobile load at Top of Page when scrolled down within the content

### ISSUE THREAD

**Issue by bisrael** [zurb/foundation#6496]
If you have a page, where the user can scroll down some, then interact with an element to reveal a modal, the modal always reveals at the top of the page, sometimes leaving the use unable to even scroll up to the modal since the reveal background prevents scrolling.

Any ideas?

**Comment by rafibomb** [comment]
Looks like this was fixed on the master branch https://github.com/zurb/foundation/commit/0dfb33664b3547fa359ad475b67f7deaf2f5ea71

It will be out in the next release next week.
