### ISSUE TITLE
Reveal Modal with disabled CSS setting doesn't fire events.

### ISSUE THREAD

**Issue by jayalfredprufrock** [zurb/foundation#6500]
On more than one occasion I've had the need to have greater control over the CSS injected into the modal upon show/hide. If passing in
```
{ css: { open: {'display':'block'}, close: {'display': 'none'}}}
```
didn't still inject `opacity:1` into the modal things would be great. Unfortunately that's not the case so I must pass in "false" for the css setting. This does prevent the injection of styles, but then events no longer get generated and the "open" class no longer gets toggled. This seems to render the plugin pretty much useless, since now custom events have to be used to get that functionality back. What is the reasoning behind the current implementation?

For instance the "show" function does this:

`return el.css(css).show().css({opacity : 1}).addClass('open').trigger('opened').trigger('opened.fndtn.reveal');`

which seems kind of silly, but forgive me if I'm missing something.

**Comment by rafibomb** [comment]
There is definitely and a balance between JS adding markup/CSS and keeping the HTML simple. In the next version there will be a lot less markup added by the JS which will make styling things even simpler. 

Especially with the reveal modal, this has been addressed.
