### ISSUE TITLE
Abide Pattern HTML5 issue

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation#6501]
As in docs http://foundation.zurb.com/docs/components/abide.html , this could be a problem:

You can use the following shortcut for named patterns that aren't valid input types:
```html
<input type="text" pattern="integer">
```
if i use
```html
<input type="text" pattern="email" required>
```
without abide validation the html5 validator returns invalid only the word "email" turns to valid

what about users turned of javascript?

maybe this is a goog solution
```javascript
var pattern = el.getAttribute('pattern') || el.getAttribute('data-pattern') || '';
```
in foundation.abide.js

so we can use pattern for real patterns regex and data-pattern for abide patterns

Greet J

**Comment by gakimball** [comment]
This is an interesting idea, but to maintain current backwards compatibility we're going to hold off until Foundation 6 for this. I added it to our [feedback thread](https://github.com/zurb/foundation/issues/4710) and [Trello board](https://trello.com/b/QBPKlQqf/foundation-sites).
