### ISSUE TITLE
Button class removed in Foundation Essentials?

### ISSUE THREAD

**Issue by iRaySpace** [zurb/foundation#6504]
Recently, I have downloaded the Foundation 5 Essentials. But then, I found myself staring the button isn't styled anymore. Is it already removed?

**Comment by Randore** [comment]
Button element already exists, what's the problem that you are facing with buttons?

**Comment by iRaySpace** [comment]
The button class on Foundation Essentials doesn't exist. I tried to search the class in the css, both the minified and non-minified. However, I found out that it is not available.

It should contain button class as it is mentioned on the [documentations](http://foundation.zurb.com/develop/download.html "Foundation 5 - Download Page").

**Comment by Randore** [comment]
@iRaySpace Yes, you are right may be they forgot to include it in Foundation 5 Essentials.

**Comment by gakimball** [comment]
Yep, buttons seem to be missing from the essentials download. We'll look into it.

**Comment by gakimball** [comment]
This has been fixed with the download for Foundation 5.5.2.
