### ISSUE TITLE
Make equalizer more responsive (again)

### ISSUE THREAD

**Issue by HugoHeneault** [zurb/foundation#6505]
Hi, 

I was very happy when I discovered that equalizer is now responsive. Great!

It could be even better if we can choose the blocks we want to equalize and not only if we want to equalize or not the whole container based on screen size. 

Actually this is not working : 
````html
<div class="row" data-equalizer>
    <div class="medium-6 large-4 columns" data-equalizer-mq="medium-up"><!--This will be equalized on medium up -->
        Some text
    </div>
    <div class="medium-6 large-4 columns" data-equalizer-mq="medium-up"><!--This will be equalized on medium up -->
        Some text
    </div>
    <div class="large-4 columns" data-equalizer-mq="large-up"><!--This will be equalized on large only -->
        Some text
    </div>
</div>
````

**Comment by zurbrandon** [comment]
Hey Hugo, We looked at doing this a couple times in Foundation 6 but couldn't justify the need in exchange for the extra code. This may be great for a standalone equalizer plugin but we think overreaches for this one right now. 

Thanks,
Brandon

**Comment by HugoHeneault** [comment]
Hey Brandon, and thanks for your reply. 

I see your point, but... It seems important anyway. And if we want to reduce the script footprint, we don't have to load it... 

If I create a PR, will you considerate it?

Thanks!
