### ISSUE TITLE
Reveal multiple modal windows doesn't seem to be working.

### ISSUE THREAD

**Issue by boomerstan** [zurb/foundation#6506]
I notice the example modal in modal at http://foundation.zurb.com/docs/components/reveal.html no longer works.

**Comment by rafibomb** [comment]
Working for us in Mac Chrome, Safari, And Firefox latest versions http://codepen.io/rafibomb/pen/EjarbV

**Comment by boomerstan** [comment]
I respectfully disagree. From your own description:

You can create a reveal modal with another inside it. Setting
reveal.multiple_opened to true *will not close previously opened reveal
modals.* You can even put a video into a reveal.
