### ISSUE TITLE
Interchange and Slick Slider

### ISSUE THREAD

**Issue by MP3en** [zurb/foundation#6507]
Hello @rafibomb, I have the following issue with Interchange and Slick Slider.

Both Interchange and the Slider are working fine, the only issue is that for some reason the last element of the slider doesn't interchange content (images).

I tried with fade set to true and it doesn't have issues, but when it's slide the last image problem occurs.

http://foundation.zurb.com/forum/posts/18344-issue-with-interchange-and-slick-slider

please change line 52 in interchange.js in             

**var orig_path = $.each(el, function(){this.src = path;});**

**Comment by mpy-pixum** [comment]
I have added a pull request to resolve this issue @jeanieshark

**Comment by jeanieshark** [comment]
Merged in the pull request and closing this issue.
