### ISSUE TITLE
Using equalizer in tabs, Equalizer not working

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation#6510]
If you use Equalizer in an tab that isn't visible (aktive) the equalizer don't work i think because of this:
```javascript
vals = group ? equalizer.find('['+this.attr_name()+'-watch="'+group+'"]:visible') : equalizer.find('['+this.attr_name()+'-watch]:visible'),
```
i created this quick and dirty workaround
```javascript
  $('.tabs').on('toggled', function (event, tab) {
    if(tab.find('[data-equalizer-watch]:visible').length > 0){
      $(document).foundation('equalizer', 'reflow');
    }
  });
```
maybe it could be better in the toggle_active_tab function of tabs

greetings
Jens

**Comment by rafibomb** [comment]
Not sure if this is a use case we're going to address since it something you can do in your own project, and you have.

We'll keep it open for now if a good Pull Request comes through.

**Comment by zurbrandon** [comment]
This will be addressed in F6, so I'll close this for now. 

Thanks!
