### ISSUE TITLE
.postfix.button, but no button.postfix

### ISSUE THREAD

**Issue by andi1984** [zurb/foundation#6515]
Inside _buttons partial all button styles are applied to the button element and all elements with class "button" (``button, .button``).

In the _forms partial however some .prefix and .postfix styles are only applied on ``.prefix.button``or ``.postfix.button``selectors. Why is that? Why aren't you also applying them to ``button.prefix`` (``button.postfix``)?

So you always need this redundancy ``<button class="button postfix">`` instead of ``<button class="postfix">`` in your markup.

**Comment by rafibomb** [comment]
One thing we want to get away from is styling tags, specifically the button tag. It's possible to have a button that is not styled like the default button and encouraging people to use the button tag is more syntactically correct. Un-doing the style on the button tag is harder than styling it if needed.

It would be a breaking change to drop styling on the button tag so we are doing it for the next version.

Essentially that makes it look like `<button class="button">`
