### ISSUE TITLE
Abide Validation broken with pattern: "email"

### ISSUE THREAD

**Issue by nickgnd** [zurb/foundation#6518]
Hi, 
I don't know if is a bug or the default behaviour, but if I add `pattern: "email"`at the end of `<input type="email" required>` I break the validation of the **whole form**.
I know that is useless to specify  `pattern: "email"` if it's already specify in the value of the input with `type="email"` (as docs says [http://foundation.zurb.com/docs/components/abide.html](http://foundation.zurb.com/docs/components/abide.html)), but I don' t think that this could be the normal behaviour.

Hope could help, 
Nico

### Rails
```` erb
<%= form_for(@patient, data: {abide: ""}) do |f| %> # form_for

1) Like this the validations will work wells*
<%= f.email_field :email, placeholder: "helloworld@example.com", required: "" %>

2) Like this the validations will break*
<%= f.email_field :email, placeholder: "helloworld@example.com", required: "", pattern: "email" %>
```` 

### obtained HTML
```` html
<!-- form -->
<form class="new_patient" id="new_patient" data-abide="" action="/my-patients" accept-charset="UTF-8" method="post" novalidate="novalidate">

<!-- first case (without patter: "email")-->
<input placeholder="helloworld@example.com" required="required" type="email" name="patient[email]" id="patient_email">
<!-- second case (with patter: "email")-->
<input placeholder="helloworld@example.com" required="required" pattern="email" type="email" name="patient[email]" id="patient_email">
````

**Comment by gakimball** [comment]
When you say it breaks validation, what's the specific issue you're running into?

#6501 might be related: if the user doesn't have JS enabled, the browser-specific validation kicks in, which would interpret `pattern="email"` as a regexp for the word "email".

**Comment by nickgnd** [comment]
Yes, I think that with `pattern: "email"` comes up a conflict between Abide and the browser validation.

In my case, I have a form where I use Abide validation on firstname, lastname, email and other fields that are required.

If I add `pattern: "email"` to email input all the validations with Abide get broken and even if I enter an email in the correct format **I can't continue to submit**, because the browser still notifies me that email format is invalid.

Moreover, Abide no longer works in the other validations. Example: 
If I left blank the name field, doesn't appear the Abide message below to the text box, but when I try to submit the browser notifies me that  it can't be blank.

I also try to insert an email like "email@example.com" but still doesn't work.

**Comment by nickgnd** [comment]
Ok, forget what I wrote.
My problem was caused by a conflict between Foundation and [Turbolinks](https://github.com/rails/turbolinks) like in this case #6438 .

I used [jquery.turbolinks gem](https://github.com/kossnocorp/jquery.turbolinks) and I solved my problem.
Now adding `patter: email` doesn't affect the right functioning of Abide.

Thanks, 
Nico

**Comment by gakimball** [comment]
Ah okay, well glad it resolved itself. Either way, we will be taking another look at `pattern` in Foundation 6.
