### ISSUE TITLE
New box-sizing rules break grid inside offcanvas menu content

### ISSUE THREAD

**Issue by xa0c** [zurb/foundation#6519]
I've mentioned that after new 5.5.2 release we have a bit new rules for box-sizing inheritance.
Commit: dd66a01bf2e37e713c545e468acdac3f8e5e6c87
Good change, but... as @gakimball had already mentioned it in #5819, this could cause wrong behavior for some elements that use another box-sizing type.
This is what happened to offcanvas menu content. Is it supposed that offcanvas should be now used for simple menus only? Because grids and full-width buttons have wrong sizes now.
I've checked sources, and it seems, that F5 uses different box-sizing for `off-canvas-menu` and `off-canvas-submenu` mixins only.

**Comment by gakimball** [comment]
We're getting a lot of comments about this, so we're going to revert it. In the mean time, you can use this as a workaround:

```css
*, *:before, *:after {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```

`*` has no specificity, so you should be able to drop this anywhere in your code.

**Comment by gakimball** [comment]
And here you go. 82f75888006c0f141ac29c9bcd1f00d0f9e6c1fb

**Comment by xa0c** [comment]
Thanks. Actually I've used a bit different workaround. F5 has non-border-box sizing in offcanvas menus only, so the fix is obvious:
````
// Don't allow menu children inherit 'content-box' box-sizing
.left-off-canvas-menu, .right-off-canvas-menu, .left-submenu, .right-submenu {
  & > * {
    @include box-sizing(border-box);
  }
}
````

**Comment by hinok** [comment]
@gakimball Could you bump Foundation to 5.5.3 because now that fix is available only on master branch and people who are using bower to manage their dependendies still will get buggy version.
