### ISSUE TITLE
Hover delay option for Top Bar dropdown

### ISSUE THREAD

**Issue by maoosi** [zurb/foundation#6521]
Would be really great to implement an hover delay option for the Top Bar navigation. When mouse hover on a parent link, childs could appears after a custom timeout.

Like for example: http://www.amazon.com (look at the Try prime & Wish list, right side of the nav)

A quite similar thing was just implemented in v5.5.2:
https://github.com/zurb/foundation/commit/f4be02c85f83b4afbd52738308b4533a407d6fae

But it applies only for dropdown buttons.

Thanks,

**Comment by rafibomb** [comment]
This makes sense since the dropdown plugin has this feature already. Since the dropdown plugin and the top-bar dropdowns don't share functionality right now, we'll save this feature for the next version where the dropdown plugin will be the same wether it's used in a main navigation or otherwise.

**Comment by krishkrush** [comment]
Is there an update to this?  We are looking for the same feature to delay the time it takes before the menu appears on hover.  

Cheers,
