### ISSUE TITLE
Publicly accessible methods for Accordion

### ISSUE THREAD

**Issue by winghouchan** [zurb/foundation#6524]
Howdy all!

A user on Foundation Forum had an issue where they wanted to toggle accordion panels according to the viewport size.

Going through the Accordion's Docs there is no documented method on how to toggle accordion panels and looking through the code it does not seem possible.

It would be greatly useful to have a publicly accessible method to toggle Accordion panels, similar to how Off Canvas has publicly available methods to programmatically show, hide and toggle.

Looking forward to such functionality being introduced. Feel free to discuss below and open a PR.

Original thread on Foundation Forum: http://foundation.zurb.com/forum/posts/24648-open-all-accordions-on-medium-up

**Comment by zurbrandon** [comment]
Looks like this was merged in I'll close this for now unless i'm mistaken.
