### ISSUE TITLE
Topbar button in firefox

### ISSUE THREAD

**Issue by mib32** [zurb/foundation#6528]
Text in the topbar button is sligtly wrong positioned in firefox - closer to bottom. Is it known issue?
![2015-05-06 15 23 59](https://cloud.githubusercontent.com/assets/8045292/7492772/19cb8cfa-f404-11e4-961f-7f6a283ae43e.png)
The same thing on my website with foundation 5.4.5 seems to be ok
![2015-05-06 15 25 52](https://cloud.githubusercontent.com/assets/8045292/7492791/3e32d440-f404-11e4-8d26-d274cd49984b.png)

**Comment by rafibomb** [comment]
The height of the button is based on the padding which is good. Right now, to center everything when you make the nav taller, there is a height being set. This causes the remainder of the button to overflow. For now you can adjust the top-padding.

Working on a fix for this to add into the next release.

**Comment by mib32** [comment]
hey @rafibomb thanks! 
I was referring to Foundation website - http://foundation.zurb.com/docs/.

**Comment by zurbrandon** [comment]
This looks like it's been taken care of, I'll close this for now. Thanks for reporting it :)
