### ISSUE TITLE
Document use of labels in the topbar

### ISSUE THREAD

**Issue by pmackay** [zurb/foundation#6530]
I'm pretty new to Foundation. While reading http://foundation.zurb.com/docs/components/topbar.html it wasnt immediately clear what the labels variables were for. What about to add a small example highlighting how a label is used?

**Comment by rafibomb** [comment]
Adding a `<label>` tag in an `<li>` it will affect the styling of the text

<li><label>Dropdown Level 1 Label</label></li>

We'll add it to the docs, thanks!

**Comment by rafibomb** [comment]
https://github.com/zurb/foundation/commit/c56c315e1d7ef24618b82f19423be38af9199658
