### ISSUE TITLE
SCSS unable to compile after upgrading foundation to 5.5.2 via bower

### ISSUE THREAD

**Issue by chintankotadia** [zurb/foundation#6531]
After updating foundation scss to latest version 5.5.2, scss compilation have stopped working. Following are error details:  
````
Error: Invalid CSS after "...th:only screen ": expected ")", was "and (min-width:..."
        on line 491 of /var/www/aqualux/public/assets/bower/foundation/scss/foundation/components/_top-bar.scss, in `@content'
        from line 19 of /var/www/aqualux/public/assets/bower/foundation/scss/foundation/_functions.scss, in `exports'
        from line 106 of /var/www/aqualux/public/assets/bower/foundation/scss/foundation/components/_top-bar.scss
````
SASS version : Sass 3.4.10 (Selective Steve)

What am I missing over here?

Thanks! :)

**Comment by rafibomb** [comment]
What version did you update from? Compass or Libsass?

**Comment by webmastersean365** [comment]
Having same issue!  Please post a fix!

**Comment by chintankotadia** [comment]
Thank you for following up.

I have upgraded from 5.5.1 to 5.5.2 version. I am using grunt-contrib-sass for compilation i.e. normal ruby based version. Following are the details of package.json and bower.json file for your reference :

package.json
````
"node-sass": "~2.1.1",
"grunt": "~0.4.5",
"grunt-contrib-watch": "~0.6.1",
"grunt-contrib-sass": "~0.9.2",
"grunt-contrib-concat": "~0.5.1",
````
Bower.json
````
"dependencies": {
	"foundation": "zurb/bower-foundation",
	"bootstrap-sass": "twbs/bootstrap-sass",
	"jquery-validation": "jzaefferer/jquery-validation",
	"font-awesome": "components/font-awesome"
},
"devDependencies": {
	"foundation": "~5.5.1",
	"bootstrap-sass": "~3.3.4",
	"jquery-validation": "~1.13.1",
	"font-awesome": "~4.3.0"
}
````
sass.js (grunt)
````
module.exports = function(grunt) {
	grunt.config('sass', {
		options: {
			loadPath: [
				'<%=paths.bower%>foundation/scss',
				'<%=paths.bower%>bootstrap-sass/assets/stylesheets',
				'<%=paths.bower%>font-awesome/scss',
			]
		},
		dist: {
			options: {
				style: 'compressed',
				compass: true,
				cacheLocation: './storage/framework/cache/'
			},
			files: {
				'<%=paths.css%>library.css': '<%=paths.scss%>library.scss',
				'<%=paths.css%>public.css': '<%=paths.scss%>public.scss',
				'<%=paths.css%>admin.css': '<%=paths.scss%>admin.scss'
			}
		}
	});

	grunt.loadNpmTasks('grunt-contrib-sass');
};

````
Thanks!

**Comment by rafibomb** [comment]
Hi are you still working through this? 

The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
