### ISSUE TITLE
postfix border-color: true huh?

### ISSUE THREAD

**Issue by corysimmons** [zurb/foundation#6532]
`border-color: true` is invalid css. sup?

**Comment by corysimmons** [comment]
Also if `.postfix` is supposed to fix stuff then why not add `!important` to `line-height`, `padding-top`, etc.?

@necolas does this for certain utilities.

Am I missing the point of postfix?

**Comment by wallacio** [comment]
I've just noticed this myself. 

.postfix.button also used to (by default) have padding: 0

_forms.scss:408 contains @include button-size(false,false) which I don't think is correct.
It should probably be @include button-size(0,false)

Similarly (your problem) the @include prefix contains incorrect parameters.

**Comment by rafibomb** [comment]
Fixed here: https://github.com/zurb/foundation/commit/6442fa2ef0f9d4481f816182627f87941943021c
