### ISSUE TITLE
Dropdown classes not coming

### ISSUE THREAD

**Issue by fclaussen** [zurb/foundation#6535]
Hey guys, I'm on the download page and if I download the entire foundation everything works fine, of course.

But if I select only what I really want I run into a problem.

I'm selecting grid, block grid, DROPDOWN BUTTONS, Visibility and Off Canvas.

The problem is, while I'm selecting dropdown buttons it will not work. The f-dropdown class isn't being included on the css file.

**Comment by rafibomb** [comment]
The dropdown button is merely a style for a button with an arrow indicator. The styles just augment the default button style.

If you need the dropdown plugin, you'll need to import those styles as well.
