### ISSUE TITLE
Missing !default for $topbar-media-query in _top-bar.scss

### ISSUE THREAD

**Issue by ArTiSTiX** [zurb/foundation#6542]
$topbar-media-query variable is defined without !default in _top-bar.scss, making impossible to override this variable for a more complex custom value.

I don't have much time to make a PR, sorry.

line 79, should be:
```
$topbar-media-query: "#{$screen} and (min-width:#{lower-bound($topbar-breakpoint)})" !default; 
```

**Comment by rafibomb** [comment]
right you are! https://github.com/zurb/foundation/commit/193487331c903ef6241a030883ce0d9d1242fb51
