### ISSUE TITLE
Combining button group advanced styling .even-x + .stack-for-small

### ISSUE THREAD

**Issue by circlecube** [zurb/foundation#6555]
When you combine the button-group even-x and stack-for-small the button widths from the even class stick on small, so you get a very thin stacked group of buttons on small screens, since the even class sets the width and the whole stack inherits the same width. Here's a codepen with a fix: http://codepen.io/circlecube/pen/LVNxEV I can issue a pull request if needed.

**Comment by rafibomb** [comment]
Yeah, it used to be 100% width when we added the stacking feature. Makes more sense to have it that way. A PR would be great, thanks!

**Comment by circlecube** [comment]
OK Working on a PR

**Comment by zurbrandon** [comment]
The PR was merged so I'll close this. Thanks for the effort on it, you rock!!!!
