### ISSUE TITLE
Data Equalizer Stacked Set to False?

### ISSUE THREAD

**Issue by ceramicskulls** [zurb/foundation#6557]
Why would this be set to false? If we're trying to go for a responsive application, I would think this should just be set true from the get go. I realized this when I re-read the docs and saw that it's just set false.

**Comment by gpspake** [comment]
@ceramicskulls What did you do? You jumped out of irc but, I kid you not, just an hour or so after we talked earlier my coworker sent me a message in slack about the exact same issue.

**Comment by gpspake** [comment]
Hey @ceramicskulls First, thanks for all your help with this... I'm dumping this here just in case it helps anyone else make sense of it.
Interestingly... I'm finding the opposite to work... based on your original example, I created this [codepen](http://codepen.io/gpspake/pen/PqNJxb) and was only able to get it to work using: 
```$(document).foundation({  "equalizer" : {equalize_on_stack: true }  });```
I'm still not clear why that would be set to false by default but that seems to be the case.
(Another note: it also breaks if `equalizer` isn't in quotes.)

**Comment by rafibomb** [comment]
If you have various height content, and using equalizer, it would be awkward to have equalizer working when things stack.

Example - http://codepen.io/rafibomb/pen/WvwXxJ

**Comment by gpspake** [comment]
+1 @rafibomb that makes a lot of sense. Thanks for the explanation.
