### ISSUE TITLE
Bug: Clearing Lightbox Background

### ISSUE THREAD

**Issue by rocbar** [zurb/foundation#6559]
I think I may have found a bug in fdn. v5.5.0 with clearing lightbox.  By using your "Including Captions" example code listed on your web site under "docs/components/clearing.html", the lightbox does not display the caption when I do the following:  I rap the code into a div as a container with an assigned class="panel callout radius".  Result - the lightbox did not display the caption.  But if I remove only the class, it works fine.

**Comment by zurbrandon** [comment]
This seems to work with Foundation 5.5.3, the key may be that you need to use single quotes for class='panel'.
