### ISSUE TITLE
Add information about Compass installation via Bundler

### ISSUE THREAD

**Issue by peterblazejewicz** [zurb/foundation#6560]
The [Readme](https://github.com/zurb/foundation/blob/master/README.md) after discussing required steps to run documentation locally just states:
> Then just run grunt build and the documentation will be compiled:

which is incorrect, as one needs to also instal Compass via Bundler:
```shell
bundle install
```
Without this most people just get error:
```shelll
grunt build
Running "clean:dist" (clean) task
Cleaning dist/...OK
Running "sass:dist" (sass) task
Could not find compass-1.0.0 in any of the sources
Run `bundle install` to install missing gems.
```
May I do PR? 
Thanks!

**Comment by gakimball** [comment]
Go for it! :)
