### ISSUE TITLE
Js Split buttons in Firefox - not working

### ISSUE THREAD

**Issue by koronowicz** [zurb/foundation#6567]
Hello, 
I've just found that Js Split buttons are not working in Firefox in older versions and also in v. 38.0.1 - tested on OSX.

![notifications3](https://cloud.githubusercontent.com/assets/11073297/7669694/b3fc9ffa-fc81-11e4-8e37-080c9c25d9a0.gif)

**Comment by zurbrandon** [comment]
Just tested with the newest version foundation and firefox 38.0.5 adn appears to be working well. 

I'll close this as it may have been a temproaray firefox issue or we fixed it in another PR.

Let me know if you're still having trouble and reopen. Thanks!
