### ISSUE TITLE
opt-out Foundation style

### ISSUE THREAD

**Issue by pedzed** [zurb/foundation#6568]
I don't believe that there is a better way and I don't suppose this has been implemented yet: an opt-out class to prevent Foundation from styling the element.

While this may not really add anything useful to SASS users, it's useful for people who just use the compiled files and don't want to touch them (e.g. to be able to easily update). An example:

```html
<div class="progress no-foundation">
    <span class="meter"></span>
</div>
```
Thoughts?

**Comment by pedzed** [comment]
While this may not really add anything useful to SASS users, it's useful for people who just use the compiled CSS files. An example:

```html
<div class="progress no-foundation">
    <span class="meter"></span>
</div>
```

**Comment by Lynda333** [comment]
Interesting, but I typically override the CSS, when required, in my CSS but I like the concept and could see it being useful. I have had some conflicts with Foundation CSS and a few third party plugins CSS. I was able to fix it but having the `no-foundation` could be useful in those cases.

**Comment by pedzed** [comment]
> Interesting, but I typically override the CSS

Exactly. Other than renaming the classes - which may result in bad names - the only option I see is overriding.

Other than unnecessarily writing extra code to reset a certain style, the problem with overriding may for example be bad forward compatibility. 

Example:
```css
/* Foundation 0.1 */
.example {
    color: red;
}
```
You want to use `.example`, so you just reset it.
```css
/* Your reset */
.example {
    color: black;
}
```
In a newer version of Foundation, `.example` now suddenly has a `margin-bottom`.
```css
/* Foundation 0.2 */
.example {
    color: red;
    margin-bottom: 32px;
}
```
Now, if you update your Foundation version, your `.example` will get a `margin-bottom` you probably didn't want. You have to update your Foundation reset.

I also see this feature request as a better practice. One should not have to reset or rename their class.

**Comment by pedzed** [comment]
It's more difficult than this actually. An element may contain multiple classes.

```html
<div class="row">
    <div class="alert small-6 medium-6 large-3 columns">
        <!-- ... -->
    </div>
</div>
```

The question is: should Foundation ignore all classes? Should Foundation also look for each class individually?

```html
<div class="row">
    <div class="alert foundation-ignore-alert small-6 medium-6 large-3 columns">
        <!-- ... -->
    </div>
</div>
```

This might not be a good example, because you could put the `alert` class in a new `div`, but that's the best I have got for now.

I think this feature (opt-out Foundation style for the current element) should be added regardless of this comment, but this is something to think about.

**Comment by gakimball** [comment]
We provide both the Customizer and the Sass version for users who want more granular control over what CSS the framework exports. With that in mind, a feature like this, while definitely interesting, will add potentially a ton of overhead when we already have two ways to achieve the same thing.
