### ISSUE TITLE
Tweak close.fndtn.alert Trigger Timing

### ISSUE THREAD

**Issue by rdetert** [zurb/foundation#6571]
The way it is now can make it difficult to recalibrate positioning for sticky elements like the top bar. Technically, the alert hasn't been closed if it is still being displayed. 

Currently:

```
S(this).trigger('close.fndtn.alert').remove();
```
https://github.com/zurb/foundation/blob/master/js/foundation/foundation.alert.js#L29

Recommended change to something like:

```
S(this).detach().trigger('close.fndtn.alert').remove();
```

**Comment by rafibomb** [comment]
Your solution sounds good. Are you able to submit a PR for this because we'll add it in?

**Comment by rafibomb** [comment]
Since we're working on Foundation 6, we'll accept a PR on this. We'll close it here, thanks!
