### ISSUE TITLE
Reveal Modal

### ISSUE THREAD

**Issue by MrPlow254** [zurb/foundation#6572]
Failed to execute 'querySelectorAll' on 'Document': '#6e57813e7014fba7b7f412240921f760' is not a valid selector.

When a data-reveal-id starts with a number the Modal fails and does not allow for the use of any more jquery functions. I use MD5 to create the id names so the fix for me is to add a constant letter in front of the id. However the use of only numbers would be appreciated.

**Comment by rdetert** [comment]
Many programming languages don't let you start a variable name with a number. Class and ID selectors may run into issues at the browser level. Best to not use numbers and prefix it with a letter like you suggested.

**Comment by zurbrandon** [comment]
Looks like the PR #6599 has taken care of this, I'll close this but let me know if i'm  mistaken. 

Thanks!
