### ISSUE TITLE
Don't show error messages of Abide in the added reveal modal from 5.5.1 to 5.5.2 version

### ISSUE THREAD

**Issue by willingchangthernguyen** [zurb/foundation#6575]
Hi Foundation
it seems errors in reflow function when I added a modal to a panel ,then submitting the panel. The error messages in the modal don't show. i see 5.5.1 doesn't have the function , it is ok 
I have to use the old version in the case
Thanks

**Comment by rafibomb** [comment]
I think this related to https://github.com/zurb/foundation/issues/6740
If not, we can help more if you open a new issue with steps to reproduce and an code example. Thanks!

We'll close this favor of it. https://github.com/zurb/foundation/issues/6740
