### ISSUE TITLE
Trigger an event before closing the Reveal Modal?

### ISSUE THREAD

**Issue by spring-91** [zurb/foundation#6576]
I need a drawer containing the modal to fully close before the modal (content) itself  closes/becomes display:none;

Current code which closes the drawer and the reveal modal simultaneously and as a result the reveal modal is display:none; before the drawer is fully closed:
```
$(document).on('close.fndtn.reveal', '[data-reveal]', function () {
    timber.quickShopDrawer.close();
  });
```
I realise I am telling it to close the drawer on close of foundation reveal modal I just can't figure out how to do it the other way round. Or is there a way to keep the reveal modal as display:block; when its being closed?

Any help would be appreciated.

**Comment by rdetert** [comment]
Do it manually and pass in a callback to your close method.

```
timber.quickShopDrawer.close(function(){
  $("#yourModalID").foundation('reveal', 'close');
});
```

**Comment by spring-91** [comment]
Thanks for your solution, I had to edit my JS slightly for the close function but that seems to have worked.
