### ISSUE TITLE
Alternative carousel proposal - carousel using only HTML and CSS 

### ISSUE THREAD

**Issue by barseghyanartur** [zurb/foundation#6577]
It would be great to have this natively supported in Foundation 5:

- http://dancort.es/web-design/2015/05/17/how-to-make-carousel-only-html-css-no-javascript.html

**Comment by gakimball** [comment]
This is an clever approach, but it has some problems for our use case. The state of the carousel is dependent on the anchor at the URL, which means if you jump somewhere else, the carousel resets, which would be confusing for the user.

It also limits our ability to do interesting things with animation. We're going to implement our [motion library](http://foundation.zurb.com/apps/docs/#!/motion-ui) from Foundation for Apps in version 6 of this framework.

Lastly, it has a lot of boilerplate, like needing to add arrows for each individual slide, and anchor targets separate from each slide. One benefit of using a plugin is that it can eliminate boilerplate for the developer, saving them time.

Solutions like this are really good when they're hand-made for a specific project, but they don't work as well in a framework, where the solution needs to be broad enough to fit a variety of use cases.

**Comment by xtianus79** [comment]
@gakimball any call on when 6 will be realy? I can't wait!
