### ISSUE TITLE
jspm foundation import

### ISSUE THREAD

**Issue by KevinLandsberg** [zurb/foundation#6578]
Hello there,

how is it possible to import foundation.offcanvas with jspm?
Only the foundation main file seems to be exported as module.

Thanks a lot!

Best regards, k

**Comment by DominicBoettger** [comment]
Hi,

the only solution i see is that the package.json should point to the min.js file as default. After that a

import foundation from 'foundation';
will include all the needed js components.

Best regards
Dominic

**Comment by DominicBoettger** [comment]
Solved by changing the package.json
https://github.com/INSPIRATIONlabs/bower-foundation

**Comment by KevinLandsberg** [comment]
Wow, thank you Dominic!
It helped a lot! ;)

**Comment by zurbrandon** [comment]
looks like this has been all resolved. I'll close it for now, but feel free to reopen it if I'm mistaken,
