### ISSUE TITLE
Dropdown - Need a way to ignore the forced repositioning

### ISSUE THREAD

**Issue by joellord** [zurb/foundation#6581]
In my current project, I need to use align: right on my dropdowns but Foundation keeps reposition to bottom.  I need a way to tell Foundation to ignore those "missRight" flags.

**Comment by zurbrandon** [comment]
Looks like we merged in the fix for this. I'll close this, but feel free to open it up if i'm mistaken. 

Thanks!

**Comment by stevepm** [comment]
@zurbrandon Hi Brandon, can you give an example of how the ignore_repositioning option is used?
