### ISSUE TITLE
[Featured] Alert-box color, alert-box background and button border color customizable

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation#6584]
Hi guys, i like Foundation, and i like sass foundation, is very completly and easy of use.
I like that it have a settings file where we can change many options.

But,  i want, i think, that have more options for customize, for example, i want do a alert seemly to boostrap, i think that its color are more smooth, whatever, but, we can't change the alert colors, and change background color, differently of the global color, in this cases, $success-color, and put a border for the buttons. 

I think that this options will be great fore much people.

For now i put a other color for success, but this affect all objects that have this color, and isn't good.
 
This could be optionals and different for each type of alert, for don't affect the buttons color and the other objects that have the same globlal color.

Thank you.

**Comment by redmoik** [comment]
Sorry, what was your problem again?

**Comment by SalahAdDin** [comment]
Nothing, is only a suggestion.

**Comment by redmoik** [comment]
ahh I see, I thought you have problem on changing the colors of Alerts.

**Comment by SalahAdDin** [comment]
Yes, it's.

**Comment by SalahAdDin** [comment]
Well, you can see the featured that i put here:
![alert-box-color](https://cloud.githubusercontent.com/assets/5034215/8021517/4fdd5e28-0c68-11e5-9bce-0c97689614c9.png)
I have to change the alert-box-color, in boostrap is by default.
And will be great that all colors in the alert-box be the same in all css class(gracias is in black).

**Comment by zurbrandon** [comment]
We're chnaging how these are treated in Foundation 6, but won;t be able to chnage this in F5 since it would be a breaking chnage. I'll close this but feel free to comment on it further.

**Comment by SalahAdDin** [comment]
Wow, will be great have Foundation 6!
