### ISSUE TITLE
dropdown element link should work on secound touch

### ISSUE THREAD

**Issue by Lanteal** [zurb/foundation#6587]
Hi,
I'm creating some dropdown menus with the dropdown element using hover on desktop.
I was expecting that the link of the dropdown, the trigger, would work on the second touch (like in a touch dropdown menu). But it doesn't work at all. 

I think I have to add a condition in line 1890 of foundation.js

` if (!settings.is_hover || Modernizr.touch) { `

but I don't know how to get the state of the respective dropdown content.

Any hints?

Thx in advance.

PS: It's Foundation 5.5.2

**Comment by rafibomb** [comment]
You are adding an href to the dropdown trigger correct? 
The dropdown trigger is clicked to open the dropdown. If the user wants to close the dropdown, they typically click the trigger again, or tap outside of it. It may be jarring for them to be sent to another page as most users wouldn't expect that to happen.

The e.preventDefault(); would be what's your looking for to change that behavior. It's not on our roadmap to change this behavior but hopefully the explanation is helpful.
