### ISSUE TITLE
Top bar: multiple sticky navigations?

### ISSUE THREAD

**Issue by numediaweb** [zurb/foundation#6591]
When adding 2 sticky top bars in a single page, only the last navigation gets sticky but not the first one.
Is there any possibility to make all sticky bars stick one bottom of the other?

**Comment by morsecodemedia** [comment]
In your Javascript you can listen for when the sticky navs become sticky. At which point you add a style to the bottom sticky nav that overrides the `top` of the `.fixed` class and updates it to the height of your top sticky nav.

**Comment by zurbrandon** [comment]
This is more an implementation issue rather than  a Foundation bug. I'll close this as it seems there are ways to get this use case to work. 

Thanks!
