### ISSUE TITLE
Offcanvas "Back" text

### ISSUE THREAD

**Issue by ierpe** [zurb/foundation#6602]
With the the foundation Topbar, you can use "data-options" to change the "Back" text, but it is not working with the data-offcanvas.

Is it possible to achieve this ? (Without changing the text with Javascript....)

**Comment by flexbox** [comment]
Hello @ierpe 

Have you an online example ? You can try http://codepen.io/ to show us your problem.

Don't hesitate to go to the forum http://foundation.zurb.com/forum and close this issue if this problem is solved.

**Comment by zurbrandon** [comment]
The back for a multi-level off-canvas is done in the html itself, so you can change it there. I'll close this since it seems like this issue can be solved with that. If I misunderstood feel free to reopen. 

Thanks!
