### ISSUE TITLE
Interchange + Files with [ and/or ] in their name.

### ISSUE THREAD

**Issue by vita10gy** [zurb/foundation#6604]
Interchange fails when files have [ ] in their name. I suspect it's because it can't parse the difference between this and the brackets that note the different rules. 

Having it select a file like /images/slide[5].jpg winds up with the source set as .jpg

**Comment by rafibomb** [comment]
Sorry this issue got stale. It's not in our roadmap to change Interchange for this use case but we'll accept a PR on it. 

We'll close this here. Thanks!
