### ISSUE TITLE
Range slider steps don't allow for floats

### ISSUE THREAD

**Issue by thats4shaw** [zurb/foundation#6609]
In the example below, the slider defaults fine to 13.95 however the first step in the slider goes to 14 rather than 14.95.  

```
<div class="range-slider round" data-slider data-options="start: 5.95; end: 19.95; initial: 13.95; step: 1;">
    <span class="range-slider-handle" role="slider" tabindex="0"></span>
    <span class="range-slider-active-segment"></span>
</div>
```

Using just a straight number input works as I would of expected the sliders to work e.g first step is 14.95.  

```
<input type="number" min="5.95" max="19.95" step="1" value="13.95" />
```

I figured the slider should replicate the same behaviour?

**Comment by tdhartwick** [comment]
Hey there, we currently handle this with the "precision" attribute. There's no examples on the docs, but you can set it to something like this:
```
<div class="range-slider round" data-slider data-options="precision: 2; start: 5.95; end: 19.95; initial: 13.95; step: 1;">
```

**Comment by cht8687** [comment]
This is helpful. thank you @tdhartwick
