### ISSUE TITLE
It is not possible to open a link in dropdown placed in top bar when using Tor browser

### ISSUE THREAD

**Issue by Frezkky** [zurb/foundation#6611]
The title describes it pretty well. Tor browser ignores click event and does not follow the link. Would it be possible to fix the JavaScript to make it compatible with Tor?

**Comment by kevinejohn** [comment]
I noticed that the "Reveal Modal" also doesn't work in the Tor browser. Would be great to get this fixed.

**Comment by zurbrandon** [comment]
Tor isn't officially supported by Foundation, we'd be happy to accept a PR if people can fix these issues though.
