### ISSUE TITLE
Touchscreen not properly detected for IE on touchscreen devices.

### ISSUE THREAD

**Issue by ReverseBlade** [zurb/foundation#6612]
I use a surface pro 3 device, which is touch enabled, when I walk through kitchen sink with IE 11 (even with Metro version), it states my browser is not touch enabled. This is incorrect. It actually doesn't work on chrome either. I am not sure if there is a way to detect this rather than checking user agent.

**Comment by dragthor** [comment]
What is Modernizr.touch telling you?  Seriously, try **not** to sniff user agents.

**Comment by zurbrandon** [comment]
Yeah, my inkling is that this is a modernizer and Windows issue more than anything we can control. Windows has been pretty bad in reporting its touch correctly. 

Might be related to the discussions here https://github.com/modernizr/modernizr/issues/548

I'll close this as it looks like there's nothing we can do about it at the moment, but feel free to reopen if i'm misunderstanding or you have thoughts.
