### ISSUE TITLE
[MinorBug] misplaced crumb-slah 

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation#6616]
I change a / for >>, but is a lot of botton placed.
I change the top for a negative top margin for fix it, but i can't change in _settings.scss of app.scss.
![problema with raquo](https://cloud.githubusercontent.com/assets/5034215/8051491/81c2a30e-0e42-11e5-982e-adffe1225900.png)

How change this top?

**Comment by zurbrandon** [comment]
Yeah, the best way to do this would be in the css itself of that ::before element. 

This seems to be less a bug and rather an explanation, so I'll close this. Feel free to reopen it if you think I've misunderstood.

**Comment by SalahAdDin** [comment]
But will be great doesn't have to change the foundation sass file adding a sass variable for this.

**Comment by SalahAdDin** [comment]
Hi man, deleted you crumb-slash setting?
