### ISSUE TITLE
Show for parent link not working on medium

### ISSUE THREAD

**Issue by joeworkman** [zurb/foundation#6617]
Issues #6393 definitely fixed the bug where the parent link was shown in the submenu, even on desktop. However, mobile_show_parent_link now only show for small only because the `hide-for-medium-up` is hard coded into Top Bar. What if I wanted to show the mobile menu on medium? 

It would be nice if this were either an option. Or maybe there could be a way to intelligently figure out where the Top Bar mobile breakpoint is set. Then use the proper hide class based on that.

**Comment by vita10gy** [comment]
There is a change for this in the pipeline. 

#6538 

Basically, there is already a media query for top bar. The change would create visibility classes based on that breakpoint and then use them where it's hard coded in the menu to show for small only (in this case the relevant one would be hide-for-top-bar-desktop-up).

**Comment by rafibomb** [comment]
@vita10gy Thanks for the PR! I think this will solve @joeworkman use case as well. We're testing it soon for merge. We'll close this here. 

Thanks!
