### ISSUE TITLE
tfoot is missing in Visibility Class 

### ISSUE THREAD

**Issue by neonoxGER** [zurb/foundation#6619]
Hi,

when using .hide-for-small-only or .show-for-small-only or any other visibility class, it doesn't work with tfoot. At the moment, only thead and tbody are supported.
Please add support for tfoot.

**Comment by vita10gy** [comment]
If you need this asap, and you're using the scss version, you call grab _visibility.scss from my pull request there.

**Comment by neonoxGER** [comment]
thx for your mail, I updated my scss yesterday, but thanks :)

best regards
Benjamin

**Comment by rafibomb** [comment]
Closing in favor of PR - thanks!
