### ISSUE TITLE
When open modal I have no background. On close i see *only* background

### ISSUE THREAD

**Issue by gerpaick** [zurb/foundation#6620]
Hi,
I have this unusual situation. When I open a reveal modal, I see for an instance background shadow, then it disappears. When i close modal, my page becomes 'darker' and I see a background that I should have when modal is open. Cannot 'close' this background. I am using Foundattion 5.5.0
Any ideas!

**Comment by zurbrandon** [comment]
I'm unable to recreate this issue as it's working fine on the docs. I'll close this for now, but if you have a live example please post it to the Foundation Forum and I'll be happy to take a look. 

http://foundation.zurb.com/forum
