### ISSUE TITLE
Accordions open wrong tabs in documentation

### ISSUE THREAD

**Issue by LPGhatguy** [zurb/foundation#6624]
In the documentation sample for accordions, I'm getting some strange behavior: http://foundation.zurb.com/docs/components/accordion.html

When I open (or close) the first element of the second accordion on the page, the last element of the first accordion also toggles.

I'm not sure whether this is a Foundation bug or just a site with the documentation site, but nonetheless it's kind of strange.

**Comment by horans** [comment]
wrong anchor of second accordions.
**current**: #panel3a / #panel3b / #panel3c
**should be**: #panel1b / #panel2b / #panel3b

**Comment by gakimball** [comment]
Merged in #6642: 0ced176d35ed83c9d9cb235e492e9f2cacec67a7
