### ISSUE TITLE
Abide does not validate fields in inactive tabs

### ISSUE THREAD

**Issue by bpiec** [zurb/foundation#6625]
When I have a form over tabs, abide (from version 5.5.2) validates only fields on a visible tab. This was introduced probably by disabling validation for hidden fields.
Please provide a way to indicate field to be validated even if it is hidden or detect tabs and run validation for all fields that would be visible if a tab had been selected.

Demo: http://jsfiddle.net/1ukfgwqt/ (don't click the second tab before clicking Submit).

**Comment by gakimball** [comment]
We'll look into it for Foundation 6. I'll add it to the Foundation 6 wishlist issue (#4710) and our [feedback Trello board](https://trello.com/b/QBPKlQqf/foundation-for-sites).

**Comment by argordmel** [comment]
+1
