### ISSUE TITLE
Double border between input and postfix

### ISSUE THREAD

**Issue by lime** [zurb/foundation#6626]
As can be seen [in the documentation](http://foundation.zurb.com/docs/components/forms.html), `.prefix` spans / buttons only have a single border between the prefix and the input, while `.postfix` have a double border.

![screenshot of documentation](https://cloud.githubusercontent.com/assets/562204/8158285/7391732e-1364-11e5-9e47-941920de2ec3.png)

I noticed this regression when updating from Foundation 5.4 to 5.5.

**Comment by rafibomb** [comment]
Close in favor of PR
