### ISSUE TITLE
Merge multiple data-clearing blocks into one popup

### ISSUE THREAD

**Issue by TWiStErRob** [zurb/foundation#6628]
I want to split my gallery into two (or more) parts.

Here's what I have (`a`/`href` `img`/`src`|`data-caption` were removed for brevity):
```html
<ul class="clearing-thumbs small-block-grid-3" data-clearing>
    <li><a><img /></a></li>
    <li><a><img /></a></li>
    <li><a><img /></a></li>
</ul>
<div><!-- anything else --></div>
<ul class="clearing-thumbs small-block-grid-3" data-clearing>
    <li><a><img /></a></li>
    <li><a><img /></a></li>
</ul>
```
This works fine with the exception that the popups for the two lines of images cannot crossnavigate. That is: *I want to have one popup with 5 images not two popups with 3 and 2 images respectively.*

I tried to pull the `data-clearing` up, but it only resulted in images disappearing entirely. 
```html
<div data-clearing>
    <ul class="clearing-thumbs small-block-grid-3">
        <li><a><img /></a></li>
        <li><a><img /></a></li>
        <li><a><img /></a></li>
    </ul>
    <div><!-- anything else --></div>
    <ul class="clearing-thumbs small-block-grid-3">
        <li><a><img /></a></li>
        <li><a><img /></a></li>
    </ul>
</div>
```
The two `<ul>`s were replaced with `<div id="foundationClearingHolder"></div>` during runtime.

**Comment by zurbrandon** [comment]
Clearings goal is to be a very minimilast version of a lightbox. You may try something like http://sachinchoolur.github.io/lightGallery/ to help out for more advanced uses.
