### ISSUE TITLE
top bar - expand nested dropdown menu on touch devices

### ISSUE THREAD

**Issue by crazedT** [zurb/foundation#6629]
Hi,
I have a hoverable top-bar with nested sub-menus. Links to expand the sub-menus are links to other pages. On desktop everything works fine, i.e. I can navigate through all levels. On touch devices, I can only expand the first level menu (links on the top-bar), but not the nested sub-menus. I don't know if this is intentional, but shouldn't the link open only on the second touch, and the sub-menu on the first?

**Comment by rafibomb** [comment]
That odd. Yes it should and I wasn't able to replicate the issue you're describing.

Are you still experiencing this? If so please open a new issue with a link or code sample so we can see what's causing it. Thanks!
