### ISSUE TITLE
Sticky Menu Unscrollable

### ISSUE THREAD

**Issue by vita10gy** [zurb/foundation#6631]
If a sticky menu is taller than the window you can't scroll to all the items.

**Comment by zurbrandon** [comment]
We're adding this feature to a brandnew plugin for Foundation 6, but since Foundation doesn;t currently support a sticky sidebar we won;t be able to port that over. For long scrollable sections we've had great luck with Sticky Kit in the past.

**Comment by vita10gy** [comment]
This was in reference to topbar.

If the menu is sticky, and taller than the phone when open, you can't get to the bottom items.
