### ISSUE TITLE
Request: Add custom.txt file to Custom Download

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#6633]
When you download Foundation from the [download](http://foundation.zurb.com/develop/download.html) page the files include a humans.txt and robots.txt file. I would like to see one additional file, I am calling it custom.txt. 

I use the customizer to choose which components I would like to use, change colors, breakpoint, etc. Then I download the files. At a later date, I may want to update the site. The problem I have run into is remembering exactly which components I chose to use and the settings I customized. 

What I would love to see is a txt file that list the components I chose as well as any settings I customized. This could be a part of the download and then I could save this file as part of the site and refer to it when I want to update a site. 

Thank You!

**Comment by zurbrandon** [comment]
The best way to do this would be to use the Sass version of Foundation, but i'm not sure we'll add this to our css download package at the moment.
