### ISSUE TITLE
Full color variations for panels

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6634]
Instead of having 2 panel colors (`default` and `callout`) why not add all the different color-dispositions? We do this for alerts, why not panels?

`success` `warning` `danger` `info`, etc should really be panel alternatives since they are quite honestly probably the most relevant use-case for those colors/terms aside from the text itself. You show danger text inside a danger panel (for a more muted alert), etc.

**Comment by SalahAdDin** [comment]
:+1: for this.

**Comment by soraphis** [comment]
+1

**Comment by rafibomb** [comment]
We think alike. We've already added this to the next version. We're working to release it by end of summer.
