### ISSUE TITLE
Expand Button should have horizontal padding

### ISSUE THREAD

**Issue by buob** [zurb/foundation#6635]
I'd prefer to have the buttons wrap than get this:

![screen shot 2015-06-17 at 11 32 07 pm](https://cloud.githubusercontent.com/assets/986404/8223673/1bcfa0fc-1549-11e5-814a-5e3c2ac01363.png)

Thanks for all your hard work!

**Comment by rafibomb** [comment]
Hi - The text does wrap when the screen gets small enough. Can't see why the padding should be set to 0 left and right.

For now you can do this
```
.button.expand {
  padding-left: 15px;
  padding-right: 15px;
}
```

We'll add the default padding to the expand button.
