### ISSUE TITLE
Add `.no-bullet` to `<ol>`

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6637]
I use `<ol>` for semantic reasons, even though I sometimes don't want the numbers to show up visually. I feel there's no reason not to allow `.no-bullet` to work on these lists also.

**Comment by gakimball** [comment]
It's a pretty trivial change, and also lowering the specificity by a hair is never a bad idea, but I'm curious—if the ordered nature of a list is important semantically, would it not also be important visually? Or are you using other elements to display the numbers?

**Comment by ProLoser** [comment]
Comments on a blog post are ordered, but you don't display numbers. I mean there are lots of examples of objects that are ordered, but not displayed via the traditional numbers. Also, I don't know if it's appropriate to use this alongside another class that would add it's own custom numbering styling or if the other class should just do the hiding itself.

**Comment by ProLoser** [comment]
This thread is ordered.

**Comment by ProLoser** [comment]
Honestly it's not a HUGE deal, just food for thought.

**Comment by gakimball** [comment]
Oh agreed, we can implement the change no problem. And like I said, it lowers specificity so that's a good thing.

```css
ul.no-bullet {}

.no-bullet {}
```

**Comment by ProLoser** [comment]
You guys are surprisingly far more receptive than the bootstrap team. Although I still at times wished we had some features bootstrap has.

**Comment by gakimball** [comment]
It's a tricky line to walk, because we want to be the more minimal framework (a scaffold more than a UI kit), and often that means saying "no" to potentially interesting features.

**Comment by ProLoser** [comment]
Yeah... I think you guys have waaay too many widgets to be considered a scaffold. Merely having javascript is more than a scaffold.

**Comment by gakimball** [comment]
Hm, maybe scaffold isn't the right word, but we do consider it a prototyping tool, along with being production-ready.

Either way, I updated the `.no-bullet` class to be generic.
