### ISSUE TITLE
XSS vulnerability in Clearing

### ISSUE THREAD

**Issue by mayakokits** [zurb/foundation#6639]
Clearing uses jQuery's `.html()` method to display the caption, which introduces XSS vulnerability.
even my safely encoded `data-caption="Cross Site Scripting Test&quot;&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;http://www.naked-design.at/js/xss-test.js&quot;&gt;&lt;/script&gt;"` got executed.

i fixed this locally and i'll submit a pull request in a minute.

**Comment by mayakokits** [comment]
hey, this was my first fix on github! :-)
somehow the commit ended up in issue #6640, sorry!

**Comment by zurbrandon** [comment]
Awesome! Thanks Keep em' coming :)
