### ISSUE TITLE
proposal: enhancement to mobile menu

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6647]
i noticed that foundation removes fixed positioning from the nav wrapper when the menu is toggled.

instead adding this css to the `ul.right` looks much better for a mobile menu:

```
height: calc(100vh - 45px);
background: #333 none repeat scroll 0% 0%;
overflow: hidden;
overflow-y: scroll;
overflow-x: hidden;
```

**Comment by zurbrandon** [comment]
Can you be more specific as to where you're suggesting this change? The height: calc(100vh - 45px); seems scary as it's a magic number that seems like it would vary based on other CSS.

**Comment by rafibomb** [comment]
Thanks for the feedback! We're working on getting Foundation 6 released soon and it has a different menu configuration. 

We're still going to push a couple small updates to Foundation 5. If you're able to submit a PR and include a reason how this will solve an existing issue, we'd love to add it in. Thanks!
