### ISSUE TITLE
Foundation 6: component mixin feedback

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation#6648]
Hello friends,

In this thread we'd like to get your feedback on how we use Sass in Foundation, specifically mixins.

Starting with Foundation 4 we went *mixin crazy* with components. Instead of writing components in plain CSS, we built a series of mixins for each one, and then applied those mixins to classes. We continued this approach for Foundation 5, and Sass will remain a big element of Foundation 6.

*However!* We have a feeling that our use of Sass has gotten away from us. As we train new designers and developers in Sass, we find that it can create bad habits. The most obvious one is nesting: Sass encourages you to do deep nesting to match the hierarchy of your HTML. For a framework, this is a bad thing, as we want to keep specificity low. That's why for Foundation 6 we're better scrutinizing the CSS output of our Sass.

**We'd like the community's feedback on the utility of component mixins.** To determine their utility, we need to figure out *why* people use them. Why do people use mixins?

### Benefits

**Semantics.** This is the big one, but you could argue it doesn't apply to everything. `medium-6 large-3 columns`? Okay, yeah, that's not semantic. And grid elements can easily have upwards of five classes, so being able to condense all that logic into one class with a mixin is very useful. In Foundation 6 we've made grid mixins even more robust, so we can be more competitive with the likes of Neat and Susy.

Now what about the rest of the components? It would be harder to argue that they're unsemantic. `button`, `menu-bar`, `label`, etc. are all fairly semantic. They describe what the component *is*, not what it *looks like*. Modifier classes venture into the unsemantic, like the sizing classes for buttons, or alignment classes, but the core classes themselves are semantic.

With that in mind, what is the utility of the mixins for those components? `.button` is a semantic class, so how does being able to replace the class using `@include button;` improve how developers use the framework?

This hits on a second, but possibly far less used, utility of Sass mixins: the ability to change class names.

**Class naming.** With the mixins, you can use our components within your own class structure. We're in the process of refining ZURB's own internal coding style, which we'll share with our developers, but it doesn't follow any popular style guide.

So this is the other main utility of Sass mixins, but we need to know: **do people actually use this?** We use Foundation every day here at ZURB, and in our own client work we find ourselves using mixins for the grid quite a bit, but less so for other components. We need to hear from our community if this is a feature worth investing in.

### Problems

**Sass mixins make our codebase complex and potentially messy.** You can find examples in the [existing codebase](https://github.com/zurb/foundation/blob/master/scss/foundation/components/_icon-bar.scss) of complicated and messy Sass. When is something a mixin? Which elements do you make parameters? When do you calculate a value automatically or let the user define it?

Also consider complicated components like Orbit, which has a container, slides, captions, arrows, and navigation dots. If we did things right, *every* class needs a mixin. And some of them have absurdly tiny mixins. For example, in Foundation 6, the Orbit container is just *one* line of CSS. So do we write a whole `orbit-container()` mixins just for that one line of CSS?

This also hints at another issue that can crop up when using Sass and creating a framework: too much abstraction. We're already cutting back on mixins in some places. A mixin is an abstraction, but it needs to be a *useful* abstraction to make it worth the developer's time to learn how it works.

### Summary

**What we want to know is if component mixins are useful. Do you use them? Which components do you use them with?** Here's a summary of our thinking on the matter:

- Mixins allow us to write semantic markup, but it's possible that we over-extended the concept into areas that are already semantic.
- Mixins allow developers to throw out our class names and write their own, but that's a time-consming process that requires thorough understanding of how our mixins work. It also requires our mixins to be well-written and well-organized, which is a challenge.
- Further, it's likely that a very small portion of our developers are actually using component mixins for this purpose.
- Sass makes our codebase complicated and more abstract for developers. Cutting back on the use of Sass where we can reduces the amount of time developers spend learning the framework, allowing them to spend more time actually using the framework.

**Comment by fredrivett** [comment]
First off, let me day I'm a big fan of Foundation and use it on pretty much all my projects.

That said, the nesting in Foundation is a real sore point for me, often leading to chaining classes to ridiculous levels to override specificity. I'm really glad this is being considered as a key factor in version 6.

In terms of mixins, we use these for a few components. At my day job we use namespacing and BEM which has led us to creating our own button classes. As a quick win we have used the button mixin but it's quite a simple mixin so this is on our list of things to refactor to our own fully custom code.

Another big one we use regularly is the block grid. It's great to be able to create custom block grid layouts and use media queries to set the number of list items wide the grid should be at each breakpoint.

These are the main mixins I can think of that we're using right now, but will have a think if there's any others over forgotten.

**Comment by rafibomb** [comment]
@fredrivett We're with you on the specificity front. We're really looking closely at our CSS output to ensure our Sass is written as cleanly as possible. 

Also, good feedback on the mixins. Thanks!

**Comment by gakimball** [comment]
@fredrivett The grid, block grid, and buttons are really good examples of where mixins can be used well. The grid and block grid are very verbose components, so abstracting away all those classes using mixins is real nice. Me personally, I don't always use the semantic method for the grid, but I *always* use block grid mixins, because those classes are so wordy.

And buttons are a good example because, even though they're a component, they're a *simple* component with a lot of configuration. So it's easy to make mixins for those elementary components: the base, the size, the style, etc.

It gets weird with more complicated components. Like I said, Orbit has like ten UI elements, and some of those elements only have a few lines of CSS, making the mixin feel like an unnecessary abstraction. It's not necessarily solving a problem for a developer faster, it's just there in case you don't like the class name `.orbit-container`.

**Comment by r3wt** [comment]
i hate `sass` and `less`. i just write the plain ole shit the browser interprets.

**Comment by SalahAdDin** [comment]
@gakimball i think that the colors are a lot of ugly, but, suck now, only the color, maybe you can change it, a color seems bootstrap button's colors.

**Comment by rafibomb** [comment]
@r3wt and @SalahAdDin These comments are off topic and not helpful to conversation we're having here. We do appreciate critical feedback, this is not the place. We'll remove them here.

**Comment by SalahAdDin** [comment]
Yes man, i'm sorry, I tried to correct the other user, I found it very rude comment.

**Comment by ProLoser** [comment]
At least allow toggling of classes for every group, if not every variation.

**Comment by michaelBenin** [comment]
Can we get mixins for visibility? 

http://foundation.zurb.com/forum/posts/633-visibility-sass-mixin

**Comment by gakimball** [comment]
@michaelBenin Yep, we've already implemented these in 6!

**Comment by zurbrandon** [comment]
Thanks for the feedback, all! We've looked it over and are really rocking away at getting Foundation 6 out very soon!
