### ISSUE TITLE
Foundation 6: RTL feedback

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation#6649]
Hello friends,

In this thread we'd like to get feedback on how we implement RTL support.

We've had RTL support for a few versions now, which we do through Sass variables.

```scss
.column {
  // Is left on LTR
  // Is right on RTL
  float: $default-float;
}
```

For Foundation 6, we've looked into using [rtlcss](https://github.com/MohammadYounes/rtlcss) to automate this process. rtlcss takes a CSS file and flips properties and class names for you. Special CSS comments allow you to fine-tune the output of the processor.

In our initial testing, rtlcss works really well, and could be a viable way to develop and distribute RTL versions of our CSS.

However, we ran into one big snag, which is how rtlcss interacts with the developers' own CSS.

Imagine you're using the Sass version of Foundation. rtlcss converts Foundation's LTR CSS into RTL for you. But what about *your* custom CSS? That's being bundled in there as well, because it's being distributed as one file. And if you're writing CSS for a website that is only read in a right-to-left language, it's going to flip your code back to LTR in the process.

Now, if you're writing CSS for a bilingual website, this approach works great, because you can code LTR, and then convert your CSS to RTL for a separate stylesheet.

So we have two options: the manual approach and the automatic approach.

**Manual approach:** We use Sass to create RTL code *before* the CSS is processed.

If we do this approach, we might find a way to make the RTL bits less wordy. Maybe a universal "flip" function that converts any value to an RTL equivalent?

```scss
.element {
  float: flip(left);
  transform: translateX(flip(100%));
}
```

This approach is more portable, because no post-processing is required, but it takes more effort to maintain.

**Automatic approach:** We use rtlcss to create RTL code **after** CSS is processed.

This approach requires an extra built step for RTL authors, and could create problems for users who are writing RTL-only code. But it makes our codebase cleaner by stripping out the vast majority of the RTL hooks.

**What we'd like to know is which approach our RTL developers would prefer.**

**Comment by apolun** [comment]
By using automatic approach we should think about LTR first design and It may reduce the quality of design also Layouts that look good in LTR not means that it looks good also in RTL if we flip everything. Also we cant go too far with sass as before
for example thinking about font family which I want to choose specific fonts for RTL or LTR pages.
If my css auto generated then I can't use sass as well. May be I don't know the best way of doing this or size of headers and things that we specify in sass variables.

**Comment by mosid** [comment]
I totally vote for the manual approach , Foundation is all about not getting in your way to do things.
and as @apolun said : 
"Layouts that look good in LTR not means that it looks good in RTL if we flip everything." 
And this way seems more controllable than the automatic approach.
My 0.02

**Comment by zurbrandon** [comment]
Thanks for the feedback, all! We've looked it over and are really rocking away at getting Foundation 6 out very soon!
