### ISSUE TITLE
5.5.0 changed abide validation timeout behaviour

### ISSUE THREAD

**Issue by AngeloG** [zurb/foundation#6651]
Since 5.4.7, abide validation had a timeout of (by default) 0, but this was changed in 5.5.0 to some other value. In the changelog (and the code), I can't seem to find any note on this change, except [this commit](https://github.com/zurb/foundation/commit/674fc9ecbfd303cff1f8e7b0e55cac5cb538336a).

Was this on purpose, or was it accidental? It seems that the `timeout` property has always been `1000` [since 5.0.3](https://github.com/zurb/foundation/commit/b5e9d05311544881e11af710bdd85113a9b7857b#diff-0fecfcb7f50be59e4f71ef75a2d8be41R14).

To get the old behaviour back, I have to manually set the timeout to 0 now:

      $(document).foundation({
        abide: {
          live_validate: false,
          timeout: 0
        }
      });

Am I writing this issue with a potential [xkcd 1172](https://xkcd.com/1172/) reference?

**Comment by rafibomb** [comment]
According to this file - foundation/js/foundation/foundation.abide.js I looks like it's now commented and 1000 by default. You can access this setting with data-options or in the JS.

**Comment by AngeloG** [comment]
So this was an intended change and my workaround for it is the way to go?
