### ISSUE TITLE
Vertical Tabs Enhancement: Display content below active tab while in mobile view

### ISSUE THREAD

**Issue by mmikitka** [zurb/foundation#6653]
If one views a set of [vertical tabs](http://foundation.zurb.com/docs/components/tabs.html) in mobile, the active tab content is displayed under the last tab title, and if the tab titles occupy the majority of screen real estate, one needs to: scroll down to view the content, scroll up to click another tab, scroll down to view the content, etc.

I recommend displaying the active tab content below the active tab title. Furthermore, it would be nice to close the active tab content by clicking the corresponding title, in which case all content would be closed.

I'm essentially advocating for a [jQuery-ui-like accordion](https://jqueryui.com/accordion/#collapsible)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by zurbrandon** [comment]
We've experimented with this in the past, but found it much too opinionated to be the default action of tabs to then turn into an accordion on mobile. There are plugins that do this and when thats the desired action we've usually opted for swapping for those. 

This may help: https://github.com/samsono/Easy-Responsive-Tabs-to-Accordion
