### ISSUE TITLE
inline-lists margin

### ISSUE THREAD

**Issue by andrewcroce** [zurb/foundation#6654]
In 5.5.2 it looks like the left negative margin on inline-lists is being overridden erroneously. The margin-left is shortly followed by a shorthand margin setting left to 'auto'. Placing the shorthand margin before the left and right rules fixes it.

Looks like this might have been fixed in the latest commit, will this be released sometime soon?

**Comment by jnemeth** [comment]
Looks like that ones already been fixed in 5.5.3 (tentatively scheduled to go out July 30th).
