### ISSUE TITLE
Foundation 5 Accessible Tabs keyboard navigation problem

### ISSUE THREAD

**Issue by xinspire** [zurb/foundation#6663]
Browser version: Chrome 43.0.2357.124
jQuery: 2.1.0
Foundation version: 5.5.2

#### Issue ####

When a page first loads, and a tab receives the tabindex focus rectangle, the arrow keys do not work to select adjacent tabs.

Minimal example here: http://jsfiddle.net/j2r158hx/
The HTML is copied directly from the Foundation docs here, under the heading Accessibility: http://foundation.zurb.com/docs/components/tabs.html.

To test, click in the whitespace area in the Result panel, press `Tab`, which should select the first tab.  If you press the `right` arrow, nothing will happen.  If you press `Tab` or `Enter` so that it "loads" the first tab (even though it's already displaying it), then pressing `right` will move the focus rectangle to the right.

Refresh the JSfiddle page to reset state.  Then, instead of pressing `Tab` after clicking in the Result panel, click `Tab 3` instead.  Now `Tab 3` has the focus rectangle.  Pressing an arrow key will direct the focus rectangle to an adjacent tab, but the focus rectangle is then stuck there.

Only after pressing `Tab` or `Enter` to load the tab content do the arrow keys move again, but this time, it only moves to the adjacent tabs that have been previously selected.

**Comment by salzz4u** [comment]
facing a similar issue, tabs nav seems to work with arrow keys to move from tab1 to 2 etc
however, tabbing into the content area does not work

**Comment by rafibomb** [comment]
Yeah, this was tricky because we added some accessibly in Foundation 5 where we couldn't make breaking changes to the code. This is already addressed in the Foundation for Sites 6 version. If you have a non breaking solution for it now, we;d love to see it.
