### ISSUE TITLE
Publish Foundation to NPM Registry

### ISSUE THREAD

**Issue by mingfang** [zurb/foundation#6665]
We don't use bower but rather npm for all our modules.
We're currently using an "unofficial" npm module containing Foundation.
Please publish to npm.

**Comment by savelbr** [comment]
+1 

For some projects Foundation is the only reason I still need Bower as well as npm, so being able to load Foundation through npm would reduce complexity.

**Comment by gakimball** [comment]
As of 5.5.2 we have an npm package, `foundation-sites`.
