### ISSUE TITLE
Interchange recursion/crash issue

### ISSUE THREAD

**Issue by rphelan** [zurb/foundation#6666]
A CMS error on a project I'm working on caused the following markup to be written to the page: 

 ```<div data-interchange="[, (default)]"></div>```

Interchange interprets this as a url that is an empty string and proceeds to ajax load the current page into itself (recursively) which quickly crashes the browser.

I realize its not technically a bug since the behavior resulted from providing a bad url but it seems like an easy mistake to make (in a content managed context) and is very difficult/frustrating to diagnose if it happens.  I can't think of a reason you'd want to ever want to use an empty string as a url in interchange so a sanity check would be nice.  I'd be happy to submit a PR if you're on board.

**Comment by zurbchris** [comment]
It's been awhile since this was posted, and for that I apologize. It seems as those this has been addressed between then and now, as I cannot reproduce the issue. If you are still having trouble with this, feel free to reopen.
