### ISSUE TITLE
Drop use of `rem`

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6667]
It is seriously causing me so many headaches and issues. In chrome, rem values are interpolated into floating pixel values, which causes extremely erratic behavior when containers sometimes ignore decimal points while the elements with the dimension values explicitly set don't. So certain things happen like this:
```css
@media only screen and (max-width: 40em)
.tabs > .tab-title > a {
  padding: 0.2rem .5rem;
}
```
which interpolates to:
```css
padding-bottom: 3.20000004768372px;
padding-left: 8px;
padding-right: 8px;
padding-top: 3.20000004768372px;
height: 32.375px;
```
however the parent element's value dimensions become interpolated to:
```css
height: 32px;
```

I'm seeing borders appearing or disappearing all over the place, especially in tabs where the tabs are butted up against another element. I have never seen use of `rem` before foundation and have been finding it cryptic to use and resulting in difficult to estimate values.

I could provide screenshots / fiddles if absolutely necessary but it's 4am so I'm going to bed.

**Comment by xtianus79** [comment]
Do you understand rem?

**Comment by ProLoser** [comment]
Blah the bug was the result of some use of `rem` my coworkers implemented after copying foundation for defining dimensions of elements.
