### ISSUE TITLE
Button mixin is extremely unflexible

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6668]
I don't get why the side padding are hard-coded to 2x the padding passed to the `button-size()` mixin.

I also wish it was possible to disable just the base button classes without disabling ALL variations.

I also find it frustrating to customize the buttons if I want to do something that doesn't look extremely close to the predefined styles of the default buttons (for instance, buttons that only have border strokes and text strokes, but no background).

Even things like making all buttons have border-radius by default is a little annoying as the `_variables.scss` that control default border-radius aren't actually the default border radius for buttons, they are in fact the `.radius` modifier class border-radius, which isn't really a 'default' since there is no other variations of this, and `.round` has it's own variable.
In fact, it doesn't even make sense really to encourage the use of a `.round` and `.radius` mixin since this is purely stylistic (where as all other classes are function-based, such as `.alert` and `.success`) and there isn't a reason why you should be doing bordered/non-bordered variations of buttons within the same app. You would more often than not change the styles of different types of widgets globally, such as dropdowns vs buttons vs labels.
Lets say someone wants to make all buttons in their app rounded, the existing classes would then encourage the usage of superfluous stylistic-only classes throughout the entire app.

**Comment by gakimball** [comment]
We hear you! The fact that border radius variables in the Sass only affect components with a `.radius` class is totally baffling. This may prove unpopular, but we're dropping `.radius` and `.round` entirely from Foundation 6. We don't consider them to be useful presentational classes.

If you look at the Sass for [buttons in Foundation for Apps](https://github.com/zurb/foundation-apps/blob/master/scss/components/_button.scss), you can get an idea of how we're iterating on buttons.

The ideal is to have as little CSS as possible on each component, so as to encourage developers to write their own CSS and not feel like they need to leave the framework as-is. We've found some developers only style Foundation components to the extent that the settings variables allow them, which is not our intention.

> I also wish it was possible to disable just the base button classes without disabling ALL variations.

We've been thinking about this a lot recently. Should we give developers more control over the CSS output of each component? Right now it's a hard toggle—either you get everything or you don't. We could allow developers to fine-tune the CSS they get from a component. But how much control do you get? Can you disable every coloring class, or can you disable `.success`, `.alert`, and `.warning` individually? Balancing developer flexibility with complexity is tricky.

If you have more opinions on this, we're trying to get feedback on our component mixins (see #6648) and we'd love your input.
