### ISSUE TITLE
.label:empty { display: none; }

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6671]
Bootstrap does this. Makes life easier.

**Comment by rafibomb** [comment]
Sounds good, can you submit a PR for this so we can add it in?

**Comment by rafibomb** [comment]
We're not seeing a use case for this. Would love some examples of how this would help. We'll close here for now.

**Comment by ProLoser** [comment]
Why would you ever show an empty label? Especially if these are used as number badges inside another button or nav
