### ISSUE TITLE
"centered"-class for medium-range (Grid)

### ISSUE THREAD

**Issue by KevinLandsberg** [zurb/foundation#6672]
Hello guys,

i found a small-centered class and a large-centered class, is there a possibility to show content centered ONLY inside the medium-range? I don't want the content to be centered on small or large.

**Comment by gakimball** [comment]
There are `uncentered` classes as well, which will achieve this effect:

```html
<div class="row">
  <div class="small-8 medium-centered large-uncentered columns"></div>
</div>
