### ISSUE TITLE
Remember Alert Close

### ISSUE THREAD

**Issue by sekjal** [zurb/foundation#6673]
It would be great if we could set an alert to remember whether a user has closed it already, much like Joyride can.  This would help in those cases where alerts show on particular pages of one's site that users navigate to again and again, but the message doesn't change between visits.  Example:  using an alert to let users know a particular service will be unavailable next week.

**Comment by rafibomb** [comment]
This kind of thing is usually handled by the back-end system you are using. Like Rails already takes care of it. Alternatively, you can use localstorage or a cookie to set this interaction. It's not going to be part of the alert plugin itself since there are so many ways to handle this.
