### ISSUE TITLE
Possible to do a rowspan on table with foundation?

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6681]
I'm trying with no success to create a table as pictured:

![img](http://puu.sh/iPxcj/cd889d3855.jpg)

Any ideas how to do it?

**Comment by gakimball** [comment]
Could you post your code? We shouldn't be doing anything too weird in our table CSS, as it's mostly just stylistic.

**Comment by r3wt** [comment]
@gakimball false alarm; i tried to stack 3 `tr`'s inside of 1 `thead`, with the top row being 100% width. `colspan="100%"` did the trick.
