### ISSUE TITLE
Dropdown fails to work correctly when right to left css is used

### ISSUE THREAD

**Issue by Behzad63** [zurb/foundation#6683]
Hi,
When using foundation for right to left languages, the dropdown fails to operate correctly.
for example the following code:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" class="no-js" lang="fa" dir="rtl">
<head>
    <title></title>
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<link rel="stylesheet" href="css/foundation.css" />		
	<script src="js/vendor/modernizr.js"></script>
	
</head>
<body>
<div class="row">
	<div class="column small-12" style="direction:ltr" >
		<div style="float:right">
			<a href="#" data-dropdown="hover1">Language</a>
			<ul id="hover1" class="f-dropdown" data-dropdown-content>
				<li><a href="#">فارسی</a></li>
				<li><a href="#">English</a></li>
				<li><a href="#">العربیه</a></li>
			</ul>
		</div>
	</div>		
</div>	

	<script src="js/vendor/jquery.js"></script>
	<script src="js/vendor/fastclick.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
		$(document).foundation();
	</script>
</body>
</html>
```
The result is like this:
![er01](https://cloud.githubusercontent.com/assets/7345919/8540674/1ff38e1a-249d-11e5-8b72-2685337fce9e.png)

and for left floated there is an ugly horizontal scrollbar like this:
![er02](https://cloud.githubusercontent.com/assets/7345919/8540694/454b620a-249d-11e5-8897-f8876d8b2f2a.png)

[Zurb Docs] (http://foundation.zurb.com/docs/components/rtl.html) mentions that for javascript components we need to ad dir="rtl" to html tag to prevent problems, when I remove this attribute from the html element it works fine but I'm worried about causing errors for other javascript components.
Looks like a bug in dropdown!
Am I missing something?!
I really appreciate your attention.

**Comment by Behzad63** [comment]
After a lot of struggling I finally managed to solve it. I don't like to change the core  because upgrading to newer versions will be annoying. But as a temporary solution it did the trick for me.
I commented the following lines from foundation.dropdown.js (lines 350 - 352): 
```javascript
if (self.rtl) {
    return {left : p.left - this.outerWidth() + t.outerWidth(), top : p.top + t.outerHeight()};
}
```

and for fixing the small triangle in dropdown "right:initial" was added to the following lines in foundation.dropdown.js (lines 408 - 418) : 
```javascript
var sel_before = '.f-dropdown.open:before',
          sel_after  = '.f-dropdown.open:after',
          css_before = 'left: ' + pip_offset_base + 'px;right:initial',
          css_after = 'left: ' + (pip_offset_base - 1) + 'px;right:initial';

      if (position.missRight == true) {
        pip_offset_base = dropdown.outerWidth() - 23;
        sel_before = '.f-dropdown.open:before',
        sel_after  = '.f-dropdown.open:after',
        css_before = 'left: ' + pip_offset_base + 'px;right:initial',
        css_after = 'left: ' + (pip_offset_base - 1) + 'px;right:initial';
      }
```

I wish I could find a better approach.
I'm really enthusiastic about your ideas for this problem.

**Comment by msdm** [comment]
@Behzad63, check out my proposed pull request for this issue (#6678). Hope it helps.

**Comment by Behzad63** [comment]
@msdm , Thank you! 
How can I merge it with my local repo?

**Comment by msdm** [comment]
@Behzad63, it has not been yet approved and merged to main repository and you should do it manually. I recommend you manually download and replace the changed files but if you are using git, you just need to clone my forked repository (https://github.com/msdm/foundation). If you are using composer, you can also use vcs repository config: https://getcomposer.org/doc/05-repositories.md#vcs
Please let me know if it works as desired.

**Comment by Behzad63** [comment]
@msdm, it works fine! good job!
This is a serious bug. The reason I chose Foundation was it's out of the box support for right to left languages but it seems RTL components are not well tested in this framework.

**Comment by msdm** [comment]
@Behzad63, good to know! thanks for your feedback.
