### ISSUE TITLE
Horizontal tabs in vertical tabs does not work

### ISSUE THREAD

**Issue by scorchio** [zurb/foundation#6684]
Hello --

We've just found out that embedding horizontal tabs in vertical tabs doesn't work. Please see the following CodePen, which triggers the issue:
http://codepen.io/scorchio/pen/YXavqr/

Kind regards,
Zoltán

**Comment by rafibomb** [comment]
Thanks for the note. We're not planning to write CSS for this use case as it seems like a custom component. A PR would be ok for the CSS styling. The JS works fine. We'll close this, thanks!
