### ISSUE TITLE
Reveal Modal: multiple_opened doesn't handle ordering properly

### ISSUE THREAD

**Issue by brianlenz** [zurb/foundation#6690]
We are trying to use multiple_opened with Reveal Modal, but Foundation doesn't properly handle the order in which the modals are opened. The issue lies in how Foundation.libs.reveal.open() and Foundation.libs.reveal.close() identify open modals. Specifically, they both use code like:

```javascript
var open_modal = self.S('[' + self.attr_name() + '].open');
```
and
```javascript
open_modals = this.S('[' + this.attr_name() + '].open')
```

The issue with this approach is that the jQuery object will return the modals in *document order*, which is not necessarily the order in which the modals were opened. Instead, open should be pushing the modals onto a stack and close should be popping the modals off of the stack (i.e. a basic window manager). This way, when close brings the next modal to_front, it will be the proper modal. Currently, it's doing:

```javascript
self.to_front($($.makeArray(open_modals).reverse()[1]));
```
Again, that relies on the document-order of the elements, and therefore will only ever be correct if you *only* open the modals in document order. Open them in any other order, and you'll have issues with the modals not being brought to the front properly.

**Comment by jeanieshark** [comment]
Fixed with the merge #6691
