### ISSUE TITLE
Disable components

### ISSUE THREAD

**Issue by dawidk92** [zurb/foundation#6693]
Right now when I comment import of buttons component it is still importing for example by top-bar component. It will be nice if you could comment out these components that you don't need in one place and make sure that they aren't including anymore.

![2015-07-10_1915](https://cloud.githubusercontent.com/assets/7023167/8624430/131b036a-2738-11e5-99c8-715531635b85.png)

**Comment by gakimball** [comment]
Each component has a settings variable that turns off its CSS output. For example, top bar's looks like this:

```scss
// Defaults to "true"
// $include-html-top-bar-classes: $include-html-classes;
```

We're going to try a simpler approach in Foundation 6 where the CSS export of each component is a mixin. The idea is explained in more detail [here](https://github.com/zurb/foundation/issues/6196#issuecomment-76801232)—if you have any feedback on how the framework exports CSS, we'd love to hear it.

**Comment by dawidk92** [comment]
It's very problematic because I'm using bower and I can't touch core code

**Comment by gakimball** [comment]
The settings file is placed along with your other Sass files, not with the framework code. (There is one in the framework code, but it's just for reference.) Our CLI generates one for you automatically when it builds new projects, but if you're integrating Foundation into your own stack, you can grab a copy [here](https://github.com/zurb/foundation/blob/master/scss/foundation/_settings.scss).

**Comment by dawidk92** [comment]
So if I want to disable e.g. buttons component I should comment out @import "foundation/components/buttons" and set $include-html-button-classes to false, right?

**Comment by gakimball** [comment]
@dawidk92 Sorry for the late response, but yes, that's the way to do it. For most components, just removing the `@import` would be enough, but some other components import buttons (button groups, forms, and one or two more), so setting `$include-html-button-classes` to `false` will prevent the CSS from being output.
