### ISSUE TITLE
Uneven button padding

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6694]
I found this line: https://github.com/zurb/foundation/blame/master/scss/foundation/components/_buttons.scss#L106

I was just wondering, WHY is the top and bottom padding not identical? What's the point of this? I'm getting weird calculations and button heights.

If I override the mixin's button padding in css, I generally just do `padding: $padding` or something, but this started creating a 1px inconsistency between buttons that had been overridden and those that hadn't. So I did some digging and realized that it's foundation who's making an uneven style. Why?

I have to do this garbage: `padding: $padding ($padding * 2) ($padding + rem-calc(1)) ($padding * 2);` if I want to override the padding yet have buttons be consistent now?

**Comment by amencarini** [comment]
I'm having some problem too with the padding. Had to remove it.
http://stackoverflow.com/questions/31905238/postfix-button-text-not-formatted-well/31905526

**Comment by tdhartwick** [comment]
Hey ProLoser,

The reason we have different top and bottom padding is visually center the text within the button. This should work great for out-of-the-box buttons and most, but we understand that people want to control it too! You still have full control of the Sass, and can remove "+  rem-calc(1)" from line 118 of "_buttons.scss."

Foundation 6 will also have a $button-padding variable that will give you full control over the button's padding.
