### ISSUE TITLE
Overwriting with Global Variables

### ISSUE THREAD

**Issue by atrivisano** [zurb/foundation#6697]
### Issue:
- Some variables in settings.scss do not overwrite the core settings.

### Example:
- `$row-width` does not overwrite the core `$row-width`, probably because of the `!default` in core.

**Comment by ZachPerkitny** [comment]
Do you have compass running ? If not, the css won't be changed; the browser doesn't understand scss.

**Comment by atrivisano** [comment]
I am running Gulp as the processor for Sass.

**Comment by zurbrandon** [comment]
Just tested row-width and it overrides fine on my machine. I'll close this but feel free to reopen if it's still bugging and we can try and resolve.
