### ISSUE TITLE
Pagination not center work

### ISSUE THREAD

**Issue by languorous001** [zurb/foundation#6706]
This my code.
![code1](https://cloud.githubusercontent.com/assets/13363683/8720150/1faddccc-2bdb-11e5-961a-c6e716130247.png)

This view.
![view1](https://cloud.githubusercontent.com/assets/13363683/8720091/c5e07cc2-2bda-11e5-8275-4014e88101fe.png)

I'm rookie. I need recommend for edit css, Thank you.

**Comment by gakimball** [comment]
Is the second screenshot the effect you want to achieve, or is it a bug?

**Comment by languorous001** [comment]
second screenshot is wrong.
i need layout row ( Previous 1 2 3 Next ) .

**Comment by JamesDullaghan** [comment]
@languorous001 The user-agent stylesheet applies `display: block;` to `<div>` elements which you have wrapping all of your `<li>`'s causing them to stack on each other. Try removing those `<div>`'s and the pagination should display correctly.

**Comment by gakimball** [comment]
@JamesDullaghan I was actually wondering about that.

You should be able to apply `ng-if` and `ng-repeat` to the `<li>` elements directly, and that will fix the issue.

**Comment by languorous001** [comment]
I make 

```
.pagination-centered ul.pagination div {
      display: inline;
}
```

OK, complete to fix it :'))

Thank @JamesDullaghan and @gakimball very much.

**Comment by gakimball** [comment]
Awesome, glad we could help!
