### ISSUE TITLE
Accordion class margin

### ISSUE THREAD

**Issue by alamowo** [zurb/foundation#6707]
The `.accordion` class sets `margin-bottom: 0`, but wouldn't `margin-left: 0` in addition or `margin: 0` be the better solution? Because you don't want to indent your accordion by default?

**Comment by jnemeth** [comment]
Good point, this must have gotten mixed in with a previous pull request we didn't catch.  We usually do try to reset all the browser stuff.  Please submit a PR if you can  :+1:

**Comment by rafibomb** [comment]
Looks like this issue ended up being fixed in another commit: 8d0494f
