### ISSUE TITLE
dropdown content in topbar behaves oddly

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6710]
![img](http://puu.sh/j40sp/f7c20290da.png)

i expected it to be floating left, but instead it just dangles off the side of the page for some strange reason.

also, the form overflows the content.

**Comment by r3wt** [comment]
GOt that fixed, now when focusing to an input the dropdown hides. so odd

**Comment by lordfpx** [comment]
Hi, I've got the same issue regarding dropdown position :-/.
Could you share how you solved that please?

Thanks a lot!

**Comment by r3wt** [comment]
@lordfpx i ended up ditching foundation and writing my own framework using foundations grid. best decision ever.
