### ISSUE TITLE
Dropdown don't close when you click again

### ISSUE THREAD

**Issue by chrissmejia** [zurb/foundation#6711]
Hi, I have a problem, when I click a top-menu dropdown open as expected, but when I click again it just stay open.

This problem is at latest for:
- Chrome 43.0.2357.134 (64-bit)
- Firefox 39.0
using Elementary OS Freya

Foundation was installed using standard ruby compass sass procedure on your web page a week ago.

This is a video showing the problem and a possible solution:
https://www.dropbox.com/s/czr70b0wlxfrzs5/dropdown_issue.ogv?dl=0

But maybe is just a problem with my code, I'm not sure.

Thanks for your time.

**Comment by SAFAD** [comment]
Can we see a JSFiddle for this ?

**Comment by chrissmejia** [comment]
Is actually Open Source :)
https://github.com/chrissmejia/OpenSloth

Probably better if you clone the repository and test in local, if you still want the JSFiddle, please let me know.

**Comment by chrissmejia** [comment]
BTW I use the same procedure 2 days ago to for ChrissMejia.com (still on development) and I notice the same problem, maybe I'm forgetting something.

**Comment by rafibomb** [comment]
I made a demo here, but can't replicate it. http://codepen.io/rafibomb/pen/rOVGxM

Can you add your dropdown there so we can help you more?

**Comment by chrissmejia** [comment]
I don't know why but my code is kind of different of yours, and still working without any custom code jeje, totally my fault, you can close it, thanks for your time.

**Comment by chrissmejia** [comment]
Oh wait, I know why, because I'm using this:
http://foundation.zurb.com/docs/components/topbar.html#

And that don't close, again my confusion.

Thanks.
