### ISSUE TITLE
weird issue when adding dropdown content inside of top bar.

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation#6716]
when i click inside of the drop down content, it closes. 

My website is at http://hogs.xyz 

this issue is driving me insane!

**Comment by r3wt** [comment]
You can see that the `a` element that triggers the content block is still being hovered when hovering inside the content block. is there any fix for this? 

![img](http://puu.sh/j4TKU/e88c80e299.png)

**Comment by r3wt** [comment]
could someone please help me with this issue, its driving me insane.

http://hogs.xyz/

**Comment by r3wt** [comment]
bump

**Comment by r3wt** [comment]
:sob:

**Comment by r3wt** [comment]
bump bump bump bump bump

**Comment by r3wt** [comment]
bump

**Comment by r3wt** [comment]
Found a solution by looking through the code.

by adding `aria-autoclose="false"` to the drop down toggle and content, the problem is resolved.

**Comment by rafibomb** [comment]
Yes, the default is to auto close but you have an option to make it persistent.
