### ISSUE TITLE
Flex video not working on Chrome Mobile

### ISSUE THREAD

**Issue by vishivish18** [zurb/foundation#6719]
The flex video is working fine for all screens but coming to mobile on chrome it is not appearing at all
Here is my code for it 

```html
<div class="landing-video-container">
  <div class="flex-video widescreen">
    <iframe id="video-iframe" src="https://www.youtube.com/embed/cQsVArKawy4?rel=0&modestbranding=1&autohide=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>
  </div>    
</div>
```

Checkout the link : http://dev.musejam.com/

**Comment by gakimball** [comment]
By Chrome Mobile do you mean iOS or Android? Or just desktop Chrome squished down?

**Comment by vishivish18** [comment]
On Android

**Comment by vishivish18** [comment]
@gakimball  Thanks for looking into it but I solved it, it was actually happening because of autoplay in the iframe.
