### ISSUE TITLE
Dual Handled Slider - Feature Request

### ISSUE THREAD

**Issue by ringo-positive** [zurb/foundation#6724]
# Double Drag(on)

It would be amazing to have a dual handled slider for ranges. Something like the below:

![jqm_range-sliders-1](https://cloud.githubusercontent.com/assets/10883847/8799123/ad8ebfa8-2f9f-11e5-9365-13e84536bf82.png)

1. Is this likely to be added to foundation at any point? 
2. Has anyone else implemented this with .js - does a guide exist anywhere?

**Comment by gakimball** [comment]
We've had a number of requests for it (see #5560 and and [#4710](https://github.com/zurb/foundation/issues/4710#issuecomment-66531910)) so we're definitely considering it for Foundation 6. :)
