### ISSUE TITLE
Magellan doc page is outdated

### ISSUE THREAD

**Issue by stephaniearnaud** [zurb/foundation#6728]
http://foundation.zurb.com/docs/components/magellan.html

This pages seems outdated to me, the code examples do not relate to the actual rendered example, and I had to look at the page source to understand how to use it. Would be nice to update it!

**Comment by rafibomb** [comment]
Thanks for the report! Are you able to submit a PR to update the docs? That would really help.

**Comment by rafibomb** [comment]
Looks like this page is up to date. Some of the markup is added by JS so you will see a difference but the documentation example is all you need to create it.
