### ISSUE TITLE
Grid "Collapse/Uncollapse Rows" Doc Issue

### ISSUE THREAD

**Issue by brettlewis** [zurb/foundation#6730]
In the documentation for [Grid Collapse/Uncollapse Rows](http://foundation.zurb.com/docs/components/grid.html#collapse-uncollapse-rows) the example explanation does not match the example html.

The explanation states: 
> Example shows no gutter at small media size and then adds the gutter to columns at medium.

However, the html shows:
`<div class="row medium-uncollapse large-collapse">
    <div class="small-6 columns">
        Removes gutter at large media query
    </div>
    <div class="small-6 columns">
        Removes gutter at large media query
    </div>
</div>`

the correct html would be:
`<div class="row small-collapse medium-uncollapse">
    <div class="small-6 columns">
        Removes gutter at large media query
    </div>
    <div class="small-6 columns">
        Removes gutter at large media query
    </div>
</div>`

**Comment by an0nh4x0r** [comment]
i have problems understanding collapse/uncollapse and i am unable to understand the concept from the docs in grid section can someone explain it more briefly ???

**Comment by rafibomb** [comment]
These classes allow you to collapse (remove column padding) based on screen size breakpoint. large-collapse means no column padding at the large breakpoint.

**Comment by rafibomb** [comment]
Updated this description!
