### ISSUE TITLE
ZURB Foundation - can't use column in class name (reserved words)

### ISSUE THREAD

**Issue by revspringjake** [zurb/foundation#6732]
Are there reserved words in the ZURB Foundation responsive framework? If there are, where are they documented?

I have a table that was built with divs using css (display: table, table-row, and table-cell).

What I get in the view is this...

![screen shot 2015-07-27 at 8 54 17 am](https://cloud.githubusercontent.com/assets/8161220/8911748/46da1106-3443-11e5-924f-49827d140e34.png)

As you can see, the last header has a space between itself and the first row.

I have troubleshot this down to the ZURB Foundation medial queries.

    @media only screen
      [class*="column"] + [class*="column"]:last-child {
        float: right;
    }

**Note:** I have tested this using Chrome (Version 43.0.2357.134 (64-bit)) only.

Depending on screen size, the space will be below or to the left as the next image displays.

![screen shot 2015-07-27 at 9 06 05 am](https://cloud.githubusercontent.com/assets/8161220/8911792/731f50f0-3443-11e5-962d-5aa769593ff0.png)

If I disable the media queries from ZURB, the issue is resolved.

However, media queries is not the root cause of this issue. The problem is that I have a class name that includes the word **column** i.e. column-sea-foam.

If the word column is included in any class name for that header, the space is included as you can see by the media query **class*="column"**

I can get around this issue by not using the world column, which I find slightly limiting in what I can now use for class names.

Could you document reserved words, or point to where this data is stated in the docs?

**Comment by jabs83** [comment]
The bit of code that generates those styles are found here: https://github.com/zurb/foundation/blob/master/scss/foundation/components/_grid.scss#L247-L254

    .column,
    .columns {
      & + &:last-child {
        float: $last-child-float;
      }
      & + &.end {
        float: $default-float;
      }
    }

You can edit the SASS to fill your specific need, or just use a more specific selector for your own stylesheet: 

    .my-div-table .column:last-child {
      float: none
    }

**Comment by gakimball** [comment]
This is fixed as of version 5.5.2 (see aab62c4432835718298816561fe6e74f013c5935). We replaced the attribute selector with class selectors.
