### ISSUE TITLE
Foundation-rails: Generate install creates an erb layout

### ISSUE THREAD

**Issue by joallard** [zurb/foundation#6733]
Given a project with a `application.html.haml` layout, generate install will create an ERB layout rather than amending the rightful template.

**Comment by flexbox** [comment]
Hello @joallard 

You can customize the scaffhold in your Gemfile
Here is an example: https://github.com/indirect/haml-rails

I think you can close the issue.
Cheers!

**Comment by joallard** [comment]
Unresolved, please reopen. Proposed solution didn't make sense
