### ISSUE TITLE
Tooltips no need js

### ISSUE THREAD

**Issue by soulcreate** [zurb/foundation#6734]
Please integrate https://github.com/arashmanteghi/simptip - no need javascript

**Comment by SalahAdDin** [comment]
:+1:
it's see very interesting.

**Comment by darolo** [comment]
IE8 supports the Attr function css, cool!

**Comment by rafibomb** [comment]
You'll notice that the text is quite padded so that the tooltip does not show off the screen. We explored these for the next version but you need JS to create edge detection so the tooltip always shows on -screen.
