### ISSUE TITLE
Table cell visibility class bug

### ISSUE THREAD

**Issue by frzsombor** [zurb/foundation#6736]
Just like in #5766, the TD elements has the same bug as table rows.
Example if I want to hide a TD on "large", no matter if I use `hide-for-large-up` or `show-for-medium-down`, it still remains visible on "large up". It would be nice to have this fixed soon.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/7306657/9043583/c0fcb776-3a16-11e5-9f48-cb00e86b4e95.png)

**Comment by youbastard** [comment]
Encountering this issue

http://codepen.io/anon/pen/vNYyjB?editors=110

**Comment by rafibomb** [comment]
We solved this in Foundation 6 by only using max-width visibility classes.

**Comment by leomendizabal** [comment]
If you are using foundation 5 you can wrap the table with a div and set the hide-for-large-up to the wrapper
