### ISSUE TITLE
slider change event bind and initialize

### ISSUE THREAD

**Issue by zhdaniel** [zurb/foundation#6737]
Hey guys, I have a page include html snippet below,
```html
<div class="row">
  <div class="small-12 large-12 columns">
    <div class="range-slider" id="slider" data-slider data-options="step: 1; start: 1; end: @Model.Count">
      <span class="range-slider-handle" role="slider" tabindex="0"></span>
      <span class="range-slider-active-segment"></span>
      <input type="hidden">
    </div>
  </div>
</div>
```
and I want to bind the `change` event and initialize the slider value from cookie when this page loaded, but I found that `console.log` executed 4 times.
```javascript
$(function(){

  ...

  // bind
  var i = 0;
  $(document).foundation({
    slider: {
      on_change: function () {
        var pos = $('#slider').attr('data-slider');
        console.log(++i);
        $('.snippet').hide();
        $('.snippet:nth-child(' + pos + ')').show();
        setPosCookie(pos);
      }
    }
  });

  // initialize
  $('#slider').foundation('slider', 'set_value', getPosCookie(source) || 1);
});
```

__*1*__
__*2*__
__*3*__
__*4*__

It doesn't make sense, I don't understand why...

**Comment by dragthor** [comment]
What is the value of your @Model.Count?  4?

**Comment by zhdaniel** [comment]
@dragthor `@Model.Count` is a asp.net mvc variable, and in that context its value is 200 usually

**Comment by dragthor** [comment]
I am unsure if setPosCookie/getPosCookie is working properly, but this CodePen is working just fine - http://codepen.io/anon/pen/Gpjmrq

**Comment by zhdaniel** [comment]
Hi @dragthor , I really appropriate your help, I shoud have described my situation more deatil though I've changed solution in my production.

When user open the web page first time, the `position` is 0, and the `position` value is changing while user does some tasks and calling `setPosCookie` to save the value, so I want to recover the slider progress with the same live `position ` value when they reload the page. so I wrote a demo as above and found the `on_change` execute 4 times. btw the `setPosCookie` and `getPosCookie ` does nothing else actually except saving or returning the `position` value.

**Comment by dragthor** [comment]
I debugged it and see it now. First, your call to...

```
$('#slider').foundation('slider', 'set_value', getPosCookie(source) || 1);
```
...is causing **another** ::init() which forces a call to ::reflow() which triggers a 'change' event.

You can get around this by setting 'initial' like this:

http://codepen.io/anon/pen/ojzyMX

This cuts console.log(++i) down to 2 from 4.

Now what is causing the 2?  The answer (unsure if I should fix it or not because we need to know about window resizing) -

foundation.slider.js::init() forces a call to ::reflow() which triggers a 'change' event.  Then, foundation.js triggers a 'resize.fndtn.slider' which triggers another ::reflow() which triggers another 'change' event.

**Comment by zhdaniel** [comment]
Thanks all for what you did, I've got my answer.
And I noticed that the window size change can trigger the slider `change` event, is that reasonable?

**Comment by dragthor** [comment]
>  we need to know about window resizing

Yup.  And changing a device from landscape to portrait will also trigger it.

**Comment by dragthor** [comment]
Can we close this issue?

**Comment by zhdaniel** [comment]
Yeah, thanks a lot.
