### ISSUE TITLE
F5 Accordion nested in another accordion not functional

### ISSUE THREAD

**Issue by TylerJBrown192** [zurb/foundation#6745]
As it says in the title, when someone tries to put an accordion inside of another accordion, the functionality is totally broken. If you click on a child element of the parent accordion section, it will close that entire parent section while still considering it 'active'. Thus, to open it again, you have to click twice.

The depreciation of F4 'Sections' left quite a big gap in necessary functionality here. Is it possible that the placement of data-slug could fix this?

**Comment by rafibomb** [comment]
Not seeing that here - http://codepen.io/rafibomb/pen/JYdrjN?editors=110 Can you add your example so we can see what's happening?

**Comment by zurbchris** [comment]
Closing this due to no response. If you are still having an issue, please reopen.
