### ISSUE TITLE
Print margin hides header/footer in Chrome and is non-configurable

### ISSUE THREAD

**Issue by TWiStErRob** [zurb/foundation#6834]
The default print `@page` margin is non-configurable: https://github.com/zurb/foundation/blob/v5.5.2/scss/foundation/components/_visibility.scss#L456

This is a problem because that margin is too small for any browser: http://stackoverflow.com/a/25388522/253468
```css
@media print {
  @page {
    margin: 0.5cm;
  }
}
```

I'm usually pro-compact layout, but In Google Chrome this means that the header and footer are not shown for pages using Foundation leaving out possibly important information like url, date, title, page #; and users can't even choose themselves whether they want header or not.

I played around a little and here are some numbers:
 * `< 0.8cm` (`0.32in`): header/footer not shown
 * `>= 0.8cm` (`0.32in`): header/footer shown, but cropped (note the `g`'s descent)  
![image](https://cloud.githubusercontent.com/assets/2906988/9204308/c9ccb56c-405c-11e5-974a-ea04a37c3ab0.png)
 * `>= 0.83cm` (`0.34in`): header/footer shown, `g` is not cropped

**Comment by tdhartwick** [comment]
Thanks for pointing that out! We made the change here 330415804f026e315238831a5475e74335fc099b.
