### ISSUE TITLE
_visibility and _type clash

### ISSUE THREAD

**Issue by TWiStErRob** [zurb/foundation#6835]
Some [styles have been moved to `_visibility.scss`](https://github.com/zurb/foundation/commit/37c01d2f1c35c689c80089c2a5f4d44c264dae15) by accident? The `@media print` styles should be in two places: `print-only` and the ones ending `-for-print` should be in `_visibility` and the rest should be in their original place in `_type`.

Imagine if I include only `_visibility.scss` because I want to use the visibility classes Foundation offers, and define my own typography (strict rules in the company for example) with that, currently, I get a lot of print related classes that have nothing to do with visiblity (as interpreted by `_visibility.scss`, that is: classes has to do with the `display` CSS attribute). I would have to write counter-styles for anything unwanted, which is a lot of work if even possible at all.

The opposite is true too: I'm not using any visibility classes, but I want to import the good typography Foundation provides. Currently, if I do that, I don't get the print typography styles, and I would have to include a lot of unwanted classes, I'll never use and will just take up compile type and bytes from CSS.

There are many reasons why be selective about which `.scss` files to include, please make it easier to choose between them.

**Comment by rafibomb** [comment]
I see your point. Can you submit a PR to clear this up because it would help many people?

**Comment by gakimball** [comment]
I went ahead and made the fixes.

- `_type.scss` now has **base print styles** only, basically just tag selectors.
- `_visibility.scss` has **print visibility classes** only.

The `$include-print-styles` variables control if that CSS is exported or not.

**Comment by TWiStErRob** [comment]
@gakimball thanks for jumping in. I was AFK for a while.
By backing out 37c01d2 you also invalidated the [fix](https://github.com/zurb/foundation/commit/330415804f026e315238831a5475e74335fc099b) for #6834 and removed documentation, I created #6910 to alleviate these.
