### ISSUE TITLE
Print visibility classes are duplicated

### ISSUE THREAD

**Issue by TWiStErRob** [zurb/foundation#6836]
`.show-for-print` and `.hide-for-print` classes are duplicated, that is included twice.
[Once](https://github.com/zurb/foundation/blob/v5.5.2/scss/foundation/components/_visibility.scss#L422) guarded by `@if $include-print-styles` and [once not, outside the `if`](https://github.com/zurb/foundation/blob/v5.5.2/scss/foundation/components/_visibility.scss#L475).

**Comment by rafibomb** [comment]
Thanks! Got it - https://github.com/zurb/foundation/commit/3ae81aecf385c3681d6333f6b7f4dff43d9b0497
