### ISSUE TITLE
Clearing Lightbox does not work with 'data-clearing-interchange' Attribute

### ISSUE THREAD

**Issue by hputzek** [zurb/foundation#6839]
Foundation 5.5.2.

[Example including images here](http://foundation.zurb.com/forum/posts/25598-images-not-advancing-in-clearing-lightbox-using-interchange)

Codepen with example here: http://codepen.io/anon/pen/NqZpyb

Clearing Lightbox does not work with 'data-clearing-interchange' Attribute

If the 'data-clearing-interchange' Attribute is used, it is not possible to switch between images in the lightbox.
The first thumbnail that was clicked is then always shown in the lightbox no matter which other thumnail clicked.

**Comment by pscdodd** [comment]
Confirm that swiping the image does not work. The arrow buttons (if displayed) work to change the image.

**Comment by tunh** [comment]
I have the same issue, any fix right now?

**Comment by rafibomb** [comment]
Although this is not a use case we have tried, we can see that 

@szinya Have any suggestions for this?

**Comment by szinya** [comment]
I'm looking at it.

**Comment by rafibomb** [comment]
Sweet thanks!

**Comment by szinya** [comment]
This bug in `foundation.js` was introduced by f9342d6ccf0a027c2c99e2a6ac135855a5ae0024. It still looks pretty messy to me.

**Comment by rafibomb** [comment]
Thanks for the PR! 

Closing in favor of it.

**Comment by sassanh** [comment]
@rafibomb this issue is not fixed in 5.5.3, where's your fix? why you closed this issue?
