### ISSUE TITLE
Forms component causing massive input lag on Android/Chrome devices

### ISSUE THREAD

**Issue by Wingar** [zurb/foundation#6845]
Hi,

A while back we noticed that Samsung Galaxy S6's and S5 phones, running stock Samsung provided Android were having insane amount of input lag on any input field, within our Rails app using the foundation-rails gem. At the time we chalked it up to our own CSS, but recently we started to dig into it and even with our CSS stripped, the input lag remained. 
Digging further, we started removing individual foundation components from the mix and found that removing 'foundation/components/forms' fixes the problem in its entirety.

We've found the issue can be replicated using the Android SDK emulator (Using Google.com as a reference for standard input latency)

We haven't found the exact source of the issue yet.

**Comment by rafibomb** [comment]
Not sure how we can replicate this one. We have forms on our Rails apps but no lag. Have link?

**Comment by rafibomb** [comment]
Can't replicate this one. Please open a new issue if you have an example we can test. Thanks!
