### ISSUE TITLE
Differences between built sources and official tarball

### ISSUE THREAD

**Issue by k0lter** [zurb/foundation#6851]
I wonder why building foundation.css from https://codeload.github.com/zurb/foundation/tar.gz/v5.5.2 (with: sass scss/foundation.scss foundation.css) produces a css file very different from the one shipped in http://foundation.zurb.com/cdn/releases/foundation-5.5.2.zip?

(Same issue while building it with grunt)

**Comment by gakimball** [comment]
I think it's a discrepancy between how the framework's Gruntfile compiles the Sass, versus how the Customizer does it. Our customizer generates those ZIP file downloads in addition to custom downloads.

If I had to guess, the compilers are different between the two (node-sass vs. Ruby Sass), and the imports are in a different order. Looking into it further.

**Comment by gakimball** [comment]
We're writing a new customizer that's built on Node instead of Ruby, so that will be a better time to address this issue.
