### ISSUE TITLE
Foundation does not work with links using method delete

### ISSUE THREAD

**Issue by bigos** [zurb/foundation#6854]
With links using data-method delete like following

```html
<a rel="nofollow" href="/users/sign_out" data-method="delete">
```

I can't perform expected actions. Signing out and deleting records has stopped working.  ;-(

if you google for:
foundation rails o route matches [GET] "/users/sign_out"
 you will get lots of SO questions without response. Is there a way to fix this problem? 

Can somebody point me to working example Rails4 application that Uses Device and Foundation?

**Comment by rafibomb** [comment]
Not sure this is a Foundation question. Perhaps a pure rails forum could help you more.
