### ISSUE TITLE
Reveal ignores scroll in Firefox

### ISSUE THREAD

**Issue by borys-p** [zurb/foundation#6856]
Hi,

It seems there's a bug in Firefox where you try to read `$(body).scrollTop()` in HTML5 page. You get zero.

The fix is simple, get the `$(document).scrollTop()` instead. It only needs to be nicely merged with `settings.root_element`, as it's not exactly an "root element".

**Comment by rafibomb** [comment]
Sorry, what is the component you are referring to?

**Comment by rafibomb** [comment]
Just tested 5.5.2 in Firefox 40.0.3 and cannot see an issue. Can you describe what you are trying to do and what is happening? Have an example?

**Comment by borys-p** [comment]
Looks like it was fixed in 5.5.2 and I was still using 5.5.0. Now it's checking the window.scrollTop not the root_element.scrollTop. Thanks for your answer and sorry about the fuss.
