### ISSUE TITLE
Topbar will get stuck open in Foundation 5.5.2 with Modernizr

### ISSUE THREAD

**Issue by lethjakman** [zurb/foundation#6860]
If you have a top bar with a target="blank" link to be opened in a separate tab the top bar will not close upon navigating back to your original tab. This bug will occur If you're on Foundation 5.5.2.x and have modernizr enabled. I have created an [example application here](https://github.com/lethjakman/test_foundation_topbar)

Steps for reproduction:
1. cd into test and run $ bundle install && rails s
2. Navigate to 127.0.0.1 in a web browser (I used chrome)
3. Hover over "Right Button Dropdown" then click the link that says "Click Me"
4. Close the new google tab and return to your page to find that the dropdown is still opened.

One oddity of this bug is that it only occurs if you have modernizr enabled; if you go to the [javascript manifest file](https://github.com/lethjakman/test_foundation_topbar/blob/master/app/assets/javascripts/application.js#L16) and remove the modernizr require the top bar won't stay open.

**Comment by zurbchris** [comment]
While perhaps not ideal, and after only a cursory look at the problem, you can add ` $('.dropdown').find('a').on('click.fndtn.dropdown', function(){
    $(document).foundation('topbar', 'reflow');
});` to your JS file. That closes the dropdown, and you can add as much specificity to the event handler as you like. As for the reason for this issue, I'l have to dig into it a little more. 
Hope that helps.

**Comment by zurbchris** [comment]
I'm going to close this for now, feel free to reopen if you haven't figured it out.

**Comment by Andraz89** [comment]
@zurbchris your solution worked for me. Tnx. Still I hope Foundation 6 fixed this issue.

**Comment by zurbchris** [comment]
You're welcome, glad I could help!
