### ISSUE TITLE
Calling 'off' on Joyride destroys settings

### ISSUE THREAD

**Issue by xsegrity** [zurb/foundation#6864]
In v5.5.2 calling 'off' on joyride sets the settings to an empty object (`this.settings = {};`). If I then call 'start' again the default settings do not get properly initialized. Specifically, the 'templates' setting does not get re-initialized. This in turn causes the joyride to completely bomb when a restart is attempted.

If settings is either set to undefined or null in the 'off' method then it seems the 'init' method properly re-initializes the settings when the joyride is restarted.

**Comment by tdhartwick** [comment]
Hey, thanks for reaching out to us! We're currently working on improving this for Foundation 6, but it sounds like that would work. We'd love it if you submitted a pull request to see this implemented sooner than later! If you can't we'll be able to add this in our next version.

**Comment by dragthor** [comment]
Actually I think preserving the settings (instead of nulling them in 'off') is a good way to go.  What if I am overriding the template or the tipcontainer?

**Comment by dragthor** [comment]
https://github.com/zurb/foundation/pull/6898

**Comment by dragthor** [comment]
I vote to close this issue.
