### ISSUE TITLE
Dropdown component documentation is FUBAR

### ISSUE THREAD

**Issue by nmschulte** [zurb/foundation#6868]
Looking at the documentation for the *Dropdown* component, it seems the documentation markup (or generator) has an issue:

http://foundation.zurb.com/docs/components/dropdown.html

It appears there is a list or heading markup issue in the *Advanced* section, causing strange emphasis (and formatting) when rendering the *Dropdown Classes* and *Directions* examples.

Further, the *Dropdown Classes* example seems like it should have five example dropdown instances, one for each "size-modifier" class.  I was expecting to see one set of HTML markup for each too, so that the `class="[tiny small medium large mega content]f-dropdown"` markup isn't confusing (as I don't think it's valid markup).

**Comment by dragthor** [comment]
Unsure if we need five difference examples for each size.

**Comment by rafibomb** [comment]
That would probably be overkill. We'll just document it in a different way like in a bulleted list of modifier options.
