### ISSUE TITLE
Stacked Progress bars

### ISSUE THREAD

**Issue by sharkoman** [zurb/foundation#6871]
"Stacked" Progress bars
It looks like this part of css doesn't exist in the foundation.css file

**Comment by eli-collins** [comment]
I ran into this as well with the sass files.  It looks it like those features weren't merged until rev 79194894d62ff2a918ec8f5be46a51a6fb528c15, which occurred after the 5.5.2 release.  I'm guessing it'll get included when they release 5.5.3, but somehow the docs got updated out of sync?

**Comment by gakimball** [comment]
Yep, we probably were deploying the docs to fix something else and that snuck in. We're doing a big review of pull requests today so a new release shouldn't be too far behind.
