### ISSUE TITLE
Add option to center tooltips horizontally when they appear above or below target

### ISSUE THREAD

**Issue by benknight** [zurb/foundation#6875]
Current behavior when tooltip is above or below its target is to be left aligned, like so:

<img width="345" alt="screen shot 2015-09-02 at 1 18 41 pm" src="https://cloud.githubusercontent.com/assets/786691/9643170/3e1bc718-5175-11e5-9210-a0a1f3e44c82.png">

In many cases it's more visually appealing for the tooltip and its arrow to be center-aligned relative to its target, as in Bootstrap:

<img width="145" alt="screen shot 2015-09-02 at 1 19 06 pm" src="https://cloud.githubusercontent.com/assets/786691/9643187/500a451c-5175-11e5-8d4c-b675c0eaa732.png">

**Comment by rafibomb** [comment]
This is something we've done for the next version. We'll close this here. Thanks!
