### ISSUE TITLE
Reveal modal position is whacky when page is scrolled

### ISSUE THREAD

**Issue by andreasheim** [zurb/foundation#6876]
For me, reveal modals work fine, for as long as there's no scrolling involved. 

As soon as there is, the top position for the reveal is way too far down, and the background doesn't cover the entire screen: 

![screen shot 2015-09-05 at 12 16 31 am](https://cloud.githubusercontent.com/assets/399306/9698262/69b0016a-5363-11e5-9288-fdced2023bdb.png)

The background can be fixed by using 
`position: fixed;`
instead of 
`position: absolute;`

For the modal itself, since it already is using `position: fixed`, it should not add the scroll position.

**Comment by rafibomb** [comment]
What version are you using? Can't replicate on the docs.

**Comment by andreasheim** [comment]
5.5.2 (installed via npm in case that matters)

**Comment by andreasheim** [comment]
Other ways it manifests is if you have the developer tools open (I assume due more likely to scroll), or if you scroll the page while the modal is open. 

That said, my css may be at 5.5.0 or 5.5.1.

**Comment by gbenedict** [comment]
I am seeing this same issue in 5.5.2.

**Comment by Guidoch** [comment]
I am facing the same problem, it's a javascript issue.
if you go through the reveal.js you'll find out. I could propose a pull request in case we have more supporters. My fix would be, for all the lines that involve $(window).scrollTop():
Example:
css.top = $(window).scrollTop() + el.data('offset') + 'px'; 
Becomes:
css.top = el.data('offset') + 'px';
if(el.css('position') === 'absolute') {
css.top += $(window).scrollTop();
}

**Comment by zurbchris** [comment]
This is an issue we are fixing in Foundation 6. If anyone wants to submit a pull request for 5, we'd love to see it.

**Comment by rafibomb** [comment]
We're still not able to replicate this. Both on the docs, a version from Master branch and a fresh install are position absolute. No matter where we scroll, the modal stays in place. What modifications to CSS are you making? Please help us replicate it.

Can anyone provide an example link or demo that can help us see what's happening?

**Comment by Guidoch** [comment]
It's easy, 2 use cases:
1. Position absolute: make the pop-up appear, THEN scroll, the pop-up will stay where it appeared (because it's not fixed). Probably people would like it to follow the scroll, so:
2. Position fixed: if you make it appear at when you are at the top of the page, it is ok and will follow the scroll. If you scroll down BEFORE and then make it appear, the more you have scrolled down the more it will appear down, until it will be out of the page.

Hope it's understandable, I'll try to raise a pull request tonight after work!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by Guidoch** [comment]
Hi all,

I am sorry but I have been really busy lately and also I am having some issues in trying to setup the proper environment for this project.

**Comment by rafibomb** [comment]
Hey all, thanks for the details on this issue. We added an option (default) to lock the modal from scrolling https://github.com/zurb/foundation/commit/c3c33ac235d635d8e30f31ec58d549798bc4acaa
It's in 5.5.3 which just went out.

This should resolve the issue.
