### ISSUE TITLE
Tooltip is not removed if parent element is removed from DOM

### ISSUE THREAD

**Issue by ChristofferKarlsson** [zurb/foundation#6877]
If I attach a tooltip to an element (link, button), and remove that element when a click action is triggered on the element, the tooltip remains visible and can't be removed.

Example: http://emberjs.jsbin.com/jutapilune/2/edit?html,css,js,output
From the discussion on the forum: http://foundation.zurb.com/forum/posts/2341-tooltips-dont-auto-hide-if-parent-element-is-removed-from-dom

**Comment by zurbchris** [comment]
There is a reply on that forum post from me, I hope it's helpful.

**Comment by dragthor** [comment]
@zurbchris I say you close this issue (as its not really an issue).

**Comment by zurbchris** [comment]
@dragthor what a great idea! Thanks for the reminder.
@ChristofferKarlsson if this continues to be an issue, please feel free to reopen.

**Comment by dragthor** [comment]
@ChristofferKarlsson if you need anything else... ping me.

**Comment by zurbchris** [comment]
On a side note, we have quite the collection of (Ch)(K)ris's on this issue.

**Comment by mindtonic** [comment]
+1 -- It seems really obtrusive to specifically remove tooltips on every action that removes or replaces an element. I started implementing the proposed solution and found myself having to go through all of my scripts and sprinkle in this housekeeping code. I have to wonder if their is either a better way to monitor the tooltip elements, or if there is a better way to construct the tooltips themselves?
