### ISSUE TITLE
Feature Request: Equalizer: Match on smallest and arbitrary match

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation#6878]
Hi Zurb.

First off, let me preface this by saying y'all have put together a truly amazing framework. I love it and it has made constructing responsive websites a lot of fun.

I have a basic feature request that I hope can make it into Foundation 6. Basically, I think it would be neat to add an option to Equalizer that matches block height to the smallest. Also, a sub option that either scales image content appropriately or masks larger images.

It also could be useful in certain contexts to match height arbitrarily -- perhaps by pointing to a certain block in the grid.

Thanks.

**Comment by rafibomb** [comment]
Thanks for the kudos @paxperscientiam !

How would this work form something that cannot scale like an image? What do you mean by mask? Overflow: hidden? This may be a very specific use case in which you might just write some CSS like max-height.

**Comment by rafibomb** [comment]
Since this is not a feature we'll be adding to Foundation 5, because we're deep in development of version 6, we'll close this here. Thanks!

**Comment by paxperscientiam** [comment]
Sorry I took too long to respond, rafibomb! I just got a hold of Foundation 6, so I'll be exploring it shortly!
