### ISSUE TITLE
Top-Bar unclickable after scroll if fixed

### ISSUE THREAD

**Issue by brightonmike** [zurb/foundation#6880]
Hello

I took over this site to maintain it and make some changes, I didn't write the original code. That said I don't think this is a problem with the code.

Please visit http://tinyurl.com/orjj5zy - in Chrome beta (specifically, I'm seeing the issue in Version 46.0.2490.22 beta-m).

If you scroll down a page, then scroll back up, all the links in the navigation are no longer clickable and you don't get the cursor.

I'm only seeing this problem in Chrome beta. I can't recreate it elsewhere. Removing the position fixed from the nav wrapper makes the links clickable again.

I don't know if this is a quirk with Chrome beta - it seems to be as the code is fine and works everywhere else. But I thought it was worth raising anyway - just in case this becomes a problem when 46 goes stable.

**Comment by rafibomb** [comment]
We're testing on the latest production version for each release. Looks like an issue with the Chrome beta version. We'll close this for now. Please open a new issue if it still happens when this Chrome version is official. Thanks!
