### ISSUE TITLE
Accordion – linking to tabs?

### ISSUE THREAD

**Issue by kavonatsalv** [zurb/foundation#6885]
Is it possible to link to a tab inside Accordion?

Let's say for example I am clicking a link such as domain.com/page#tab-23 from an external page – how can I make tab 23 active when the page is opened?

Thanks.

**Comment by rafibomb** [comment]
This is not an interaction that we're looking to add to Foundation. There is a forum post though I think that will help you: http://foundation.zurb.com/forum/posts/18116-accordion-deep-linking
