### ISSUE TITLE
Equalizer performance is not consistent.

### ISSUE THREAD

**Issue by MsTrends** [zurb/foundation#6886]
I'm using foundation 5 in my project. My project can be [seen here](http://html.mstrends.com/dist/index.html). I'm using 'Equalizer' functionality on 'Services' section on the homepage. I've done every thing as per documentation. 

But now the issue is behaviour of equalizing both services column is not consistent. 

In chrome/firefox it mostly works but sometimes it doesn't work. Whereas, in EDGE browser of windows 10 it mostly does not work. I'm not sure what is the issue.

**Comment by zurbchris** [comment]
I see what you're talking about. Can you replicate this in a codepen so we can take a look at it with code?

**Comment by rafibomb** [comment]
I would imagine the issue is with the image slider you are using with Equalizer. It works great on standard div's. Using the inspector I can see that the slider JS is adjusting the height after Equalizer does.
