### ISSUE TITLE
spec/interchange testing failing

### ISSUE THREAD

**Issue by dragthor** [zurb/foundation#6887]
Anyone else seeing this?  I can reproduce on Windows 10 and Windows 7... both with Firefox 40.0.3 installed.

Firefox 40.0.0 (Windows) interchange: setting data-interchange-last-path when below the large breakpoint should set data-interchange-last-path on element when replace occurs FAILED
        Expected 'medium.html' to match 'default.html'.
        @c:/Users/kkrause/Documents/gitprojects/foundation/spec/interchange/interchange.js:75:9

**Comment by zurbchris** [comment]
Any chance you can make a codepen replicating this?

**Comment by dragthor** [comment]
This is not happening with Firefox 41.0.0 (windows).  And I think it was just a jasmine timing issue with Firefox 40.0.0.
