### ISSUE TITLE
split button does not work when data-method is set

### ISSUE THREAD

**Issue by coin3d** [zurb/foundation#6894]
I'm using Rails 4 and trying to use the split button. The paths I'm trying to link with Rails are POST actions, therefore the attribute data-method="post" is needed. However, if this attribute is set, the split button behaves not like it should: It is not possible to click the drop-down menu, instead, when pressing the dropdown button, the actual href of the <a> element is ran.

does not work:
```html
      <a class="button split" rel="nofollow" data-method="post" href="...">start <span data-dropdown="drop"></span></a><br>
      <ul id="drop" class="f-dropdown" data-dropdown-content="">
        <li><a>....</a></li>
      </ul>
```

works:
```html
      <a class="button split" rel="nofollow" href="">start <span data-dropdown="drop"></span></a><br>
      <ul id="drop" class="f-dropdown" data-dropdown-content="">
        <li><a>....</a></li>
      </ul>
```

Any ideas what I'm doing wrong - or if this is actually a bug?

Thanks

**Comment by dragthor** [comment]
I think you just need to prevent the default action of the link.  
Check it out - http://codepen.io/anon/pen/jbrMvG
```javascript
$("#start").on("click.fndtn.dropdown", function(e) {
  e.preventDefault();
  
  console.log("did not go to whatever.php");
});
```

**Comment by gakimball** [comment]
Yep, the split button itself doesn't intrinsically separate those click events. If you want to add an event handler to the inner button, you need to stop propagation of the click event to the outer button. Our dropdown plugin does this automatically because it's partially designed to work with split buttons.
