### ISSUE TITLE
postfix.button and prefix.button have a difrent css

### ISSUE THREAD

**Issue by phryniszak** [zurb/foundation#6895]
Hi,

As in topic. If postfix button is placed in row it is not respecting width of column. Setting .postfix.button as .prefix.button fix it.

/* Adjust padding, alignment and radius if pre/post element is a button */
.postfix.button {
  border-color: true; }

.prefix.button {
  border: none;
  padding-left: 0;
  padding-right: 0;
  padding-bottom: 0;
  padding-top: 0;
  text-align: center; }

![postfix](https://cloud.githubusercontent.com/assets/10012370/9989942/c0e2fa5c-6054-11e5-9ef8-4f541e6e4ff1.png)

**Comment by rafibomb** [comment]
I can't replicate this in 5.5.2 http://codepen.io/rafibomb/pen/WQxJgp?editors=110

Perhaps this has already been addressed.

**Comment by phryniszak** [comment]
I don't think so:

http://codepen.io/phryniszak/pen/QjErXq

**Comment by phryniszak** [comment]
Please have look here:

http://codepen.io/phryniszak/pen/QjErXq

To see it beter you can change sreen width and observe + and - buttons.

**Comment by rafibomb** [comment]
Thanks! Got it now. Testing on the master branch shows that this was already fixed. looks like this commit also fixed the border https://github.com/zurb/foundation/commit/37b1dfeb6fcb6f25ed1297efef911d7476a934b5
