### ISSUE TITLE
Add specific dependencies versions in bower.json

### ISSUE THREAD

**Issue by Gorzas** [zurb/foundation#6896]
I'm working with Foundation framework and I have got recently a problem with the library. The problem is that Modernizr library has been updated to version 3.0 and this version has some major changes that are not compatible with Foundation. With the dependency set as `>= 2.7.2` in the bower.json file, with a `bower install`it retrieves the most updated version of the library (3.0, incompatible) instead of an actually working version of Modernizr (between 2.7.2 to 2.8.3 have been working in my project).

Can it be fixed? Is better practice to set relative version dependencies insted of specific ones?

Thanks.

**Comment by l3rady** [comment]
Just come across this on our sites after deploying new code when `bower update` runs because the dependency is set to `>=` it goes and grabs 3.0.0 of modernizr and breaking our sites by modernizr.js no longer existing

**Comment by Baedda** [comment]
Same problem right here! This broke a lot of projects from us this week. Please set fix versions or make foundation compatible to modernizr 3-

**Comment by rafibomb** [comment]
Yes - modernizr 3.0 comes with breaking changes. Until everything is tested for 3.0, we've locked in modernizr on the latest tested version.

"modernizr": "2.7.2",

**Comment by rafibomb** [comment]
We'll push it up to 2.8.3 since it was tested good on that version.
