### ISSUE TITLE
Conflict with Jplayer and data-interchange

### ISSUE THREAD

**Issue by kelster44** [zurb/foundation#6899]
Hello,
I just bought Clean Html5 Audio Player with Playlist on Envato this morning and already have it working. I am having a couple of issues. I am using Zurb Foundation for grid layout. My header uses data-interchange feature to serve different size images for different devices. This is causing a conflict with the jplayer jquery. If I remove the data-interchange code and just put in a src attribute all works correctly but I want to serve different sizes for devices. When I try validating the html the data-interchange doesn't validate due to mising src attribute. I don't know if that could be causing this weird situation? Basically, I think there is a conflict between the jplayer's jquery and yours. Do you know what it could be? If I remove jplayer jquery code and use Foundation's the header still won't work correctly and it messes up the jplayer. I created several files to illustrate:
scfpapresents.com/stella-music-cds-fj.php (includes only foundation jquery)
scfpapresents.com/stella-music-cds-yourj.php (includes only Clean HTML5  jquery)
scfpapresents.com/stella-music-cds-both.php(includes both jquery)
scfpapresents.com/stella-music-cds.php (includes both but header changed to src)

Thank you for any help you can give me!

**Comment by kelster44** [comment]
Has anyone had a chance to look at this one yet? Any help is appreciated!

**Comment by zurbchris** [comment]
All of your links give me a 404. I'd be interested to see what the issue is though, I haven't yet used jplayer.

**Comment by kelster44** [comment]
Yes sorry. I deleted them. I created a workaround. Instead of using data-interchange to swap out images for different devices I used:

<picture>

<source srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-large.jpg" media="(min-width: 1025px)">
<source srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-medium.jpg" media="(min-width: 641px)">
<source srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-small.jpg" media="(min-width: 150px)">

	
 
 <source media="(min-width: 150px)" srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-small.jpg" >
 
 <source media="(min-width: 641px)" srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-medium.jpg" >
 
 <source media="(min-width: 1025px)" srcset="http://www.scfpapresents.org/images/header-bars/scfpa-banner-large.jpg" >
 <img src="http://www.scfpapresents.org/images/header-bars/scfpa-banner-large.jpg" alt="The Santa Cruz Foundation for the Performing Arts: Patagonia, Arizona" />
</picture>

This caused everything to behave properly. I am guessing there is some conflict between using data-interchange and jPlayer but don't know what it is. Annoying but at least I was able to work around it!
Thank you!
