### ISSUE TITLE
Form ought to emit `valid.fndtn.abide` when there are no validatable fields

### ISSUE THREAD

**Issue by charneykaye** [zurb/foundation#6901]
This issue is follow-up to the original issue #6881 Abide throws an error if form has no validatable fields, and will be accompanied by a pull request within a couple hours.

The original issue #6881 is still an improvement, because prior to that Abide was simply throwing a JavaScript error in this case: **a form that hides its validatable elements before submission**

However, we identified a paradox that made it very difficult to actually implement such a form without hacking our way around Abide's blocking of the original form `submit` event.

So, the solution to the original issue #6881 was fine in that it prevented a JavaScript error. However, the failure to emit `valid.fndtn.abide` was caused by a totally separate oversight in how Abide identifies the form element to which the validation belongs.

The expected enhanced behavior would still *skip validation,* but then it would also still emit the `valid.fndtn.abide` event.

**Comment by rafibomb** [comment]
Thanks for the PR! We'll test it soon and continue the conversation there.
