### ISSUE TITLE
How to Update Instructions in sass.html Outdated?

### ISSUE THREAD

**Issue by boucains** [zurb/foundation#6905]
## Problem

In sass.html, on line 222, the [See an example](http://zurb.us/1kl96mM) image shows a specific version  of Foundation, but the recommended installation bower.json file shows "zurb/bower-foundation" instead. The resulting {project-name}/bower_components/foundation/bower.json file matches the __update__ example, bar the version, shown on line 231 under [See an Example](http://zurb.us/1klal5c).

![bower-foundation](https://cloud.githubusercontent.com/assets/5030015/10121220/7f9c02b4-6496-11e5-8644-f3c5de551389.png)

![matches-json-bower](https://cloud.githubusercontent.com/assets/5030015/10121263/3cc7d33a-6498-11e5-9630-77c1e58a9353.png)

## Question

Is the "zurb/bower-foundation" due to the recommended installation method vs. a different method, or is it a newer entry that always resolves to the latest version of Foundation, or something else?

## Request

Please either update the image to match the latest entry, or add documentation to explain the difference for newbs like me.

## Comment

I'd be happy to provide a substitute image, but I don't use a Mac, and would probably add to the confusion. :confused:

**Comment by rafibomb** [comment]
In the bower.json file - in your parent directory you can change the version number to an exact release that exists on GitHub. By default, the file point to zurb/bower-foundation this repo and pulls the latest tagged version. The repo is here - https://github.com/zurb/bower-foundation

If you leave it pointing to https://github.com/zurb/bower-foundation then you will always update to the latest version. If you change to a specific # then you can target an older version.

The version in the bower_components folder is to be read and not modified.

**Comment by boucains** [comment]
Thank you  - this is a great explanation of how it works. However, you didn't respond to what I wrote. The question is not about how it works, it is pointing out that the documentation as written doesn't match the configuration of what is currently distributed. Could you please reopen it, or at least address the question I posed? Thanks!
