### ISSUE TITLE
Provide componentized CSS in addition to the all-in-one pre-built CSS file

### ISSUE THREAD

**Issue by mnquintana** [zurb/foundation#6907]
Currently the pre-built CSS that Foundation includes in its various downloads (npm, Bower, the Foundation website, etc) is *all* of Foundation in one file. Sometimes users may want to include just the CSS for particular components, instead of the whole thing - this may be for performance or conflict reasons, among other things. In my case, I have to use Less for a project, but still want to make use of some particular Foundation components. Using all of Foundation is a non-starter, because much of it conflicts with other UI components (and our grid system). 

Unfortunately, this is currently only possible by maintaining both a Sass and Less build pipeline, and selecting the Foundation components I want to use in a Sass file.

It would be incredibly helpful to have separate CSS files for each component in the pre-built distributions of Foundation.

**Comment by rafibomb** [comment]
@gakimball @zurbrandon Thoughts?

**Comment by gakimball** [comment]
Unfortunately it's not quite worth the added overhead for us. This is a Sass-powered framework, so we recommend that developers who want the most control over the framework use it with Sass. We also provide the customizer as a way to get some of that same flexibility, but for compiled CSS instead. It seems like the main use case for this feature is LESS support, but that isn't a priority for us, as we're focused exclusively on Sass.

**Comment by mnquintana** [comment]
Thanks for the update! I wasn't looking for Less support though, just compiled CSS for each component. I actually didn't know about the customizer though, and that'll work as a workaround, but it's really far from ideal since we won't be able to manage versions easily with dependency management.

**Comment by gakimball** [comment]
To come back to this, we're looking at adding a feature to the customizer to generate a unique URL for a custom download, which would allow you to revisit the download later, make changes, and then create a new CSS file to replace your existing one. jQuery UI's [Themeroller](http://jqueryui.com/themeroller/) does this.
