### ISSUE TITLE
Publishing newer releases to NPM

### ISSUE THREAD

**Issue by vtambourine** [zurb/foundation#6908]
Last release published to NPM is [5.4.7](https://www.npmjs.com/package/zurb-foundation-5). It seems outdated, since last release tag on GH is 5.5.2. Can you please make new release on NPM?

**Comment by rafibomb** [comment]
I think this is one you're looking for - https://www.npmjs.com/package/foundation-sites

The other names were taken when we registered with NPM and Foundation now has 3 frameworks (sites, emails, apps) so it makes sense.
