### ISSUE TITLE
Topbar component as module(mixin)

### ISSUE THREAD

**Issue by anithegregorian** [zurb/foundation#6915]
It's a feature request rather than a bug. Now that Foundation 6 is on its way, I think it would be nice to have the Topbar (and any other components) as a module (mixins). They already have it for Grids, Blockgrids and such. Like for a 6 column grid you'd have something like this:

```sass
@include grid-column($columns: 6, $last-column: false, $center: false, $offset: 0, $push: 0, $pull: 0, $collapse: false, $float: left);
```

I have no clue if this feature has already been accounted for in Foundation 6. In Foundation 5.5.2 you have to set ```$include-html-top-bar-classes ``` to true to get the topbar html classes in your CSS. But think of it as a component which can be controlled with a mixin...

**Comment by rafibomb** [comment]
Top-bar is a very complex component that does so many things. For that reason it doesn't have a mixin. Everything else has mixins. In the new version we have componentized the menu pieces so that you can make a more custom nav easily. Each of these have their own mixin.
