### ISSUE TITLE
Off-canvas doesn't work on iOS9

### ISSUE THREAD

**Issue by kugaevsky** [zurb/foundation#6916]
`zf-toggle` attribute don't open `zf-offcanvas` element on iOS9.

**Comment by rafibomb** [comment]
I think you are referring to Foundation for Apps - https://github.com/zurb/foundation-apps

You can open the issue there, but please provide steps to reproduce and an example would be helpful!

**Comment by kugaevsky** [comment]
Oh, sorry. For sure I want to refer to another repo.
