### ISSUE TITLE
Responsive Table Duplicate Column Bug

### ISSUE THREAD

**Issue by kkeelingECSC** [zurb/foundation#6918]
Hi There,

First off, I’m a big fan of Foundation 5.

I am looking to implement a responsive table and it’s working as expected…however I noticed a bug that I can’t pinpoint and was wondering if someone could shed some light on the issue. Basically between 768px and 783px the “pinned table” with only column 1 showing is duplicated below the main table. Now the likelihood of a user noticing this is slim (depending on screen width), but I couldn’t find any forums that raise the issue.

Here is the link to the Demo page, shrink your browser window to see: http://zurb.com/playground/projects/responsive-tables/index.html

Here is a screenshot of your demo page to show what I’m talking about:
![responsive-table](https://cloud.githubusercontent.com/assets/9598945/10285271/eeb7562e-6b3c-11e5-89eb-4577f0b024ee.png)

OS:
Windows 8.1 Pro (64 bit).

Browsers: 
Chrome Version 45.0.2454.101 m, 
Internet Explorer 11.0.9600.18036
Firefox 36.0.1

**Comment by rafibomb** [comment]
Thanks for the kind words! Sorry, this is a playground piece you are referring to. It's typically experimental code and not something that is part of Foundation. 

The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help with troubleshooting what might be going on here. 

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by kkeelingECSC** [comment]
no worries, I was given wrong URL.
