### ISSUE TITLE
Shouldn't ul.button-group be display:inline-block?

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation#6920]
Since it's supposed to appear as if it's one button, I don't understand why it's display property shouldn't be more suited to behave as if the entire group is just an ordinary button?

TL;DR:

Shouldn't we do `.button-group { display: inline-block; }`?

**Comment by rafibomb** [comment]
The buttons are already display: inline-block; The button-group class just creates the container which basically controls the borders and the float.

**Comment by ProLoser** [comment]
Except a `<ul>` is display block.

**Comment by ProLoser** [comment]
Honestly, I've sorta given up trying to get button-groups to look even half-respectable when my buttons have borders. I have no idea why they are this complicated. Bootstrap just wraps the whole darn thing in a span tag, tweaks some border-radius if/when necessary, and moves on with life. I don't think this component should be as complex as it currently is.

**Comment by rafibomb** [comment]
Totally get it - right now It'd be a breaking change. We are addressing this in the next version (Foundation 6)

Thanks!
