### ISSUE TITLE
Issue while compiling bower-foundation v 5.5.3

### ISSUE THREAD

**Issue by ah-taktik** [zurb/foundation#6921]
Hello,

While trying to compile my css files using compass, I am facing to an issue related to the new version of foundation :

```javascript
remote: Running "compass:env" (compass) task
remote: directory public/css
remote:     error assets/sass/style.scss (Line 124 of public/js/components/foundation/scss/foundation/components/_global.scss: Undefined variable: "$_property".)
remote: Compilation failed in 1 files.
remote: Warning: ↑ Use --force to continue.
remote: 
remote: Aborted due to warnings.
```

Here is my config of Gruntfile.js:

```javascript
compass: {
      env: {
        options: {
          importPath: ['public/js/components/foundation/scss',
                       'public/js/components/font-awesome/scss'],
          sassDir: 'assets/sass',
          cssDir: 'public/css',
          specify: 'assets/sass/style.scss',
          fontsDir: 'public/font',
          httpFontsDir: 'font'
        }
      },
      production: {
        options: {
          importPath: ['public/js/components/foundation/scss',
                       'public/js/components/font-awesome/scss'],
          sassDir: 'assets/sass',
          cssDir: 'public/css/build',
          specify: 'assets/sass/style.scss',
          fontsDir: 'public/font',
          httpFontsDir: 'font'
        }
      }
    },
```

Do you have any idea ? 

Thanks in advance.

**Comment by scottybollinger** [comment]
Having the same issue

**Comment by rafibomb** [comment]
Hmm, could be related to this? https://github.com/zurb/foundation/commit/5f6a72e816cc7fda545179f99faf1409b23dee49

Seems like grunt-sass doesn't have this issue.

**Comment by ntswebserve** [comment]
I'm getting the same error, not present in Foundation 5.5.2.

**Comment by cmenning** [comment]
I'm getting the same error compiling with compass. The error was not present in Foundation 5.5.2.

**Comment by chrischimen** [comment]
Same issue!

**Comment by rafibomb** [comment]
Just cleated a libsass and compass project with the CLI. No issues. - what are the steps to reproduce?

**Comment by rafibomb** [comment]
Also what Sass and Compass versions? 

Sass -v
Compass -v

Im running 
Sass 3.4.13 (Selective Steve)
Compass 1.0.1 (Polaris)

**Comment by cmenning** [comment]
I'm using Sass 3.4.18 and Compass 1.0.3. I'm importing Foundation in my bower.json:

```
{
  ...
  "dependencies": {
    ...
    foundation: "5.5.3"
  }
}

**Comment by rafibomb** [comment]
Still need a way to reproduce this.

I just updated Compass and Sass to 
Compass 1.0.3 (Polaris)
Sass 3.4.18 (Selective Steve)

**Comment by scottybollinger** [comment]
I'm using sass 3.4.18 and compass 1.0.3

**Comment by scottybollinger** [comment]
@rafibomb I won't post here but if it will help, I can email you our sass files for our app (You guys actually originally designed and coded it at Zurb) and you can try compiling it yourself to troubleshoot.

**Comment by rafibomb** [comment]
Can someone post a code sample where they use the transition mixin so we can see what's going on here? 

```
 .button {
  @include transition(color, 1s, ease);
}
```

Doing this throws no error so we need more info.

**Comment by scottybollinger** [comment]
This may be the culprit in our codebase:
```
&.ng-animate {
      @include transition(none!important);
}
```

**Comment by cmenning** [comment]
Ours is choking on

```
section.choice-videos {
    ...
    a.video {
        ...
        &:hover, &.selected {
            ...
            @include transition(background-color 500ms ease-in-out);
        }
    }
}

**Comment by rafibomb** [comment]
I see a difference in that I'm using comma's between the arguments. Do you think that could cause the difference?

**Comment by cmenning** [comment]
Quite likely. We've been relying on the implementation in Compass for transitions, which is now overridden by Foundation's new implementation in 5.5.3.

The Compass version allows for syntax like ```@include transition(opacity 500ms ease-in-out, height 300ms ease-in-out);``` which looking at the Foundation source does not appear to be supported (though I could be misreading it).

**Comment by anithegregorian** [comment]
+1 Having same error after updating to Foundation 5.5.3

**Comment by rafibomb** [comment]
Ok, got it. The transition mixin in Foundation was recently extended and has the same name as the Compass transition mixin. Name-spacing or renaming the mixin is the solution. 
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_global.scss#L85

**Comment by jbrooksuk** [comment]
Seeing this too. What's the solution? :)

**Comment by jbrooksuk** [comment]
We're using Compass by the way.

**Comment by ahudson87** [comment]
Name-spacing the mixin at: ..scss/foundation/components/_global.scss#L85 seems to fix the problem for me. However, my concern now is when running a foundation/compass update won't this revert?

Seems a little bit dangerous to have a small single custom configuration buried deep inside components files.

Is this a legitimate concern? Any other suggestions or fixes coming?

Thanks-

**Comment by rafibomb** [comment]
Foundation has a transition mixin that is used on many components. Because Compass also has a transition mixin, Foundation's is name spaced "single-transition". We removed the old transition and renamed the new one that now had transition delay. 5d1fb96

This change is in the master branch. You can duplicate the commit above to resolve.

**Comment by danishraza** [comment]
yup can confirm, the solution is to go to Line 124 of bower_components/foundation/scss/foundation/components/_global.scss:
and change @mixin transition(....){}  to @mixin single-transition(....){}
cheers

**Comment by vacas5** [comment]
the naming convention "single-transition" may still conflict with Compass mixins http://compass-style.org/reference/compass/css3/transition/#mixin-single-transition

**Comment by danishraza** [comment]
@vacas5 but its working today i had conflict on pulling from my repo and this time i had error "error scss/app.scss (Line 124 of bower_components/foundation/scss/foundation/components/_global.scss: Undefined variable: "$_property".)"  so again 
Fix was: on line 85 change mixin name of  @mixin transition($property:all, $speed:300ms, $ease:ease-out, $delay:null) {
to the
 @mixin single-transition($property:all, $speed:300ms, $ease:ease-out, $delay:null) {

so, this works for me.

**Comment by jadidian** [comment]
Same issue with Gulp:
```
[20:06:10] Finished 'views' after 9.31 μs
directory destination/styles

    error source/styles/main.scss (Line 124 of source/styles/vendor/foundation/foundation/components/_global.scss: Undefined variable: "$_property".)

directory destination/styles/fix

    write destination/styles/fix/ie.css
Compilation failed in 1 files.

[20:06:15] 

[20:06:15] Plumber found unhandled error:
 Error in plugin 'gulp-compass'
Message:
    directory destination/styles
    error source/styles/main.scss (Line 124 of source/styles/vendor/foundation/foundation/components/_global.scss: Undefined variable: "$_property".)
directory destination/styles/fix
    write destination/styles/fix/ie.css
Compilation failed in 1 files.
```
Versions:
`Sass 3.4.4 (Selective Steve)`
`Compass 1.0.1 (Polaris)`

**Comment by ix-xerri** [comment]
I'm having the same issue.
I use dropdown, and dropdown requires global.
While i'm compiling with gulp the same error is thrown.

**Comment by cosmorogers** [comment]
@ix-xerri I've just had a similar problem. It looks like something has been updated in the gulp npm packages somewhere and it is now using mixins with the same name in a different order. Have a look through your code for a mixin called "transition" and renamed it to something else.
