### ISSUE TITLE
No longer possible to combine "expand" class with other button sizing classes

### ISSUE THREAD

**Issue by Deckluhm** [zurb/foundation#6922]
In Foundation **5.5.2** it was possible to combine both `expand` and any other button sizing class (for example `tiny`).

Since **5.5.3**, the `expand` class now has the same `font-size` / `padding` than the default button style so it's no longer possible to combined it with another sizing class.

I don't know if it's a wanted behavior or a regression but I think it offers less flexibility and should be reverted to **5.5.2** behavior.

Here are both behaviors:
* **5.5.2**: http://codepen.io/anon/pen/YyVBwa?editors=100
* **5.5.3**: http://codepen.io/anon/pen/pjPGRJ?editors=100

**Comment by rafibomb** [comment]
Thanks for the report and the examples. Fixed by adding padding argument 6fa2668
