### ISSUE TITLE
Accordion target element selection

### ISSUE THREAD

**Issue by blaMck** [zurb/foundation#6923]
The accordion selects the element that needs to be toggled based on the hash parameter in the URL.
This causes issues when using a single page library like angular or knockout with pager because they use the hash to determine what page should be loaded.

Since there is an 'aria-controls' attribute on the link it should be possible to use that attribute to select the correct content element.

Is there a reason this is not already implemented like this?

**Comment by rafibomb** [comment]
Probably just legacy reasons - We'd love to see a better solution. Would you be able to put in a PR because it would be valuable to lots of people?

**Comment by zurbrandon** [comment]
Tested and Pulled  Thanks, man!
