### ISSUE TITLE
Documentation for Interchange may be wrong

### ISSUE THREAD

**Issue by oshovah** [zurb/foundation#6924]
I hade problems with interchange and topnav. The Mobile burger menu dosnt work after implementing interchange. 

This line of code (copied from your Doc)

```
$(document).foundation('interchange', {
  named_queries : {
    my_custom_query : 'only screen and (max-width: 200px)'
  }
});
```
makes the problem with topbar. So i dug through your Doc and found that the other plugins need a little bit different syntax for theirs settings. So i change the above code to this:
```
$(document).foundation({
  interchange : {
    named_queries : {
      my_custom_query : 'only screen and (max-width: 200px)'
    }
  }
});
```
and now everything is fine :) So I thought that you should know this. Hey and greate framework!

**Comment by rafibomb** [comment]
Thanks! I think the second example is the right way to do it anyways. Can you submit a PR so the documentation can be updated?

**Comment by oshovah** [comment]
Yea sure i can do a commit. But i dont get it how i can update the documentation? 'dist' is ignored by .gitignore. Ist there a seperate repo for the documentation?

**Comment by zurbrandon** [comment]
This has been updated for the next push! Thanks so much for pointing this out, you rock!
