### ISSUE TITLE
slider adds decimal values

### ISSUE THREAD

**Issue by GeertHauwaerts** [zurb/foundation#6927]
In the 5.5.3 release, any slider will return a decimal value when sliding; you can validate this bug on your own [documentation page](http://foundation.zurb.com/docs/components/range_slider.html).

How to reproduce:

1. Go to http://foundation.zurb.com/docs/components/range_slider.html
1. The default value of the first slider on the page is 50
1. Move the slider
1. 50 will become 50.00
1. Any new value of the slider will be a decimal value with a precision of 2

**Comment by rafibomb** [comment]
Looks like this is an option in the JS. Needs to be documented and default set to 0. Are you able to submit a Pull Request for this?
