### ISSUE TITLE
Foundation-rails 5.5.3.1 Foundation is not defined

### ISSUE THREAD

**Issue by SylarRuby** [zurb/foundation#6933]
Urgent fix please. I have to downgrade to 5.5.1.2

**Comment by rafibomb** [comment]
Can you provide a bit more detail? What does the error look like?

**Comment by rafibomb** [comment]
Found another repo on the repo itself. It will be addressed here: https://github.com/zurb/foundation-rails/pull/129

**Comment by SylarRuby** [comment]
My issue was that I could not close the alert box
