### ISSUE TITLE
Foundation CLI throws error

### ISSUE THREAD

**Issue by OndrejVasicek** [zurb/foundation#6936]
All of a sudden, the Foundation CLI for creating project doesn’t work anymore. It worked few days ago, but now it throws error on 3 different computers.
I don’t say it’s Foundation’s fault, maybe there is a “bad” dependency. But does it mean, that in a situation, where one of the many dependencies is corrupt, unavailable or something, the CLI won’t work? It’s quite dangerous, isn’t it?

On the beginning, there is this. (after that a lot of dependencies is installed)
```
> node-sass@2.0.1 install C:\Users\Kalimero\Documents\projekty\lol\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-4.1/binding.node

> node-sass@2.0.1 postinstall C:\Users\Kalimero\Documents\projekty\lol\node_modules\node-sass
> node scripts/build.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'C:\Users\Kalimero\Documents\projekty\lol\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
Build failed
```
And then in the end is this.
```
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.
```

**Comment by andersonnguyen** [comment]
Is your Node.js version 4.x by any chance? I had this issue as well today but realized that Node.js made the weird leap from 0.12.x to 4.x recently, which caused problems with the node packages.

If you just update the versions numbers of

**Comment by andersonnguyen** [comment]
Is your Node.js version 4.x by any chance? I had this problem as well today, but I noticed that Node.js made a huge leap from 0.12.x to 4.x recently.

If your Node.js version is 4.x, you most likely just need to update the version numbers of the dependencies listed in the `package.json` file and then reinstall those node modules afterwards.

Changing the `node-sass` version to `~3.3.3` and the `grunt-sass` version to `~1.0.0` was what made it work for me again.

**Comment by OndrejVasicek** [comment]
Thanks @andersonnguyen for the help. It's working now, but I wouldn't say it’s proper/final solution, because people have to just go through wrong installation process, then change package.json and then update again.
I suppose we should still aim this issue to Zurb to solve it. Am I get it right?

**Comment by gakimball** [comment]
The [dependencies for the libsass template](https://github.com/zurb/foundation-libsass-template/blob/master/package.json) are out of date, so we'll update them shortly.

**Comment by zurbchris** [comment]
Dependencies are updated, working just fine on OSX Yosemite. Let us know if you continue having troubles with it, but I'm closing this for now.

**Comment by OndrejVasicek** [comment]
It's working now, thanks.
