### ISSUE TITLE
reveal modal

### ISSUE THREAD

**Issue by xensor** [zurb/foundation#6937]
seems like the reveal modal is not centered nor able to be scrolled. its alittle annoying.

how do we fix this issue.

i tried css styles. it didnt work. 

any way of fixing this

**Comment by rafibomb** [comment]
There is now a setting for locking scroll

no_scroll: true,

**Comment by xensor** [comment]
ok that still didn't solve the issue of it positioning to the bottom of the page or not showing when clicking on a link at footer.
