### ISSUE TITLE
Tooltip nub issues for small devices

### ISSUE THREAD

**Issue by nategraves** [zurb/foundation#6939]
The documentation for tooltips states
>On a small device, the tooltips are full-width and bottom aligned

This works as expected, however, the nubs for the tooltips don't get updated. This means that for `tip-top`, `tip-left`, and `tip-right` the nubs look and are positioned the same as on larger sizes. Here's an example of a `tip-left`:
![screen shot 2015-10-14 at 3 36 09 pm](https://cloud.githubusercontent.com/assets/788530/10495410/b61bc2a6-7289-11e5-91e4-bec142369f9e.png)

The nubs for small size tooltips should probably use the same styling as the `tip-bottom` class as that's how they are being treated.

**Comment by rafibomb** [comment]
Thanks for the PR! We'll close this in favor the PR and look to merge soon.
