### ISSUE TITLE
Range Sliders not working in Dropdown Menus

### ISSUE THREAD

**Issue by jaketlarson** [zurb/foundation#6946]
I'm having an issue where a range slider (http://foundation.zurb.com/docs/components/range_slider.html) will not work inside of a dropdown (http://foundation.zurb.com/docs/components/dropdown.html) without some kind of hack.

Of course, a simple `$(document).foundation('slider', 'reflow');` in the JS console fixes this, but is there way that I can add a callback on a dropdown-open action to perform a function that reflows the slider? I'm not seeing a callback on the dropdown docs.

Right now I'm resorting to a setTimeout to call the reflow function upon clicking the link that opens the dropdown, assuming that after the setTimeout function fires, the dropdown will have been displayed. I feel incredibly dirty with this method.

**Comment by rafibomb** [comment]
Thanks the report. The reflow method is available to re-apply listeners especially for hidden elements being added after the page loads.

We were able to confirm this. We're working on getting Foundation 6 and just checking it there, looks like it's not an issue. It's not a use case we're going to solve for in Foundation 5, but if you submit a Pull Request we'll merge it so people can benefit form it. Thanks!
