### ISSUE TITLE
Open up dependency for modular-scale for old foundation 3.

### ISSUE THREAD

**Issue by justin808** [zurb/foundation#6947]
I created a branch for this:

https://github.com/zurb/foundation/compare/v3.2.5...justin808:justin-v3.2.5

I'm having a heck of a time making foundation 3 work with the latest sass, ruby, etc.

This change seems to help. At least others might see this. I'll try to log some of the sass errors I see. While we'd like to upgrade foundation, we're trying to do our Rails 4 migration first.

Thanks,

Justin

**Comment by rafibomb** [comment]
Thanks for posting in case anyone else needs it. We're trying to keep the issue list focused on confirmed defects in Foundation 5, so we'll close this. Thanks!
