### ISSUE TITLE
Breadcrumbs - use :after instead of :before

### ISSUE THREAD

**Issue by tehlivi** [zurb/foundation#6949]
Visual issue with breadcrumbs...

Breadcrumbs use pseudo element <code>:before </code> to create the "/" separator. 

On mobile devices with larger titles, the separator's margins wrap the list elements oddly

![screen shot 2015-10-19 at 4 34 09 pm](https://cloud.githubusercontent.com/assets/5497842/10592394/6f339af2-7681-11e5-858a-b249e9b483c2.png)

It makes much more since to me to use <code>:after</code> instead

![screen shot 2015-10-19 at 4 35 44 pm](https://cloud.githubusercontent.com/assets/5497842/10592402/7a2d47dc-7681-11e5-992c-4ac1b8a21adc.png)

I'm not sure if there is a particular reasoning behind why it is set to <code>:before</code>, but I definitely think this is a much cleaner look.

<pre>
.breadcrumbs>*:before{
    display: none;
}
.breadcrumbs>*:after {
    color: #392d2d !important;
}
.breadcrumbs>*:after {
    color: #aaa;
    content: "/";
    margin: 0 0.75rem;
    position: relative;
    top: 1px;
}
.breadcrumbs>*:last-child:after {
    content: "";
}
</pre>

**Comment by SalahAdDin** [comment]
:+1:

**Comment by thiagotomasi** [comment]
@tehlivi I just made a PR with this proposal! :smile:

**Comment by rafibomb** [comment]
Thanks for the report and thanks to @thiagotomasi for the PR!

**Comment by thiagotomasi** [comment]
Your welcome @rafibomb! :smile:
