### ISSUE TITLE
nodeJS and browserify - docs woefully sparse

### ISSUE THREAD

**Issue by jamesaspence** [zurb/foundation#6950]
After struggling for hours to get a foundation modal to work via npm, I realized I had to include foundation.reveal as well as the base library in order to get modals to work.

`require('foundation-sites');`
`require('foundation-sites/js/foundation/foundation.reveal.js');`

I wish the docs had greater explanation as to how to get this up and running in an existing project via NPM. I found zero support for this issue anywhere.

**Comment by rafibomb** [comment]
Sorry - not sure this is the right place to ask this question. The forum would be a better place.

You need to include additional <script> tags for extra plugins.
It would make sense you would in turn need to `require` them using commonJS

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
