### ISSUE TITLE
Name margin variables consistently

### ISSUE THREAD

**Issue by mojavelinux** [zurb/foundation#6961]
Margin variables sometimes appear as `<position>-margin` and sometimes as `margin-<position>`. It would be a lot easier to use these variables if they followed the same pattern throughout. The pattern that is most consistent with other variable names is `margin-<position>`.

This affects the following variables:

* $alert-bottom-margin
* $form-label-bottom-margin
* $header-bottom-margin
* $header-top-margin
* $inline-list-bottom-margin
* $inline-list-top-margin
* $subheader-bottom-margin
* $subheader-top-margin
* $switch-bottom-margin

Maybe a change for Foundation 6?

**Comment by rafibomb** [comment]
Agreed! This has been addressed in Foundation 6. In addition to the naming, there are fewer of these variables and they are set to a $global-margin out of the box.

**Comment by mojavelinux** [comment]
That's great news! I'm curious, though, where is Foundation 6. I checked master before filing the issue and I saw the same issue. (https://github.com/zurb/foundation/blob/master/scss/foundation/components/_type.scss#L15).

**Comment by thiagotomasi** [comment]
@rafibomb can get this one?
