### ISSUE TITLE
Links inside .dropdown-content make menu "closable" by clicking on it

### ISSUE THREAD

**Issue by marienfressinaud** [zurb/foundation#6963]
I have a `.dropdown-content` menu with a very simple form inside, it was working fine until I add a link too : when I click anywhere on the `.dropdown-content`, the menu is closed immediately (even on my form input).

You can try this behaviour on http://codepen.io/anon/pen/avGzYJ (open the `.dropdown-content` and click on the text input)

It's also problematic to copy/paste text (you can try on http://foundation.zurb.com/docs/components/dropdown.html ;))

Tested on Firefox 41 and Chromium 46

**Comment by rafibomb** [comment]
You can add the aria-autoclose="false" attribute to control this behavior.

http://codepen.io/rafibomb/pen/bVMOaO

**Comment by marienfressinaud** [comment]
Thanks for your answer, I thought I tried this before opening this ticket but I probably missed something.
