### ISSUE TITLE
Placeholder almost indistinguishable from regular text

### ISSUE THREAD

**Issue by myndzi** [zurb/foundation#6968]
This commit introduced into 5.5.3:

https://github.com/zurb/foundation/commit/eed46d098b49a2d7b39d38f792ff50d25a3f31ab

Changes the placeholder color to $steel; in Chrome on Windows, at least, this makes the font color almost indistinguishable from entered text (worse, in some fonts). This may have something to do with font rendering/anti-aliasing, but it is certainly a poor default configuration on a widely used platform. I'm not entirely certain why the browser default is insufficient in this specific case, but please change it back to something more distinct.

![color "difference"](http://i.imgur.com/1KNDSKg.png)

**Comment by thiagotomasi** [comment]
Hey @myndzi, I just made this PR to if new idea of color font to the inputs:

<img width="474" alt="screen shot 2015-10-30 at 11 06 29 am" src="https://cloud.githubusercontent.com/assets/4387026/10846371/5561cac2-7ef6-11e5-86fe-af774b87c5a7.png">

How it looks? :smile: 
 
Here you can check my PR: #6969

**Comment by rafibomb** [comment]
@thiagotomasi Thanks for the PR! Probably the best practice is to not style these placeholders at all and let the browser decide. Thoughts?

**Comment by thiagotomasi** [comment]
@rafibomb Your welcome!
I believe change the color of the placeholders it a good idea. Please take a look in this articles:
- http://www.nngroup.com/articles/form-design-placeholders
- http://ux.stackexchange.com/questions/63040/placeholder-text-vs-disabled-text

I agree with them when they say the default contrast isn't enough, specially in poor quality display. But please let me know your opinion?

And if you want I can send another PR removing the placeholders' styles! :smile: 

PS.: I'm a UX designer, that's the reason I think about the contrast and legibility :smile:!

**Comment by rafibomb** [comment]
@thiagotomasi We'd need to set each one manually to make them look consistent across all browsers. If you ca submit the PR to change the colors we'd pull it in.

**Comment by thiagotomasi** [comment]
@rafibomb do you mean like this:

```
::-webkit-input-placeholder {
   color: $input-placeholder-font-color;
}

:-moz-placeholder { /* Firefox 18- */
   color: $input-placeholder-font-color;
}

::-moz-placeholder {  /* Firefox 19+ */
   color: $input-placeholder-font-color;
}

:-ms-input-placeholder {
   color: $input-placeholder-font-color;
}
```

I already made an PR with this change, you can check here #6969. 
Please let me know if is that something more I can help

**Comment by ion1** [comment]
This issue seems to be back in v6. The input color seems too light (`#8a8a8a` in v6.0.3) and is difficult to distinguish from the placeholder color. Is there a reason for the input color not to be the same as normal text color?
