### ISSUE TITLE
Block Grid Demo Page unequal blocks

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation#6971]
Advanced section on the link. 
http://foundation.zurb.com/docs/components/block_grid.html

I don't know if this intended but it was working ok on my works.
Here screenshot
![capture](https://cloud.githubusercontent.com/assets/1254613/10858694/fd8274ec-7f67-11e5-9e03-27929d2e5a10.PNG)

Tested on
Windows 7 / Chrome / Firefox / Opera

**Comment by anik786** [comment]
This seems to be working as intended as the images you used are of different sizes. Howe did you want it to look?

**Comment by atilkan** [comment]
So, according to image size. I checked sizes and understood. Thanks.
