### ISSUE TITLE
Reveal close don't have a visible focus

### ISSUE THREAD

**Issue by mik-laj** [zurb/foundation#6973]
Hi. 
I think that reveal close button should have a visible focus when you navigate to it from the mouse and keyboard.
Thanks in advance!

Example: http://foundation.zurb.com/docs/components/reveal.html

**Comment by rafibomb** [comment]
Totally agree. This is the case in Foundation 6 which we are working to get released soon. We'll accept a PR for 5 since tons of people will still use it. We'll close this here as we are working to F6 out.
