### ISSUE TITLE
ios 9.1: modal background .reveal-modal-bg is not visible

### ISSUE THREAD

**Issue by gkiely** [zurb/foundation#6974]
Device: iphone 6s

![foundation-error](https://cloud.githubusercontent.com/assets/1948935/10875187/960d6f24-8183-11e5-9487-028f7c1f9cdd.jpg)

**Comment by gkiely** [comment]
Please note this is only while using the crystal content blocker.

**Comment by rafibomb** [comment]
Thanks for the report. We tested on a 6s with IOS 9.1 and couldn't replicate. We're not testing with the content blocker you mentioned. If you find a solution, we'd love to know about it. We'll close this - thanks!
