### ISSUE TITLE
Dropdown data attribute [data-dropdown-content] generates unrecognized expression: [data-dropdown=] error

### ISSUE THREAD

**Issue by TechFounder** [zurb/foundation#6992]
I'm not sure what's happening but when I use the ```data-dropdown-content``` attribute in my dropdown I'm getting an ```Uncaught Error: Syntax error, unrecognized expression: [data-dropdown=]``` error in the console and the dropdown stops working.

I have the code like this:
```   
.small-11.small-centered.columns.show-for-small-only
    .small-3.columns.hamburger-top-padding
         = link_to content_tag(:i, nil, class: 'fa fa-bars fa-lg'), '#', { 'data-dropdown': 'mobile-login', 'aria-controls': 'mobile-login', 'aria-expanded': 'false' }
.mobile-dropdown#mobile-login
   .row
      .small-11.small-centered.columns.text-center
          %ul.mobile-login-button-group.even-2{ 'aria-hidden': 'true', 'data-dropdown-content': '', 'aria-autoclose': 'false', tabindex: '-1' }
            %li
```
If I remove the 'data-dropdown-content': '' the dropdown works and I don't get that error. But I do get some bottom navbar margin shortening. Why would that be?

**Comment by TechFounder** [comment]
Found my problem...sorry about the mixup.

**Comment by sawanr** [comment]
How did you fix it? I am facing same problem

**Comment by TechFounder** [comment]
Hi sawanr, this was last year so I don't remember exactly what my fix was but think it had to do with me not having html tags and data attributes in the right place. I would recommend that you look at yours closely using either inspect or page source to see the exact html rendered. You must have made a mistake there somewhere. For foundation 5, you have to have the anchor link html with a data-link="id" and a separate ul with the same "id" and data-dropdown-content right below it.
